
CREATE PROCEDURE [dbo].[RECUP_ESTIA_PATRIMOINE_CSV]
AS
BEGIN

DECLARE @ID_LOG INT, @NB INT

--AGENCE: TABLE DES AGENCES
INSERT INTO L_RECUPERATION_ESTIA (NOM_TABLE, IND_SUCCES, DT_DEBUT) VALUES ('AGENCE', 'N', GETDATE())
SET @ID_LOG = @@IDENTITY
TRUNCATE TABLE AGENCE

BULK INSERT AGENCE
FROM 'C:\ESTIA_DATA\AGENCE.csv'
WITH
(
    FIRSTROW = 2,
    FIELDTERMINATOR = ';',  --CSV field delimiter
    ROWTERMINATOR = '\n',   --Use to shift the control to next row
    TABLOCK,
	CODEPAGE  = '65001',
	KEEPNULLS 
)

SET @NB = @@ROWCOUNT
UPDATE L_RECUPERATION_ESTIA SET IND_SUCCES = 'O', DT_FIN = GETDATE(), NB_LIGNES = @NB WHERE ID_LOG = @ID_LOG


--APE: TABLE DES CODES APE
INSERT INTO L_RECUPERATION_ESTIA (NOM_TABLE, IND_SUCCES, DT_DEBUT) VALUES ('APE', 'N', GETDATE())
SET @ID_LOG = @@IDENTITY
TRUNCATE TABLE APE

BULK INSERT APE
FROM 'C:\ESTIA_DATA\APE.csv'
WITH
(
    FIRSTROW = 2,
    FIELDTERMINATOR = ';',  --CSV field delimiter
    ROWTERMINATOR = '\n',   --Use to shift the control to next row
    TABLOCK,
	CODEPAGE  = '65001',
	KEEPNULLS 
)

SET @NB = @@ROWCOUNT
UPDATE L_RECUPERATION_ESTIA SET IND_SUCCES = 'O', DT_FIN = GETDATE(), NB_LIGNES = @NB WHERE ID_LOG = @ID_LOG


--BANALDET: TABLE BANAL DETAIL
INSERT INTO L_RECUPERATION_ESTIA (NOM_TABLE, IND_SUCCES, DT_DEBUT) VALUES ('BANALDET', 'N', GETDATE())
SET @ID_LOG = @@IDENTITY
TRUNCATE TABLE BANALDET

BULK INSERT BANALDET
FROM 'C:\ESTIA_DATA\BANALDET.csv'
WITH
(
    FIRSTROW = 2,
    FIELDTERMINATOR = ';',  --CSV field delimiter
    ROWTERMINATOR = '\n',   --Use to shift the control to next row
    TABLOCK,
	CODEPAGE  = '65001',
	KEEPNULLS 
)

SET @NB = @@ROWCOUNT
UPDATE L_RECUPERATION_ESTIA SET IND_SUCCES = 'O', DT_FIN = GETDATE(), NB_LIGNES = @NB WHERE ID_LOG = @ID_LOG


--BANQUE: TABLE DE BANQUE
INSERT INTO L_RECUPERATION_ESTIA (NOM_TABLE, IND_SUCCES, DT_DEBUT) VALUES ('BANQUE', 'N', GETDATE())
SET @ID_LOG = @@IDENTITY
TRUNCATE TABLE BANQUE

BULK INSERT BANQUE
FROM 'C:\ESTIA_DATA\BANQUE.csv'
WITH
(
    FIRSTROW = 2,
    FIELDTERMINATOR = ';',  --CSV field delimiter
    ROWTERMINATOR = '\n',   --Use to shift the control to next row
    TABLOCK,
	CODEPAGE  = '65001',
	KEEPNULLS 
)

SET @NB = @@ROWCOUNT
UPDATE L_RECUPERATION_ESTIA SET IND_SUCCES = 'O', DT_FIN = GETDATE(), NB_LIGNES = @NB WHERE ID_LOG = @ID_LOG


--BASE: TABLE DE BASE DES TANTIEMES
INSERT INTO L_RECUPERATION_ESTIA (NOM_TABLE, IND_SUCCES, DT_DEBUT) VALUES ('BASE', 'N', GETDATE())
SET @ID_LOG = @@IDENTITY
TRUNCATE TABLE BASE

BULK INSERT BASE
FROM 'C:\ESTIA_DATA\BASE.csv'
WITH
(
    FIRSTROW = 2,
    FIELDTERMINATOR = ';',  --CSV field delimiter
    ROWTERMINATOR = '\n',   --Use to shift the control to next row
    TABLOCK,
	CODEPAGE  = '65001',
	KEEPNULLS 
)

SET @NB = @@ROWCOUNT
UPDATE L_RECUPERATION_ESTIA SET IND_SUCCES = 'O', DT_FIN = GETDATE(), NB_LIGNES = @NB WHERE ID_LOG = @ID_LOG


--BASELOC: TABLE DES TANTIEMES
INSERT INTO L_RECUPERATION_ESTIA (NOM_TABLE, IND_SUCCES, DT_DEBUT) VALUES ('BASELOC', 'N', GETDATE())
SET @ID_LOG = @@IDENTITY
TRUNCATE TABLE BASELOC

BULK INSERT BASELOC
FROM 'C:\ESTIA_DATA\BASELOC.csv'
WITH
(
    FIRSTROW = 2,
    FIELDTERMINATOR = ';',  --CSV field delimiter
    ROWTERMINATOR = '\n',   --Use to shift the control to next row
    TABLOCK,
	CODEPAGE  = '65001',
	KEEPNULLS 
)

SET @NB = @@ROWCOUNT
UPDATE L_RECUPERATION_ESTIA SET IND_SUCCES = 'O', DT_FIN = GETDATE(), NB_LIGNES = @NB WHERE ID_LOG = @ID_LOG


--CATEG: TABLE DES CATEGORIES DE TIERS
INSERT INTO L_RECUPERATION_ESTIA (NOM_TABLE, IND_SUCCES, DT_DEBUT) VALUES ('CATEG', 'N', GETDATE())
SET @ID_LOG = @@IDENTITY
TRUNCATE TABLE CATEG

BULK INSERT CATEG
FROM 'C:\ESTIA_DATA\CATEG.csv'
WITH
(
    FIRSTROW = 2,
    FIELDTERMINATOR = ';',  --CSV field delimiter
    ROWTERMINATOR = '\n',   --Use to shift the control to next row
    TABLOCK,
	CODEPAGE  = '65001',
	KEEPNULLS 
)

SET @NB = @@ROWCOUNT
UPDATE L_RECUPERATION_ESTIA SET IND_SUCCES = 'O', DT_FIN = GETDATE(), NB_LIGNES = @NB WHERE ID_LOG = @ID_LOG

--COMMENT_: TABLE DES COMMENTAIRES
INSERT INTO L_RECUPERATION_ESTIA (NOM_TABLE, IND_SUCCES, DT_DEBUT) VALUES ('COMMENT_', 'N', GETDATE())
SET @ID_LOG = @@IDENTITY
TRUNCATE TABLE COMMENT_

BULK INSERT COMMENT_
FROM 'C:\ESTIA_DATA\COMMENT.csv'
WITH
(
    FIRSTROW = 2,
    FIELDTERMINATOR = ';',  --CSV field delimiter
    ROWTERMINATOR = ';;\n',   --Use to shift the control to next row
    TABLOCK,
	CODEPAGE  = '65001',
	KEEPNULLS 
)

SET @NB = @@ROWCOUNT
UPDATE L_RECUPERATION_ESTIA SET IND_SUCCES = 'O', DT_FIN = GETDATE(), NB_LIGNES = @NB WHERE ID_LOG = @ID_LOG


--COORDBANQ: TABLE DE GESTION DES BIC ET IBAN POUR LES COORDONNEES
INSERT INTO L_RECUPERATION_ESTIA (NOM_TABLE, IND_SUCCES, DT_DEBUT) VALUES ('COORDBANQ', 'N', GETDATE())
SET @ID_LOG = @@IDENTITY
TRUNCATE TABLE COORDBANQ

BULK INSERT COORDBANQ
FROM 'C:\ESTIA_DATA\COORDBANQ.csv'
WITH
(
    FIRSTROW = 2,
    FIELDTERMINATOR = ';',  --CSV field delimiter
    ROWTERMINATOR = '\n',   --Use to shift the control to next row
    TABLOCK,
	CODEPAGE  = '65001',
	KEEPNULLS 
)

SET @NB = @@ROWCOUNT
UPDATE L_RECUPERATION_ESTIA SET IND_SUCCES = 'O', DT_FIN = GETDATE(), NB_LIGNES = @NB WHERE ID_LOG = @ID_LOG


--CTRTIERS: TABLE DES CONTRATS PAR TIERS
INSERT INTO L_RECUPERATION_ESTIA (NOM_TABLE, IND_SUCCES, DT_DEBUT) VALUES ('CTRTIERS', 'N', GETDATE())
SET @ID_LOG = @@IDENTITY
TRUNCATE TABLE CTRTIERS

BULK INSERT CTRTIERS
FROM 'C:\ESTIA_DATA\CTRTIERS.csv'
WITH
(
    FIRSTROW = 2,
    FIELDTERMINATOR = ';',  --CSV field delimiter
    ROWTERMINATOR = '\n',   --Use to shift the control to next row
    TABLOCK,
	CODEPAGE  = '65001',
	KEEPNULLS 
)

SET @NB = @@ROWCOUNT
UPDATE L_RECUPERATION_ESTIA SET IND_SUCCES = 'O', DT_FIN = GETDATE(), NB_LIGNES = @NB WHERE ID_LOG = @ID_LOG


--BAIL: TABLE DES NATURES DE BAIL
INSERT INTO L_RECUPERATION_ESTIA (NOM_TABLE, IND_SUCCES, DT_DEBUT) VALUES ('BAIL', 'N', GETDATE())
SET @ID_LOG = @@IDENTITY
TRUNCATE TABLE BAIL

BULK INSERT BAIL
FROM 'C:\ESTIA_DATA\BAIL.csv'
WITH
(
    FIRSTROW = 2,
    FIELDTERMINATOR = ';',  --CSV field delimiter
    ROWTERMINATOR = '\n',   --Use to shift the control to next row
    TABLOCK,
	CODEPAGE  = '65001',
	KEEPNULLS 
)

SET @NB = @@ROWCOUNT
UPDATE L_RECUPERATION_ESTIA SET IND_SUCCES = 'O', DT_FIN = GETDATE(), NB_LIGNES = @NB WHERE ID_LOG = @ID_LOG


--COMPTE: TABLE DES COMPTES
INSERT INTO L_RECUPERATION_ESTIA (NOM_TABLE, IND_SUCCES, DT_DEBUT) VALUES ('COMPTE', 'N', GETDATE())
SET @ID_LOG = @@IDENTITY
TRUNCATE TABLE COMPTE

BULK INSERT COMPTE
FROM 'C:\ESTIA_DATA\COMPTE.csv'
WITH
(
    FIRSTROW = 2,
    FIELDTERMINATOR = ';',  --CSV field delimiter
    ROWTERMINATOR = '\n',   --Use to shift the control to next row
    TABLOCK,
	CODEPAGE  = '65001',
	KEEPNULLS 
)
SET @NB = @@ROWCOUNT
UPDATE L_RECUPERATION_ESTIA SET IND_SUCCES = 'O', DT_FIN = GETDATE(), NB_LIGNES = @NB WHERE ID_LOG = @ID_LOG


--CONTNAT: TABLE DES CONTRATS
INSERT INTO L_RECUPERATION_ESTIA (NOM_TABLE, IND_SUCCES, DT_DEBUT) VALUES ('CONTNAT', 'N', GETDATE())
SET @ID_LOG = @@IDENTITY
TRUNCATE TABLE CONTNAT

BULK INSERT CONTNAT
FROM 'C:\ESTIA_DATA\CONTNAT.csv'
WITH
(
    FIRSTROW = 2,
    FIELDTERMINATOR = ';',  --CSV field delimiter
    ROWTERMINATOR = '\n',   --Use to shift the control to next row
    TABLOCK,
	CODEPAGE  = '65001',
	KEEPNULLS 
)
SET @NB = @@ROWCOUNT
UPDATE L_RECUPERATION_ESTIA SET IND_SUCCES = 'O', DT_FIN = GETDATE(), NB_LIGNES = @NB WHERE ID_LOG = @ID_LOG


--CPTGLOB: TABLE DES COMPTES
INSERT INTO L_RECUPERATION_ESTIA (NOM_TABLE, IND_SUCCES, DT_DEBUT) VALUES ('CPTGLOB', 'N', GETDATE())
SET @ID_LOG = @@IDENTITY
TRUNCATE TABLE CPTGLOB

BULK INSERT CPTGLOB
FROM 'C:\ESTIA_DATA\CPTGLOB.csv'
WITH
(
    FIRSTROW = 2,
    FIELDTERMINATOR = ';',  --CSV field delimiter
    ROWTERMINATOR = '\n',   --Use to shift the control to next row
    TABLOCK,
	CODEPAGE  = '65001',
	KEEPNULLS 
)
SET @NB = @@ROWCOUNT
UPDATE L_RECUPERATION_ESTIA SET IND_SUCCES = 'O', DT_FIN = GETDATE(), NB_LIGNES = @NB WHERE ID_LOG = @ID_LOG

-- correction de 2 enregistrements errones
update CPTGLOB
set TYPCPTA = LETTRAGE,
	LETTRAGE = MONTANT,
	MONTANT = NOPIECE,
	NOPIECE = REF,
	REF = TRIG,
	TRIG = TRAIT,
	TRAIT = CRUB,
	CRUB = NOLOCAT,
	NOLOCAT = NOBAIL,
    NOBAIL = MONTDOUT,
	MONTDOUT = REGROUPLOC,
	REGROUPLOC = CTIERS,
	CTIERS = CORGPAY,
	CORGPAY = CSTE,
	CSTE = CTYPTIERS,
	CTYPTIERS = CTASS,
	NOCHEQUE = REFREJET,
	REFREJET = DREJET,
	DREJET = INFO,
	INFO = MONTEXC,
	MONTEXC = MONTCRE,
    MONTCRE = GELE,
	GELE = ECHEANCE,
	ECHEANCE = MOTREJ,
	MOTREJ = REMANGES,
	REMANGES = CMONNAIE,
	CMONNAIE = MTEURO,
	MTEURO = MTEDV,
	MTEDV = MONTD1,
	MONTD1 = PATYPTIERS,
	PATYPTIERS = PATIERS,
	PATIERS = DVAL,
	DVAL = MONTD2,
	MONTD2 = MONTD3,
	MONTD3 = MONTEDV,
	MONTEDV = LETECH,
	LETECH = EDITQUIT,
	EDITQUIT = CSINIS,
	CSINIS = MIGCOMPT,
	MIGCOMPT = CTYPRGLT,
	CTYPRGLT = ORDREV,
	ORDREV = CMANDAT,
	CMANDAT = DTERME,
	DHONO = NULL,
    LIB = LIB + ' ' + CBANQUE,
    CBANQUE = NULL
where CORG = '11'
and CCOMPTE = 206
and CBANQUE = 'FRAIS ETAT LIEUX 31.1.2001';


--CRIT: TABLE DES DIFFERENTS SOUS-CRITERES LIBRES
INSERT INTO L_RECUPERATION_ESTIA (NOM_TABLE, IND_SUCCES, DT_DEBUT) VALUES ('CRIT', 'N', GETDATE())
SET @ID_LOG = @@IDENTITY
TRUNCATE TABLE CRIT

BULK INSERT CRIT
FROM 'C:\ESTIA_DATA\CRIT.csv'
WITH
(
    FIRSTROW = 2,
    FIELDTERMINATOR = ';',  --CSV field delimiter
    ROWTERMINATOR = '\n',   --Use to shift the control to next row
    TABLOCK,
	CODEPAGE  = '65001',
	KEEPNULLS 
)

SET @NB = @@ROWCOUNT
UPDATE L_RECUPERATION_ESTIA SET IND_SUCCES = 'O', DT_FIN = GETDATE(), NB_LIGNES = @NB WHERE ID_LOG = @ID_LOG


--CRITDP: TABLE DES CRITERES DE DEPENSES
INSERT INTO L_RECUPERATION_ESTIA (NOM_TABLE, IND_SUCCES, DT_DEBUT) VALUES ('CRITDP', 'N', GETDATE())
SET @ID_LOG = @@IDENTITY
TRUNCATE TABLE CRITDP

BULK INSERT CRITDP
FROM 'C:\ESTIA_DATA\CRITDP.csv'
WITH
(
    FIRSTROW = 2,
    FIELDTERMINATOR = ';',  --CSV field delimiter
    ROWTERMINATOR = '\n',   --Use to shift the control to next row
    TABLOCK,
	CODEPAGE  = '65001',
	KEEPNULLS 
)

SET @NB = @@ROWCOUNT
UPDATE L_RECUPERATION_ESTIA SET IND_SUCCES = 'O', DT_FIN = GETDATE(), NB_LIGNES = @NB WHERE ID_LOG = @ID_LOG


--CRITLIB: TABLE DES CRITERES LIBRES ASSOCIES AUX LOCAUX ET COMPTES LOCATAIRES
INSERT INTO L_RECUPERATION_ESTIA (NOM_TABLE, IND_SUCCES, DT_DEBUT) VALUES ('CRITLIB', 'N', GETDATE())
SET @ID_LOG = @@IDENTITY
TRUNCATE TABLE CRITLIB

BULK INSERT CRITLIB
FROM 'C:\ESTIA_DATA\CRITLIB.csv'
WITH
(
    FIRSTROW = 2,
    FIELDTERMINATOR = ';',  --CSV field delimiter
    ROWTERMINATOR = '\n',   --Use to shift the control to next row
    TABLOCK,
	CODEPAGE  = '65001',
	KEEPNULLS 
)

SET @NB = @@ROWCOUNT
UPDATE L_RECUPERATION_ESTIA SET IND_SUCCES = 'O', DT_FIN = GETDATE(), NB_LIGNES = @NB WHERE ID_LOG = @ID_LOG



--DEMINT: TABLE DES DEMANDES D'INTERVENTION
INSERT INTO L_RECUPERATION_ESTIA (NOM_TABLE, IND_SUCCES, DT_DEBUT) VALUES ('DEMINT', 'N', GETDATE())
SET @ID_LOG = @@IDENTITY
TRUNCATE TABLE DEMINT

BULK INSERT DEMINT
FROM 'C:\ESTIA_DATA\DEMINT.csv'
WITH
(
    FIRSTROW = 2,
    FIELDTERMINATOR = ';',  --CSV field delimiter
    ROWTERMINATOR = '\n',   --Use to shift the control to next row
    TABLOCK,
	CODEPAGE  = '65001',
	KEEPNULLS 
)

SET @NB = @@ROWCOUNT
UPDATE L_RECUPERATION_ESTIA SET IND_SUCCES = 'O', DT_FIN = GETDATE(), NB_LIGNES = @NB WHERE ID_LOG = @ID_LOG


--DETSEC: TABLE DES DETAILS DE LA VENTILATION COMPTABLE
INSERT INTO L_RECUPERATION_ESTIA (NOM_TABLE, IND_SUCCES, DT_DEBUT) VALUES ('DETSEC', 'N', GETDATE())
SET @ID_LOG = @@IDENTITY
TRUNCATE TABLE DETSEC

BULK INSERT DETSEC
FROM 'C:\ESTIA_DATA\DETSEC.csv'
WITH
(
    FIRSTROW = 2,
    FIELDTERMINATOR = ';',  --CSV field delimiter
    ROWTERMINATOR = '\n',   --Use to shift the control to next row
    TABLOCK,
	CODEPAGE  = '65001',
	KEEPNULLS 
)

SET @NB = @@ROWCOUNT
UPDATE L_RECUPERATION_ESTIA SET IND_SUCCES = 'O', DT_FIN = GETDATE(), NB_LIGNES = @NB WHERE ID_LOG = @ID_LOG



--DPROCTX: TABLE DOMAINE CONTENTIEUX
INSERT INTO L_RECUPERATION_ESTIA (NOM_TABLE, IND_SUCCES, DT_DEBUT) VALUES ('DPROCTX', 'N', GETDATE())
SET @ID_LOG = @@IDENTITY
TRUNCATE TABLE DPROCTX

BULK INSERT DPROCTX
FROM 'C:\ESTIA_DATA\DPROCTX.csv'
WITH
(
    FIRSTROW = 2,
    FIELDTERMINATOR = ';',  --CSV field delimiter
    ROWTERMINATOR = '\n',   --Use to shift the control to next row
    TABLOCK,
	CODEPAGE  = '65001',
	KEEPNULLS 
)

SET @NB = @@ROWCOUNT
UPDATE L_RECUPERATION_ESTIA SET IND_SUCCES = 'O', DT_FIN = GETDATE(), NB_LIGNES = @NB WHERE ID_LOG = @ID_LOG


--EBUDLOC: TABLE DES 
INSERT INTO L_RECUPERATION_ESTIA (NOM_TABLE, IND_SUCCES, DT_DEBUT) VALUES ('EBUDLOC', 'N', GETDATE())
SET @ID_LOG = @@IDENTITY
TRUNCATE TABLE EBUDLOC

BULK INSERT EBUDLOC
FROM 'C:\ESTIA_DATA\EBUDLOC.csv'
WITH
(
    FIRSTROW = 2,
    FIELDTERMINATOR = ';',  --CSV field delimiter
    ROWTERMINATOR = '\n',   --Use to shift the control to next row
    TABLOCK,
	CODEPAGE  = '65001',
	KEEPNULLS 
)

SET @NB = @@ROWCOUNT
UPDATE L_RECUPERATION_ESTIA SET IND_SUCCES = 'O', DT_FIN = GETDATE(), NB_LIGNES = @NB WHERE ID_LOG = @ID_LOG


--ECRAC: TABLE DE COMPTABILITE GENERALE 
INSERT INTO L_RECUPERATION_ESTIA (NOM_TABLE, IND_SUCCES, DT_DEBUT) VALUES ('ECRAC', 'N', GETDATE())
SET @ID_LOG = @@IDENTITY
TRUNCATE TABLE ECRAC

BULK INSERT ECRAC
FROM 'C:\ESTIA_DATA\ECRAC.csv'
WITH
(
    FIRSTROW = 2,
    FIELDTERMINATOR = ';',  --CSV field delimiter
    ROWTERMINATOR = '\n',   --Use to shift the control to next row
    TABLOCK,
	CODEPAGE  = '65001',
	KEEPNULLS 
)

SET @NB = @@ROWCOUNT
UPDATE L_RECUPERATION_ESTIA SET IND_SUCCES = 'O', DT_FIN = GETDATE(), NB_LIGNES = @NB WHERE ID_LOG = @ID_LOG


--ECRIB: TABLE DES ECRITURES AUXILIAIRES 
INSERT INTO L_RECUPERATION_ESTIA (NOM_TABLE, IND_SUCCES, DT_DEBUT) VALUES ('ECRIB', 'N', GETDATE())
SET @ID_LOG = @@IDENTITY
TRUNCATE TABLE ECRIB

BULK INSERT ECRIB
FROM 'C:\ESTIA_DATA\ECRIB.csv'
WITH
(
    FIRSTROW = 2,
    FIELDTERMINATOR = ';',  --CSV field delimiter
    ROWTERMINATOR = '\n',   --Use to shift the control to next row
    TABLOCK,
	CODEPAGE  = '65001',
	KEEPNULLS 
)

SET @NB = @@ROWCOUNT
UPDATE L_RECUPERATION_ESTIA SET IND_SUCCES = 'O', DT_FIN = GETDATE(), NB_LIGNES = @NB WHERE ID_LOG = @ID_LOG


--ECRITANA: TABLE DES ECRITURES ANALYTIQUES 
INSERT INTO L_RECUPERATION_ESTIA (NOM_TABLE, IND_SUCCES, DT_DEBUT) VALUES ('ECRITANA', 'N', GETDATE())
SET @ID_LOG = @@IDENTITY
TRUNCATE TABLE ECRITANA

BULK INSERT ECRITANA
FROM 'C:\ESTIA_DATA\ECRITANA.csv'
WITH
(
    FIRSTROW = 2,
    FIELDTERMINATOR = ';',  --CSV field delimiter
    ROWTERMINATOR = '\n',   --Use to shift the control to next row
    TABLOCK,
	CODEPAGE  = '65001',
	KEEPNULLS 
)

SET @NB = @@ROWCOUNT
UPDATE L_RECUPERATION_ESTIA SET IND_SUCCES = 'O', DT_FIN = GETDATE(), NB_LIGNES = @NB WHERE ID_LOG = @ID_LOG


--ECRITAUX: TABLE DES ECRITURES AUXILIAIRES 
INSERT INTO L_RECUPERATION_ESTIA (NOM_TABLE, IND_SUCCES, DT_DEBUT) VALUES ('ECRITAUX', 'N', GETDATE())
SET @ID_LOG = @@IDENTITY
TRUNCATE TABLE ECRITAUX

BULK INSERT ECRITAUX
FROM 'C:\ESTIA_DATA\ECRITAUX.csv'
WITH
(
    FIRSTROW = 2,
    FIELDTERMINATOR = ';',  --CSV field delimiter
    ROWTERMINATOR = '\n',   --Use to shift the control to next row
    TABLOCK,
	CODEPAGE  = '65001',
	KEEPNULLS 
)

SET @NB = @@ROWCOUNT
UPDATE L_RECUPERATION_ESTIA SET IND_SUCCES = 'O', DT_FIN = GETDATE(), NB_LIGNES = @NB WHERE ID_LOG = @ID_LOG



--EMPLOY: TABLE DES EMPLOYES
INSERT INTO L_RECUPERATION_ESTIA (NOM_TABLE, IND_SUCCES, DT_DEBUT) VALUES ('EMPLOY', 'N', GETDATE())
SET @ID_LOG = @@IDENTITY
TRUNCATE TABLE EMPLOY

BULK INSERT EMPLOY
FROM 'C:\ESTIA_DATA\EMPLOY.csv'
WITH
(
    FIRSTROW = 2,
    FIELDTERMINATOR = ';',  --CSV field delimiter
    ROWTERMINATOR = '\n',   --Use to shift the control to next row
    TABLOCK,
	CODEPAGE  = '65001',
	KEEPNULLS 
)

SET @NB = @@ROWCOUNT
UPDATE L_RECUPERATION_ESTIA SET IND_SUCCES = 'O', DT_FIN = GETDATE(), NB_LIGNES = @NB WHERE ID_LOG = @ID_LOG


--ENTFAC: TABLE DES 
INSERT INTO L_RECUPERATION_ESTIA (NOM_TABLE, IND_SUCCES, DT_DEBUT) VALUES ('ENTFAC', 'N', GETDATE())
SET @ID_LOG = @@IDENTITY
TRUNCATE TABLE ENTFAC

BULK INSERT ENTFAC
FROM 'C:\ESTIA_DATA\ENTFAC.csv'
WITH
(
    FIRSTROW = 2,
    FIELDTERMINATOR = ';',  --CSV field delimiter
    ROWTERMINATOR = '\n',   --Use to shift the control to next row
    TABLOCK,
	CODEPAGE  = '65001',
	KEEPNULLS 
)

SET @NB = @@ROWCOUNT
UPDATE L_RECUPERATION_ESTIA SET IND_SUCCES = 'O', DT_FIN = GETDATE(), NB_LIGNES = @NB WHERE ID_LOG = @ID_LOG



--FINDIV: TABLE DE début et fin de gestion des fournisseurs
INSERT INTO L_RECUPERATION_ESTIA (NOM_TABLE, IND_SUCCES, DT_DEBUT) VALUES ('FINDIV', 'N', GETDATE())
SET @ID_LOG = @@IDENTITY
TRUNCATE TABLE FINDIV

BULK INSERT FINDIV
FROM 'C:\ESTIA_DATA\FINDIV.csv'
WITH
(
    FIRSTROW = 2,
    FIELDTERMINATOR = ';',  --CSV field delimiter
    ROWTERMINATOR = '\n',   --Use to shift the control to next row
    TABLOCK,
	CODEPAGE  = '65001',
	KEEPNULLS 
)

SET @NB = @@ROWCOUNT
UPDATE L_RECUPERATION_ESTIA SET IND_SUCCES = 'O', DT_FIN = GETDATE(), NB_LIGNES = @NB WHERE ID_LOG = @ID_LOG


--GROUPE: TABLE DES GROUPES
INSERT INTO L_RECUPERATION_ESTIA (NOM_TABLE, IND_SUCCES, DT_DEBUT) VALUES ('GROUPE', 'N', GETDATE())
SET @ID_LOG = @@IDENTITY
TRUNCATE TABLE GROUPE

BULK INSERT GROUPE
FROM 'C:\ESTIA_DATA\GROUPE.csv'
WITH
(
    FIRSTROW = 2,
    FIELDTERMINATOR = ';',  --CSV field delimiter
    ROWTERMINATOR = '\n',   --Use to shift the control to next row
    TABLOCK,
	CODEPAGE  = '65001',
	KEEPNULLS 
)

SET @NB = @@ROWCOUNT
UPDATE L_RECUPERATION_ESTIA SET IND_SUCCES = 'O', DT_FIN = GETDATE(), NB_LIGNES = @NB WHERE ID_LOG = @ID_LOG


--GRPSEC: TABLE DES LIENS GROUPES/SECTIONS
INSERT INTO L_RECUPERATION_ESTIA (NOM_TABLE, IND_SUCCES, DT_DEBUT) VALUES ('GRPSEC', 'N', GETDATE())
SET @ID_LOG = @@IDENTITY

TRUNCATE TABLE GRPSEC

BULK INSERT GRPSEC
FROM 'C:\ESTIA_DATA\GRPSEC.csv'
WITH
(
    FIRSTROW = 2,
    FIELDTERMINATOR = ';',  --CSV field delimiter
    ROWTERMINATOR = '\n',   --Use to shift the control to next row
    TABLOCK,
	CODEPAGE  = '65001',
	KEEPNULLS 
)

SET @NB = @@ROWCOUNT
UPDATE L_RECUPERATION_ESTIA SET IND_SUCCES = 'O', DT_FIN = GETDATE(), NB_LIGNES = @NB WHERE ID_LOG = @ID_LOG


--HAVENAN: HISTORIQUE DES AVENANTS AU BAIL
INSERT INTO L_RECUPERATION_ESTIA (NOM_TABLE, IND_SUCCES, DT_DEBUT) VALUES ('HAVENAN', 'N', GETDATE())
SET @ID_LOG = @@IDENTITY
TRUNCATE TABLE HAVENAN

BULK INSERT HAVENAN
FROM 'C:\ESTIA_DATA\HAVENAN.csv'
WITH
(
    FIRSTROW = 2,
    FIELDTERMINATOR = ';',  --CSV field delimiter
    ROWTERMINATOR = '\n',   --Use to shift the control to next row
    TABLOCK,
	CODEPAGE  = '65001',
	KEEPNULLS 
)

SET @NB = @@ROWCOUNT
UPDATE L_RECUPERATION_ESTIA SET IND_SUCCES = 'O', DT_FIN = GETDATE(), NB_LIGNES = @NB WHERE ID_LOG = @ID_LOG


--HDEPCS: TABLE DES HISTORIQUES DES DEPENSES CRITERE/SOUS-CRI
INSERT INTO L_RECUPERATION_ESTIA (NOM_TABLE, IND_SUCCES, DT_DEBUT) VALUES ('HDEPCS', 'N', GETDATE())
SET @ID_LOG = @@IDENTITY
TRUNCATE TABLE HDEPCS

BULK INSERT HDEPCS
FROM 'C:\ESTIA_DATA\HDEPCS.csv'
WITH
(
    FIRSTROW = 2,
    FIELDTERMINATOR = ';',  --CSV field delimiter
    ROWTERMINATOR = '\n',   --Use to shift the control to next row
    TABLOCK,
	CODEPAGE  = '65001',
	KEEPNULLS 
)

SET @NB = @@ROWCOUNT
UPDATE L_RECUPERATION_ESTIA SET IND_SUCCES = 'O', DT_FIN = GETDATE(), NB_LIGNES = @NB WHERE ID_LOG = @ID_LOG


--HLOYCA: TABLE D'HISTORIQUE DES CHIFFRES D'AFFAIRE table non utilisee par SWISS LIFE
INSERT INTO L_RECUPERATION_ESTIA (NOM_TABLE, IND_SUCCES, DT_DEBUT) VALUES ('HLOYCA', 'N', GETDATE())
SET @ID_LOG = @@IDENTITY
TRUNCATE TABLE HLOYCA

BULK INSERT HLOYCA
FROM 'C:\ESTIA_DATA\HLOYCA.csv'
WITH
(
    FIRSTROW = 2,
    FIELDTERMINATOR = ';',  --CSV field delimiter
    ROWTERMINATOR = '\n',   --Use to shift the control to next row
    TABLOCK,
	CODEPAGE  = '65001',
	KEEPNULLS 
)

SET @NB = @@ROWCOUNT
UPDATE L_RECUPERATION_ESTIA SET IND_SUCCES = 'O', DT_FIN = GETDATE(), NB_LIGNES = @NB WHERE ID_LOG = @ID_LOG


--HQFAC: TABLE DES 
INSERT INTO L_RECUPERATION_ESTIA (NOM_TABLE, IND_SUCCES, DT_DEBUT) VALUES ('HQFAC', 'N', GETDATE())
SET @ID_LOG = @@IDENTITY
TRUNCATE TABLE HQFAC

BULK INSERT HQFAC
FROM 'C:\ESTIA_DATA\HQFAC.csv'
WITH
(
    FIRSTROW = 2,
    FIELDTERMINATOR = ';',  --CSV field delimiter
    ROWTERMINATOR = '\n',   --Use to shift the control to next row
    TABLOCK,
	CODEPAGE  = '65001',
	KEEPNULLS 
)

SET @NB = @@ROWCOUNT
UPDATE L_RECUPERATION_ESTIA SET IND_SUCCES = 'O', DT_FIN = GETDATE(), NB_LIGNES = @NB WHERE ID_LOG = @ID_LOG


--HQLOCAL: HISTORIQUE DES RUBRIQUES DE QUITTANCEMENT LIES AUX LOCAUX (VLM)
INSERT INTO L_RECUPERATION_ESTIA (NOM_TABLE, IND_SUCCES, DT_DEBUT) VALUES ('HQLOCAL', 'N', GETDATE())
SET @ID_LOG = @@IDENTITY
TRUNCATE TABLE HQLOCAL

BULK INSERT HQLOCAL
FROM 'C:\ESTIA_DATA\HQLOCAL.csv'
WITH
(
    FIRSTROW = 2,
    FIELDTERMINATOR = ';',  --CSV field delimiter
    ROWTERMINATOR = '\n',   --Use to shift the control to next row
    TABLOCK,
	CODEPAGE  = '65001',
	KEEPNULLS 
)

SET @NB = @@ROWCOUNT
UPDATE L_RECUPERATION_ESTIA SET IND_SUCCES = 'O', DT_FIN = GETDATE(), NB_LIGNES = @NB WHERE ID_LOG = @ID_LOG


--HQLOCAT: TABLE DES VARIABLES DE QUITTANCEMENT DES BAUX
INSERT INTO L_RECUPERATION_ESTIA (NOM_TABLE, IND_SUCCES, DT_DEBUT) VALUES ('HQLOCAT', 'N', GETDATE())
SET @ID_LOG = @@IDENTITY
TRUNCATE TABLE HQLOCAT

BULK INSERT HQLOCAT
FROM 'C:\ESTIA_DATA\HQLOCAT.csv'
WITH
(
    FIRSTROW = 2,
    FIELDTERMINATOR = ';',  --CSV field delimiter
    ROWTERMINATOR = '\n',   --Use to shift the control to next row
    TABLOCK,
	CODEPAGE  = '65001',
	KEEPNULLS 
)

SET @NB = @@ROWCOUNT
UPDATE L_RECUPERATION_ESTIA SET IND_SUCCES = 'O', DT_FIN = GETDATE(), NB_LIGNES = @NB WHERE ID_LOG = @ID_LOG


--HQRBAIL: TABLE D'HISTORIQUE DE RENOUVELLEMENT DES BAUX
INSERT INTO L_RECUPERATION_ESTIA (NOM_TABLE, IND_SUCCES, DT_DEBUT) VALUES ('HQRBAIL', 'N', GETDATE())
SET @ID_LOG = @@IDENTITY
TRUNCATE TABLE HQRBAIL

BULK INSERT HQRBAIL
FROM 'C:\ESTIA_DATA\HQRBAIL.csv'
WITH
(
    FIRSTROW = 2,
    FIELDTERMINATOR = ';',  --CSV field delimiter
    ROWTERMINATOR = '\n',   --Use to shift the control to next row
    TABLOCK,
	CODEPAGE  = '65001',
	KEEPNULLS 
)

SET @NB = @@ROWCOUNT
UPDATE L_RECUPERATION_ESTIA SET IND_SUCCES = 'O', DT_FIN = GETDATE(), NB_LIGNES = @NB WHERE ID_LOG = @ID_LOG


--HREVI: TABLE D'HISTORIQUE DES REVISIONS
INSERT INTO L_RECUPERATION_ESTIA (NOM_TABLE, IND_SUCCES, DT_DEBUT) VALUES ('HREVI', 'N', GETDATE())
SET @ID_LOG = @@IDENTITY
TRUNCATE TABLE HREVI

BULK INSERT HREVI
FROM 'C:\ESTIA_DATA\HREVI.csv'
WITH
(
    FIRSTROW = 2,
    FIELDTERMINATOR = ';',  --CSV field delimiter
    ROWTERMINATOR = '\n',   --Use to shift the control to next row
    TABLOCK,
	CODEPAGE  = '65001',
	KEEPNULLS 
)
SET @NB = @@ROWCOUNT
UPDATE L_RECUPERATION_ESTIA SET IND_SUCCES = 'O', DT_FIN = GETDATE(), NB_LIGNES = @NB WHERE ID_LOG = @ID_LOG


--HTRCA: TABLE DES TRANCHES DE CA table non utilisee par SWISS LIFE
/*
INSERT INTO L_RECUPERATION_ESTIA (NOM_TABLE, IND_SUCCES, DT_DEBUT) VALUES ('HTRCA', 'N', GETDATE())
SET @ID_LOG = @@IDENTITY
TRUNCATE TABLE HTRCA

BULK INSERT HTRCA
FROM 'C:\ESTIA_DATA\HTRCA.csv'
WITH
(
    FIRSTROW = 2,
    FIELDTERMINATOR = ';',  --CSV field delimiter
    ROWTERMINATOR = '\n',   --Use to shift the control to next row
    TABLOCK,
	CODEPAGE  = '65001',
	KEEPNULLS 
)

SET @NB = @@ROWCOUNT
UPDATE L_RECUPERATION_ESTIA SET IND_SUCCES = 'O', DT_FIN = GETDATE(), NB_LIGNES = @NB WHERE ID_LOG = @ID_LOG
*/

--IMMEUB: TABLE DES IMMEUBLES
INSERT INTO L_RECUPERATION_ESTIA (NOM_TABLE, IND_SUCCES, DT_DEBUT) VALUES ('IMMEUB', 'N', GETDATE())
SET @ID_LOG = @@IDENTITY
TRUNCATE TABLE IMMEUB

BULK INSERT IMMEUB
FROM 'C:\ESTIA_DATA\IMMEUB.csv'
WITH
(
    FIRSTROW = 2,
    FIELDTERMINATOR = ';',  --CSV field delimiter
    ROWTERMINATOR = '\n',   --Use to shift the control to next row
    TABLOCK,
	CODEPAGE  = '65001',
	KEEPNULLS 
)

SET @NB = @@ROWCOUNT
UPDATE L_RECUPERATION_ESTIA SET IND_SUCCES = 'O', DT_FIN = GETDATE(), NB_LIGNES = @NB WHERE ID_LOG = @ID_LOG


--INDICE: TABLE DE VALEURS DES INDICES DE REVISION
INSERT INTO L_RECUPERATION_ESTIA (NOM_TABLE, IND_SUCCES, DT_DEBUT) VALUES ('INDICE', 'N', GETDATE())
SET @ID_LOG = @@IDENTITY
TRUNCATE TABLE INDICE

BULK INSERT INDICE
FROM 'C:\ESTIA_DATA\INDICE.csv'
WITH
(
    FIRSTROW = 2,
    FIELDTERMINATOR = ';',  --CSV field delimiter
    ROWTERMINATOR = '\n',   --Use to shift the control to next row
    TABLOCK,
	CODEPAGE  = '65001',
	KEEPNULLS 
)

SET @NB = @@ROWCOUNT
UPDATE L_RECUPERATION_ESTIA SET IND_SUCCES = 'O', DT_FIN = GETDATE(), NB_LIGNES = @NB WHERE ID_LOG = @ID_LOG



--ESTIA_INTBT: TABLE DES BONS DE TRAVAUX
INSERT INTO L_RECUPERATION_ESTIA (NOM_TABLE, IND_SUCCES, DT_DEBUT) VALUES ('INTBT', 'N', GETDATE())
SET @ID_LOG = @@IDENTITY
TRUNCATE TABLE INTBT

BULK INSERT INTBT
FROM 'C:\ESTIA_DATA\INTBT.csv'
WITH
(
    FIRSTROW = 2,
    FIELDTERMINATOR = ';',  --CSV field delimiter
    ROWTERMINATOR = '\n',   --Use to shift the control to next row
    TABLOCK,
	CODEPAGE  = '65001',
	KEEPNULLS 
)

SET @NB = @@ROWCOUNT
UPDATE L_RECUPERATION_ESTIA SET IND_SUCCES = 'O', DT_FIN = GETDATE(), NB_LIGNES = @NB WHERE ID_LOG = @ID_LOG


--JOURNAL: TABLE DES JOURNAUX
INSERT INTO L_RECUPERATION_ESTIA (NOM_TABLE, IND_SUCCES, DT_DEBUT) VALUES ('JOURNAL', 'N', GETDATE())
SET @ID_LOG = @@IDENTITY
TRUNCATE TABLE JOURNAL

BULK INSERT JOURNAL
FROM 'C:\ESTIA_DATA\JOURNAL.csv'
WITH
(
    FIRSTROW = 2,
    FIELDTERMINATOR = ';',  --CSV field delimiter
    ROWTERMINATOR = '\n',   --Use to shift the control to next row
    TABLOCK,
	CODEPAGE  = '65001',
	KEEPNULLS 
)

SET @NB = @@ROWCOUNT
UPDATE L_RECUPERATION_ESTIA SET IND_SUCCES = 'O', DT_FIN = GETDATE(), NB_LIGNES = @NB WHERE ID_LOG = @ID_LOG


--LCAUTION: TABLE DES CAUTIONS
INSERT INTO L_RECUPERATION_ESTIA (NOM_TABLE, IND_SUCCES, DT_DEBUT) VALUES ('LCAUTION', 'N', GETDATE())
SET @ID_LOG = @@IDENTITY
TRUNCATE TABLE LCAUTION

BULK INSERT LCAUTION
FROM 'C:\ESTIA_DATA\LCAUTION.csv'
WITH
(
    FIRSTROW = 2,
    FIELDTERMINATOR = ';',  --CSV field delimiter
    ROWTERMINATOR = '\n',   --Use to shift the control to next row
    TABLOCK,
	CODEPAGE  = '65001',
	KEEPNULLS 
)

SET @NB = @@ROWCOUNT
UPDATE L_RECUPERATION_ESTIA SET IND_SUCCES = 'O', DT_FIN = GETDATE(), NB_LIGNES = @NB WHERE ID_LOG = @ID_LOG


--LBUDLOC: TABLE  
INSERT INTO L_RECUPERATION_ESTIA (NOM_TABLE, IND_SUCCES, DT_DEBUT) VALUES ('LBUDLOC', 'N', GETDATE())
SET @ID_LOG = @@IDENTITY
TRUNCATE TABLE LBUDLOC

BULK INSERT LBUDLOC
FROM 'C:\ESTIA_DATA\LBUDLOC.csv'
WITH
(
    FIRSTROW = 2,
    FIELDTERMINATOR = ';',  --CSV field delimiter
    ROWTERMINATOR = '\n',   --Use to shift the control to next row
    TABLOCK,
	CODEPAGE  = '65001',
	KEEPNULLS 
)

SET @NB = @@ROWCOUNT
UPDATE L_RECUPERATION_ESTIA SET IND_SUCCES = 'O', DT_FIN = GETDATE(), NB_LIGNES = @NB WHERE ID_LOG = @ID_LOG


--LIENBN: TABLE DES FACTURES FOURNISSEUR ASSOCIES
INSERT INTO L_RECUPERATION_ESTIA (NOM_TABLE, IND_SUCCES, DT_DEBUT) VALUES ('LIENBN', 'N', GETDATE())
SET @ID_LOG = @@IDENTITY
TRUNCATE TABLE LIENBN

BULK INSERT LIENBN
FROM 'C:\ESTIA_DATA\LIENBN.csv'
WITH
(
    FIRSTROW = 2,
    FIELDTERMINATOR = ';',  --CSV field delimiter
    ROWTERMINATOR = '\n',   --Use to shift the control to next row
    TABLOCK,
	CODEPAGE  = '65001',
	KEEPNULLS 
)

SET @NB = @@ROWCOUNT
UPDATE L_RECUPERATION_ESTIA SET IND_SUCCES = 'O', DT_FIN = GETDATE(), NB_LIGNES = @NB WHERE ID_LOG = @ID_LOG


--LIENLOC: TABLE DES LIENS ENTRE LES LOCAUX ET LES COMPTES
INSERT INTO L_RECUPERATION_ESTIA (NOM_TABLE, IND_SUCCES, DT_DEBUT) VALUES ('LIENLOC', 'N', GETDATE())
SET @ID_LOG = @@IDENTITY
TRUNCATE TABLE LIENLOC

BULK INSERT LIENLOC
FROM 'C:\ESTIA_DATA\LIENLOC.csv'
WITH
(
    FIRSTROW = 2,
    FIELDTERMINATOR = ';',  --CSV field delimiter
    ROWTERMINATOR = '\n',   --Use to shift the control to next row
    TABLOCK,
	CODEPAGE  = '65001',
	KEEPNULLS 
)

SET @NB = @@ROWCOUNT
UPDATE L_RECUPERATION_ESTIA SET IND_SUCCES = 'O', DT_FIN = GETDATE(), NB_LIGNES = @NB WHERE ID_LOG = @ID_LOG


--LIENV: TABLE DES LIENS
INSERT INTO L_RECUPERATION_ESTIA (NOM_TABLE, IND_SUCCES, DT_DEBUT) VALUES ('LIENV', 'N', GETDATE())
SET @ID_LOG = @@IDENTITY
TRUNCATE TABLE LIENV

BULK INSERT LIENV
FROM 'C:\ESTIA_DATA\LIENV.csv'
WITH
(
    FIRSTROW = 2,
    FIELDTERMINATOR = ';',  --CSV field delimiter
    ROWTERMINATOR = '\n',   --Use to shift the control to next row
    TABLOCK,
	CODEPAGE  = '65001',
	KEEPNULLS 
)

SET @NB = @@ROWCOUNT
UPDATE L_RECUPERATION_ESTIA SET IND_SUCCES = 'O', DT_FIN = GETDATE(), NB_LIGNES = @NB WHERE ID_LOG = @ID_LOG


--LOCAL: TABLE DES LOCAUX
INSERT INTO L_RECUPERATION_ESTIA (NOM_TABLE, IND_SUCCES, DT_DEBUT) VALUES ('LOCAL', 'N', GETDATE())
SET @ID_LOG = @@IDENTITY
TRUNCATE TABLE LOCAL

BULK INSERT LOCAL
FROM 'C:\ESTIA_DATA\LOCAL.csv'
WITH
(
    FIRSTROW = 2,
    FIELDTERMINATOR = ';',  --CSV field delimiter
    ROWTERMINATOR = '\n',   --Use to shift the control to next row
    TABLOCK,
	CODEPAGE  = '65001',
	KEEPNULLS 
)

SET @NB = @@ROWCOUNT
UPDATE L_RECUPERATION_ESTIA SET IND_SUCCES = 'O', DT_FIN = GETDATE(), NB_LIGNES = @NB WHERE ID_LOG = @ID_LOG


--LIENMO: TABLE DES LIENS MARCHE OPERATION
INSERT INTO L_RECUPERATION_ESTIA (NOM_TABLE, IND_SUCCES, DT_DEBUT) VALUES ('LIENMO', 'N', GETDATE())
SET @ID_LOG = @@IDENTITY
TRUNCATE TABLE LIENMO

BULK INSERT LIENMO
FROM 'C:\ESTIA_DATA\LIENMO.csv'
WITH
(
    FIRSTROW = 2,
    FIELDTERMINATOR = ';',  --CSV field delimiter
    ROWTERMINATOR = '\n',   --Use to shift the control to next row
    TABLOCK,
	CODEPAGE  = '65001',
	KEEPNULLS 
)

SET @NB = @@ROWCOUNT
UPDATE L_RECUPERATION_ESTIA SET IND_SUCCES = 'O', DT_FIN = GETDATE(), NB_LIGNES = @NB WHERE ID_LOG = @ID_LOG


--LOCASSUR: TABLE DES CONTRATS D'ASSURANCE
INSERT INTO L_RECUPERATION_ESTIA (NOM_TABLE, IND_SUCCES, DT_DEBUT) VALUES ('LOCASSUR', 'N', GETDATE())
SET @ID_LOG = @@IDENTITY
TRUNCATE TABLE LOCASSUR

BULK INSERT LOCASSUR
FROM 'C:\ESTIA_DATA\LOCASSUR.csv'
WITH
(
    FIRSTROW = 2,
    FIELDTERMINATOR = ';',  --CSV field delimiter
    ROWTERMINATOR = '\n',   --Use to shift the control to next row
    TABLOCK,
	CODEPAGE  = '65001',
	KEEPNULLS 
)

SET @NB = @@ROWCOUNT
UPDATE L_RECUPERATION_ESTIA SET IND_SUCCES = 'O', DT_FIN = GETDATE(), NB_LIGNES = @NB WHERE ID_LOG = @ID_LOG


--LOCATION: TABLE DES BAUX
INSERT INTO L_RECUPERATION_ESTIA (NOM_TABLE, IND_SUCCES, DT_DEBUT) VALUES ('LOCATION', 'N', GETDATE())
SET @ID_LOG = @@IDENTITY
TRUNCATE TABLE LOCATION

BULK INSERT LOCATION
FROM 'C:\ESTIA_DATA\LOCATION.csv'
WITH
(
    FIRSTROW = 2,
    FIELDTERMINATOR = ';',  --CSV field delimiter
    ROWTERMINATOR = '\n',   --Use to shift the control to next row
    TABLOCK,
	CODEPAGE  = '65001',
	KEEPNULLS 
)

SET @NB = @@ROWCOUNT
UPDATE L_RECUPERATION_ESTIA SET IND_SUCCES = 'O', DT_FIN = GETDATE(), NB_LIGNES = @NB WHERE ID_LOG = @ID_LOG


--MANSEC: TABLE DES MANSEC
INSERT INTO L_RECUPERATION_ESTIA (NOM_TABLE, IND_SUCCES, DT_DEBUT) VALUES ('MANSEC', 'N', GETDATE())
SET @ID_LOG = @@IDENTITY
TRUNCATE TABLE MANSEC

BULK INSERT MANSEC
FROM 'C:\ESTIA_DATA\MANSEC.csv'
WITH
(
    FIRSTROW = 2,
    FIELDTERMINATOR = ';',  --CSV field delimiter
    ROWTERMINATOR = '\n',   --Use to shift the control to next row
    TABLOCK,
	CODEPAGE  = '65001',
	KEEPNULLS 
)

SET @NB = @@ROWCOUNT
UPDATE L_RECUPERATION_ESTIA SET IND_SUCCES = 'O', DT_FIN = GETDATE(), NB_LIGNES = @NB WHERE ID_LOG = @ID_LOG


--MANGES: TABLE DES MANDATS
INSERT INTO L_RECUPERATION_ESTIA (NOM_TABLE, IND_SUCCES, DT_DEBUT) VALUES ('MANGES', 'N', GETDATE())
SET @ID_LOG = @@IDENTITY
TRUNCATE TABLE MANGES

BULK INSERT MANGES
FROM 'C:\ESTIA_DATA\MANGES.csv'
WITH
(
    FIRSTROW = 2,
    FIELDTERMINATOR = ';',  --CSV field delimiter
    ROWTERMINATOR = '\n',   --Use to shift the control to next row
    TABLOCK,
	CODEPAGE  = '65001',
	KEEPNULLS 
)

SET @NB = @@ROWCOUNT
UPDATE L_RECUPERATION_ESTIA SET IND_SUCCES = 'O', DT_FIN = GETDATE(), NB_LIGNES = @NB WHERE ID_LOG = @ID_LOG


--MANPAT: TABLE DE RATTACHEMENT DU PATRIMOINE AUX MANDATS (NIVEAU SELON COLONNE NIVEAU SUR MANGES - G POUR GROUPE, I POUR IMMEUBLE ET L POUR LOCAL)
INSERT INTO L_RECUPERATION_ESTIA (NOM_TABLE, IND_SUCCES, DT_DEBUT) VALUES ('MANPAT', 'N', GETDATE())
SET @ID_LOG = @@IDENTITY
TRUNCATE TABLE MANPAT

BULK INSERT MANPAT
FROM 'C:\ESTIA_DATA\MANPAT.csv'
WITH
(
    FIRSTROW = 2,
    FIELDTERMINATOR = ';',  --CSV field delimiter
    ROWTERMINATOR = '\n',   --Use to shift the control to next row
    TABLOCK,
	CODEPAGE  = '65001',
	KEEPNULLS 
)

SET @NB = @@ROWCOUNT
UPDATE L_RECUPERATION_ESTIA SET IND_SUCCES = 'O', DT_FIN = GETDATE(), NB_LIGNES = @NB WHERE ID_LOG = @ID_LOG


--MANPROP: TABLE DES PROPRIETAIRES LIES AUX MANDATS
INSERT INTO L_RECUPERATION_ESTIA (NOM_TABLE, IND_SUCCES, DT_DEBUT) VALUES ('MANPROP', 'N', GETDATE())
SET @ID_LOG = @@IDENTITY
TRUNCATE TABLE MANPROP

BULK INSERT MANPROP
FROM 'C:\ESTIA_DATA\MANPROP.csv'
WITH
(
    FIRSTROW = 2,
    FIELDTERMINATOR = ';',  --CSV field delimiter
    ROWTERMINATOR = '\n',   --Use to shift the control to next row
    TABLOCK,
	CODEPAGE  = '65001',
	KEEPNULLS 
)

SET @NB = @@ROWCOUNT
UPDATE L_RECUPERATION_ESTIA SET IND_SUCCES = 'O', DT_FIN = GETDATE(), NB_LIGNES = @NB WHERE ID_LOG = @ID_LOG


--MANTVA: TABLE D'HISTORIQUE DE PRORATA DE TVA PAR MANDAT
INSERT INTO L_RECUPERATION_ESTIA (NOM_TABLE, IND_SUCCES, DT_DEBUT) VALUES ('MANTVA', 'N', GETDATE())
SET @ID_LOG = @@IDENTITY
TRUNCATE TABLE MANTVA

BULK INSERT MANTVA
FROM 'C:\ESTIA_DATA\MANTVA.csv'
WITH
(
    FIRSTROW = 2,
    FIELDTERMINATOR = ';',  --CSV field delimiter
    ROWTERMINATOR = '\n',   --Use to shift the control to next row
    TABLOCK,
	CODEPAGE  = '65001',
	KEEPNULLS 
)

SET @NB = @@ROWCOUNT
UPDATE L_RECUPERATION_ESTIA SET IND_SUCCES = 'O', DT_FIN = GETDATE(), NB_LIGNES = @NB WHERE ID_LOG = @ID_LOG


--MENPRIN: TABLE
INSERT INTO L_RECUPERATION_ESTIA (NOM_TABLE, IND_SUCCES, DT_DEBUT) VALUES ('MENPRIN', 'N', GETDATE())
SET @ID_LOG = @@IDENTITY
TRUNCATE TABLE MENPRIN

BULK INSERT MENPRIN
FROM 'C:\ESTIA_DATA\MENPRIN.csv'
WITH
(
    FIRSTROW = 2,
    FIELDTERMINATOR = ';',  --CSV field delimiter
    ROWTERMINATOR = '\n',   --Use to shift the control to next row
    TABLOCK,
	CODEPAGE  = '65001',
	KEEPNULLS 
)

SET @NB = @@ROWCOUNT
UPDATE L_RECUPERATION_ESTIA SET IND_SUCCES = 'O', DT_FIN = GETDATE(), NB_LIGNES = @NB WHERE ID_LOG = @ID_LOG


--METREV: TABLE DES METHODES RE REVISION
INSERT INTO L_RECUPERATION_ESTIA (NOM_TABLE, IND_SUCCES, DT_DEBUT) VALUES ('METREV', 'N', GETDATE())
SET @ID_LOG = @@IDENTITY
TRUNCATE TABLE METREV

BULK INSERT METREV
FROM 'C:\ESTIA_DATA\METREV.csv'
WITH
(
    FIRSTROW = 2,
    FIELDTERMINATOR = ';',  --CSV field delimiter
    ROWTERMINATOR = '\n',   --Use to shift the control to next row
    TABLOCK,
	CODEPAGE  = '65001',
	KEEPNULLS 
)

SET @NB = @@ROWCOUNT
UPDATE L_RECUPERATION_ESTIA SET IND_SUCCES = 'O', DT_FIN = GETDATE(), NB_LIGNES = @NB WHERE ID_LOG = @ID_LOG


--MODREG: TABLE DES MODES DE REGLEMENT
INSERT INTO L_RECUPERATION_ESTIA (NOM_TABLE, IND_SUCCES, DT_DEBUT) VALUES ('MODREG', 'N', GETDATE())
SET @ID_LOG = @@IDENTITY
TRUNCATE TABLE MODREG

BULK INSERT MODREG
FROM 'C:\ESTIA_DATA\MODREG.csv'
WITH
(
    FIRSTROW = 2,
    FIELDTERMINATOR = ';',  --CSV field delimiter
    ROWTERMINATOR = '\n',   --Use to shift the control to next row
    TABLOCK,
	CODEPAGE  = '65001',
	KEEPNULLS 
)

SET @NB = @@ROWCOUNT
UPDATE L_RECUPERATION_ESTIA SET IND_SUCCES = 'O', DT_FIN = GETDATE(), NB_LIGNES = @NB WHERE ID_LOG = @ID_LOG


--MOTDDE: TABLE DES MOTIFS DE CONGE
INSERT INTO L_RECUPERATION_ESTIA (NOM_TABLE, IND_SUCCES, DT_DEBUT) VALUES ('MOTDDE', 'N', GETDATE())
SET @ID_LOG = @@IDENTITY
TRUNCATE TABLE MOTDDE

BULK INSERT MOTDDE
FROM 'C:\ESTIA_DATA\MOTDDE.csv'
WITH
(
    FIRSTROW = 2,
    FIELDTERMINATOR = ';',  --CSV field delimiter
    ROWTERMINATOR = '\n',   --Use to shift the control to next row
    TABLOCK,
	CODEPAGE  = '65001',
	KEEPNULLS 
)

SET @NB = @@ROWCOUNT
UPDATE L_RECUPERATION_ESTIA SET IND_SUCCES = 'O', DT_FIN = GETDATE(), NB_LIGNES = @NB WHERE ID_LOG = @ID_LOG


--MOTIF: TABLE DES MOTIFS
INSERT INTO L_RECUPERATION_ESTIA (NOM_TABLE, IND_SUCCES, DT_DEBUT) VALUES ('MOTIF', 'N', GETDATE())
SET @ID_LOG = @@IDENTITY
TRUNCATE TABLE MOTIF

BULK INSERT MOTIF
FROM 'C:\ESTIA_DATA\MOTIF.csv'
WITH
(
    FIRSTROW = 2,
    FIELDTERMINATOR = ';',  --CSV field delimiter
    ROWTERMINATOR = '\n',   --Use to shift the control to next row
    TABLOCK,
	CODEPAGE  = '65001',
	KEEPNULLS 
)

SET @NB = @@ROWCOUNT
UPDATE L_RECUPERATION_ESTIA SET IND_SUCCES = 'O', DT_FIN = GETDATE(), NB_LIGNES = @NB WHERE ID_LOG = @ID_LOG


--MOTVAC: TABLE DES MOTIFS DE VACANCE
INSERT INTO L_RECUPERATION_ESTIA (NOM_TABLE, IND_SUCCES, DT_DEBUT) VALUES ('MOTVAC', 'N', GETDATE())
SET @ID_LOG = @@IDENTITY
TRUNCATE TABLE MOTVAC

BULK INSERT MOTVAC
FROM 'C:\ESTIA_DATA\MOTVAC.csv'
WITH
(
    FIRSTROW = 2,
    FIELDTERMINATOR = ';',  --CSV field delimiter
    ROWTERMINATOR = '\n',   --Use to shift the control to next row
    TABLOCK,
	CODEPAGE  = '65001',
	KEEPNULLS 
)

SET @NB = @@ROWCOUNT
UPDATE L_RECUPERATION_ESTIA SET IND_SUCCES = 'O', DT_FIN = GETDATE(), NB_LIGNES = @NB WHERE ID_LOG = @ID_LOG


--NEGOCH: TABLE DES NEGOCIATIONS DE CHARGES
INSERT INTO L_RECUPERATION_ESTIA (NOM_TABLE, IND_SUCCES, DT_DEBUT) VALUES ('NEGOCH', 'N', GETDATE())
SET @ID_LOG = @@IDENTITY
TRUNCATE TABLE NEGOCH

BULK INSERT NEGOCH
FROM 'C:\ESTIA_DATA\NEGOCH.csv'
WITH
(
    FIRSTROW = 2,
    FIELDTERMINATOR = ';',  --CSV field delimiter
    ROWTERMINATOR = '\n',   --Use to shift the control to next row
    TABLOCK,
	CODEPAGE  = '65001',
	KEEPNULLS 
)

SET @NB = @@ROWCOUNT
UPDATE L_RECUPERATION_ESTIA SET IND_SUCCES = 'O', DT_FIN = GETDATE(), NB_LIGNES = @NB WHERE ID_LOG = @ID_LOG


--NATRUB: TABLE DES NATURES DE TARIF
INSERT INTO L_RECUPERATION_ESTIA (NOM_TABLE, IND_SUCCES, DT_DEBUT) VALUES ('NATRUB', 'N', GETDATE())
SET @ID_LOG = @@IDENTITY
TRUNCATE TABLE NATRUB

BULK INSERT NATRUB
FROM 'C:\ESTIA_DATA\NATRUB.csv'
WITH
(
    FIRSTROW = 2,
    FIELDTERMINATOR = ';',  --CSV field delimiter
    ROWTERMINATOR = '\n',   --Use to shift the control to next row
    TABLOCK,
	CODEPAGE  = '65001',
	KEEPNULLS 
)

SET @NB = @@ROWCOUNT
UPDATE L_RECUPERATION_ESTIA SET IND_SUCCES = 'O', DT_FIN = GETDATE(), NB_LIGNES = @NB WHERE ID_LOG = @ID_LOG


--NUMI: TABLE DES INDICES DE REVISION
INSERT INTO L_RECUPERATION_ESTIA (NOM_TABLE, IND_SUCCES, DT_DEBUT) VALUES ('NUMI', 'N', GETDATE())
SET @ID_LOG = @@IDENTITY
TRUNCATE TABLE NUMI

BULK INSERT NUMI
FROM 'C:\ESTIA_DATA\NUMI.csv'
WITH
(
    FIRSTROW = 2,
    FIELDTERMINATOR = ';',  --CSV field delimiter
    ROWTERMINATOR = '\n',   --Use to shift the control to next row
    TABLOCK,
	CODEPAGE  = '65001',
	KEEPNULLS 
)

SET @NB = @@ROWCOUNT
UPDATE L_RECUPERATION_ESTIA SET IND_SUCCES = 'O', DT_FIN = GETDATE(), NB_LIGNES = @NB WHERE ID_LOG = @ID_LOG


--ORG: TABLE DES ORGANISATIONS
INSERT INTO L_RECUPERATION_ESTIA (NOM_TABLE, IND_SUCCES, DT_DEBUT) VALUES ('ORG', 'N', GETDATE())
SET @ID_LOG = @@IDENTITY
TRUNCATE TABLE ORG

BULK INSERT ORG
FROM 'C:\ESTIA_DATA\ORG.csv'
WITH
(
    FIRSTROW = 2,
    FIELDTERMINATOR = ';',  --CSV field delimiter
    ROWTERMINATOR = '\n',   --Use to shift the control to next row
    TABLOCK,
	CODEPAGE  = '65001',
	KEEPNULLS 
)

SET @NB = @@ROWCOUNT
UPDATE L_RECUPERATION_ESTIA SET IND_SUCCES = 'O', DT_FIN = GETDATE(), NB_LIGNES = @NB WHERE ID_LOG = @ID_LOG


--PAYS: TABLE DES PAYS
INSERT INTO L_RECUPERATION_ESTIA (NOM_TABLE, IND_SUCCES, DT_DEBUT) VALUES ('PAYS', 'N', GETDATE())
SET @ID_LOG = @@IDENTITY
TRUNCATE TABLE PAYS

BULK INSERT PAYS
FROM 'C:\ESTIA_DATA\PAYS.csv'
WITH
(
    FIRSTROW = 2,
    FIELDTERMINATOR = ';',  --CSV field delimiter
    ROWTERMINATOR = '\n',   --Use to shift the control to next row
    TABLOCK,
	CODEPAGE  = '65001',
	KEEPNULLS 
)

SET @NB = @@ROWCOUNT
UPDATE L_RECUPERATION_ESTIA SET IND_SUCCES = 'O', DT_FIN = GETDATE(), NB_LIGNES = @NB WHERE ID_LOG = @ID_LOG


--PDEPOP: TABLE DE DEPENSES REELLES D'UNE OPERATION table non utilisee par SWISS LIFE
INSERT INTO L_RECUPERATION_ESTIA (NOM_TABLE, IND_SUCCES, DT_DEBUT) VALUES ('PDEPOP', 'N', GETDATE())
SET @ID_LOG = @@IDENTITY
TRUNCATE TABLE PDEPOP

BULK INSERT PDEPOP
FROM 'C:\ESTIA_DATA\PDEPOP.csv'
WITH
(
    FIRSTROW = 2,
    FIELDTERMINATOR = ';',  --CSV field delimiter
    ROWTERMINATOR = '\n',   --Use to shift the control to next row
    TABLOCK,
	CODEPAGE  = '65001',
	KEEPNULLS 
)

SET @NB = @@ROWCOUNT
UPDATE L_RECUPERATION_ESTIA SET IND_SUCCES = 'O', DT_FIN = GETDATE(), NB_LIGNES = @NB WHERE ID_LOG = @ID_LOG


--PABASIT: TABLE D'HISTORIQUE DES ABATEMENTS POUR SITUATIONS PROMOTION
INSERT INTO L_RECUPERATION_ESTIA (NOM_TABLE, IND_SUCCES, DT_DEBUT) VALUES ('PABASIT', 'N', GETDATE())
SET @ID_LOG = @@IDENTITY
TRUNCATE TABLE PABASIT

BULK INSERT PABASIT
FROM 'C:\ESTIA_DATA\PABASIT.csv'
WITH
(
    FIRSTROW = 2,
    FIELDTERMINATOR = ';',  --CSV field delimiter
    ROWTERMINATOR = '\n',   --Use to shift the control to next row
    TABLOCK,
	CODEPAGE  = '65001',
	KEEPNULLS 
)

SET @NB = @@ROWCOUNT
UPDATE L_RECUPERATION_ESTIA SET IND_SUCCES = 'O', DT_FIN = GETDATE(), NB_LIGNES = @NB WHERE ID_LOG = @ID_LOG



--PCRITDEP: VENTILATION DES POSTES DE DEPENSE
INSERT INTO L_RECUPERATION_ESTIA (NOM_TABLE, IND_SUCCES, DT_DEBUT) VALUES ('PCRITDEP', 'N', GETDATE())
SET @ID_LOG = @@IDENTITY
TRUNCATE TABLE PCRITDEP

BULK INSERT PCRITDEP
FROM 'C:\ESTIA_DATA\PCRITDEP.csv'
WITH
(
    FIRSTROW = 2,
    FIELDTERMINATOR = ';',  --CSV field delimiter
    ROWTERMINATOR = '\n',   --Use to shift the control to next row
    TABLOCK,
	CODEPAGE  = '65001',
	KEEPNULLS 
)

SET @NB = @@ROWCOUNT
UPDATE L_RECUPERATION_ESTIA SET IND_SUCCES = 'O', DT_FIN = GETDATE(), NB_LIGNES = @NB WHERE ID_LOG = @ID_LOG


--PDEPR: Postes de dépenses GO
INSERT INTO L_RECUPERATION_ESTIA (NOM_TABLE, IND_SUCCES, DT_DEBUT) VALUES ('PDEPR', 'N', GETDATE())
SET @ID_LOG = @@IDENTITY
TRUNCATE TABLE PDEPR

BULK INSERT PDEPR
FROM 'C:\ESTIA_DATA\PDEPR.csv'
WITH
(
    FIRSTROW = 2,
    FIELDTERMINATOR = ';',  --CSV field delimiter
    ROWTERMINATOR = '\n',   --Use to shift the control to next row
    TABLOCK,
	CODEPAGE  = '65001',
	KEEPNULLS 
)

SET @NB = @@ROWCOUNT
UPDATE L_RECUPERATION_ESTIA SET IND_SUCCES = 'O', DT_FIN = GETDATE(), NB_LIGNES = @NB WHERE ID_LOG = @ID_LOG


--PECRIP: TABLE  
INSERT INTO L_RECUPERATION_ESTIA (NOM_TABLE, IND_SUCCES, DT_DEBUT) VALUES ('PECRIP', 'N', GETDATE())
SET @ID_LOG = @@IDENTITY
TRUNCATE TABLE PECRIP

BULK INSERT PECRIP
FROM 'C:\ESTIA_DATA\PECRIP.csv'
WITH
(
    FIRSTROW = 2,
    FIELDTERMINATOR = ';',  --CSV field delimiter
    ROWTERMINATOR = '\n',   --Use to shift the control to next row
    TABLOCK,
	CODEPAGE  = '65001',
	KEEPNULLS 
)

SET @NB = @@ROWCOUNT
UPDATE L_RECUPERATION_ESTIA SET IND_SUCCES = 'O', DT_FIN = GETDATE(), NB_LIGNES = @NB WHERE ID_LOG = @ID_LOG


--PERIODICITE: TABLE DES PERIODICITES
INSERT INTO L_RECUPERATION_ESTIA (NOM_TABLE, IND_SUCCES, DT_DEBUT) VALUES ('PERIODICITE', 'N', GETDATE())
SET @ID_LOG = @@IDENTITY
TRUNCATE TABLE PERIODICITE

BULK INSERT PERIODICITE
FROM 'C:\ESTIA_DATA\PERIODICITE.csv'
WITH
(
    FIRSTROW = 2,
    FIELDTERMINATOR = ';',  --CSV field delimiter
    ROWTERMINATOR = '\n',   --Use to shift the control to next row
    TABLOCK,
	CODEPAGE  = '65001',
	KEEPNULLS 
)

SET @NB = @@ROWCOUNT
UPDATE L_RECUPERATION_ESTIA SET IND_SUCCES = 'O', DT_FIN = GETDATE(), NB_LIGNES = @NB WHERE ID_LOG = @ID_LOG


--PIOPE: TABLE DES INTERVENANTS DES OPERATIONS (CHANTIERS)
INSERT INTO L_RECUPERATION_ESTIA (NOM_TABLE, IND_SUCCES, DT_DEBUT) VALUES ('PIOPE', 'N', GETDATE())
SET @ID_LOG = @@IDENTITY
TRUNCATE TABLE PIOPE 

BULK INSERT PIOPE
FROM 'C:\ESTIA_DATA\PIOPE.csv'
WITH
(
    FIRSTROW = 2,
    FIELDTERMINATOR = ';',  --CSV field delimiter
    ROWTERMINATOR = '\n',   --Use to shift the control to next row
    TABLOCK,
	CODEPAGE  = '65001',
	KEEPNULLS 
)

SET @NB = @@ROWCOUNT
UPDATE L_RECUPERATION_ESTIA SET IND_SUCCES = 'O', DT_FIN = GETDATE(), NB_LIGNES = @NB WHERE ID_LOG = @ID_LOG


--PLANC: TABLE DES PLANS COMPTABLES
INSERT INTO L_RECUPERATION_ESTIA (NOM_TABLE, IND_SUCCES, DT_DEBUT) VALUES ('PLANC', 'N', GETDATE())
SET @ID_LOG = @@IDENTITY
TRUNCATE TABLE PLANC

BULK INSERT PLANC
FROM 'C:\ESTIA_DATA\PLANC.csv'
WITH
(
    FIRSTROW = 2,
    FIELDTERMINATOR = ';',  --CSV field delimiter
    ROWTERMINATOR = '\n',   --Use to shift the control to next row
    TABLOCK,
	CODEPAGE  = '65001',
	KEEPNULLS 
)

SET @NB = @@ROWCOUNT
UPDATE L_RECUPERATION_ESTIA SET IND_SUCCES = 'O', DT_FIN = GETDATE(), NB_LIGNES = @NB WHERE ID_LOG = @ID_LOG


--PLOCAL: TABLE DES LOCAUX
INSERT INTO L_RECUPERATION_ESTIA (NOM_TABLE, IND_SUCCES, DT_DEBUT) VALUES ('PLOCAL', 'N', GETDATE())
SET @ID_LOG = @@IDENTITY
TRUNCATE TABLE PLOCAL

BULK INSERT PLOCAL
FROM 'C:\ESTIA_DATA\PLOCAL.csv'
WITH
(
    FIRSTROW = 2,
    FIELDTERMINATOR = ';',  --CSV field delimiter
    ROWTERMINATOR = '\n',   --Use to shift the control to next row
    TABLOCK,
	CODEPAGE  = '65001',
	KEEPNULLS 
)

SET @NB = @@ROWCOUNT
UPDATE L_RECUPERATION_ESTIA SET IND_SUCCES = 'O', DT_FIN = GETDATE(), NB_LIGNES = @NB WHERE ID_LOG = @ID_LOG



--POPE: TABLE DES OPERATIONS (CHANTIERS) table non utilisee
INSERT INTO L_RECUPERATION_ESTIA (NOM_TABLE, IND_SUCCES, DT_DEBUT) VALUES ('POPE', 'N', GETDATE())
SET @ID_LOG = @@IDENTITY
TRUNCATE TABLE POPE

BULK INSERT POPE
FROM 'C:\ESTIA_DATA\POPE.csv'
WITH
(
    FIRSTROW = 2,
    FIELDTERMINATOR = ';',  --CSV field delimiter
    ROWTERMINATOR = ';;\n',   --Use to shift the control to next row
    TABLOCK,
	CODEPAGE  = '65001',
	KEEPNULLS 
)

SET @NB = @@ROWCOUNT
UPDATE L_RECUPERATION_ESTIA SET IND_SUCCES = 'O', DT_FIN = GETDATE(), NB_LIGNES = @NB WHERE ID_LOG = @ID_LOG


--POPS1: Ligne de budget GO
INSERT INTO L_RECUPERATION_ESTIA (NOM_TABLE, IND_SUCCES, DT_DEBUT) VALUES ('POPS1', 'N', GETDATE())
SET @ID_LOG = @@IDENTITY
TRUNCATE TABLE POPS1

BULK INSERT POPS1
FROM 'C:\ESTIA_DATA\POPS1.csv'
WITH
(
    FIRSTROW = 2,
    FIELDTERMINATOR = ';',  --CSV field delimiter
    ROWTERMINATOR = '\n',   --Use to shift the control to next row
    TABLOCK,
	CODEPAGE  = '65001',
	KEEPNULLS 
)

SET @NB = @@ROWCOUNT
UPDATE L_RECUPERATION_ESTIA SET IND_SUCCES = 'O', DT_FIN = GETDATE(), NB_LIGNES = @NB WHERE ID_LOG = @ID_LOG


--QC: TABLE DES QUALITES CIVILES
INSERT INTO L_RECUPERATION_ESTIA (NOM_TABLE, IND_SUCCES, DT_DEBUT) VALUES ('QC', 'N', GETDATE())
SET @ID_LOG = @@IDENTITY
TRUNCATE TABLE QC

BULK INSERT QC
FROM 'C:\ESTIA_DATA\QC.csv'
WITH
(
    FIRSTROW = 2,
    FIELDTERMINATOR = ';',  --CSV field delimiter
    ROWTERMINATOR = '\n',   --Use to shift the control to next row
    TABLOCK,
	CODEPAGE  = '65001',
	KEEPNULLS 
)

SET @NB = @@ROWCOUNT
UPDATE L_RECUPERATION_ESTIA SET IND_SUCCES = 'O', DT_FIN = GETDATE(), NB_LIGNES = @NB WHERE ID_LOG = @ID_LOG


--RUB: TABLE DES RUBRIQUES DE QUITTANCEMENT
INSERT INTO L_RECUPERATION_ESTIA (NOM_TABLE, IND_SUCCES, DT_DEBUT) VALUES ('RUB', 'N', GETDATE())
SET @ID_LOG = @@IDENTITY
TRUNCATE TABLE RUB

BULK INSERT RUB
FROM 'C:\ESTIA_DATA\RUB.csv'
WITH
(
    FIRSTROW = 2,
    FIELDTERMINATOR = ';',  --CSV field delimiter
    ROWTERMINATOR = '\n',   --Use to shift the control to next row
    TABLOCK,
	CODEPAGE  = '65001',
	KEEPNULLS 
)

SET @NB = @@ROWCOUNT
UPDATE L_RECUPERATION_ESTIA SET IND_SUCCES = 'O', DT_FIN = GETDATE(), NB_LIGNES = @NB WHERE ID_LOG = @ID_LOG


--RUBPER: TABLE DES PERIODES DE REGULARISATION PAR RUBRIQUE
INSERT INTO L_RECUPERATION_ESTIA (NOM_TABLE, IND_SUCCES, DT_DEBUT) VALUES ('RUBPER', 'N', GETDATE())
SET @ID_LOG = @@IDENTITY
TRUNCATE TABLE RUBPER

BULK INSERT RUBPER
FROM 'C:\ESTIA_DATA\RUBPER.csv'
WITH
(
    FIRSTROW = 2,
    FIELDTERMINATOR = ';',  --CSV field delimiter
    ROWTERMINATOR = '\n',   --Use to shift the control to next row
    TABLOCK,
	CODEPAGE  = '65001',
	KEEPNULLS 
)

SET @NB = @@ROWCOUNT
UPDATE L_RECUPERATION_ESTIA SET IND_SUCCES = 'O', DT_FIN = GETDATE(), NB_LIGNES = @NB WHERE ID_LOG = @ID_LOG


--SCRITDP: TABLE DES SOUS-CRITERES DE DEPENSES
INSERT INTO L_RECUPERATION_ESTIA (NOM_TABLE, IND_SUCCES, DT_DEBUT) VALUES ('SCRITDP', 'N', GETDATE())
SET @ID_LOG = @@IDENTITY
TRUNCATE TABLE SCRITDP

BULK INSERT SCRITDP
FROM 'C:\ESTIA_DATA\SCRITDP.csv'
WITH
(
    FIRSTROW = 2,
    FIELDTERMINATOR = ';',  --CSV field delimiter
    ROWTERMINATOR = '\n',   --Use to shift the control to next row
    TABLOCK,
	CODEPAGE  = '65001',
	KEEPNULLS 
)

SET @NB = @@ROWCOUNT
UPDATE L_RECUPERATION_ESTIA SET IND_SUCCES = 'O', DT_FIN = GETDATE(), NB_LIGNES = @NB WHERE ID_LOG = @ID_LOG


--SURFLOC: TABLE DES SURFACES DES LOTS
INSERT INTO L_RECUPERATION_ESTIA (NOM_TABLE, IND_SUCCES, DT_DEBUT) VALUES ('SURFLOC', 'N', GETDATE())
SET @ID_LOG = @@IDENTITY
TRUNCATE TABLE SURFLOC

BULK INSERT SURFLOC
FROM 'C:\ESTIA_DATA\SURFLOC.csv'
WITH
(
    FIRSTROW = 2,
    FIELDTERMINATOR = ';',  --CSV field delimiter
    ROWTERMINATOR = '\n',   --Use to shift the control to next row
    TABLOCK,
	CODEPAGE  = '65001',
	KEEPNULLS 
)

SET @NB = @@ROWCOUNT
UPDATE L_RECUPERATION_ESTIA SET IND_SUCCES = 'O', DT_FIN = GETDATE(), NB_LIGNES = @NB WHERE ID_LOG = @ID_LOG


--TASS: TABLE TASS
INSERT INTO L_RECUPERATION_ESTIA (NOM_TABLE, IND_SUCCES, DT_DEBUT) VALUES ('TASS', 'N', GETDATE())
SET @ID_LOG = @@IDENTITY
TRUNCATE TABLE TASS

BULK INSERT TASS
FROM 'C:\ESTIA_DATA\TASS.csv'
WITH
(
    FIRSTROW = 2,
    FIELDTERMINATOR = ';',  --CSV field delimiter
    ROWTERMINATOR = '\n',   --Use to shift the control to next row
    TABLOCK,
	CODEPAGE  = '65001',
	KEEPNULLS 
)

SET @NB = @@ROWCOUNT
UPDATE L_RECUPERATION_ESTIA SET IND_SUCCES = 'O', DT_FIN = GETDATE(), NB_LIGNES = @NB WHERE ID_LOG = @ID_LOG


--TAUX: TABLE DES TAUX DE TAXES
TRUNCATE TABLE TAUX

BULK INSERT TAUX
FROM 'C:\ESTIA_DATA\TAUX.csv'
WITH
(
    FIRSTROW = 2,
    FIELDTERMINATOR = ';',  --CSV field delimiter
    ROWTERMINATOR = '\n',   --Use to shift the control to next row
    TABLOCK,
	CODEPAGE  = '65001',
	KEEPNULLS 
)

SET @NB = @@ROWCOUNT
UPDATE L_RECUPERATION_ESTIA SET IND_SUCCES = 'O', DT_FIN = GETDATE(), NB_LIGNES = @NB WHERE ID_LOG = @ID_LOG


--TIERS: TABLE DES TIERS
INSERT INTO L_RECUPERATION_ESTIA (NOM_TABLE, IND_SUCCES, DT_DEBUT) VALUES ('TIERS', 'N', GETDATE())
SET @ID_LOG = @@IDENTITY
TRUNCATE TABLE TIERS

BULK INSERT TIERS
FROM 'C:\ESTIA_DATA\TIERS.csv'
WITH
(
    FIRSTROW = 2,
    FIELDTERMINATOR = ';',  --CSV field delimiter
    ROWTERMINATOR = '\n',   --Use to shift the control to next row
    TABLOCK,
	CODEPAGE  = '65001',
	KEEPNULLS 
)

SET @NB = @@ROWCOUNT
UPDATE L_RECUPERATION_ESTIA SET IND_SUCCES = 'O', DT_FIN = GETDATE(), NB_LIGNES = @NB WHERE ID_LOG = @ID_LOG


--TIERSF: TABLE DES TIERS FOURNISSEURS
INSERT INTO L_RECUPERATION_ESTIA (NOM_TABLE, IND_SUCCES, DT_DEBUT) VALUES ('TIERSF', 'N', GETDATE())
SET @ID_LOG = @@IDENTITY
TRUNCATE TABLE TIERSF

BULK INSERT TIERSF
FROM 'C:\ESTIA_DATA\TIERSF.csv'
WITH
(
    FIRSTROW = 2,
    FIELDTERMINATOR = ';',  --CSV field delimiter
    ROWTERMINATOR = '\n',   --Use to shift the control to next row
    TABLOCK,
	CODEPAGE  = '65001',
	KEEPNULLS 
)

SET @NB = @@ROWCOUNT
UPDATE L_RECUPERATION_ESTIA SET IND_SUCCES = 'O', DT_FIN = GETDATE(), NB_LIGNES = @NB WHERE ID_LOG = @ID_LOG


--TRAIT: TABLE DES ORIGINES DE TRAITEMENT
INSERT INTO L_RECUPERATION_ESTIA (NOM_TABLE, IND_SUCCES, DT_DEBUT) VALUES ('TRAIT', 'N', GETDATE())
SET @ID_LOG = @@IDENTITY
TRUNCATE TABLE TRAIT

BULK INSERT TRAIT
FROM 'C:\ESTIA_DATA\TRAIT.csv'
WITH
(
    FIRSTROW = 2,
    FIELDTERMINATOR = ';',  --CSV field delimiter
    ROWTERMINATOR = '\n',   --Use to shift the control to next row
    TABLOCK,
	CODEPAGE  = '65001',
	KEEPNULLS 
)

SET @NB = @@ROWCOUNT
UPDATE L_RECUPERATION_ESTIA SET IND_SUCCES = 'O', DT_FIN = GETDATE(), NB_LIGNES = @NB WHERE ID_LOG = @ID_LOG


--TRANCHE: TABLE DES TANCHES DES LA GESTION DES OPERATIONS
INSERT INTO L_RECUPERATION_ESTIA (NOM_TABLE, IND_SUCCES, DT_DEBUT) VALUES ('TRANCHE', 'N', GETDATE())
SET @ID_LOG = @@IDENTITY
TRUNCATE TABLE TRANCHE

BULK INSERT TRANCHE
FROM 'C:\ESTIA_DATA\TRANCHE.csv'
WITH
(
    FIRSTROW = 2,
    FIELDTERMINATOR = ';',  --CSV field delimiter
    ROWTERMINATOR = '\n',   --Use to shift the control to next row
    TABLOCK,
	CODEPAGE  = '65001',
	KEEPNULLS 
)

SET @NB = @@ROWCOUNT
UPDATE L_RECUPERATION_ESTIA SET IND_SUCCES = 'O', DT_FIN = GETDATE(), NB_LIGNES = @NB WHERE ID_LOG = @ID_LOG


--TSCAT: TABLE DES CATEGORIES DE TIERS
INSERT INTO L_RECUPERATION_ESTIA (NOM_TABLE, IND_SUCCES, DT_DEBUT) VALUES ('TSCAT', 'N', GETDATE())
SET @ID_LOG = @@IDENTITY
TRUNCATE TABLE TSCAT

BULK INSERT TSCAT
FROM 'C:\ESTIA_DATA\TSCAT.csv'
WITH
(
    FIRSTROW = 2,
    FIELDTERMINATOR = ';',  --CSV field delimiter
    ROWTERMINATOR = '\n',   --Use to shift the control to next row
    TABLOCK,
	CODEPAGE  = '65001',
	KEEPNULLS 
)

SET @NB = @@ROWCOUNT
UPDATE L_RECUPERATION_ESTIA SET IND_SUCCES = 'O', DT_FIN = GETDATE(), NB_LIGNES = @NB WHERE ID_LOG = @ID_LOG


--TSECR: TABLE 
INSERT INTO L_RECUPERATION_ESTIA (NOM_TABLE, IND_SUCCES, DT_DEBUT) VALUES ('TSECR', 'N', GETDATE())
SET @ID_LOG = @@IDENTITY
TRUNCATE TABLE TSECR

BULK INSERT TSECR
FROM 'C:\ESTIA_DATA\TSECR.csv'
WITH
(
    FIRSTROW = 2,
    FIELDTERMINATOR = ';',  --CSV field delimiter
    ROWTERMINATOR = '\n',   --Use to shift the control to next row
    TABLOCK,
	CODEPAGE  = '65001',
	KEEPNULLS 
)

SET @NB = @@ROWCOUNT
UPDATE L_RECUPERATION_ESTIA SET IND_SUCCES = 'O', DT_FIN = GETDATE(), NB_LIGNES = @NB WHERE ID_LOG = @ID_LOG


--TSLIEN: TABLE DES CATEGORIES DE TIERS D'UN TIERS
INSERT INTO L_RECUPERATION_ESTIA (NOM_TABLE, IND_SUCCES, DT_DEBUT) VALUES ('TSLIEN', 'N', GETDATE())
SET @ID_LOG = @@IDENTITY
TRUNCATE TABLE TSLIEN

BULK INSERT TSLIEN
FROM 'C:\ESTIA_DATA\TSLIEN.csv'
WITH
(
    FIRSTROW = 2,
    FIELDTERMINATOR = ';',  --CSV field delimiter
    ROWTERMINATOR = '\n',   --Use to shift the control to next row
    TABLOCK,
	CODEPAGE  = '65001',
	KEEPNULLS 
)

SET @NB = @@ROWCOUNT
UPDATE L_RECUPERATION_ESTIA SET IND_SUCCES = 'O', DT_FIN = GETDATE(), NB_LIGNES = @NB WHERE ID_LOG = @ID_LOG


--TYPLOG: TABLE DES TYPE DE LOCAUX
INSERT INTO L_RECUPERATION_ESTIA (NOM_TABLE, IND_SUCCES, DT_DEBUT) VALUES ('TVA', 'N', GETDATE())
SET @ID_LOG = @@IDENTITY
TRUNCATE TABLE TVA

BULK INSERT TVA
FROM 'C:\ESTIA_DATA\TVA.csv'
WITH
(
    FIRSTROW = 2,
    FIELDTERMINATOR = ';',  --CSV field delimiter
    ROWTERMINATOR = '\n',   --Use to shift the control to next row
    TABLOCK,
	CODEPAGE  = '65001',
	KEEPNULLS 
)

SET @NB = @@ROWCOUNT
UPDATE L_RECUPERATION_ESTIA SET IND_SUCCES = 'O', DT_FIN = GETDATE(), NB_LIGNES = @NB WHERE ID_LOG = @ID_LOG


--TYPCOM: TABLE DES TYPES DE SOUS-COMPTES CLIENTS ET FOURNISSEURS
INSERT INTO L_RECUPERATION_ESTIA (NOM_TABLE, IND_SUCCES, DT_DEBUT) VALUES ('TYPCOM', 'N', GETDATE())
SET @ID_LOG = @@IDENTITY
TRUNCATE TABLE TYPCOM

BULK INSERT TYPCOM
FROM 'C:\ESTIA_DATA\TYPCOM.csv'
WITH
(
    FIRSTROW = 2,
    FIELDTERMINATOR = ';',  --CSV field delimiter
    ROWTERMINATOR = '\n',   --Use to shift the control to next row
    TABLOCK,
	CODEPAGE  = '65001',
	KEEPNULLS 
)

SET @NB = @@ROWCOUNT
UPDATE L_RECUPERATION_ESTIA SET IND_SUCCES = 'O', DT_FIN = GETDATE(), NB_LIGNES = @NB WHERE ID_LOG = @ID_LOG


--TYPECRI: TABLE DES TYPES ECRITURES
INSERT INTO L_RECUPERATION_ESTIA (NOM_TABLE, IND_SUCCES, DT_DEBUT) VALUES ('TYPECRI', 'N', GETDATE())
SET @ID_LOG = @@IDENTITY
TRUNCATE TABLE TYPECRI

BULK INSERT TYPECRI
FROM 'C:\ESTIA_DATA\TYPECRI.csv'
WITH
(
    FIRSTROW = 2,
    FIELDTERMINATOR = ';',  --CSV field delimiter
    ROWTERMINATOR = '\n',   --Use to shift the control to next row
    TABLOCK,
	CODEPAGE  = '65001',
	KEEPNULLS 
)

SET @NB = @@ROWCOUNT
UPDATE L_RECUPERATION_ESTIA SET IND_SUCCES = 'O', DT_FIN = GETDATE(), NB_LIGNES = @NB WHERE ID_LOG = @ID_LOG


--TYPLOG: TABLE DES TYPE DE LOCAUX
INSERT INTO L_RECUPERATION_ESTIA (NOM_TABLE, IND_SUCCES, DT_DEBUT) VALUES ('TYPLOG', 'N', GETDATE())
SET @ID_LOG = @@IDENTITY
TRUNCATE TABLE TYPLOG

BULK INSERT TYPLOG
FROM 'C:\ESTIA_DATA\TYPLOG.csv'
WITH
(
    FIRSTROW = 2,
    FIELDTERMINATOR = ';',  --CSV field delimiter
    ROWTERMINATOR = '\n',   --Use to shift the control to next row
    TABLOCK,
	CODEPAGE  = '65001',
	KEEPNULLS 
)

SET @NB = @@ROWCOUNT
UPDATE L_RECUPERATION_ESTIA SET IND_SUCCES = 'O', DT_FIN = GETDATE(), NB_LIGNES = @NB WHERE ID_LOG = @ID_LOG


--TYPROPR: TABLE DE PLAN DE COMPTE PAR TYPE DE PROPRIETAIRE
INSERT INTO L_RECUPERATION_ESTIA (NOM_TABLE, IND_SUCCES, DT_DEBUT) VALUES ('TYPROPR', 'N', GETDATE())
SET @ID_LOG = @@IDENTITY
TRUNCATE TABLE TYPROPR

BULK INSERT TYPROPR
FROM 'C:\ESTIA_DATA\TYPROPR.csv'
WITH
(
    FIRSTROW = 2,
    FIELDTERMINATOR = ';',  --CSV field delimiter
    ROWTERMINATOR = '\n',   --Use to shift the control to next row
    TABLOCK,
	CODEPAGE  = '65001',
	KEEPNULLS 
)

SET @NB = @@ROWCOUNT
UPDATE L_RECUPERATION_ESTIA SET IND_SUCCES = 'O', DT_FIN = GETDATE(), NB_LIGNES = @NB WHERE ID_LOG = @ID_LOG


--USALOC: TABLE DES USAGES DE LOCAUX
INSERT INTO L_RECUPERATION_ESTIA (NOM_TABLE, IND_SUCCES, DT_DEBUT) VALUES ('USALOC', 'N', GETDATE())
SET @ID_LOG = @@IDENTITY
TRUNCATE TABLE USALOC

BULK INSERT USALOC
FROM 'C:\ESTIA_DATA\USALOC.csv'
WITH
(
    FIRSTROW = 2,
    FIELDTERMINATOR = ';',  --CSV field delimiter
    ROWTERMINATOR = '\n',   --Use to shift the control to next row
    TABLOCK,
	CODEPAGE  = '65001',
	KEEPNULLS 
)

SET @NB = @@ROWCOUNT
UPDATE L_RECUPERATION_ESTIA SET IND_SUCCES = 'O', DT_FIN = GETDATE(), NB_LIGNES = @NB WHERE ID_LOG = @ID_LOG


--VENTPCHA: TABLE DES VENTILATIONS DE FACTURES
INSERT INTO L_RECUPERATION_ESTIA (NOM_TABLE, IND_SUCCES, DT_DEBUT) VALUES ('VENTPCHA', 'N', GETDATE())
SET @ID_LOG = @@IDENTITY
TRUNCATE TABLE VENTPCHA

BULK INSERT VENTPCHA
FROM 'C:\ESTIA_DATA\VENTPCHA.csv'
WITH
(
    FIRSTROW = 2,
    FIELDTERMINATOR = ';',  --CSV field delimiter
    ROWTERMINATOR = '\n',   --Use to shift the control to next row
    TABLOCK,
	CODEPAGE  = '65001',
	KEEPNULLS 
)

SET @NB = @@ROWCOUNT
UPDATE L_RECUPERATION_ESTIA SET IND_SUCCES = 'O', DT_FIN = GETDATE(), NB_LIGNES = @NB WHERE ID_LOG = @ID_LOG

END


