CREATE FUNCTION [dbo].[ALERTES_MAIL] ()
RETURNS VARCHAR(MAX)
AS
BEGIN
	
	DECLARE @PK_TEMPS DATE
	SET @PK_TEMPS = CONVERT(VARCHAR(10), DATEADD(DAY, -1, GETDATE()), 103)
	DECLARE @PARAM VARCHAR(MAX)
	SET @PARAM = CHAR(10) + 'Paramétrage Immeubles Easyfolder et alimentation baux, contrats et opérations vers Easyfolder' + CHAR(10) + '-------------------------------------' + CHAR(10);
	SELECT @PARAM = @PARAM + CASE
				WHEN COUNT(*) > 0 THEN 'Immeuble(s) : ' + CONVERT(VARCHAR(10), COUNT(*)) + ' immeuble(s) non paramétré(s)' + CHAR(10) 
				ELSE '' 
			END 
		FROM P_TRANSCO_IMMEUBLE_EASYFOLDER WHERE NM_IMMEUBLE_ESTIA IS NOT NULL AND CD_IMMEUBLE_DREAM IS NULL;
	SELECT @PARAM = @PARAM + CONVERT(VARCHAR(10), NM_IMMEUBLE_ESTIA) + ' - ' + NOM_IMMEUBLE_DREAM + CHAR(10)
		FROM P_TRANSCO_IMMEUBLE_EASYFOLDER WHERE NM_IMMEUBLE_ESTIA IS NOT NULL AND CD_IMMEUBLE_DREAM IS NULL;

	SELECT @PARAM = @PARAM + CASE
				WHEN COUNT(*) > 0 THEN 'Baux vers Easyfolder : ' + CONVERT(VARCHAR(10), COUNT(*)) + ' bail(ux) en échec' + CHAR(10) 
				ELSE '' 
			END 
		FROM WRK_INTERFACE_EASYFOLDER_BAUX WHERE IFC_STATUT_TRAITEMENT = 'Echec' AND CONVERT(DATE, CONVERT(VARCHAR(10), IFC_DT_TRAITEMENT, 103), 103) = @PK_TEMPS;
	SELECT @PARAM = @PARAM + CONVERT(VARCHAR(10), IDENTIFIANT_BAIL_DREAM) + ' - ' + IDENTIFIANT_DREAM_IMMEUBLE + ' - ' + NOM_IMMEUBLE + ' - ' + CONVERT(VARCHAR(10), IDENTIFIANT_ESTIA_IMMEUBLE) +  '- ' + IFC_ERREUR_TRAITEMENT + CHAR(10)
		FROM WRK_INTERFACE_EASYFOLDER_BAUX WHERE IFC_STATUT_TRAITEMENT = 'Echec' AND CONVERT(DATE, CONVERT(VARCHAR(10), IFC_DT_TRAITEMENT, 103), 103) = @PK_TEMPS;

	SELECT @PARAM = @PARAM + CASE
				WHEN COUNT(*) > 0 THEN 'Contrats vers Easyfolder : ' + CONVERT(VARCHAR(10), COUNT(*)) + ' contrat(s) en échec' + CHAR(10) 
				ELSE '' 
			END 
		FROM WRK_INTERFACE_EASYFOLDER_CONTRATS WHERE IFC_STATUT_TRAITEMENT = 'Echec' AND CONVERT(DATE, CONVERT(VARCHAR(10), IFC_DT_TRAITEMENT, 103), 103) = @PK_TEMPS;
	SELECT @PARAM = @PARAM + IDENTIFIANT_DREAM_IMMEUBLE + ' - ' + CONVERT(VARCHAR(10), IDENTIFIANT_ESTIA_IMMEUBLE) + ' - ' + NOM_IMMEUBLE_ESTIA + ' - ' + CONVERT(VARCHAR(10), NUM_CONTRAT) + '- ' + LB_CONTRAT + ' - ' + IFC_ERREUR_TRAITEMENT + CHAR(10)
		FROM WRK_INTERFACE_EASYFOLDER_CONTRATS WHERE IFC_STATUT_TRAITEMENT = 'Echec' AND CONVERT(DATE, CONVERT(VARCHAR(10), IFC_DT_TRAITEMENT, 103), 103) = @PK_TEMPS;

	SELECT @PARAM = @PARAM + CASE
				WHEN COUNT(*) > 0 THEN 'Opérations vers Easyfolder : ' + CONVERT(VARCHAR(10), COUNT(*)) + ' opération(s) en échec' + CHAR(10) 
				ELSE '' 
			END 
		FROM WRK_INTERFACE_EASYFOLDER_OPERATIONS WHERE IFC_STATUT_TRAITEMENT = 'Echec' AND CONVERT(DATE, CONVERT(VARCHAR(10), IFC_DT_TRAITEMENT, 103), 103) = @PK_TEMPS;
	SELECT @PARAM = @PARAM + CONVERT(VARCHAR(10), CD_IMMEUBLE) + ' - ' + NOM_IMMEUBLE_ESTIA + ' - ' + CD_OPERATION + ' - ' + CONVERT(VARCHAR(10), CD_TRANCHE) + '- ' + LB_OPERATION + ' - ' + IFC_ERREUR_TRAITEMENT + CHAR(10)
		FROM WRK_INTERFACE_EASYFOLDER_OPERATIONS WHERE IFC_STATUT_TRAITEMENT = 'Echec' AND CONVERT(DATE, CONVERT(VARCHAR(10), IFC_DT_TRAITEMENT, 103), 103) = @PK_TEMPS;
	
	RETURN @PARAM;

END