CREATE TABLE [dbo].[BANQUE] (
    [CBANQUE]    VARCHAR (5)  NULL,
    [DECOUV]     INT          NULL,
    [AGIOS]      INT          NULL,
    [RESPONS]    VARCHAR (50) NULL,
    [COMPTE]     VARCHAR (50) NULL,
    [TYPBQ]      VARCHAR (50) NULL,
    [CMODREG]    VARCHAR (10) NULL,
    [BGTYPTIERS] VARCHAR (50) NULL,
    [BGTIERS]    VARCHAR (50) NULL,
    [TRIGD]      DATE         NULL,
    [LBANQUE]    VARCHAR (50) NULL,
    [RUE]        VARCHAR (50) NULL,
    [LIEUDIT]    VARCHAR (50) NULL,
    [CPOS]       VARCHAR (5)  NULL,
    [VILLE]      VARCHAR (50) NULL,
    [CCOMM]      VARCHAR (50) NULL,
    [TELPH]      VARCHAR (20) NULL,
    [TELEX]      VARCHAR (20) NULL,
    [FAX]        VARCHAR (20) NULL,
    [TRIG]       VARCHAR (1)  NULL,
    [ADRCOMP]    VARCHAR (50) NULL,
    [MIGCOMPT]   INT          NULL,
    [BIC]        VARCHAR (50) NULL,
    [LACTIF]     INT          NULL,
    [CPAYSBIC]   VARCHAR (50) NULL,
    [BIC8]       VARCHAR (50) NULL
);

