CREATE TABLE [dbo].[BASE] (
    [CBASE]     VARCHAR (50) NULL,
    [LBASE]     VARCHAR (50) NULL,
    [TRIG]      VARCHAR (50) NULL,
    [CORG]      VARCHAR (50) NULL,
    [CAGENCE]   VARCHAR (50) NULL,
    [CGROUPE]   VARCHAR (50) NULL,
    [TBASE]     VARCHAR (50) NULL,
    [REGROUP1]  VARCHAR (50) NULL,
    [REGROUP2]  VARCHAR (50) NULL,
    [MIGCOMPT]  VARCHAR (50) NULL,
    [GROUPE_ID] VARCHAR (50) NULL,
    [LACTIF]    VARCHAR (50) NULL
);

