CREATE TABLE [dbo].[BASELOC] (
    [CORG]     VARCHAR (50) NULL,
    [CAGENCE]  VARCHAR (50) NULL,
    [CGROUPE]  VARCHAR (50) NULL,
    [CIMMEUB]  VARCHAR (50) NULL,
    [CLOCAL]   VARCHAR (50) NULL,
    [CBASE]    VARCHAR (50) NULL,
    [TRIG]     VARCHAR (50) NULL,
    [MONTANT]  VARCHAR (50) NULL,
    [DEFFET]   VARCHAR (50) NULL,
    [MIGCOMPT] VARCHAR (50) NULL,
    [LOCAL_ID] VARCHAR (50) NULL
);

