CREATE TABLE [dbo].[CATEG] (
    [LISTORG]   VARCHAR (50) NULL,
    [CCATEG]    VARCHAR (50) NULL,
    [LCATEG]    VARCHAR (50) NULL,
    [CTYPTIERS] VARCHAR (50) NULL,
    [FJOURNAL]  VARCHAR (50) NULL,
    [AJOURNAL]  VARCHAR (50) NULL,
    [DERCLO]    VARCHAR (50) NULL,
    [BALEDIT]   VARCHAR (50) NULL,
    [XJOURNAL]  VARCHAR (50) NULL,
    [TRIG]      VARCHAR (50) NULL,
    [LACTIF]    VARCHAR (50) NULL
);

