CREATE TABLE [dbo].[COMMENT_] (
    [NOFICH]      VARCHAR (8)    NULL,
    [CLEFICH]     VARCHAR (21)   NULL,
    [COMMENT]     VARCHAR (1074) NULL,
    [NPAGE]       VARCHAR (300)  NULL,
    [AUTEUR]      VARCHAR (100)  NULL,
    [DCREA]       VARCHAR (10)   NULL,
    [DPREV]       VARCHAR (MAX)  NULL,
    [DREEL]       VARCHAR (MAX)  NULL,
    [TYPE]        VARCHAR (1)    NULL,
    [ETAT]        VARCHAR (1)    NULL,
    [REFER]       VARCHAR (1)    NULL,
    [INTERLOC]    VARCHAR (1)    NULL,
    [SECTEUR]     VARCHAR (5)    NULL,
    [TRIG]        VARCHAR (1)    NULL,
    [DEST]        VARCHAR (50)   NULL,
    [SUP]         VARCHAR (1)    NULL,
    [MODIF]       VARCHAR (MAX)  NULL,
    [DAVIS]       VARCHAR (MAX)  NULL,
    [DBANAL]      VARCHAR (MAX)  NULL,
    [MONTANT]     VARCHAR (50)   NULL,
    [BANAL]       VARCHAR (1)    NULL,
    [MOTCLE]      VARCHAR (1)    NULL,
    [CLE2]        VARCHAR (1)    NULL,
    [HEURE]       VARCHAR (50)   NULL,
    [DMODIF]      VARCHAR (10)   NULL,
    [POSTE]       VARCHAR (20)   NULL,
    [MIGCOMPT]    VARCHAR (5)    NULL,
    [CCATCOMMENT] VARCHAR (1)    NULL,
    [LIBELLE]     VARCHAR (1)    NULL,
    [ENTITE_ID]   SMALLINT       NULL,
    [NIVEAU]      VARCHAR (1)    NULL,
    [UTIL]        VARCHAR (1)    NULL,
    [CMODULE]     VARCHAR (100)  NULL
);

