CREATE TABLE [dbo].[CRIT] (
    [NOFICH]    VARCHAR (50) NULL,
    [CLCRIT]    VARCHAR (50) NULL,
    [CCRIT]     VARCHAR (50) NULL,
    [LCRIT]     VARCHAR (50) NULL,
    [TRIG]      VARCHAR (50) NULL,
    [LACTIF]    VARCHAR (50) NULL,
    [MIGCOMPT]  VARCHAR (50) NULL,
    [LCOURRIER] VARCHAR (50) NULL,
    [CEPPERSO]  VARCHAR (50) NULL,
    [LIBLABEL]  VARCHAR (50) NULL
);

