CREATE TABLE [dbo].[CRITLIB] (
    [NOFICH]   VARCHAR (50) NULL,
    [CLEFICH]  VARCHAR (50) NULL,
    [CLCRIT]   VARCHAR (50) NULL,
    [CCRIT]    VARCHAR (50) NULL,
    [TRIG]     VARCHAR (50) NULL,
    [DCRITLIB] VARCHAR (50) NULL,
    [BANAL]    VARCHAR (50) NULL,
    [MIGCOMPT] VARCHAR (50) NULL
);

