CREATE TABLE [dbo].[DEMINT] (
    [corg]      VARCHAR (50) NULL,
    [nodem]     VARCHAR (50) NULL,
    [datedem]   DATETIME     NULL,
    [xorg]      VARCHAR (50) NULL,
    [cnatrec]   VARCHAR (50) NULL,
    [datsoufin] VARCHAR (50) NULL,
    [cagence]   VARCHAR (50) NULL,
    [cgroupe]   VARCHAR (50) NULL,
    [cimmeub]   VARCHAR (50) NULL,
    [clocal]    VARCHAR (50) NULL,
    [cnatpiec]  VARCHAR (50) NULL,
    [teldom]    VARCHAR (50) NULL,
    [teltra]    VARCHAR (50) NULL,
    [trig]      VARCHAR (50) NULL,
    [iemploy]   VARCHAR (50) NULL,
    [encours]   VARCHAR (50) NULL,
    [oemploy]   VARCHAR (50) NULL,
    [datclo]    DATETIME     NULL,
    [compl]     VARCHAR (50) NULL,
    [cmotclo]   VARCHAR (50) NULL,
    [occ]       VARCHAR (50) NULL,
    [cnatfin]   VARCHAR (50) NULL,
    [dnatfin]   VARCHAR (50) NULL,
    [corirec]   VARCHAR (50) NULL,
    [curgence]  VARCHAR (50) NULL,
    [datlim]    VARCHAR (50) NULL,
    [datinf]    VARCHAR (50) NULL,
    [escalier]  VARCHAR (50) NULL,
    [etage]     VARCHAR (50) NULL,
    [factedit]  VARCHAR (50) NULL,
    [regcpt]    VARCHAR (50) NULL,
    [cle]       VARCHAR (50) NULL,
    [bat]       VARCHAR (50) NULL,
    [ctyptiers] VARCHAR (50) NULL,
    [ctiers]    VARCHAR (50) NULL,
    [heurdem]   VARCHAR (50) NULL,
    [occ2]      VARCHAR (50) NULL,
    [cmandat]   VARCHAR (50) NULL,
    [migcompt]  VARCHAR (50) NULL,
    [CSOLLICIT] VARCHAR (50) NULL
);

