CREATE TABLE [dbo].[EBUDLOC] (
    [CORG]     VARCHAR (50) NULL,
    [CAGENCE]  VARCHAR (50) NULL,
    [CGROUPE]  VARCHAR (50) NULL,
    [CBUDLOC]  VARCHAR (50) NULL,
    [VERSION]  VARCHAR (50) NULL,
    [LBUDLOC]  VARCHAR (50) NULL,
    [DDEB]     VARCHAR (50) NULL,
    [DFIN]     VARCHAR (50) NULL,
    [VOTE]     VARCHAR (50) NULL,
    [METHREG]  VARCHAR (50) NULL,
    [TYPBUD]   VARCHAR (50) NULL,
    [OBUDLOC]  VARCHAR (50) NULL,
    [COMMENT_] VARCHAR (50) NULL,
    [TRIG]     VARCHAR (50) NULL,
    [MIGCOMPT] VARCHAR (50) NULL
);

