CREATE TABLE [dbo].[HAVENAN] (
    [CORG]     VARCHAR (4)   NULL,
    [CCOMPTE]  VARCHAR (22)  NULL,
    [NOBAIL]   SMALLINT      NULL,
    [NAVENAN]  SMALLINT      NULL,
    [DDEB]     DATE          NULL,
    [COMMENT]  VARCHAR (500) NULL,
    [TRIG]     VARCHAR (10)  NULL,
    [NOLOCAT]  SMALLINT      NULL,
    [CMOTIF]   VARCHAR (4)   NULL,
    [DSIGNATU] VARCHAR (MAX) NULL
);

