CREATE TABLE [dbo].[HLOYCA] (
    [CORG]     VARCHAR (50) NULL,
    [CAGENCE]  VARCHAR (50) NULL,
    [CGROUPE]  VARCHAR (50) NULL,
    [CIMMEUB]  VARCHAR (50) NULL,
    [CLOCAL]   VARCHAR (50) NULL,
    [OCC]      VARCHAR (50) NULL,
    [DDEB]     VARCHAR (50) NULL,
    [MTPROVI]  VARCHAR (50) NULL,
    [MTFINAL]  VARCHAR (50) NULL,
    [DMAJ]     VARCHAR (50) NULL,
    [UTIL]     VARCHAR (50) NULL,
    [TRIG]     VARCHAR (50) NULL,
    [DREVIS]   VARCHAR (50) NULL,
    [LRATTRAP] VARCHAR (50) NULL
);

