CREATE TABLE [dbo].[HQLOCAL] (
    [CORG]     VARCHAR (50) NULL,
    [CAGENCE]  VARCHAR (50) NULL,
    [CGROUPE]  VARCHAR (50) NULL,
    [CIMMEUB]  VARCHAR (50) NULL,
    [CLOCAL]   VARCHAR (50) NULL,
    [CRUB]     VARCHAR (50) NULL,
    [DDEB]     VARCHAR (50) NULL,
    [DFIN]     VARCHAR (50) NULL,
    [NB]       VARCHAR (50) NULL,
    [TRIG]     VARCHAR (50) NULL,
    [CMETREV]  VARCHAR (50) NULL,
    [MONTREV]  VARCHAR (50) NULL,
    [MTCUMREA] VARCHAR (50) NULL,
    [MTCUMVAC] VARCHAR (50) NULL,
    [INDANC]   VARCHAR (50) NULL,
    [LFACIAL]  VARCHAR (50) NULL,
    [CCATHLM]  VARCHAR (50) NULL,
    [MIGCOMPT] VARCHAR (50) NULL,
    [LOCAL_ID] VARCHAR (50) NULL
);

