CREATE TABLE [dbo].[HQRBAIL] (
    [CORG]     VARCHAR (50) NULL,
    [CAGENCE]  VARCHAR (50) NULL,
    [CGROUPE]  VARCHAR (50) NULL,
    [CIMMEUB]  VARCHAR (50) NULL,
    [CLOCAL]   VARCHAR (50) NULL,
    [OCC]      VARCHAR (50) NULL,
    [DPRORENO] DATE         NULL,
    [DRELANCE] DATE         NULL,
    [DSIGNLOC] VARCHAR (50) NULL,
    [DRENOUV]  DATE         NULL,
    [DREEXAM]  DATE         NULL,
    [TRIG]     VARCHAR (50) NULL,
    [CCOMPTE]  VARCHAR (50) NULL,
    [NOBAIL]   VARCHAR (50) NULL,
    [TEMOIN]   VARCHAR (50) NULL,
    [DREPONSE] VARCHAR (50) NULL
);

