CREATE TABLE [dbo].[HTRCA] (
    [CORG]    VARCHAR (50) NULL,
    [CAGENCE] VARCHAR (50) NULL,
    [CGROUPE] VARCHAR (50) NULL,
    [CIMMEUB] VARCHAR (50) NULL,
    [CLOCAL]  VARCHAR (50) NULL,
    [OCC]     VARCHAR (50) NULL,
    [MTMINI]  VARCHAR (50) NULL,
    [MTMAXI]  VARCHAR (50) NULL,
    [PRCCA]   VARCHAR (50) NULL,
    [TRIG]    VARCHAR (50) NULL,
    [DDEB]    VARCHAR (50) NULL,
    [DREVIS]  VARCHAR (50) NULL,
    [ANCIND]  VARCHAR (50) NULL,
    [NOUIND]  VARCHAR (50) NULL,
    [CNUMI]   VARCHAR (50) NULL
);

