CREATE TABLE [dbo].[INDICE] (
    [CNUMI]  VARCHAR (50) NULL,
    [ANNEE]  VARCHAR (50) NULL,
    [MOIS]   VARCHAR (50) NULL,
    [VAL]    VARCHAR (50) NULL,
    [DEFPRO] VARCHAR (50) NULL,
    [TRIG]   VARCHAR (50) NULL,
    [LACTIF] VARCHAR (50) NULL
);

