CREATE TABLE [dbo].[MANPAT] (
    [CTYPTIERS] VARCHAR (50) NULL,
    [CTIERS]    VARCHAR (50) NULL,
    [CMANDAT]   VARCHAR (50) NULL,
    [NIVEAU]    VARCHAR (50) NULL,
    [CORG]      VARCHAR (50) NULL,
    [CAGENCE]   VARCHAR (50) NULL,
    [CGROUPE]   VARCHAR (50) NULL,
    [CIMMEUB]   VARCHAR (50) NULL,
    [CLOCAL]    VARCHAR (50) NULL,
    [MTCOL1]    VARCHAR (50) NULL,
    [MTCOL2]    VARCHAR (50) NULL,
    [MTCOL3]    VARCHAR (50) NULL,
    [MTCOL4]    VARCHAR (50) NULL,
    [MTCOL5]    VARCHAR (50) NULL,
    [MTCOL6]    VARCHAR (50) NULL,
    [MTVENT]    VARCHAR (50) NULL,
    [TRIG]      VARCHAR (50) NULL,
    [MIGCOMPT]  VARCHAR (50) NULL,
    [CMANDOM]   VARCHAR (50) NULL
);

