CREATE TABLE [dbo].[MOTDDE] (
    [CMOTDDE]      VARCHAR (50)  NULL,
    [LMOTDDE]      NVARCHAR (50) NULL,
    [CEXTERNE##1]  VARCHAR (50)  NULL,
    [CEXTERNE##2]  VARCHAR (50)  NULL,
    [CEXTERNE##3]  VARCHAR (50)  NULL,
    [CEXTERNE##4]  VARCHAR (50)  NULL,
    [CEXTERNE##5]  VARCHAR (50)  NULL,
    [LGEXTERNE##1] VARCHAR (50)  NULL,
    [LGEXTERNE##2] VARCHAR (50)  NULL,
    [LGEXTERNE##3] VARCHAR (50)  NULL,
    [LGEXTERNE##4] VARCHAR (50)  NULL,
    [LGEXTERNE##5] VARCHAR (50)  NULL,
    [TRIG]         VARCHAR (50)  NULL,
    [POINT]        VARCHAR (50)  NULL,
    [REGROUP]      VARCHAR (50)  NULL,
    [LACTIF]       VARCHAR (50)  NULL
);

