CREATE TABLE [dbo].[MOTIF] (
    [CSTE]     VARCHAR (50) NULL,
    [CMOTIF]   VARCHAR (50) NULL,
    [LMOTIF]   VARCHAR (50) NULL,
    [TRIG]     VARCHAR (50) NULL,
    [LMOTIFL]  VARCHAR (50) NULL,
    [MIGCOMPT] VARCHAR (50) NULL,
    [LACTIF]   VARCHAR (50) NULL
);

