CREATE TABLE [dbo].[PCRITDEP] (
    [CORG]     VARCHAR (50) NULL,
    [COPE]     VARCHAR (50) NULL,
    [CTRANCHE] VARCHAR (50) NULL,
    [CDEPR]    VARCHAR (50) NULL,
    [NORD]     VARCHAR (50) NULL,
    [CAGENCE]  VARCHAR (50) NULL,
    [CGROUPE]  VARCHAR (50) NULL,
    [CIMMEUB]  VARCHAR (50) NULL,
    [CLOCAL]   VARCHAR (50) NULL,
    [CCRITDP]  VARCHAR (50) NULL,
    [CSCRITDP] VARCHAR (50) NULL,
    [POURC]    VARCHAR (50) NULL,
    [BANAL]    VARCHAR (50) NULL
);

