CREATE TABLE [dbo].[PERIODICITE] (
    [CPERIODICITE] VARCHAR (50) NULL,
    [LPERIODICITE] VARCHAR (50) NULL,
    [TRIG]         VARCHAR (50) NULL,
    [MIGCOMPT]     VARCHAR (50) NULL,
    [LACTIF]       VARCHAR (50) NULL
);

