CREATE TABLE [dbo].[PLANC] (
    [CORG]      VARCHAR (2)   NULL,
    [CCG]       INT           NULL,
    [INTIT]     VARCHAR (51)  NULL,
    [INTITR]    VARCHAR (14)  NULL,
    [DOUV]      VARCHAR (10)  NULL,
    [DBLOC]     VARCHAR (10)  NULL,
    [DMAJ]      DATETIME      NULL,
    [TIERS]     VARCHAR (5)   NULL,
    [ANAL]      VARCHAR (5)   NULL,
    [CNATANA]   VARCHAR (4)   NULL,
    [COMPCENT]  VARCHAR (5)   NULL,
    [COMPCLO]   VARCHAR (5)   NULL,
    [SOLDOK]    VARCHAR (1)   NULL,
    [SENSINT]   VARCHAR (1)   NULL,
    [TYPCPTA]   VARCHAR (1)   NULL,
    [TRESOR]    VARCHAR (5)   NULL,
    [REGROUPE]  VARCHAR (5)   NULL,
    [CTRCIL]    VARCHAR (5)   NULL,
    [CHPC]      VARCHAR (1)   NULL,
    [BCG]       VARCHAR (1)   NULL,
    [CMONEY]    VARCHAR (1)   NULL,
    [CRESI]     VARCHAR (2)   NULL,
    [CAGECO]    VARCHAR (5)   NULL,
    [CRESO]     VARCHAR (1)   NULL,
    [SCB]       VARCHAR (8)   NULL,
    [VCB]       VARCHAR (5)   NULL,
    [VISORD]    VARCHAR (5)   NULL,
    [ANOUVO]    VARCHAR (1)   NULL,
    [CBANQUE]   VARCHAR (1)   NULL,
    [GUICHET]   VARCHAR (1)   NULL,
    [COMPTE]    VARCHAR (1)   NULL,
    [NBJOUR]    SMALLINT      NULL,
    [TEMRB]     VARCHAR (5)   NULL,
    [SOLDBANQ]  VARCHAR (5)   NULL,
    [CG68]      VARCHAR (5)   NULL,
    [CG28]      VARCHAR (5)   NULL,
    [CMETIMMO]  VARCHAR (5)   NULL,
    [CPTIMMO]   VARCHAR (5)   NULL,
    [ENGA]      VARCHAR (1)   NULL,
    [CCATEG]    VARCHAR (1)   NULL,
    [RECUP]     VARCHAR (1)   NULL,
    [CPTVA]     VARCHAR (1)   NULL,
    [CDOMSOC]   SMALLINT      NULL,
    [TRIGD]     VARCHAR (MAX) NULL,
    [FISC]      VARCHAR (1)   NULL,
    [CNATHON]   VARCHAR (1)   NULL,
    [SAISINT]   VARCHAR (5)   NULL,
    [TRIG]      VARCHAR (1)   NULL,
    [VISREC]    VARCHAR (5)   NULL,
    [CNTVA]     VARCHAR (1)   NULL,
    [GSECT]     VARCHAR (5)   NULL,
    [NATMOD]    VARCHAR (1)   NULL,
    [NATBIEN]   VARCHAR (1)   NULL,
    [CG675]     VARCHAR (1)   NULL,
    [AUTORISE]  VARCHAR (1)   NULL,
    [SAUTORISE] VARCHAR (1)   NULL,
    [CAUTORISE] VARCHAR (1)   NULL,
    [TEMOIN]    VARCHAR (1)   NULL,
    [CPBUDD]    VARCHAR (1)   NULL,
    [CCOLBUD]   VARCHAR (1)   NULL,
    [CPANA]     VARCHAR (1)   NULL,
    [LISTORG]   VARCHAR (5)   NULL,
    [ASSMDT]    VARCHAR (1)   NULL,
    [COMPAMOFI] VARCHAR (1)   NULL,
    [MIGCOMPT]  SMALLINT      NULL,
    [RF]        VARCHAR (1)   NULL
);

