CREATE TABLE [dbo].[RUBPER] (
    [CORG]       VARCHAR (50) NULL,
    [CAGENCE]    VARCHAR (50) NULL,
    [CGROUPE]    VARCHAR (50) NULL,
    [DDEBPER]    VARCHAR (50) NULL,
    [DFINPER]    DATE         NULL,
    [CRUB]       VARCHAR (50) NULL,
    [CPRC]       VARCHAR (50) NULL,
    [REGUL]      VARCHAR (50) NULL,
    [TRIG]       VARCHAR (50) NULL,
    [BCOPLOC]    VARCHAR (50) NULL,
    [LIB]        VARCHAR (50) NULL,
    [ANALYSE]    VARCHAR (50) NULL,
    [COMPLEMENT] VARCHAR (50) NULL,
    [PARTIEL]    VARCHAR (50) NULL,
    [EDITAVIS]   VARCHAR (50) NULL,
    [CALCULOK]   VARCHAR (50) NULL,
    [CLOTURE]    VARCHAR (50) NULL
);

