CREATE TABLE [dbo].[TRAIT] (
    [CTRAIT]    VARCHAR (50) NULL,
    [LTRAIT]    VARCHAR (50) NULL,
    [TASS]      VARCHAR (50) NULL,
    [TRIG]      VARCHAR (50) NULL,
    [AUTORISE]  VARCHAR (50) NULL,
    [SAUTORISE] VARCHAR (50) NULL,
    [CAUTORISE] VARCHAR (50) NULL
);

