CREATE TABLE [dbo].[TSCAT] (
    [LISTORG]   VARCHAR (50) NULL,
    [CTSCAT]    VARCHAR (50) NULL,
    [LTSCAT]    VARCHAR (50) NULL,
    [CTYPTIERS] VARCHAR (50) NULL,
    [LETTRAG]   VARCHAR (50) NULL,
    [DERCLO]    VARCHAR (50) NULL,
    [BALEDIT]   VARCHAR (50) NULL,
    [TRIG]      VARCHAR (50) NULL,
    [SLET]      VARCHAR (50) NULL,
    [LISTAGE]   VARCHAR (50) NULL,
    [LACTIF]    VARCHAR (50) NULL
);

