CREATE TABLE [dbo].[TSLIEN] (
    [CTYPTIERS] VARCHAR (50) NULL,
    [CTIERS]    VARCHAR (50) NULL,
    [CTSCAT]    VARCHAR (50) NULL,
    [CORG]      VARCHAR (50) NULL,
    [TRIG]      VARCHAR (50) NULL,
    [LETT]      VARCHAR (50) NULL
);

