CREATE TABLE [dbo].[TVA] (
    [CTVA]    VARCHAR (50) NULL,
    [LTVA]    VARCHAR (50) NULL,
    [TTVA]    VARCHAR (50) NULL,
    [TRIG]    VARCHAR (50) NULL,
    [TXTVAP]  VARCHAR (50) NULL,
    [DFVTXP]  VARCHAR (50) NULL,
    [DFVTXP1] VARCHAR (50) NULL,
    [TXTVAP1] VARCHAR (50) NULL,
    [DFVTXP2] VARCHAR (50) NULL,
    [TXTVAP2] VARCHAR (50) NULL,
    [DFVTXP3] VARCHAR (50) NULL,
    [TXTVAP3] VARCHAR (50) NULL,
    [LACTIF]  VARCHAR (50) NULL
);

