CREATE TABLE [dbo].[TYPECRI] (
    [CTYPECRI] VARCHAR (50) NULL,
    [LTYPECRI] VARCHAR (50) NULL,
    [TRIG]     VARCHAR (50) NULL,
    [RTYPECRI] VARCHAR (50) NULL,
    [TASS]     VARCHAR (50) NULL,
    [DCN]      VARCHAR (50) NULL,
    [RVA]      VARCHAR (50) NULL,
    [PRL]      VARCHAR (50) NULL,
    [PIN]      VARCHAR (50) NULL,
    [DEA]      VARCHAR (50) NULL,
    [FAC]      VARCHAR (50) NULL,
    [RPRL]     VARCHAR (50) NULL,
    [RAUP]     VARCHAR (50) NULL,
    [LACTIF]   VARCHAR (50) NULL
);

