CREATE TABLE [dbo].[TYPLOG] (
    [CTYPLOG]      VARCHAR (50)  NULL,
    [LTYPLOG]      NVARCHAR (50) NULL,
    [CEXTERNE##1]  VARCHAR (50)  NULL,
    [CEXTERNE##2]  VARCHAR (50)  NULL,
    [CEXTERNE##3]  VARCHAR (50)  NULL,
    [CEXTERNE##4]  VARCHAR (50)  NULL,
    [CEXTERNE##5]  VARCHAR (50)  NULL,
    [LGEXTERNE##1] VARCHAR (50)  NULL,
    [LGEXTERNE##2] VARCHAR (50)  NULL,
    [LGEXTERNE##3] VARCHAR (50)  NULL,
    [LGEXTERNE##4] VARCHAR (50)  NULL,
    [LGEXTERNE##5] VARCHAR (50)  NULL,
    [TRIG]         VARCHAR (50)  NULL,
    [TRIGD]        VARCHAR (50)  NULL,
    [NBPIEC]       VARCHAR (50)  NULL,
    [CTYPCIL]      VARCHAR (50)  NULL,
    [PEGAS]        VARCHAR (50)  NULL,
    [TSOUMTAX]     VARCHAR (50)  NULL,
    [TYPUSALO]     VARCHAR (50)  NULL,
    [LACTIF]       VARCHAR (50)  NULL,
    [MIGCOMPT]     VARCHAR (50)  NULL
);

