CREATE TABLE [dbo].[TYPROPR] (
    [CMANDAT]    VARCHAR (50) NULL,
    [CTIERS]     VARCHAR (50) NULL,
    [CTYPTIERS]  VARCHAR (50) NULL,
    [CTYPROPR]   VARCHAR (50) NULL,
    [DARRETE]    VARCHAR (50) NULL,
    [DDEB]       VARCHAR (50) NULL,
    [DFIN]       VARCHAR (50) NULL,
    [MIGCOMPT]   VARCHAR (50) NULL,
    [TRIG]       VARCHAR (50) NULL,
    [TYPROPR_ID] VARCHAR (50) NULL
);

