CREATE TABLE [dbo].[USALOC] (
    [CUSALOC]  VARCHAR (50)  NULL,
    [LUSALOC]  NVARCHAR (50) NULL,
    [TRIG]     VARCHAR (50)  NULL,
    [TRIGD]    VARCHAR (50)  NULL,
    [PEGAS]    VARCHAR (50)  NULL,
    [TYPUSALO] VARCHAR (50)  NULL,
    [TSOUMTAX] VARCHAR (50)  NULL,
    [NBMMINI]  VARCHAR (50)  NULL,
    [LACTIF]   VARCHAR (50)  NULL,
    [MIGCOMPT] VARCHAR (50)  NULL
);

