-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
CREATE PROCEDURE [dbo].[BILAN_PERMANENT] 
(
	@DT_ANALYSE DATETIME,
	@PK_PROPRIETAIRE INT,
	@PK_IMMEUBLE VARCHAR(MAX),
	@PK_POPE VARCHAR(MAX),
	@ANNEE_DEB_OPERATION INT
)
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;

SELECT	FK_PROPRIETAIRE
	  , FK_IMMEUBLE
	  , FK_MANDAT_GERANCE
	  , PK_POPE
	  , CORG
	  , COPE
	  , LOPE
	  , CD_PROPRIETAIRE
	  , NOM_PROPRIETAIRE
	  , CD_IMMEUBLE
	  , NOM_IMMEUBLE
	  , NOMTECH
	  , CTRANCHE
	  , CMANDAT
	  , CGROUPE
	  , DT_CLOTURE
	  , CA_PREVISIONNEL_OPERATION
	  , CD_ETAT_OPERATION
	  , CD_POSTE_REGROUP
	  , LB_POSTE_REGROUP
	  , CD_POSTE_DEPENSE
	  , LB_POSTE_DEPENSE
	  , CD_POSTE_REEL
	  , LB_POSTE_REEL
	  , CD_FOURNISSEUR
	  , LB_FOURNISSEUR
	  , NOM_FOURNISSEUR_COMPLET
	  , ISNULL(CASE WHEN CD_POSTE_REEL = 1 AND RK = 1 THEN MT_BUDGET_HT_PRORATISE ELSE 0 END, 0) AS MT_BUDGET_HT_PRORATISE
	  , MT_INITIAL_TTC
	  , MT_INITIAL_HT
	  , MT_AVENANTS_TS
	  , MT_ENG_HT_PRORATISE
	  , MT_ENG_HT_PRORATISE - ISNULL(CASE WHEN CD_POSTE_REEL = 1 AND RK = 1 THEN MT_BUDGET_HT_PRORATISE ELSE 0 END, 0) AS ECARTS
      , REVALORISATIONS
	  , MT_CUMUL_ENG_HT_PRORATISE
	  , MT_ENG_TVA
	  , MT_ENG_HT_FACTURE
	  , MT_FACTURE_HT_PRORATISE
	  , MT_PAYE_TTC
	  , MT_AVANCE_TTC
	  , MT_AVANCE_TTC_RECUP
	  , MT_SOLDE_OS_TTC
	  , MT_RESTE_A_PAYER_TTC
	  , MT_SOLDE_RG_TTC
	  , MT_AUTRES_RETENUES_TTC
FROM
(		
    SELECT POPE.PK_POPE
		 , WGM.FK_TIERS AS FK_PROPRIETAIRE
		 , WGM.PK_GROUPE AS FK_IMMEUBLE
		 , WGM.FK_MANGES AS FK_MANDAT_GERANCE
		 , PROPRIETAIRE.CTIERS AS CD_PROPRIETAIRE
		 , PROPRIETAIRE.LTIERS AS NOM_PROPRIETAIRE
		 , IMMEUBLE.CGROUPE AS CD_IMMEUBLE
		 , IMMEUBLE.LGROUPE AS NOM_IMMEUBLE
		 , POPE.CORG
		 , POPE.COPE
		 , POPE.LOPE
		 , POPE.NOMTECH 
		 , T.CTRANCHE
		 , POPE.CMANDAT
		 , POPE.CGROUPE
		 , POPE.DCLOTU DT_CLOTURE
		 , POPE.CAPREV CA_PREVISIONNEL_OPERATION
		 , POPE.CETAT CD_ETAT_OPERATION
		 , POP.CDEPG AS CD_POSTE_REGROUP
		 , POP.LDEPG AS LB_POSTE_REGROUP
		 , PDE.CDEPR AS CD_POSTE_DEPENSE
		 , PDEPR.LDEPR AS LB_POSTE_DEPENSE
		 , PDE.NORD AS CD_POSTE_REEL
		 , RANK() OVER (PARTITION BY PDE.CORG, PDE.COPE, PDE.CTRANCHE ORDER BY POP.MT_BUDGET_HT DESC, PDE.CDEPR) RK
		 , PDE.LNORD AS LB_POSTE_REEL
		 , PDE.CFOUR AS CD_FOURNISSEUR
		 , FOURNISSEUR.LTIERS AS LB_FOURNISSEUR
		 , CONCAT(PDE.CFOUR + ' ', FOURNISSEUR.LTIERS) AS NOM_FOURNISSEUR_COMPLET
		 , CAST(POP.MT_BUDGET_HT AS NUMERIC(18,2)) MT_BUDGET_HT_PRORATISE
		 , CAST(PDE.MTINI + (PDE.MTINI*TVA.TTVA)/100 AS NUMERIC(18,2)) AS MT_INITIAL_TTC
		 , ENG.MT_INITIAL_HT
		 , ENG.MT_AVENANTS_TS
		 , CAST(ENG.MT_INITIAL_HT + ENG.MT_AVENANTS_TS AS NUMERIC(18,2)) MT_ENG_HT_PRORATISE
		 , CAST(0 AS NUMERIC(18,2)) ECARTS
		 , CAST(0 AS NUMERIC(18,2)) REVALORISATIONS
		 , CAST(ENG.MT_INITIAL_HT + ENG.MT_AVENANTS_TS AS NUMERIC(18,2)) MT_CUMUL_ENG_HT_PRORATISE
		 , ENG.MT_ENG_TVA
		 , ENG.MT_ENG_HT_FACTURE
		 , ISNULL(REA.MT_FACTURE_TTC, 0) MT_FACTURE_HT_PRORATISE
		 , ISNULL(REA.MT_PAYE_TTC, 0) MT_PAYE_TTC
		 , CAST(0 AS NUMERIC(18,2)) MT_AVANCE_TTC
		 , CAST(0 AS NUMERIC(18,2)) MT_AVANCE_TTC_RECUP
		 , CAST((PDE.MTINI + (PDE.MTINI*TVA.TTVA)/100 + ENG.MT_AVENANTS_TS) - ISNULL(REA.MT_FACTURE_TTC, 0) AS NUMERIC(18,2)) MT_SOLDE_OS_TTC
		 , CAST(0 AS NUMERIC(18,2)) MT_RESTE_A_PAYER_TTC
		 , CAST(0 AS NUMERIC(18,2)) MT_SOLDE_RG_TTC
		 , CAST(0 AS NUMERIC(18,2)) MT_AUTRES_RETENUES_TTC
	FROM MASTER_ESTIA..ESTIA_POPE POPE
	LEFT JOIN MASTER_ESTIA..ESTIA_TRANCHE T
    ON T.CORG = POPE.CORG AND T.COPE = POPE.COPE 
	LEFT JOIN MASTER_ESTIA..ESTIA_PDEPOP PDE
    ON PDE.CORG = T.CORG AND PDE.COPE = T.COPE AND PDE.CTRANCHE = T.CTRANCHE
	LEFT JOIN MASTER_ESTIA..ESTIA_PDEPR PDEPR
	ON PDEPR.CDEPR = PDE.CDEPR
	LEFT JOIN MASTER_ESTIA..ESTIA_TIERS FOURNISSEUR
	ON FOURNISSEUR.CTIERS = PDE.CFOUR
	LEFT JOIN MASTER_ESTIA..ESTIA_TVA TVA
	ON TVA.CTVA = PDE.CTVA
	LEFT JOIN
    (
	  SELECT PAB.CORG
		   , PAB.COPE
		   , PAB.CTRANCHE
		   , PAB.CDEPR
		   , PAB.NORD 
		   , SUM(CASE WHEN PAB.SITUAT <> 1 THEn PAB.MTTTC ELSE 0 END) AS MT_AVENANTS_TS	   
		   , SUM(CASE WHEN PAB.SITUAT = 1 THEN PAB.MTTTC ELSE 0 END) AS MT_INITIAL_HT
		   , SUM(PAB.MTTTC) AS MT_CUMUL_TTC
		   , SUM(PAB.MTTVA) AS MT_ENG_TVA
		   , SUM(PAB.HTBASE) AS MT_ENG_HT_FACTURE
	  FROM MASTER_ESTIA..ESTIA_PABASIT PAB
	  WHERE PAB.CORG = '11'
	  AND PAB.DECR <= @DT_ANALYSE
      GROUP BY PAB.CORG, PAB.COPE, PAB.CTRANCHE, PAB.CDEPR, PAB.NORD
    ) ENG
    ON ENG.CORG = PDE.CORG AND ENG.COPE = PDE.COPE AND ENG.CTRANCHE = PDE.CTRANCHE AND ENG.CDEPR = PDE.CDEPR AND ENG.NORD = PDE.NORD 
	LEFT JOIN
    (
		SELECT P.CORG
			, P.COPE
			, P.CTRANCHE
			, P.LOTDEP
			, P.NORD
			, SUM(CASE WHEN P.CTYPECRI <> 'REG' THEN CASE SENS WHEN 'C' THEN (MONTANT + TTVA) ELSE -(MONTANT + TTVA) END ELSE 0 END) AS MT_FACTURE_TTC
			, SUM(CASE WHEN P.CTYPECRI = 'REG' THEN CASE SENS WHEN 'D' THEN (MONTANT + TTVA) ELSE -(MONTANT + TTVA) END ELSE 0 END) AS MT_PAYE_TTC
		FROM MASTER_ESTIA..ESTIA_PECRIP P
		WHERE P.TYPCPTA = 'TF'
		AND P.CTYPCOM = 'F'
		AND P.CORG = '11'
		AND P.DECR <= @DT_ANALYSE
		--AND P.CTYPECRI <> 'REG'
		--AND COPE = '20170600036'
		--AND P.LOTDEP = 272
		GROUP BY P.CORG, P.COPE, P.CTRANCHE, P.LOTDEP, P.NORD
    ) REA
    ON REA.CORG = PDE.CORG AND REA.COPE = PDE.COPE AND REA.CTRANCHE = PDE.CTRANCHE AND REA.LOTDEP = PDE.CDEPR AND REA.NORD = PDE.NORD 
	LEFT JOIN MASTER_ESTIA..ESTIA_PREPOPE PREP
	ON PREP.CORG = PDE.CORG AND PREP.COPE = PDE.COPE AND PREP.CTRANCHE = PDE.CTRANCHE AND PREP.CDEPR = PDE.CDEPR AND PREP.NORD = PDE.NORD
	LEFT JOIN MASTER_ESTIA..ESTIA_PTYPOP PTYPOP
    ON PTYPOP.CTYPOP = PREP.CTYPOP
	LEFT JOIN MASTER_ESTIA..WRK_GROUPE_MANGES WGM
	ON WGM.CORG = POPE.CORG AND WGM.CGROUPE = POPE.CGROUPE
	LEFT JOIN MASTER_ESTIA..ESTIA_TIERS PROPRIETAIRE
	ON PROPRIETAIRE.PK_TIERS = WGM.FK_TIERS
	LEFT JOIN MASTER_ESTIA..ESTIA_GROUPE IMMEUBLE
	ON IMMEUBLE.PK_GROUPE = WGM.PK_GROUPE
	LEFT JOIN
	(
		select POPS1.COPE
			 , POPS1.CDEPP
			 , POPS1.CDEPG
			 , DEPG.LDEPG
			 , POPS1.MTHT MT_BUDGET_HT
		FROM MASTER_ESTIA..ESTIA_POPS1 POPS1
		LEFT JOIN MASTER_ESTIA..ESTIA_DEPG DEPG
		ON DEPG.CDEPG = POPS1.CDEPG
		WHERE  POPS1.TYPE = 'A'
		AND POPS1.DETREG = 'R'--'D'
		AND POPS1.CORG = '11'
		--AND POPS1.COPE = '20170600036'
		--and POPS1.CTRANCHE = 1	
	) POP
	ON POP.COPE = PDE.COPE AND POP.CDEPP = PDEPR.CDEPP
	WHERE POPE.CORG = '11'
	--AND PDE.CDEPR = 272
	--AND POPE.COPE = '20170600036'
	AND PROPRIETAIRE.PK_TIERS = @PK_PROPRIETAIRE
	AND IMMEUBLE.PK_GROUPE IN (SELECT VALUE FROM dbo.ufn_SplitMultiValue(@PK_IMMEUBLE,','))
	AND POPE.PK_POPE IN (SELECT VALUE FROM dbo.ufn_SplitMultiValue(@PK_POPE,','))
	AND DATEPART(YEAR, T.DDEXEC) >= @ANNEE_DEB_OPERATION
) SRC
ORDER BY CD_PROPRIETAIRE, CD_IMMEUBLE, COPE, CD_POSTE_REGROUP, CD_POSTE_DEPENSE, CD_POSTE_REEL

END