
CREATE PROCEDURE [dbo].[BUDGET_CHARGES_DETAIL] 
(
	@PK_PROPRIETAIRE VARCHAR(MAX),
	@PK_IMMEUBLE VARCHAR(MAX),
	@CCRITDP VARCHAR(MAX),
	@CSCRITDP VARCHAR(MAX),
	@TYPBON VARCHAR(MAX),
	@ANNEE_BUDGET VARCHAR(10)
)
AS
BEGIN

	SET NOCOUNT ON;

with REQ_BT as
(
	select CORG
		 , CGROUPE
		 , NOBON
		 , CCRITDP
		 , CSCRITDP
		 , ANNEE
		 , SUM(ISNULL(MT_ENG, 0)) MT_ENG
		 , SUM(ISNULL(MT_REA, 0)) MT_REA
	from
	(
		select  ECRIB.CORG
				, GROUPE.CGROUPE
				, ECRIB.NOBON
				, ECRIB.CCRITDP
				, ECRIB.CSCRITDP
				, ECRIB.CEXO ANNEE
				, case ECRIB.CSTE when 'EG' then isnull(MONTANT, 0) else 0 end MT_ENG
				, MT_REA
		from MASTER_ESTIA..ESTIA_ECRIB ECRIB
		left join MASTER_ESTIA..ESTIA_GROUPE GROUPE on GROUPE.PK_GROUPE = ECRIB.FK_GROUPE
		left join
		(
			select ECRIB.CORG
				, GROUPE.CGROUPE
				, ECRIB.NOBON
				, ECRIB.CCRITDP
				, ECRIB.CSCRITDP
				, ECRIB.CEXO
				, case ECRIB.CSTE when 'RE' then isnull(MONTANT, 0) else 0 end MT_REA
			from MASTER_ESTIA..ESTIA_ECRIB ECRIB
			left join MASTER_ESTIA..ESTIA_GROUPE GROUPE on GROUPE.PK_GROUPE = ECRIB.FK_GROUPE
			where ECRIB.CORG = '11'
			and ECRIB.TYPBON = 'BT'
			and ECRIB.CSTE in ('RE')
		) REA
		on REA.CORG = ECRIB.CORG and REA.CGROUPE = GROUPE.CGROUPE and REA.NOBON = ECRIB.NOBON and REA.CCRITDP = ECRIB.CCRITDP and REA.CSCRITDP = ECRIB.CSCRITDP and REA.CEXO = ECRIB.CEXO--datepart(year, ECRIB.DATEC)
		where ECRIB.CORG = '11'
		and GROUPE.PK_GROUPE IN (SELECT VALUE FROM dbo.ufn_SplitMultiValue(@PK_IMMEUBLE,','))
		and ECRIB.TYPBON = 'BT'
		and ECRIB.CSTE in ('EG')
		and ECRIB.CTRAIT in ('LBT')
	) SRC
	group by CORG, CGROUPE, NOBON, CCRITDP, CSCRITDP, ANNEE
),
REQ_CTR as
(
	SELECT EC.CORG
		 , EC.CGROUPE
		 , EC.CCONTFRS
		 , EC.CCRITDP
		 , EC.CSCRITDP
		 , EC.CEXO ANNEE
		 , CAST(((CONTNAT.MT_CONTRAT + ISNULL(AVENANT_CTR.MT_AVENANT_CONTRAT, 0)) * VENTPCHA.TXVENT)/100 AS NUMERIC(17,2)) AS MT_ENG
		 , SUM(ISNULL(EC.MONTANT, 0)) AS MT_REA
	FROM MASTER_ESTIA..ESTIA_ECRITAUX ECRITAUX
	INNER JOIN
	(
		SELECT ECRAC.CORG
			 , EB.PK_GROUPE
			 , EB.CGROUPE
			 , EB.CCONTFRS
			 , EB.DLIMPREST
			 , EB.CCRITDP
			 , EB.CSCRITDP
			 , EB.CEXO
			 , ECRAC.REF
			 , ECRAC.ORD		
			 , ECRAC.MONTANT
		FROM MASTER_ESTIA..ESTIA_ECRAC ECRAC
		LEFT JOIN MASTER_ESTIA..WRK_GROUPE_MANGES WGM
		ON WGM.CORG = ECRAC.CORG AND WGM.CMANDAT = ECRAC.CMANDAT
		INNER JOIN
		(
			SELECT B.CORG
				 , GROUPE.PK_GROUPE
				 , GROUPE.CGROUPE
				 , CTRTIERS.CCONTFRS
				 , CTRTIERS.DLIMPREST
				 , B.CCRITDP
				 , B.CSCRITDP
				 , B.CEXO 
				 , B.REF
				 , B.ORD
			FROM MASTER_ESTIA..ESTIA_ECRIB B
			left join MASTER_ESTIA..ESTIA_GROUPE GROUPE on GROUPE.PK_GROUPE = B.FK_GROUPE
			left join MASTER_ESTIA..ESTIA_CTRTIERS CTRTIERS on CTRTIERS.PK_CTRTIERS = B.FK_CTRTIERS
			WHERE B.TYPBON = 'CTR' 
			AND B.CORG = '11'
			AND B.CSTE IN  ('RE')
		) EB
		ON EB.CORG = ECRAC.CORG AND EB.REF = ECRAC.REF AND EB.ORD = ECRAC.ORD
		WHERE ECRAC.CORG = '11'
		AND ECRAC.SENS = 'D'
	) EC
	ON EC.CORG = ECRITAUX.CORG AND EC.REF = ECRITAUX.REF
	LEFT JOIN 
	(
		SELECT CORG
				, CCONTFRS
				, ISNULL(SUM(MTTC), 0) AS MT_CONTRAT
		FROM MASTER_ESTIA..ESTIA_CONTNAT 
		GROUP BY CORG, CCONTFRS
	) CONTNAT
	ON CONTNAT.CORG = EC.CORG AND CONTNAT.CCONTFRS = EC.CCONTFRS
	LEFT JOIN 
	(
		SELECT CORG
				, CCONTFRS
				, ISNULL(SUM(MTTC), 0) AS MT_AVENANT_CONTRAT
		FROM MASTER_ESTIA..ESTIA_AVENAN
		WHERE DSIGN BETWEEN cast(@ANNEE_BUDGET as varchar(4))+'0101' and cast(@ANNEE_BUDGET as varchar(4))+'1231'
		--WHERE DSIGN >= DATEADD(YEAR , DATEDIFF(YEAR, 0, GETDATE()), 0)
		GROUP BY CORG, CCONTFRS
	) AVENANT_CTR
	ON AVENANT_CTR.CORG = EC.CORG AND AVENANT_CTR.CCONTFRS = EC.CCONTFRS
	LEFT JOIN MASTER_ESTIA..ESTIA_VENTPCHA VENTPCHA on VENTPCHA.CORG = EC.CORG and VENTPCHA.CCONTFRS = EC.CCONTFRS and VENTPCHA.CCRITDP = EC.CCRITDP and VENTPCHA.CSCRITDP = EC.CSCRITDP
	WHERE ECRITAUX.CTYPECRI = 'FAC'
	AND ECRITAUX.CORG = '11'
	AND EC.PK_GROUPE IN (SELECT VALUE FROM dbo.ufn_SplitMultiValue(@PK_IMMEUBLE,','))
	AND datepart(year, EC.DLIMPREST) = EC.CEXO
	GROUP BY EC.CORG, EC.CGROUPE, EC.CCONTFRS, EC.CCRITDP, EC.CSCRITDP, EC.CEXO, CONTNAT.MT_CONTRAT, AVENANT_CTR.MT_AVENANT_CONTRAT, VENTPCHA.TXVENT
),
REQ_ALL AS
(
	SELECT CORG
		 , CGROUPE
		 , TYPBON
		 , BT_CTR
		 , CCRITDP
		 , CSCRITDP
		 , ANNEE
		 , SUM(MT_ENG) MT_ENG
		 , SUM(MT_REA) MT_REA
	FROM
	(
		SELECT CORG, CGROUPE, 'BT' TYPBON, NOBON BT_CTR, CCRITDP, CSCRITDP, ANNEE, MT_ENG, MT_REA
		FROM REQ_BT
		UNION
		SELECT CORG, CGROUPE, 'CTR' TYPBON, CCONTFRS BT_CTR, CCRITDP, CSCRITDP, ANNEE, MT_ENG, MT_REA
		FROM REQ_CTR
	) SRC
	GROUP BY CORG, CGROUPE, TYPBON, BT_CTR, CCRITDP, CSCRITDP, ANNEE
)

select REQ_ALL.CGROUPE
	 , GROUPE.LGROUPE
	 --, dbo.initcap(PC.LB_CATEGORIE) LB_CATEGORIE
	 , case when REQ_ALL.CSCRITDP = 990 then 'Non récupérable' else 'Récupérable' end LB_CATEGORIE
	 , TYPBON
	 , BT_CTR
	 , ANNEE ANNEE_BUDGET
	 , REQ_ALL.CCRITDP CD_CRITERE
	 , CRITDP.LCRITDP LB_CRITERE
	 , REQ_ALL.CSCRITDP CD_SOUS_CRITERE
	 , SCRITDP.LSCRITDP LB_SOUS_CRITERE
	 , MT_ENG
	 , MT_REA
--from REQ_ALL
from MASTER_ESTIA..ESTIA_LBUDLOC LBUDLOC
left join MASTER_ESTIA..ESTIA_GROUPE GROUPE
on GROUPE.CORG = LBUDLOC.CORG and GROUPE.CGROUPE = LBUDLOC.CGROUPE
left join MASTER_ESTIA..WRK_GROUPE_MANGES WGM
on WGM.PK_GROUPE = GROUPE.PK_GROUPE
left join MASTER_ESTIA..ESTIA_TIERS PROP
on PROP.PK_TIERS = WGM.FK_TIERS
left join MASTER_ESTIA..ESTIA_CRITDP CRITDP 
on CRITDP.CCRITDP = LBUDLOC.CCRITDP
left join MASTER_ESTIA..ESTIA_SCRITDP SCRITDP 
on SCRITDP.CORG = LBUDLOC.CORG and SCRITDP.CGROUPE = LBUDLOC.CGROUPE and SCRITDP.CCRITDP = LBUDLOC.CCRITDP and SCRITDP.CSCRITDP = LBUDLOC.CSCRITDP
left join MASTER_ESTIA..P_CRITERES PC on PC.CD_CRITERE = LBUDLOC.CCRITDP
left join REQ_ALL 
on REQ_ALL.CORG = LBUDLOC.CORG and REQ_ALL.CGROUPE = LBUDLOC.CGROUPE and REQ_ALL.CCRITDP = LBUDLOC.CCRITDP and REQ_ALL.CSCRITDP = LBUDLOC.CSCRITDP and REQ_ALL.ANNEE = LBUDLOC.CBUDLOC
where LBUDLOC.CORG = '11'
and PROP.PK_TIERS IN (SELECT VALUE FROM dbo.ufn_SplitMultiValue(@PK_PROPRIETAIRE,','))
and GROUPE.PK_GROUPE IN (SELECT VALUE FROM dbo.ufn_SplitMultiValue(@PK_IMMEUBLE,','))
and CRITDP.CCRITDP IN (SELECT VALUE FROM dbo.ufn_SplitMultiValue(@CCRITDP,','))
and SCRITDP.CSCRITDP IN (SELECT VALUE FROM dbo.ufn_SplitMultiValue(@CSCRITDP,','))
and LBUDLOC.CBUDLOC = @ANNEE_BUDGET
and TYPBON IN (SELECT VALUE FROM dbo.ufn_SplitMultiValue(@TYPBON,','))
--and LBUDLOC.CGROUPE = 610
--and CBUDLOC in (2019)
order by REQ_ALL.CGROUPE, ANNEE, PC.LB_CATEGORIE desc, REQ_ALL.CCRITDP, REQ_ALL.CSCRITDP, TYPBON, BT_CTR

END