-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
CREATE PROCEDURE [dbo].[COMPTABILITE_LOCATAIRE] 
(
	@DT_DEBUT DATETIME,
	@DT_FIN DATETIME,
	@PK_PROPRIETAIRE NVARCHAR(MAX),
	@PK_IMMEUBLE NVARCHAR(MAX),
	@PK_LOCATAIRE NVARCHAR(MAX)
)
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;
WITH REQ AS
(SELECT
   D_PROPRIETAIRE.PK_PROPRIETAIRE
  ,D_IMMEUBLE.PK_IMMEUBLE
  ,D_IMMEUBLE.CD_IMMEUBLE
  ,D_IMMEUBLE.NM_IMMEUBLE
  ,D_IMMEUBLE.ADRLGN1 AS NOM_IMMEUBLE
  ,D_BAIL.PK_BAIL
  ,D_BAIL.CD_BAIL
  ,D_BAIL.NM_BAIL
  ,D_LOCATAIRE.PK_LOCATAIRE
  ,DBO.INITCAP(D_LOCATAIRE.NOM_LOCATAIRE) AS NOM_LOCATAIRE
  ,D_RUBRIQUE.CD_NATURE_RUBRIQUE
  ,D_RUBRIQUE.LB_NATURE_RUBRIQUE
  ,SUM(F_COMPTABILITE_LOCATAIRE.MT_QUITTANCE) AS MT_QUITTANCE
  ,SUM(F_COMPTABILITE_LOCATAIRE.MT_ENCAISSE) *-1 AS MT_ENCAISSE
  ,SUM(F_COMPTABILITE_LOCATAIRE.MT_SOLDE) AS MT_SOLDE
FROM
  D_IMMEUBLE
  RIGHT OUTER JOIN F_COMPTABILITE_LOCATAIRE
    ON D_IMMEUBLE.PK_IMMEUBLE = F_COMPTABILITE_LOCATAIRE.FK_IMMEUBLE
  LEFT OUTER JOIN D_PROPRIETAIRE
	ON D_PROPRIETAIRE.PK_PROPRIETAIRE = F_COMPTABILITE_LOCATAIRE.FK_PROPRIETAIRE
  LEFT OUTER JOIN D_BAIL
    ON D_BAIL.PK_BAIL = F_COMPTABILITE_LOCATAIRE.FK_BAIL
  LEFT OUTER JOIN D_LOCATAIRE
    ON D_LOCATAIRE.PK_LOCATAIRE = F_COMPTABILITE_LOCATAIRE.FK_LOCATAIRE
  LEFT OUTER JOIN D_RUBRIQUE
    ON D_RUBRIQUE.PK_RUBRIQUE = F_COMPTABILITE_LOCATAIRE.FK_RUBRIQUE

WHERE F_COMPTABILITE_LOCATAIRE.DT_COMPTABLE BETWEEN @DT_DEBUT AND @DT_FIN
AND F_COMPTABILITE_LOCATAIRE.DT_TERME <= @DT_FIN
AND D_PROPRIETAIRE.PK_PROPRIETAIRE IN (SELECT VALUE FROM dbo.ufn_SplitMultiValue(@PK_PROPRIETAIRE,',')) 
AND D_IMMEUBLE.PK_IMMEUBLE IN (SELECT VALUE FROM dbo.ufn_SplitMultiValue(@PK_IMMEUBLE,','))
AND D_LOCATAIRE.PK_LOCATAIRE IN (SELECT VALUE FROM dbo.ufn_SplitMultiValue(@PK_LOCATAIRE,','))
AND D_IMMEUBLE.CD_SOCIETE = '11'
GROUP BY  D_PROPRIETAIRE.PK_PROPRIETAIRE
  ,D_IMMEUBLE.PK_IMMEUBLE
  ,D_IMMEUBLE.NM_IMMEUBLE
  ,D_IMMEUBLE.CD_IMMEUBLE
  ,D_IMMEUBLE.ADRLGN1
  ,D_BAIL.PK_BAIL
  ,D_BAIL.CD_BAIL
  ,D_BAIL.NM_BAIL
  ,D_LOCATAIRE.PK_LOCATAIRE
  ,D_LOCATAIRE.NOM_LOCATAIRE
  ,D_RUBRIQUE.CD_NATURE_RUBRIQUE
  ,D_RUBRIQUE.LB_NATURE_RUBRIQUE
UNION
 SELECT
   D_PROPRIETAIRE.PK_PROPRIETAIRE
  ,D_IMMEUBLE.PK_IMMEUBLE
  ,D_IMMEUBLE.CD_IMMEUBLE
  ,D_IMMEUBLE.NM_IMMEUBLE
  ,D_IMMEUBLE.ADRLGN1 AS NOM_IMMEUBLE
  ,D_BAIL.PK_BAIL
  ,D_BAIL.CD_BAIL
  ,D_BAIL.NM_BAIL
  ,D_LOCATAIRE.PK_LOCATAIRE
  ,DBO.INITCAP(D_LOCATAIRE.NOM_LOCATAIRE) AS NOM_LOCATAIRE
  ,'D' AS CD_NATURE_RUBRIQUE
  , 'Divers' AS LB_NATURE_RUBRIQUE
  ,SUM(F_COMPTABILITE_LOCATAIRE.MT_QUITTANCE) AS MT_QUITTANCE
  ,SUM(F_COMPTABILITE_LOCATAIRE.MT_ENCAISSE) *-1 AS MT_ENCAISSE
  ,SUM(F_COMPTABILITE_LOCATAIRE.MT_SOLDE) AS MT_SOLDE
FROM
  D_IMMEUBLE
  RIGHT OUTER JOIN F_COMPTABILITE_LOCATAIRE
    ON D_IMMEUBLE.PK_IMMEUBLE = F_COMPTABILITE_LOCATAIRE.FK_IMMEUBLE
  LEFT OUTER JOIN D_PROPRIETAIRE
	ON D_PROPRIETAIRE.PK_PROPRIETAIRE = F_COMPTABILITE_LOCATAIRE.FK_PROPRIETAIRE
  LEFT OUTER JOIN D_BAIL
    ON D_BAIL.PK_BAIL = F_COMPTABILITE_LOCATAIRE.FK_BAIL
  LEFT OUTER JOIN D_LOCATAIRE
    ON D_LOCATAIRE.PK_LOCATAIRE = F_COMPTABILITE_LOCATAIRE.FK_LOCATAIRE

WHERE F_COMPTABILITE_LOCATAIRE.DT_COMPTABLE BETWEEN @DT_DEBUT AND @DT_FIN
AND (F_COMPTABILITE_LOCATAIRE.DT_TERME IS NULL)
AND D_PROPRIETAIRE.PK_PROPRIETAIRE IN (SELECT VALUE FROM dbo.ufn_SplitMultiValue(@PK_PROPRIETAIRE,',')) 
AND D_IMMEUBLE.PK_IMMEUBLE IN (SELECT VALUE FROM dbo.ufn_SplitMultiValue(@PK_IMMEUBLE,','))
AND D_LOCATAIRE.PK_LOCATAIRE IN (SELECT VALUE FROM dbo.ufn_SplitMultiValue(@PK_LOCATAIRE,','))
AND D_IMMEUBLE.CD_SOCIETE = '11'
GROUP BY  D_PROPRIETAIRE.PK_PROPRIETAIRE
  ,D_IMMEUBLE.PK_IMMEUBLE
  ,D_IMMEUBLE.NM_IMMEUBLE
  ,D_IMMEUBLE.CD_IMMEUBLE
  ,D_IMMEUBLE.ADRLGN1
  ,D_BAIL.PK_BAIL
  ,D_BAIL.CD_BAIL
  ,D_BAIL.NM_BAIL
  ,D_LOCATAIRE.PK_LOCATAIRE
  ,D_LOCATAIRE.NOM_LOCATAIRE
)
, REQ2 AS
(
	SELECT
	   D_PROPRIETAIRE.PK_PROPRIETAIRE
	  ,D_IMMEUBLE.PK_IMMEUBLE
	  ,D_IMMEUBLE.CD_IMMEUBLE
	  ,D_IMMEUBLE.NM_IMMEUBLE
	  ,D_IMMEUBLE.ADRLGN1 AS NOM_IMMEUBLE
	  ,D_BAIL.PK_BAIL
	  ,D_BAIL.CD_BAIL
	  ,D_BAIL.NM_BAIL
	  ,D_LOCATAIRE.PK_LOCATAIRE
	  ,DBO.INITCAP(D_LOCATAIRE.NOM_LOCATAIRE) AS NOM_LOCATAIRE
	  ,D_RUBRIQUE.CD_NATURE_RUBRIQUE
	  ,D_RUBRIQUE.LB_NATURE_RUBRIQUE
	  ,SUM(F_COMPTABILITE_LOCATAIRE.MT_SOLDE) AS MT_SOLDE
	FROM
	  D_IMMEUBLE
	  RIGHT OUTER JOIN F_COMPTABILITE_LOCATAIRE
		ON D_IMMEUBLE.PK_IMMEUBLE = F_COMPTABILITE_LOCATAIRE.FK_IMMEUBLE
	  LEFT OUTER JOIN D_PROPRIETAIRE
	    ON D_PROPRIETAIRE.PK_PROPRIETAIRE = F_COMPTABILITE_LOCATAIRE.FK_PROPRIETAIRE
	  LEFT OUTER JOIN D_BAIL
		ON D_BAIL.PK_BAIL = F_COMPTABILITE_LOCATAIRE.FK_BAIL
	  LEFT OUTER JOIN D_LOCATAIRE
		ON D_LOCATAIRE.PK_LOCATAIRE = F_COMPTABILITE_LOCATAIRE.FK_LOCATAIRE
	  LEFT OUTER JOIN D_RUBRIQUE
		ON D_RUBRIQUE.PK_RUBRIQUE = F_COMPTABILITE_LOCATAIRE.FK_RUBRIQUE
	WHERE F_COMPTABILITE_LOCATAIRE.DT_COMPTABLE < @DT_DEBUT
	AND D_IMMEUBLE.PK_IMMEUBLE IN (SELECT VALUE FROM dbo.ufn_SplitMultiValue(@PK_IMMEUBLE,','))
	AND D_LOCATAIRE.PK_LOCATAIRE IN (SELECT VALUE FROM dbo.ufn_SplitMultiValue(@PK_LOCATAIRE,','))
	AND D_IMMEUBLE.CD_SOCIETE = '11'
	GROUP BY D_PROPRIETAIRE.PK_PROPRIETAIRE
	  ,D_IMMEUBLE.PK_IMMEUBLE
	  ,D_IMMEUBLE.CD_IMMEUBLE
	  ,D_IMMEUBLE.NM_IMMEUBLE
	  ,D_IMMEUBLE.ADRLGN1
	  ,D_BAIL.PK_BAIL
	  ,D_BAIL.CD_BAIL
	  ,D_BAIL.NM_BAIL
	  ,D_LOCATAIRE.PK_LOCATAIRE
	  ,D_LOCATAIRE.NOM_LOCATAIRE
	  ,D_RUBRIQUE.CD_NATURE_RUBRIQUE
	  ,D_RUBRIQUE.LB_NATURE_RUBRIQUE
), REQ3 AS
(
SELECT REQ.PK_PROPRIETAIRE
	 , REQ.PK_IMMEUBLE
	 , REQ.CD_IMMEUBLE
	 , REQ.NM_IMMEUBLE
	 , REQ.NOM_IMMEUBLE
	 , REQ.PK_BAIL
	 , REQ.CD_BAIL
	 , REQ.NM_BAIL
	 , REQ.PK_LOCATAIRE
	 , REQ.NOM_LOCATAIRE
	 , REQ.CD_NATURE_RUBRIQUE
	 , REQ.LB_NATURE_RUBRIQUE
	 , 0 AS MT_SOLDE_AVT_PERIODE
	 , ISNULL(REQ.MT_QUITTANCE,0) AS MT_QUITTANCE
	 , ISNULL(REQ.MT_ENCAISSE,0) AS MT_ENCAISSE
	 , ISNULL(REQ.MT_SOLDE,0) AS MT_SOLDE
FROM REQ
UNION
SELECT REQ2.PK_PROPRIETAIRE
	 , REQ2.PK_IMMEUBLE
	 , REQ2.CD_IMMEUBLE
	 , REQ2.NM_IMMEUBLE
	 , REQ2.NOM_IMMEUBLE
	 , REQ2.PK_BAIL
	 , REQ2.CD_BAIL
	 , REQ2.NM_BAIL
	 , REQ2.PK_LOCATAIRE
	 , REQ2.NOM_LOCATAIRE
	 , REQ2.CD_NATURE_RUBRIQUE
	 , REQ2.LB_NATURE_RUBRIQUE
	 , REQ2.MT_SOLDE AS MT_SOLDE_AVT_PERIODE
	 , 0 AS MT_QUITTANCE
	 , 0 AS MT_ENCAISSE
	 , 0 AS MT_SOLDE
FROM REQ2
WHERE REQ2.MT_SOLDE <> 0
)

SELECT REQ3.PK_PROPRIETAIRE
	 , REQ3.PK_IMMEUBLE
	 , REQ3.CD_IMMEUBLE
	 , REQ3.NM_IMMEUBLE
	 , REQ3.NOM_IMMEUBLE
	 , REQ3.PK_BAIL
	 , REQ3.CD_BAIL
	 , REQ3.NM_BAIL
	 , REQ3.PK_LOCATAIRE
	 , REQ3.NOM_LOCATAIRE
	 , REQ3.CD_NATURE_RUBRIQUE
	 , REQ3.LB_NATURE_RUBRIQUE
	 , SUM(REQ3.MT_SOLDE_AVT_PERIODE) AS MT_SOLDE_AVT_PERIODE
	 , SUM(REQ3.MT_QUITTANCE) AS MT_QUITTANCE
	 , SUM(REQ3.MT_ENCAISSE) AS MT_ENCAISSE
	 , SUM(REQ3.MT_SOLDE) AS MT_SOLDE
	 , SUM(REQ3.MT_SOLDE_AVT_PERIODE + REQ3.MT_SOLDE) AS MT_SOLDE_FIN_PERIODE
FROM REQ3
	GROUP BY REQ3.PK_PROPRIETAIRE
	  ,REQ3.PK_IMMEUBLE
	  ,REQ3.CD_IMMEUBLE
	  ,REQ3.NM_IMMEUBLE
	  ,REQ3.NOM_IMMEUBLE
	  ,REQ3.PK_BAIL
	  ,REQ3.CD_BAIL
	  ,REQ3.NM_BAIL
	  ,REQ3.PK_LOCATAIRE
	  ,REQ3.NOM_LOCATAIRE
	  ,REQ3.CD_NATURE_RUBRIQUE
	  ,REQ3.LB_NATURE_RUBRIQUE
ORDER BY REQ3.NM_IMMEUBLE,REQ3.NM_BAIL, REQ3.CD_NATURE_RUBRIQUE

/*SELECT
  D_PROPRIETAIRE.PK_PROPRIETAIRE
  ,D_IMMEUBLE.PK_IMMEUBLE
  ,D_IMMEUBLE.CD_IMMEUBLE
  ,D_IMMEUBLE.NM_IMMEUBLE
  ,D_IMMEUBLE.ADRLGN1 AS NOM_IMMEUBLE
  ,D_BAIL.PK_BAIL
  ,D_BAIL.CD_BAIL
  ,D_BAIL.NM_BAIL
  ,D_LOCATAIRE.PK_LOCATAIRE
  ,dbo.InitCap(D_LOCATAIRE.NOM_LOCATAIRE) AS NOM_LOCATAIRE
  ,D_RUBRIQUE.CD_NATURE_RUBRIQUE
  ,D_RUBRIQUE.LB_NATURE_RUBRIQUE
  ,SUM(SOLDE_AVT_PERIODE.MT_SOLDE) AS MT_SOLDE_AVT_PERIODE
  ,SUM(F_COMPTABILITE_LOCATAIRE.MT_QUITTANCE) AS MT_QUITTANCE
  ,SUM(F_COMPTABILITE_LOCATAIRE.MT_ENCAISSE) *-1 AS MT_ENCAISSE
  ,SUM(F_COMPTABILITE_LOCATAIRE.MT_SOLDE) AS MT_SOLDE
  ,SUM(SOLDE_AVT_PERIODE.MT_SOLDE+F_COMPTABILITE_LOCATAIRE.MT_SOLDE) AS MT_SOLDE_FIN_PERIODE
FROM
  D_IMMEUBLE
  RIGHT OUTER JOIN F_COMPTABILITE_LOCATAIRE
    ON D_IMMEUBLE.PK_IMMEUBLE = F_COMPTABILITE_LOCATAIRE.FK_IMMEUBLE
  LEFT OUTER JOIN D_PROPRIETAIRE
	ON D_PROPRIETAIRE.PK_PROPRIETAIRE = F_COMPTABILITE_LOCATAIRE.FK_PROPRIETAIRE
  LEFT OUTER JOIN D_BAIL
    ON D_BAIL.PK_BAIL = F_COMPTABILITE_LOCATAIRE.FK_BAIL
  LEFT OUTER JOIN D_LOCATAIRE
    ON D_LOCATAIRE.PK_LOCATAIRE = F_COMPTABILITE_LOCATAIRE.FK_LOCATAIRE
  LEFT OUTER JOIN D_RUBRIQUE
    ON D_RUBRIQUE.PK_RUBRIQUE = F_COMPTABILITE_LOCATAIRE.FK_RUBRIQUE
  LEFT OUTER JOIN
  (
	SELECT
	  D_IMMEUBLE.PK_IMMEUBLE
	  ,D_BAIL.PK_BAIL
	  ,D_RUBRIQUE.PK_RUBRIQUE
	  ,D_RUBRIQUE.CD_NATURE_RUBRIQUE
	  ,D_RUBRIQUE.LB_NATURE_RUBRIQUE
	  ,SUM(F_COMPTABILITE_LOCATAIRE.MT_SOLDE) AS MT_SOLDE
	FROM
	  D_IMMEUBLE
	  RIGHT OUTER JOIN F_COMPTABILITE_LOCATAIRE
		ON D_IMMEUBLE.PK_IMMEUBLE = F_COMPTABILITE_LOCATAIRE.FK_IMMEUBLE
	  LEFT OUTER JOIN D_BAIL
		ON D_BAIL.PK_BAIL = F_COMPTABILITE_LOCATAIRE.FK_BAIL
	  LEFT OUTER JOIN D_LOCATAIRE
		ON D_LOCATAIRE.PK_LOCATAIRE = F_COMPTABILITE_LOCATAIRE.FK_LOCATAIRE
	  LEFT OUTER JOIN D_RUBRIQUE
		ON D_RUBRIQUE.PK_RUBRIQUE = F_COMPTABILITE_LOCATAIRE.FK_RUBRIQUE
	WHERE F_COMPTABILITE_LOCATAIRE.DT_COMPTABLE < @DT_DEBUT
	AND D_IMMEUBLE.CD_SOCIETE = '11'
	GROUP BY D_IMMEUBLE.PK_IMMEUBLE
	  ,D_BAIL.PK_BAIL
	  ,D_LOCATAIRE.PK_LOCATAIRE
	  ,D_RUBRIQUE.PK_RUBRIQUE
	  ,D_RUBRIQUE.CD_RUBRIQUE
	  ,D_RUBRIQUE.NM_RUBRIQUE
	  ,D_RUBRIQUE.LB_RUBRIQUE
	  ,D_RUBRIQUE.CD_NATURE_RUBRIQUE
	  ,D_RUBRIQUE.LB_NATURE_RUBRIQUE
  )
  SOLDE_AVT_PERIODE
  ON SOLDE_AVT_PERIODE.PK_IMMEUBLE = F_COMPTABILITE_LOCATAIRE.FK_IMMEUBLE
  AND SOLDE_AVT_PERIODE.PK_BAIL = F_COMPTABILITE_LOCATAIRE.FK_BAIL
  AND SOLDE_AVT_PERIODE.PK_RUBRIQUE = F_COMPTABILITE_LOCATAIRE.FK_RUBRIQUE
WHERE F_COMPTABILITE_LOCATAIRE.DT_COMPTABLE BETWEEN @DT_DEBUT AND @DT_FIN
AND F_COMPTABILITE_LOCATAIRE.DT_TERME <= @DT_FIN--BETWEEN @DT_DEBUT AND @DT_FIN
AND D_PROPRIETAIRE.PK_PROPRIETAIRE = @PK_PROPRIETAIRE
AND D_IMMEUBLE.PK_IMMEUBLE IN (SELECT VALUE FROM dbo.ufn_SplitMultiValue(@PK_IMMEUBLE,',')) --(@PK_IMMEUBLE)
AND D_LOCATAIRE.PK_LOCATAIRE IN (SELECT VALUE FROM dbo.ufn_SplitMultiValue(@PK_LOCATAIRE,',')) --(@PK_LOCATAIRE)
AND D_IMMEUBLE.CD_SOCIETE = '11'
GROUP BY  D_PROPRIETAIRE.PK_PROPRIETAIRE
  ,D_IMMEUBLE.PK_IMMEUBLE
  ,D_IMMEUBLE.NM_IMMEUBLE
  ,D_IMMEUBLE.CD_IMMEUBLE
  ,D_IMMEUBLE.ADRLGN1
  ,D_BAIL.PK_BAIL
  ,D_BAIL.CD_BAIL
  ,D_BAIL.NM_BAIL
  ,D_LOCATAIRE.PK_LOCATAIRE
  ,D_LOCATAIRE.NOM_LOCATAIRE
  ,D_RUBRIQUE.CD_NATURE_RUBRIQUE
  ,D_RUBRIQUE.LB_NATURE_RUBRIQUE
ORDER BY D_IMMEUBLE.NM_IMMEUBLE,D_BAIL.NM_BAIL
*/
END