-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
CREATE PROCEDURE [dbo].[COMPTABILITE_LOCATAIRE_CAIRN] 
(
	  @DT_DEBUT DATETIME
	, @DT_FIN DATETIME
	, @PK_PROPRIETAIRE NVARCHAR(MAX)
	, @PK_IMMEUBLE NVARCHAR(MAX)
	, @PK_LOCATAIRE NVARCHAR(MAX)
)
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;

SELECT WGM.CMANDAT MANDAT
     , TIERS.LTIERS SOCIETE
	 , CASE MANGES.PROVHT WHEN 0 THEN 'Transparent' ELSE 'Opaque' END AS TYPE
	 , LOCATION.CAGENCE AGENCE
	 , LOCATION.CGROUPE GROUPE
	 , LOCATION.CIMMEUB IMMEUBLE
	 , LOCATION.CLOCAL LOCAL
	 , LOCATION.CCOMPTE COMPTE
	 , CASE LOCATION.LTVA WHEN 0 THEN 'Non' ELSE 'Oui' END AS ASSUJETTI_TVA
	 , LOCATION.TERME AS TERME
	 , LOCATION.PERIOD PERIODICITE
	 , CASE LOCATION.LTVA WHEN 0 THEN 'Non' ELSE 'Oui' END AS TVA
	 , CPTGLOB.CJOURNAL AS JOURNAL
	 , DBO.LPAD(CPTGLOB.CALC_CRUB, 3, '0') AS RUBRIQUE_COMPTA
	 , CPTGLOB.LIB LIBELLE
	 , CPTGLOB.DATEC DATE_ECRITURE
	 , CPTGLOB.LETTRAGE LETTRAGE
	 , RIGHT(CPTGLOB.LETTRAGE, 3) RUBRIQUE
	 , RUB_LET.LRUB LIBELLE_RUBRIQUE
	 , CPTGLOB.SENS SENS_ECRITURE
	 , CPTGLOB.MONTANT MONTANT

FROM MASTER_ESTIA..ESTIA_CPTGLOB CPTGLOB
LEFT JOIN MASTER_ESTIA..ESTIA_GROUPE GROUPE
ON GROUPE.PK_GROUPE = CPTGLOB.FK_GROUPE
LEFT JOIN MASTER_ESTIA..WRK_GROUPE_MANGES WGM
ON WGM.PK_GROUPE = CPTGLOB.FK_GROUPE
LEFT JOIN MASTER_ESTIA..ESTIA_MANGES MANGES
ON MANGES.PK_MANGES = WGM.FK_MANGES
LEFT JOIN MASTER_ESTIA..ESTIA_TIERS TIERS
ON TIERS.PK_TIERS = WGM.FK_TIERS
LEFT JOIN MASTER_ESTIA..ESTIA_LOCATION LOCATION
--ON LOCATION.FK_BAIL = CPTGLOB.FK_BAIL
ON LOCATION.PK_LOCATION = CPTGLOB.FK_BAIL
LEFT JOIN MASTER_ESTIA..ESTIA_RUB RUB
ON RUB.CRUB = CPTGLOB.CALC_CRUB
LEFT JOIN MASTER_ESTIA..ESTIA_RUB RUB_LET
ON RUB_LET.CRUB = RIGHT(CPTGLOB.LETTRAGE, 3)
WHERE CPTGLOB.CORG = '11'
AND CPTGLOB.DATEC BETWEEN @DT_DEBUT AND @DT_FIN --'20170902' AND '20171124'
AND WGM.FK_TIERS IN (SELECT VALUE FROM dbo.ufn_SplitMultiValue(@PK_PROPRIETAIRE,','))  --= 7378
AND CPTGLOB.FK_GROUPE IN (SELECT VALUE FROM dbo.ufn_SplitMultiValue(@PK_IMMEUBLE,','))
AND CPTGLOB.FK_TIERS IN (SELECT VALUE FROM dbo.ufn_SplitMultiValue(@PK_LOCATAIRE,','))
AND CPTGLOB.TYPCPTA = 'LG'


END