-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
CREATE PROCEDURE [dbo].[COMPTABILITE_LOCATAIRE_DET] 
(
	@DT_DEBUT DATETIME,
	@DT_FIN DATETIME,
	@PK_PROPRIETAIRE NVARCHAR(MAX),
	@PK_IMMEUBLE NVARCHAR(MAX),
	@PK_LOCATAIRE NVARCHAR(MAX)
)
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;

SELECT FCL.FK_PROPRIETAIRE
	 , P.NOM_PROPRIETAIRE
	 , FCL.FK_IMMEUBLE
	 , I.NM_IMMEUBLE
	 , I.ADRLGN1 AS NOM_IMMEUBLE
	 , FCL.FK_BAIL
	 , B.CD_BAIL
	 , B.NM_BAIL
	 , FCL.FK_LOCATAIRE
	 , L.NM_LOCATAIRE
	 , L.NOM_LOCATAIRE
	 , FCL.FK_RUBRIQUE
	 , R.CD_RUBRIQUE
	 , R.LB_RUBRIQUE
	 , R.CD_NATURE_RUBRIQUE
	 , R.LB_NATURE_RUBRIQUE
	 , FCL.DT_TERME
	 , FCL.DT_COMPTABLE
	 , FCL.NUM_SAISIE
	 , FCL.LB_ECRITURE
	 , SUM(FCL.MT_QUITTANCE) AS MT_QUITTANCE
	 , SUM(FCL.MT_ENCAISSE) AS MT_ENCAISSE
	 , SUM(FCL.MT_SOLDE) AS MT_SOLDE
FROM F_COMPTABILITE_LOCATAIRE FCL
LEFT JOIN D_PROPRIETAIRE P
ON P.PK_PROPRIETAIRE = FCL.FK_PROPRIETAIRE
LEFT JOIN D_IMMEUBLE I
ON I.PK_IMMEUBLE = FCL.FK_IMMEUBLE
LEFT JOIN D_BAIL B
ON B.PK_BAIL = FCL.FK_BAIL
LEFT JOIN D_LOCATAIRE L
ON L.PK_LOCATAIRE = FCL.FK_LOCATAIRE
LEFT JOIN D_RUBRIQUE R
ON R.PK_RUBRIQUE = FCL.FK_RUBRIQUE
WHERE FCL.DT_COMPTABLE BETWEEN @DT_DEBUT AND @DT_FIN
AND FCL.DT_TERME <= @DT_FIN
AND P.PK_PROPRIETAIRE IN (SELECT VALUE FROM dbo.ufn_SplitMultiValue(@PK_PROPRIETAIRE,','))
AND I.PK_IMMEUBLE IN (SELECT VALUE FROM dbo.ufn_SplitMultiValue(@PK_IMMEUBLE,','))
AND L.PK_LOCATAIRE IN (SELECT VALUE FROM dbo.ufn_SplitMultiValue(@PK_LOCATAIRE,','))
AND I.CD_SOCIETE = '11'
and R.CD_RUBRIQUE NOT IN (503, 515, 516)
--FCL.FK_IMMEUBLE = 188
--AND FCL.FK_TEMPS BETWEEN '20170101' AND '20170331'
--AND FCL.FK_LOCATAIRE = 8907
GROUP BY FCL.FK_PROPRIETAIRE, P.NOM_PROPRIETAIRE, FCL.FK_IMMEUBLE, I.NM_IMMEUBLE, I.ADRLGN1, FCL.FK_BAIL, B.CD_BAIL, B.NM_BAIL, FCL.FK_LOCATAIRE, L.NM_LOCATAIRE, L.NOM_LOCATAIRE, FK_RUBRIQUE, R.CD_RUBRIQUE, R.LB_RUBRIQUE, R.CD_NATURE_RUBRIQUE, R.LB_NATURE_RUBRIQUE, DT_TERME, FCL.DT_COMPTABLE, FCL.NUM_SAISIE, LB_ECRITURE
--ORDER BY DT_TERME, FCL.DT_COMPTABLE, FCL.NUM_SAISIE, R.CD_RUBRIQUE, R.CD_NATURE_RUBRIQUE
UNION
SELECT FCL.FK_PROPRIETAIRE
	 , P.NOM_PROPRIETAIRE
	 , FCL.FK_IMMEUBLE
	 , I.NM_IMMEUBLE
	 , I.ADRLGN1 AS NOM_IMMEUBLE
	 , FCL.FK_BAIL
	 , B.CD_BAIL
	 , B.NM_BAIL
	 , FCL.FK_LOCATAIRE
	 , L.NM_LOCATAIRE
	 , L.NOM_LOCATAIRE
	 , FCL.FK_RUBRIQUE
	 , R.CD_RUBRIQUE
	 , R.LB_RUBRIQUE
	 , R.CD_NATURE_RUBRIQUE
	 , R.LB_NATURE_RUBRIQUE
	 , FCL.DT_TERME
	 , FCL.DT_COMPTABLE
	 , CASE WHEN FCL.LB_ECRITURE LIKE '%TB + TASS%' THEN 'M9999999999' ELSE FCL.NUM_SAISIE END AS NUM_SAISIE--FCL.NUM_SAISIE
	 , FCL.LB_ECRITURE
	 , SUM(FCL.MT_QUITTANCE) AS MT_QUITTANCE
	 , SUM(FCL.MT_ENCAISSE) AS MT_ENCAISSE
	 , SUM(FCL.MT_SOLDE) AS MT_SOLDE
FROM --F_COMPTABILITE_LOCATAIRE FCL
(
 SELECT FK_PROPRIETAIRE, FK_IMMEUBLE, FK_BAIL, FK_LOCATAIRE, FK_RUBRIQUE, DT_TERME, DT_COMPTABLE, LB_ECRITURE,
 CASE WHEN LB_ECRITURE LIKE '%TB + TASS%' THEN 'M9999999999' ELSE NUM_SAISIE END AS NUM_SAISIE,
   MT_QUITTANCE, MT_ENCAISSE, MT_SOLDE
 FROM F_COMPTABILITE_LOCATAIRE
) FCL
LEFT JOIN D_PROPRIETAIRE P
ON P.PK_PROPRIETAIRE = FCL.FK_PROPRIETAIRE
LEFT JOIN D_IMMEUBLE I
ON I.PK_IMMEUBLE = FCL.FK_IMMEUBLE
LEFT JOIN D_BAIL B
ON B.PK_BAIL = FCL.FK_BAIL
LEFT JOIN D_LOCATAIRE L
ON L.PK_LOCATAIRE = FCL.FK_LOCATAIRE
LEFT JOIN D_RUBRIQUE R
ON R.PK_RUBRIQUE = FCL.FK_RUBRIQUE
WHERE FCL.DT_COMPTABLE BETWEEN @DT_DEBUT AND @DT_FIN
AND FCL.DT_TERME <= @DT_FIN
AND P.PK_PROPRIETAIRE IN (SELECT VALUE FROM dbo.ufn_SplitMultiValue(@PK_PROPRIETAIRE,','))
AND I.PK_IMMEUBLE IN (SELECT VALUE FROM dbo.ufn_SplitMultiValue(@PK_IMMEUBLE,','))
AND L.PK_LOCATAIRE IN (SELECT VALUE FROM dbo.ufn_SplitMultiValue(@PK_LOCATAIRE,','))
AND I.CD_SOCIETE = '11'
AND R.CD_RUBRIQUE IN (503, 515, 516)
GROUP BY FCL.FK_PROPRIETAIRE, P.NOM_PROPRIETAIRE, FCL.FK_IMMEUBLE, I.NM_IMMEUBLE, I.ADRLGN1, FCL.FK_BAIL, B.CD_BAIL, B.NM_BAIL, FCL.FK_LOCATAIRE, L.NM_LOCATAIRE, L.NOM_LOCATAIRE, FK_RUBRIQUE, R.CD_RUBRIQUE, R.LB_RUBRIQUE, R.CD_NATURE_RUBRIQUE, R.LB_NATURE_RUBRIQUE, DT_TERME, FCL.DT_COMPTABLE, FCL.NUM_SAISIE, LB_ECRITURE
ORDER BY DT_TERME, FCL.DT_COMPTABLE, FCL.NUM_SAISIE, R.CD_RUBRIQUE, R.CD_NATURE_RUBRIQUE

END