-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
CREATE PROCEDURE [dbo].[EDD_CAIRN]
( 
	@DT_DEBUT DATETIME,
	@DT_FIN DATETIME,
	@PK_PROPRIETAIRE NVARCHAR(MAX)
)
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;

select HDEPCS.CORG
	 , HDEPCS.CAGENCE
	 , AGENCE.LAGENCE
	 , HDEPCS.CGROUPE
	 , GROUPE.LGROUPE
	 , HDEPCS.CSCRITDP
	 , SCRITDP.LSCRITDP
	 , HDEPCS.CCRITDP
	 , CRITDP.LCRITDP
	 , HDEPCS.DEFFETREG
	 , HDEPCS.DATEC
	 , ECRITAUX.CJOURNAL
	 , ECRITAUX.NOPIECE
	 , ECRITAUX.REF
	 , ECRITAUX.CTIERS
	 , TIERS.LTIERS
	 , HDEPCS.LIBELLE
	 , SCRITDP.TREGUL
	 , SCRITDP.TRECUP
	 , SUM(HDEPCS.MTHT) MTHT
	 , SUM(HDEPCS.MTTVA) MTTVA
	 , SUM(HDEPCS.MTTC) MTTC
	 , SUM(CASE WHEN SCRITDP.TRECUP = 0 THEN HDEPCS.MTNREC - HDEPCS.MTTVADED ELSE 0 END) MTNREC
	 , SUM(HDEPCS.MTRECUP) MTRECUP
	 , SUM(CASE WHEN SCRITDP.TREGUL = 1 THEN HDEPCS.MTTC ELSE 0 END) MTREGUL
from MASTER_ESTIA..ESTIA_HDEPCS HDEPCS
LEFT JOIN MASTER_ESTIA..ESTIA_SCRITDP SCRITDP
ON SCRITDP.PK_SCRITDP =  HDEPCS.FK_SCRITDP
LEFT JOIN MASTER_ESTIA..ESTIA_CRITDP CRITDP
on CRITDP.CCRITDP = HDEPCS.CCRITDP 
LEFT JOIN MASTER_ESTIA..ESTIA_AGENCE AGENCE
ON AGENCE.PK_AGENCE = HDEPCS.FK_AGENCE
LEFT JOIN MASTER_ESTIA..ESTIA_GROUPE GROUPE
ON GROUPE.PK_GROUPE = HDEPCS.FK_GROUPE
LEFT JOIN 
(
	SELECT ECRITAUX.FK_TIERS, ECRITAUX.CORG, ECRITAUX.REF, ECRITAUX.CTYPTIERS, ECRITAUX.CTIERS, ECRITAUX.CJOURNAL, ECRITAUX.NOPIECE
	FROM MASTER_ESTIA..ESTIA_ECRITAUX ECRITAUX
	WHERE ECRITAUX.CORG = '11'
) ECRITAUX
ON ECRITAUX.REF = HDEPCS.REF 
LEFT JOIN MASTER_ESTIA..ESTIA_TIERS TIERS
ON TIERS.PK_TIERS = ECRITAUX.FK_TIERS
LEFT JOIN MASTER_ESTIA..WRK_GROUPE_MANGES WGM
ON WGM.PK_GROUPE = HDEPCS.FK_GROUPE
LEFT JOIN MASTER_ESTIA..ESTIA_TIERS PROPRIETAIRE
ON PROPRIETAIRE.PK_TIERS = WGM.FK_TIERS
WHERE HDEPCS.CORG = '11'
AND HDEPCS.DATEC BETWEEN @DT_DEBUT AND @DT_FIN
AND WGM.FK_TIERS IN (SELECT VALUE FROM dbo.ufn_SplitMultiValue(@PK_PROPRIETAIRE,',')) 
AND HDEPCS.CMANDAT IS NOT NULL
GROUP  BY HDEPCS.CORG
		, HDEPCS.CAGENCE
		, AGENCE.LAGENCE
		, HDEPCS.CGROUPE
		, GROUPE.LGROUPE
		, HDEPCS.CSCRITDP
		, SCRITDP.LSCRITDP
		, HDEPCS.CCRITDP
		, CRITDP.LCRITDP
		, HDEPCS.DEFFETREG
		, HDEPCS.DATEC
		, ECRITAUX.CJOURNAL
		, ECRITAUX.NOPIECE
		, ECRITAUX.REF
		, ECRITAUX.CTIERS
		, TIERS.LTIERS
		, HDEPCS.LIBELLE
		, SCRITDP.TREGUL
		, SCRITDP.TRECUP
ORDER BY HDEPCS.CSCRITDP, HDEPCS.CCRITDP

END