-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
CREATE PROCEDURE [dbo].[EDP] 
( 
	@DT_DEBUT DATETIME,
	@DT_FIN DATETIME,
	@PK_PROPRIETAIRE NVARCHAR(MAX),
	@PK_IMMEUBLE NVARCHAR(MAX)
)
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;

	SELECT WGM.FK_TIERS AS PK_PROPRIETAIRE
		 , PROP.LTIERS AS NOM_PROPRIETAIRE
		 , HQFAC.CORG
	     , LOCATION.CAGENCE
		 , LOCATION.CGROUPE
		 , LOCATION.CIMMEUB
		 , LOCATION.CLOCAL
		 , CAST(HQFAC.CCOMPTE AS NUMERIC(10,0)) AS CCOMPTE
		 , LOC.LTIERS AS NOM_LOC
		 , HQFAC.CRUB
		 --, HQFAC.TRUB
		 , RUB.LRUB
		 , HQFAC.DATEC
		 , CASE HQFAC.SENS WHEN 'C' THEN CAST(HQFAC.MONTANT AS NUMERIC(18,2)) ELSE 0 END MT_DEBIT 
		 , CASE HQFAC.SENS WHEN 'D' THEN CAST(HQFAC.MONTANT AS NUMERIC(18,2)) ELSE 0 END MT_CREDIT
		 , CASE WHEN HQFAC.CRUB IN ('501', '502', '503', '504', '505') THEN '46777000' ELSE '46770000' END AS NUM_COMPTE
		 , ROW_NUMBER() OVER(ORDER BY LOC.LTIERS) AS ROW
	FROM MASTER_ESTIA..ESTIA_HQFAC HQFAC
	LEFT JOIN MASTER_ESTIA..ESTIA_LOCATION LOCATION
	ON LOCATION.CORG = HQFAC.CORG AND LOCATION.CCOMPTE = HQFAC.CCOMPTE AND LOCATION.NOLOCAT = HQFAC.NOLOCAT
	LEFT JOIN MASTER_ESTIA..WRK_GROUPE_MANGES WGM
	ON WGM.PK_GROUPE = LOCATION.FK_GROUPE
	LEFT JOIN  MASTER_ESTIA..ESTIA_GROUPE GROUPE
	ON GROUPE.PK_GROUPE = WGM.PK_GROUPE
	LEFT JOIN MASTER_ESTIA..ESTIA_TIERS PROP
	ON PROP.PK_TIERS = WGM.FK_TIERS
	LEFT JOIN MASTER_ESTIA..ESTIA_RUB RUB
	ON RUB.CRUB = HQFAC.CRUB
	--ON RUB.CRUB = HQFAC.TRUB
	LEFT JOIN MASTER_ESTIA..ESTIA_TIERS LOC
	ON LOC.PK_TIERS = LOCATION.FK_TIERS
	WHERE HQFAC.CORG = '11'
	AND CAST(HQFAC.DATEC AS DATE) BETWEEN @DT_DEBUT AND @DT_FIN
	AND WGM.FK_TIERS IN (SELECT VALUE FROM dbo.ufn_SplitMultiValue(@PK_PROPRIETAIRE,',')) 
	AND GROUPE.PK_GROUPE IN (SELECT VALUE FROM dbo.ufn_SplitMultiValue(@PK_IMMEUBLE,','))

END