-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
CREATE PROCEDURE [dbo].[ENGAGEMENT_OPERATIONS] 
(
	@DT_ANALYSE DATETIME,
	@PK_PROPRIETAIRE VARCHAR(MAX),
	@PK_IMMEUBLE VARCHAR(MAX),
	@PK_POPE VARCHAR(MAX),
	@ANNEE_DEB_OPERATION INT
)
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;

	SELECT PROPRIETAIRE.PK_TIERS As PK_PROPRIETAIRE
		 , GROUPE.PK_GROUPE
		 , POPE.PK_POPE
		 , PROPRIETAIRE.CTIERS AS CD_PROPRIETAIRE
		 , PROPRIETAIRE.LTIERS AS NOM_PROPRIETAIRE
		 , GROUPE.CGROUPE
		 , GROUPE.LGROUPE
		 , PDEPOP.COPE
		 , CONCAT(POPE.LOPE, ' - ' + POPE.NOMTECH) LOPE
		 , PIOPE.PTIERS AS CD_RESPONSABLE
		 , RESPONSABLE.LTIERS AS NOM_RESPONSABLE
		 , PIOPE.TRESP AS CD_RESPONSABLE_TECHNIQUE
		 , TECHNICIEN.LTIERS AS NOM_RESPONSABLE_TECHNIQUE
		 , LIENV.CD_AGENT
		 , CONCAT(CONCAT(EMPLOY.LEMPLOY, ' '), EMPLOY.PRENOM) AS NOM_AGENT
		 , PDEPOP.CFOUR
		 , FOURNISSEUR.LTIERS AS NOM_FOURNISSEUR
		 , PDEPOP.CTRANCHE
		 , PDEPOP.CDEPR AS CD_POSTE_DEPENSE
		 , PDEPR.LDEPR AS LB_POSTE_DEPENSE
		 --, PDEPOP.LNORD
		 , PDEPOP.MARSIGN DT_ENGAGEMENT
		 --, PDEPOP.RLIB
		 , PDEPOP.MTINI AS MT_INITIAL_HT
		 --, ENG.MT_INITIAL_TTC
		 , ENG.MT_AVENANTS_TS_HT
		 , ENG.MT_AVENANTS_TS_TTC
		 , ENG.MT_CUMUL_HT
		 , ENG.MT_ENG_HT_FACTURE
	FROM MASTER_ESTIA..ESTIA_PDEPOP PDEPOP
	LEFT JOIN MASTER_ESTIA..ESTIA_POPE POPE
	ON POPE.PK_POPE = PDEPOP.FK_POPE
	LEFT JOIN MASTER_ESTIA..ESTIA_TRANCHE TRANCHE
	ON TRANCHE.CORG = PDEPOP.CORG AND TRANCHE.COPE = PDEPOP.COPE AND TRANCHE.CTRANCHE = PDEPOP.CTRANCHE
	LEFT JOIN MASTER_ESTIA..ESTIA_PIOPE PIOPE
	ON PIOPE.CORG = TRANCHE.CORG AND PIOPE.COPE = TRANCHE.COPE AND PIOPE.CTRANCHE =  TRANCHE.CTRANCHE
	LEFT JOIN MASTER_ESTIA..WRK_GROUPE_MANGES WGM
	ON WGM.CORG = POPE.CORG AND WGM.CGROUPE = POPE.CGROUPE
	LEFT JOIN MASTER_ESTIA..ESTIA_GROUPE GROUPE
	ON GROUPE.PK_GROUPE = WGM.PK_GROUPE
	LEFT JOIN MASTER_ESTIA..ESTIA_TIERS FOURNISSEUR
	ON FOURNISSEUR.CTIERS = PDEPOP.CFOUR
	LEFT JOIN MASTER_ESTIA..ESTIA_TIERS RESPONSABLE
	ON RESPONSABLE.CTIERS = PIOPE.PTIERS
	LEFT JOIN MASTER_ESTIA..ESTIA_TIERS TECHNICIEN
	ON TECHNICIEN.CTIERS = PIOPE.TRESP
	LEFT JOIN MASTER_ESTIA..ESTIA_PDEPR PDEPR
	ON PDEPR.CDEPR = PDEPOP.CDEPR
	LEFT JOIN MASTER_ESTIA..ESTIA_TVA TVA
	ON TVA.CTVA = PDEPOP.CTVA
	LEFT JOIN MASTER_ESTIA..ESTIA_TIERS PROPRIETAIRE
	ON PROPRIETAIRE.PK_TIERS = WGM.FK_TIERS
	LEFT JOIN
	(
		SELECT PAB.CORG
			, PAB.COPE
			, PAB.CTRANCHE
			, PAB.CDEPR
			, PAB.NORD 
			, SUM(CASE WHEN PAB.SITUAT <> 1 THEN PAB.MTTTC ELSE 0 END) AS MT_AVENANTS_TS_TTC  
			, SUM(CASE WHEN PAB.SITUAT <> 1 THEN PAB.HTBASE ELSE 0 END) AS MT_AVENANTS_TS_HT   
			, SUM(CASE WHEN PAB.SITUAT = 1 THEN PAB.MTTTC ELSE 0 END) AS MT_INITIAL_TTC
			, SUM(PAB.MTTTC) AS MT_CUMUL_TTC
			, SUM(PAB.MTTVA) AS MT_ENG_TVA
			, SUM(PAB.MTTTC - PAB.MTTVA) AS MT_CUMUL_HT
			, SUM(PAB.HTBASE) AS MT_ENG_HT_FACTURE
		FROM MASTER_ESTIA..ESTIA_PABASIT PAB
		WHERE PAB.CORG = '11'
		AND PAB.DECR <= @DT_ANALYSE
		GROUP BY PAB.CORG, PAB.COPE, PAB.CTRANCHE, PAB.CDEPR, PAB.NORD
	) ENG
	ON ENG.CORG = PDEPOP.CORG AND ENG.COPE = PDEPOP.COPE AND ENG.CTRANCHE = PDEPOP.CTRANCHE AND ENG.CDEPR = PDEPOP.CDEPR AND ENG.NORD = PDEPOP.NORD 

	LEFT JOIN 
	(
		SELECT CLEOR
			 , CAST(SUBSTRING(CLEDE, 16, 6) AS NUMERIC(10,0)) AS CD_AGENT 
		FROM MASTER_ESTIA..ESTIA_LIENV
		WHERE CSTE = 'TECHNICIEN'
	) LIENV
	on LIENV.CLEOR = CAST(DBO.LPAD(PIOPE.CORG, 2, '0') AS VARCHAR(2)) + CAST(DBO.LPAD(PIOPE.COPE, 11, '0') AS VARCHAR(11)) + CAST(DBO.LPAD(PIOPE.CTRANCHE, 2, '0') AS VARCHAR(2)) + CAST(DBO.LPAD(PIOPE.TRESP, 7, '0') AS VARCHAR(7))
	LEFT JOIN MASTER_ESTIA..ESTIA_EMPLOY EMPLOY
	ON EMPLOY.CEMPLOY = LIENV.CD_AGENT
	WHERE PDEPOP.CORG = '11'
	--AND PDEPOP.DECR <= '20181210'--@DT_ANALYSE
	--AND PDEPOP.COPE = '20141100017'
	--AND PDEPOP.CDEPR = 406
	AND PROPRIETAIRE.PK_TIERS IN (SELECT VALUE FROM dbo.ufn_SplitMultiValue(@PK_PROPRIETAIRE,',')) 
	AND GROUPE.PK_GROUPE IN (SELECT VALUE FROM dbo.ufn_SplitMultiValue(@PK_IMMEUBLE,','))
	AND POPE.PK_POPE IN (SELECT VALUE FROM dbo.ufn_SplitMultiValue(@PK_POPE,','))
	AND DATEPART(YEAR, TRANCHE.DDEXEC) >= @ANNEE_DEB_OPERATION
	ORDER BY PROPRIETAIRE.CTIERS, GROUPE.CGROUPE, PDEPOP.COPE

END