-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
CREATE PROCEDURE [dbo].[ETAT_LOCATIF_BAIL_PREVISION] 
(
	@PK_TEMPS DATETIME,
	@PK_PROPRIETAIRE INT,
	@PK_IMMEUBLE NVARCHAR(MAX),
	@PK_LOCATAIRE NVARCHAR(MAX),
	@ANNUEL BIT
)
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;
WITH REQ AS
(
	SELECT FEL.DT_REF
	, FEL.FK_PROPRIETAIRE
	, FEL.FK_IMMEUBLE
	, ISNULL(FEL.FK_BAIL, 0) AS FK_BAIL
	, DP.CD_PROPRIETAIRE
	, DP.NM_PROPRIETAIRE
	, dbo.initcap(DP.NOM_PROPRIETAIRE) AS NOM_PROPRIETAIRE
	, DI.CD_IMMEUBLE 
	, DI.NM_IMMEUBLE
	, UPPER(DI.ADRLGN1) AS ADRLGN1
	, DI.SURFACE_TOTALE
	, DI.VLM_ARCHIVE
	, DI.VLM_PARKING_DOUBLE
	, DI.VLM_PARKING_SIMPLE
	, FEL.FK_LOCATAIRE
	, DL.CD_LOCATAIRE
	, DL.NM_LOCATAIRE
	, CASE WHEN FEL.CD_STATUT = 'L' THEN
	CASE WHEN FEL.FK_LOCATAIRE = '-88888'
	THEN 'Gardien' ELSE dbo.initcap(DL.NOM_LOCATAIRE) END
	ELSE 'Vacant'  
	END AS NOM_LOCATAIRE
	, DB.CD_LOT_PRINCIPAL
	, DB.CD_BAIL
	, DB.NM_BAIL
	, dbo.initcap(DB.LB_NATURE_BAIL) AS LB_NATURE_BAIL
	, DB.LB_DUREE
	, DB.DT_SIGNATURE
	, DB.DT_EFFET
	, DATEADD(MONTH, (DB.DUREE_AN*12) + DB.DUREE_MOIS, DB.DT_EFFET)-1 AS DT_FIN
	, DB.DT_ENTREE
	, DB.DT_CONGE
	, DB.DT_SORTIE
	, DB.DT_PRCH_TRIEN_POT
	, CASE WHEN P_NATURE_BAIL.CD_TYPE_BAIL = 'COM' THEN DB.DT_RISQUE ELSE DATEADD(month, -NB_MOIS_PREAVIS, DT_PRCH_TRIEN_POT) END AS DT_RISQUE
	, FEL.CCOMPTE
	, FEL.CD_STATUT 
	, FEL.LB_STATUT
	, DB.LB_TYPE_CAUTION
	, DB.DT_DEBUT_FRANCHISE
	, DB.DT_FIN_FRANCHISE
	, ISNULL(DB.MT_LOYER_BASE, VLB.MT_LOYER_BASE) AS MT_LOYER_BASE
	--, DB.MT_DG_BASE AS MT_DG_BASE
	, SUM(FEL.MT_LOYER_ACTUEL) AS MT_LOYER_ACTUEL
	, SUM(FEL.MT_LOYER_ACTUEL_FACTURABLE) AS MT_LOYER_ACTUEL_FACTURABLE
	, SUM(FEL.MT_DG) AS MT_DG
	, SUM(FEL.MT_CHARGES) AS MT_CHARGES
	, SUM(FEL.MT_LOYER_FRANCHISE) AS MT_LOYER_FRANCHISE
	, SUM(FEL.MT_PALIER) AS MT_PALIER
	, FEL.LB_INDICE_INITIAL
	, FEL.DT_INDICE_INITIAL
	, FEL.LB_INDICE_ACTUEL
	, FEL.DT_INDICE_ACTUEL
	, ISNULL(FEL.CD_INDICE_REVISION, DB.CD_MODE_REVISION) AS TYPE_INDICE
	, left(FEL.CD_INDICE_INITIAL, 1) + 'T' + right(FEL.CD_INDICE_INITIAL, 4) AS INDICE_BASE
	--, left(LOCATION.INDREF, 1) + 'T' + right(LOCATION.INDREF, 4) AS INDICE_BASE
	, FEL.VAL_INDICE_INITIAL AS VAL_INDICE_BASE
	--, INDICE.VAL AS VAL_INDICE_BASE
	, FEL.DT_REVISION_PRECEDENTE AS DT_DERNIERE_REVISION
	, left(FEL.CD_INDICE_ACTUEL, 1) + 'T' + right(FEL.CD_INDICE_ACTUEL, 4) AS INDICE_REVISION
	, FEL.VAL_INDICE_ACTUEL AS VAL_INDICE_REVISION
	, CASE WHEN DB.PC_RECUP_TF = 0 THEN 'N' WHEN DB.PC_RECUP_TF = 100 THEN 'O' END AS PC_RECUP_TF
	, CASE WHEN DB.PC_RECUP_HO = 0 THEN 'N' WHEN DB.PC_RECUP_HO = 100 THEN 'O' END AS PC_RECUP_HO
	, CASE WHEN DB.PC_RECUP_TB = 0 THEN 'N' WHEN DB.PC_RECUP_TB = 100 THEN 'O' END AS PC_RECUP_TB
	, CASE WHEN DB.PC_RECUP_AS = 0 THEN 'N' WHEN DB.PC_RECUP_AS = 100 THEN 'O' END AS PC_RECUP_AS
	--, CASE WHEN DB.PC_RECUP_606 = 0 THEN 'N' WHEN DB.PC_RECUP_606 = 100 THEN 'O' END AS PC_RECUP_606
	, 'N' AS PC_RECUP_606
	, CASE WHEN DB.PC_RECUP_TOM = 0 THEN 'N' WHEN DB.PC_RECUP_TOM = 100 THEN 'O' END AS PC_RECUP_TOM
	, ISNULL(AB.NB_AVENANT, 0) AS NB_AVENANT
	, NULL AS A_SUIVRE
	, 0 AS VAL_SURF_UTILE_GEOMETRE
	, CAST(0 AS NUMERIC(18,2)) AS VLM
	, CAST(0 AS NUMERIC(18,2)) AS LOYER_REVISE_SUR_VLM
	, NULL AS RISQUE_DEPART
	, DB.COMMENTAIRES AS COMMENTAIRES
	, DB.CHEMIN_BAIL
	, DI.CHEMIN_PLAN
	, DI.CHEMIN_ETAT_SURFACES
	, DI.CHEMIN_TB
	, DI.CHEMIN_TF
	, CASE DB.CD_FREQUENCE_QUITTANCEMENT WHEN '01' THEN 'M' WHEN '03' THEN 'T' WHEN '06' THEN 'S' WHEN '12' THEN 'A' END + DB.CD_TERME AS PAIEMENT
	, DI.CHEMIN_MANDAT
	FROM F_ETAT_LOCATIF FEL
	LEFT JOIN D_MANDAT_GERANCE DMG
	ON DMG.PK_MANDAT_GERANCE = FEL.FK_MANDAT_GERANCE
	LEFT JOIN D_IMMEUBLE DI
	ON DI.PK_IMMEUBLE = FEL.FK_IMMEUBLE
	LEFT JOIN D_PROPRIETAIRE DP
	ON DP.PK_PROPRIETAIRE = FEL.FK_PROPRIETAIRE
	LEFT JOIN D_BAIL DB
	ON DB.PK_BAIL = FEL.FK_BAIL
	--LEFT JOIN MASTER_ESTIA..ESTIA_LOCATION LOCATION
	--ON LOCATION.PK_LOCATION = DB.PK_BAIL
	LEFT JOIN D_LOCATAIRE DL
	ON DL.PK_LOCATAIRE = FEL.FK_LOCATAIRE
	LEFT JOIN D_LOT L
	ON L.PK_LOT = FEL.PK_LOT 
	LEFT JOIN V_AVENANT_BAIL AB
	ON AB.PK_BAIL = DB.PK_BAIL
	LEFT JOIN V_LOYER_BASE VLB
	ON VLB.FK_BAIL = DB.PK_BAIL
	LEFT JOIN MASTER_ESTIA..P_NATURE_BAIL
	ON P_NATURE_BAIL.CD_NATURE_BAIL = DB.CD_NATURE_BAIL
	--LEFT JOIN MASTER_ESTIA..ESTIA_INDICE INDICE
	--ON INDICE.ANNEE = right(LOCATION.INDREF, 4) AND INDICE.MOIS = left(LOCATION.INDREF, 1) AND INDICE.CNUMI = LOCATION.CNUMI
	WHERE
	  FEL.PK_TEMPS = @PK_TEMPS
	  AND FEL.CORG = 11
	  AND FEL.FK_PROPRIETAIRE = @PK_PROPRIETAIRE
	  AND FEL.FK_IMMEUBLE IN (SELECT VALUE FROM dbo.ufn_SplitMultiValue(@PK_IMMEUBLE,','))
	  AND ISNULL(FEL.FK_LOCATAIRE, 99999) IN (SELECT VALUE FROM dbo.ufn_SplitMultiValue(@PK_LOCATAIRE,','))
	  AND DMG.IND_MANDAT_ACTIF = 'O'
	  AND CONVERT(DATETIME, CONVERT(VARCHAR(10),GETDATE(),103), 103) BETWEEN ISNULL(L.DT_DEBUT_EN_SERVICE, '1900/01/01') AND ISNULL(L.DT_FIN_EN_SERVICE,'2999/01/01')
	GROUP BY FEL.DT_REF
		   , FEL.FK_PROPRIETAIRE
		   , FEL.FK_IMMEUBLE
		   , FEL.FK_BAIL
		   , FEL.FK_LOCATAIRE
		   , DP.CD_PROPRIETAIRE
		   , DP.NM_PROPRIETAIRE
		   , DP.NOM_PROPRIETAIRE
		   , DI.CD_IMMEUBLE 
		   , DI.NM_IMMEUBLE
		   , DI.ADRLGN1
		   , DI.SURFACE_TOTALE
           , DI.VLM_ARCHIVE
           , DI.VLM_PARKING_DOUBLE
		   , DI.VLM_PARKING_SIMPLE
	       , DL.CD_LOCATAIRE
	       , DL.NM_LOCATAIRE
	       , DL.NOM_LOCATAIRE
		   , DB.CD_LOT_PRINCIPAL
		   , DB.CD_BAIL
		   , DB.NM_BAIL
           , DB.CD_TERME
		   , DB.LB_NATURE_BAIL
		   , DB.LB_DUREE
		   , DB.DT_SIGNATURE
		   , DB.DT_EFFET
           , DB.DUREE_AN
           , DB.DUREE_MOIS
		   , DB.DT_ENTREE
		   , DB.DT_CONGE
		   , DB.DT_SORTIE
		   , DB.DT_PRCH_TRIEN_POT
		   , P_NATURE_BAIL.CD_TYPE_BAIL
		   , DB.DT_RISQUE
           , NB_MOIS_PREAVIS
		   , FEL.CCOMPTE
		   , FEL.CD_STATUT 
           , FEL.LB_STATUT
		   , DB.LB_TYPE_CAUTION
		   , DB.DT_DEBUT_FRANCHISE
		   , DB.DT_FIN_FRANCHISE
		   , VLB.MT_LOYER_BASE
		   , DB.MT_LOYER_BASE
		   --, DB.MT_DG_BASE
		   , FEL.LB_INDICE_INITIAL
		   , FEL.DT_INDICE_INITIAL
		   , FEL.LB_INDICE_ACTUEL
		   , FEL.DT_INDICE_ACTUEL
           , FEL.CD_INDICE_REVISION
		   , DB.CD_MODE_REVISION
           , FEL.CD_INDICE_INITIAL
		   --, LOCATION.INDREF
           , FEL.VAL_INDICE_INITIAL
		   --, INDICE.VAL
           , FEL.DT_REVISION_PRECEDENTE
           , FEL.CD_INDICE_ACTUEL
           , FEL.VAL_INDICE_ACTUEL
		   , DB.PC_RECUP_TF
		   , DB.PC_RECUP_HO
		   , DB.PC_RECUP_TB
		   , DB.PC_RECUP_AS
		   , DB.PC_RECUP_606
		   , DB.PC_RECUP_TOM
		   , AB.NB_AVENANT
		   , DB.COMMENTAIRES
           , DB.CHEMIN_BAIL
           , DI.CHEMIN_PLAN
           , DI.CHEMIN_ETAT_SURFACES
           , DI.CHEMIN_TB
           , DI.CHEMIN_TF
           , DB.CD_FREQUENCE_QUITTANCEMENT
		   , DI.CHEMIN_MANDAT
),
REQ2 AS
(
	SELECT FEL.FK_PROPRIETAIRE
		 , FEL.FK_IMMEUBLE
		 , ISNULL(FEL.FK_BAIL, 0) AS FK_BAIL
		 , SUM(L.VAL_SURFACE_REELLE) AS VAL_SURFACE_REELLE
		 , SUM(L.NB_EMPLACEMENTS_PARKING) AS NB_PARKINGS
		 , CAST(RIGHT(CASE WHEN L.ETAGE = 'RDC' THEN 'R+0' ELSE L.ETAGE END, LEN(L.ETAGE)-1) AS INT) AS ETAGE
		 , SUM(ISNULL(PKG.NB_PARKINGS_SIMPLES, 0)) AS NB_PARKINGS_SIMPLES
		 , SUM(ISNULL(PKG.NB_PARKINGS_DOUBLES, 0)) AS NB_PARKINGS_DOUBLES
	FROM F_ETAT_LOCATIF FEL
	LEFT JOIN D_MANDAT_GERANCE DMG
	ON DMG.PK_MANDAT_GERANCE = FEL.FK_MANDAT_GERANCE
	LEFT JOIN D_LOT L
	ON L.PK_LOT = FEL.PK_LOT
	LEFT JOIN
	(
		SELECT PK_LOT,
		SUM(CASE WHEN CD_TYPE_LOT IN ('BOX', 'PK', 'PKG') THEN 1 ELSE 0 END) AS NB_PARKINGS_SIMPLES,
		SUM(CASE WHEN CD_TYPE_LOT IN ('BDO', 'PKD') THEN 1 ELSE 0 END) AS NB_PARKINGS_DOUBLES
		FROM D_LOT
		WHERE NB_EMPLACEMENTS_PARKING > 0
		GROUP BY PK_LOT
	) PKG
	ON PKG.PK_LOT = L.PK_LOT
	WHERE
	  FEL.PK_TEMPS = @PK_TEMPS
	  AND FEL.CORG = 11
	  AND FEL.FK_PROPRIETAIRE = @PK_PROPRIETAIRE
	  AND FEL.FK_IMMEUBLE IN (SELECT VALUE FROM dbo.ufn_SplitMultiValue(@PK_IMMEUBLE,','))
                  AND ISNULL(FEL.FK_LOCATAIRE, 99999) IN (SELECT VALUE FROM dbo.ufn_SplitMultiValue(@PK_LOCATAIRE,','))
	  AND DMG.IND_MANDAT_ACTIF = 'O'
	  AND CONVERT(DATETIME, CONVERT(VARCHAR(10),GETDATE(),103), 103) BETWEEN ISNULL(L.DT_DEBUT_EN_SERVICE, '1900/01/01') AND ISNULL(L.DT_FIN_EN_SERVICE,'2999/01/01')
	GROUP BY FEL.FK_PROPRIETAIRE, FEL.FK_IMMEUBLE, FEL.FK_BAIL, L.ETAGE
),
REQ3 AS
(
	SELECT RES.FK_PROPRIETAIRE, RES.FK_IMMEUBLE, RES.FK_BAIL, SUM(RES.VAL_SURFACE_REELLE) AS VAL_SURFACE_REELLE, SUM(RES.NB_PARKINGS) AS NB_PARKINGS, SUM(NB_PARKINGS_SIMPLES) AS NB_PARKINGS_SIMPLES, SUM(NB_PARKINGS_DOUBLES) AS NB_PARKINGS_DOUBLES,
	STUFF((
			SELECT ', ' + CAST(RES2.ETAGE AS VARCHAR(MAX))
			FROM REQ2 RES2
			WHERE (RES2.FK_PROPRIETAIRE = RES.FK_PROPRIETAIRE AND RES2.FK_IMMEUBLE = RES.FK_IMMEUBLE AND RES2.FK_BAIL = RES.FK_BAIL)
			ORDER BY RES2.FK_PROPRIETAIRE, RES2.FK_IMMEUBLE, RES2.FK_BAIL, RES2.ETAGE 
			FOR XML PATH(''), TYPE).value('.','VARCHAR(MAX)'),1,2,'') AS ETAGE
	FROM REQ2 AS RES
	GROUP BY RES.FK_PROPRIETAIRE, RES.FK_IMMEUBLE, RES.FK_BAIL
)

SELECT REQ.DT_REF
	 , REQ.FK_PROPRIETAIRE
	 , REQ.FK_IMMEUBLE
	 , REQ.FK_BAIL
	 , REQ.CD_PROPRIETAIRE
	 , REQ.NM_PROPRIETAIRE
	 , REQ.NOM_PROPRIETAIRE
	 , REQ.CD_IMMEUBLE 
	 , REQ.NM_IMMEUBLE
	 , REQ.ADRLGN1
	 , REQ.SURFACE_TOTALE
     , REQ.VLM_ARCHIVE
     , REQ.VLM_PARKING_DOUBLE
	 , REQ.VLM_PARKING_SIMPLE
	 , REQ3.VAL_SURFACE_REELLE
     , REQ.FK_LOCATAIRE
	 , REQ.CD_LOCATAIRE
	 , REQ.NM_LOCATAIRE
	 , REQ.NOM_LOCATAIRE
	 , REQ.CD_LOT_PRINCIPAL
	 , REQ.CD_BAIL
	 , REQ.NM_BAIL
	 , REQ.LB_NATURE_BAIL
	 , REQ.LB_DUREE
	 , REQ.DT_SIGNATURE
	 , CASE WHEN PNB.CD_NATURE_BAIL = '02' THEN DATEADD(YEAR, (DATEDIFF(YEAR, REQ.DT_EFFET, GETDATE())/6) *6, REQ.DT_EFFET) ELSE REQ.DT_EFFET END DT_EFFET
     , CASE WHEN PNB.CD_NATURE_BAIL = '02' THEN DATEADD(YEAR, 6, DATEADD(YEAR, (DATEDIFF(YEAR, REQ.DT_EFFET, GETDATE())/6) *6, REQ.DT_EFFET))-1 ELSE REQ.DT_FIN END DT_FIN
	 , REQ.DT_ENTREE
	 , REQ.DT_CONGE
	 , REQ.DT_SORTIE
	 , CASE WHEN PNB.CD_NATURE_BAIL = '02' THEN DATEADD(MONTH, 1, @PK_TEMPS) ELSE REQ.DT_PRCH_TRIEN_POT END DT_PRCH_TRIEN_POT --DATEADD(MONTH, 1, GETDATE()) ELSE REQ.DT_PRCH_TRIEN_POT END DT_PRCH_TRIEN_POT
	 --, CASE WHEN PNB.CD_NATURE_BAIL <> '02' THEN REQ.DT_PRCH_TRIEN_POT END DT_PRCH_TRIEN_POT
	 , CASE WHEN PNB.CD_NATURE_BAIL <> '02' THEN REQ.DT_RISQUE ELSE @PK_TEMPS END DT_RISQUE
	 , CASE WHEN CASE WHEN PNB.CD_NATURE_BAIL = '02' THEN DATEADD(YEAR, 6, DATEADD(YEAR, (DATEDIFF(YEAR, REQ.DT_EFFET, GETDATE())/6) *6, REQ.DT_EFFET))-1 ELSE REQ.DT_FIN END < GETDATE() THEN 'O' ELSE 'N' END AS IND_ECHU
	 , REQ.CCOMPTE
	 , REQ.CD_STATUT 
     , REQ.LB_STATUT
	 , REQ3.NB_PARKINGS
     , REQ3.NB_PARKINGS_SIMPLES
     , REQ3.NB_PARKINGS_DOUBLES
	 , W.VAL_SURF_BUR
	 , W.VAL_SURF_COM
	 , W.VAL_SURF_ACT
	 , W.VAL_SURF_ARC
	 , W.VAL_SURF_HAB
     , W.VAL_SURF_BUR + W.VAL_SURF_COM + W.VAL_SURF_ACT + W.VAL_SURF_ARC + W.VAL_SURF_HAB AS VAL_SURF_BAIL
	 , CASE WHEN REQ.SURFACE_TOTALE > 0 THEN (W.VAL_SURF_BUR + W.VAL_SURF_COM + W.VAL_SURF_ACT + W.VAL_SURF_ARC + W.VAL_SURF_HAB)/REQ.SURFACE_TOTALE ELSE 0 END AS PC_SURF_IMMEUBLE
	 , REQ3.ETAGE
	 , REQ.LB_TYPE_CAUTION
	 , REQ.DT_DEBUT_FRANCHISE
	 , REQ.DT_FIN_FRANCHISE
	 , CASE WHEN @ANNUEL = 1 THEN REQ.MT_LOYER_BASE ELSE CAST(REQ.MT_LOYER_BASE/12 AS NUMERIC(18,2)) END AS MT_LOYER_BASE
	 --, REQ.MT_DG_BASE
     , CASE WHEN @ANNUEL = 1 THEN CASE WHEN REQ.VAL_INDICE_BASE = 0 THEN 0 ELSE (REQ.MT_LOYER_BASE*REQ.VAL_INDICE_REVISION)/REQ.VAL_INDICE_BASE END 
	   ELSE CAST((CASE WHEN REQ.VAL_INDICE_BASE = 0 THEN 0 ELSE (REQ.MT_LOYER_BASE*REQ.VAL_INDICE_REVISION)/REQ.VAL_INDICE_BASE END)/12 AS NUMERIC(18,2)) END AS MT_LOYER_INDEXE
	 , CASE WHEN PNB.CD_TYPE_BAIL = 'HAB' THEN REQ.MT_DG ELSE (CASE WHEN REQ.VAL_INDICE_BASE = 0 THEN 0 ELSE (REQ.MT_DG*REQ.VAL_INDICE_REVISION)/REQ.VAL_INDICE_BASE END) END AS MT_DG_INDEXE
	 , REQ.MT_LOYER_ACTUEL
	 , REQ.MT_LOYER_ACTUEL_FACTURABLE
	 , REQ.MT_DG
	 , REQ.MT_CHARGES
     , REQ.MT_LOYER_FRANCHISE
	 , REQ.MT_PALIER
	 , CAST(CASE REQ.MT_LOYER_BASE WHEN 0 THEN 0 ELSE(REQ.MT_LOYER_ACTUEL/REQ.MT_LOYER_BASE) -1 END AS NUMERIC(18,2)) AS LOYER_REVISE_SUR_LOYER_BASE
	 , REQ.LB_INDICE_INITIAL
	 , REQ.DT_INDICE_INITIAL
	 , REQ.LB_INDICE_ACTUEL
	 , REQ.DT_INDICE_ACTUEL
     , REQ.TYPE_INDICE
     , REQ.INDICE_BASE
     , REQ.VAL_INDICE_BASE
     , REQ.DT_DERNIERE_REVISION
     , REQ.INDICE_REVISION
     , REQ.VAL_INDICE_REVISION
	 , REQ.PC_RECUP_TF
	 , REQ.PC_RECUP_HO
	 , REQ.PC_RECUP_TB
	 , REQ.PC_RECUP_AS
	 , REQ.PC_RECUP_606
	 , REQ.PC_RECUP_TOM
	 , REQ.NB_AVENANT
	 , REQ.A_SUIVRE
	 , REQ.VAL_SURF_UTILE_GEOMETRE
	 , REQ.VLM
	 , REQ.LOYER_REVISE_SUR_VLM
	 , REQ.RISQUE_DEPART
	 , REQ.COMMENTAIRES
     , REQ.CHEMIN_BAIL
     , REQ.CHEMIN_PLAN
     , REQ.CHEMIN_ETAT_SURFACES
     , REQ.CHEMIN_TB
     , REQ.CHEMIN_TF
     , REQ.PAIEMENT
  	 , REQ.CHEMIN_MANDAT
	 , FRANCHISE_PALIER_PREV.MT_LOYER_FRANCHISE_AN_PREC2
	 , FRANCHISE_PALIER_PREV.MT_LOYER_FRANCHISE_AN_PREC1
	 , FRANCHISE_PALIER_PREV.MT_LOYER_FRANCHISE_AN1
	 , FRANCHISE_PALIER_PREV.MT_LOYER_FRANCHISE_AN2
	 , FRANCHISE_PALIER_PREV.MT_LOYER_FRANCHISE_AN3
	 , FRANCHISE_PALIER_PREV.MT_LOYER_FRANCHISE_AN4
	 , FRANCHISE_PALIER_PREV.MT_LOYER_FRANCHISE_AN5
	 , FRANCHISE_PALIER_PREV.MT_LOYER_FRANCHISE_AN6
	 , FRANCHISE_PALIER_PREV.MT_LOYER_FRANCHISE_AN7
 	 , FRANCHISE_PALIER_PREV.MT_LOYER_FRANCHISE_AN8
 	 , FRANCHISE_PALIER_PREV.MT_LOYER_FRANCHISE_AN9
	 , FRANCHISE_PALIER_PREV.MT_LOYER_FRANCHISE_AN10
	 , FRANCHISE_PALIER_PREV.MT_PALIER_AN_PREC2
	 , FRANCHISE_PALIER_PREV.MT_PALIER_AN_PREC1
	 , FRANCHISE_PALIER_PREV.MT_PALIER_AN1
	 , FRANCHISE_PALIER_PREV.MT_PALIER_AN2
	 , FRANCHISE_PALIER_PREV.MT_PALIER_AN3
	 , FRANCHISE_PALIER_PREV.MT_PALIER_AN4
	 , FRANCHISE_PALIER_PREV.MT_PALIER_AN5
	 , FRANCHISE_PALIER_PREV.MT_PALIER_AN6
	 , FRANCHISE_PALIER_PREV.MT_PALIER_AN7
	 , FRANCHISE_PALIER_PREV.MT_PALIER_AN8
	 , FRANCHISE_PALIER_PREV.MT_PALIER_AN9
	 , FRANCHISE_PALIER_PREV.MT_PALIER_AN10
FROM REQ
LEFT JOIN D_BAIL ON D_BAIL.PK_BAIL = REQ.FK_BAIL
LEFT JOIN MASTER_ESTIA..P_NATURE_BAIL PNB
ON PNB.CD_NATURE_BAIL = D_BAIL.CD_NATURE_BAIL
LEFT JOIN REQ3
ON REQ3.FK_PROPRIETAIRE = REQ.FK_PROPRIETAIRE AND REQ3.FK_IMMEUBLE = REQ.FK_IMMEUBLE AND (REQ.FK_BAIL IS NULL OR REQ3.FK_BAIL = REQ.FK_BAIL)
LEFT JOIN
(
		SELECT FEL.PK_TEMPS, FEL.FK_IMMEUBLE, ISNULL(FEL.FK_BAIL, 0) AS FK_BAIL
			, SUM(CASE WHEN CD_REG_USAGE = 'BUR' THEN ISNULL(VAL_SURFACE_REELLE, 0) ELSE 0 END) VAL_SURF_BUR
			, SUM(CASE WHEN CD_REG_USAGE = 'COM' THEN ISNULL(VAL_SURFACE_REELLE, 0) ELSE 0 END) VAL_SURF_COM
			, SUM(CASE WHEN CD_REG_USAGE = 'ARC' THEN ISNULL(VAL_SURFACE_REELLE, 0) ELSE 0 END) VAL_SURF_ARC
			, SUM(CASE WHEN CD_REG_USAGE = 'HAB' THEN ISNULL(VAL_SURFACE_REELLE, 0) ELSE 0 END) VAL_SURF_HAB
			, SUM(CASE WHEN CD_REG_USAGE NOT IN ('BUR', 'COM', 'ARC', 'HAB') THEN ISNULL(VAL_SURFACE_REELLE, 0) ELSE 0 END) VAL_SURF_ACT
		FROM F_ETAT_LOCATIF FEL INNER JOIN
		(
			SELECT L.PK_LOT, L.NM_LOT, L.CD_USAGE, L.CD_REG_USAGE, L.LB_REG_USAGE, L.LB_USAGE, VAL_SURFACE_REELLE  
			FROM D_LOT L
			WHERE FK_IMMEUBLE IN (SELECT VALUE FROM dbo.ufn_SplitMultiValue(@PK_IMMEUBLE,','))
			AND VAL_SURFACE_REELLE > 0
		) LOT
		ON LOT.PK_LOT = FEL.PK_LOT
		WHERE FEL.PK_TEMPS = @PK_TEMPS AND FEL.FK_IMMEUBLE IN (SELECT VALUE FROM dbo.ufn_SplitMultiValue(@PK_IMMEUBLE,','))
		GROUP BY FEL.PK_TEMPS, FEL.FK_IMMEUBLE, FEL.FK_BAIL
) W
ON W.FK_IMMEUBLE = REQ.FK_IMMEUBLE AND (W.FK_BAIL = REQ.FK_BAIL)
LEFT JOIN
(
	select IMMEUBLE.PK_IMMEUBLE
		 , BAIL.PK_BAIL
		 , BAIL.NM_IMMEUBLE
		 , BAIL.CD_BAIL 
		 , BAIL.DT_EFFET
		 , BAIL.DT_ENTREE
		 , BAIL.DT_SORTIE
		 , BAIL.CD_FREQUENCE_QUITTANCEMENT
		 , isnull(FRANCHISE_PALIER_AN_PREC2.MT_LOYER_FRANCHISE, 0) MT_LOYER_FRANCHISE_AN_PREC2 -- a proratiser
		 , isnull(FRANCHISE_PALIER_AN_PREC1.MT_LOYER_FRANCHISE, 0) MT_LOYER_FRANCHISE_AN_PREC1 -- a proratiser
		 , isnull(FRANCHISE_PALIER_AN1.MT_LOYER_FRANCHISE, 0) MT_LOYER_FRANCHISE_AN1 -- a proratiser
		 , isnull(FRANCHISE_PALIER_AN2.MT_LOYER_FRANCHISE, 0) MT_LOYER_FRANCHISE_AN2 -- a proratiser
		 , isnull(FRANCHISE_PALIER_AN3.MT_LOYER_FRANCHISE, 0) MT_LOYER_FRANCHISE_AN3 -- a proratiser
		 , isnull(FRANCHISE_PALIER_AN4.MT_LOYER_FRANCHISE, 0) MT_LOYER_FRANCHISE_AN4 -- a proratiser
		 , isnull(FRANCHISE_PALIER_AN5.MT_LOYER_FRANCHISE, 0) MT_LOYER_FRANCHISE_AN5 -- a proratiser
		 , isnull(FRANCHISE_PALIER_AN6.MT_LOYER_FRANCHISE, 0) MT_LOYER_FRANCHISE_AN6 -- a proratiser
		 , isnull(FRANCHISE_PALIER_AN7.MT_LOYER_FRANCHISE, 0) MT_LOYER_FRANCHISE_AN7 -- a proratiser
		 , isnull(FRANCHISE_PALIER_AN8.MT_LOYER_FRANCHISE, 0) MT_LOYER_FRANCHISE_AN8 -- a proratiser
		 , isnull(FRANCHISE_PALIER_AN9.MT_LOYER_FRANCHISE, 0) MT_LOYER_FRANCHISE_AN9 -- a proratiser
		 , isnull(FRANCHISE_PALIER_AN10.MT_LOYER_FRANCHISE, 0) MT_LOYER_FRANCHISE_AN10 -- a proratiser
		 , isnull(FRANCHISE_PALIER_AN_PREC2.MT_PALIER, 0) MT_PALIER_AN_PREC2
		 , isnull(FRANCHISE_PALIER_AN_PREC1.MT_PALIER, 0) MT_PALIER_AN_PREC1
		 , isnull(FRANCHISE_PALIER_AN1.MT_PALIER, 0) MT_PALIER_AN1
		 , isnull(FRANCHISE_PALIER_AN2.MT_PALIER, 0) MT_PALIER_AN2
		 , isnull(FRANCHISE_PALIER_AN3.MT_PALIER, 0) MT_PALIER_AN3
		 , isnull(FRANCHISE_PALIER_AN4.MT_PALIER, 0) MT_PALIER_AN4
		 , isnull(FRANCHISE_PALIER_AN5.MT_PALIER, 0) MT_PALIER_AN5
		 , isnull(FRANCHISE_PALIER_AN6.MT_PALIER, 0) MT_PALIER_AN6
		 , isnull(FRANCHISE_PALIER_AN7.MT_PALIER, 0) MT_PALIER_AN7
		 , isnull(FRANCHISE_PALIER_AN8.MT_PALIER, 0) MT_PALIER_AN8
		 , isnull(FRANCHISE_PALIER_AN9.MT_PALIER, 0) MT_PALIER_AN9
		 , isnull(FRANCHISE_PALIER_AN10.MT_PALIER, 0) MT_PALIER_AN10
	from D_BAIL BAIL
	left join D_IMMEUBLE IMMEUBLE
	on IMMEUBLE.PK_IMMEUBLE = BAIL.FK_IMMEUBLE
	left join D_MANDAT_GERANCE MANDAT
	on MANDAT.FK_IMMEUBLE = IMMEUBLE.PK_IMMEUBLE
	left join
	(
		select * from dbo.f_GET_ANNUAL_LEASE_ALLOWANCES(DATEADD(YEAR, -2, @PK_TEMPS))
	) FRANCHISE_PALIER_AN_PREC2
	on FRANCHISE_PALIER_AN_PREC2.PK_BAIL = BAIL.PK_BAIL
	left join
	(
		select * from dbo.f_GET_ANNUAL_LEASE_ALLOWANCES(DATEADD(YEAR, -1, @PK_TEMPS))
	) FRANCHISE_PALIER_AN_PREC1
	on FRANCHISE_PALIER_AN_PREC1.PK_BAIL = BAIL.PK_BAIL
	left join
	(
		--SELECT LOCATION.FK_GROUPE AS PK_GROUPE, LOCATION.PK_LOCATION AS PK_BAIL,
		--		SUM(CASE WHEN PSRE.IND_CALCUL_FRANCHISE = 'O' THEN 
		--			((HQLOCAT.NB)/12)*DATEDIFF(MONTH, CASE WHEN DATEPART(YEAR, HQLOCAT.DDEB) < DATEPART(YEAR, @PK_TEMPS) THEN DATEADD(YEAR , DATEDIFF(YEAR, 0, @PK_TEMPS), 0) ELSE HQLOCAT.DDEB END, 
		--				CASE WHEN DATEPART(YEAR, HQLOCAT.DFIN) > DATEPART(YEAR, @PK_TEMPS) THEN DATEADD(DAY, -1, DATEADD(YEAR , DATEDIFF(YEAR, 0, @PK_TEMPS) + 1, 0)) ELSE HQLOCAT.DFIN END) ELSE 0 END) AS MT_LOYER_FRANCHISE,
		--		SUM(CASE WHEN PSRE.IND_CALCUL_PALIER = 'O' THEN HQLOCAT.NB ELSE 0 END) AS MT_PALIER
		--	FROM MASTER_ESTIA..ESTIA_LOCATION AS LOCATION
		--			INNER JOIN MASTER_ESTIA..ESTIA_HQLOCAT AS HQLOCAT
		--				ON HQLOCAT.CORG = LOCATION.CORG
		--				AND HQLOCAT.CAGENCE = LOCATION.CAGENCE
		--				AND HQLOCAT.CGROUPE = LOCATION.CGROUPE
		--				AND HQLOCAT.CIMMEUB = LOCATION.CIMMEUB
		--				AND HQLOCAT.CLOCAL = LOCATION.CLOCAL
		--				AND HQLOCAT.OCC = LOCATION.OCC
		--			INNER JOIN MASTER_ESTIA..P_RUBRIQUE AS P
		--				ON P.CD_RUBRIQUE = HQLOCAT.CRUB
		--			INNER JOIN MASTER_ESTIA..P_SOUS_REG_ELTFAC AS PSRE
		--				ON PSRE.CD_SOUS_REG_ELTFAC = P.CD_SOUS_REG_ELTFAC
		--			INNER JOIN MASTER_ESTIA..ESTIA_GROUPE GROUPE
		--			ON GROUPE.PK_GROUPE = LOCATION.FK_GROUPE
		--			INNER JOIN MASTER_ESTIA..V_D_MANDAT_GERANCE MANDAT
		--			ON MANDAT.FK_IMMEUBLE = GROUPE.PK_GROUPE
		--	WHERE DATEPART(YEAR, @PK_TEMPS) BETWEEN DATEPART(YEAR, HQLOCAT.DDEB) AND DATEPART(YEAR, ISNULL(HQLOCAT.DFIN, '2999/01/01'))
		--	AND LOCATION.FK_BAIL IS NOT NULL
		--	AND LOCATION.CORG = '11'
		--	--AND LOCATION.CGROUPE = 880
		--	--AND LOCATION.CLOCAL = 3004
		--	AND (LOCATION.DATSORQUIT IS NULL OR LOCATION.DATSORQUIT > @PK_TEMPS)
		--	AND IND_MANDAT_ACTIF = 'O'
		--	GROUP BY LOCATION.FK_GROUPE, LOCATION.PK_LOCATION
		select * from dbo.f_GET_ANNUAL_LEASE_ALLOWANCES(@PK_TEMPS)
	) FRANCHISE_PALIER_AN1
	on FRANCHISE_PALIER_AN1.PK_BAIL = BAIL.PK_BAIL
	left join
	(
		select * from dbo.f_GET_ANNUAL_LEASE_ALLOWANCES(DATEADD(YEAR, 1, @PK_TEMPS))
	) FRANCHISE_PALIER_AN2
	on FRANCHISE_PALIER_AN2.PK_BAIL = BAIL.PK_BAIL
	left join
	(
		select * from dbo.f_GET_ANNUAL_LEASE_ALLOWANCES(DATEADD(YEAR, 2, @PK_TEMPS))
	) FRANCHISE_PALIER_AN3
	on FRANCHISE_PALIER_AN3.PK_BAIL = BAIL.PK_BAIL
	left join
	(
		select * from dbo.f_GET_ANNUAL_LEASE_ALLOWANCES(DATEADD(YEAR, 3, @PK_TEMPS))
	) FRANCHISE_PALIER_AN4
	on FRANCHISE_PALIER_AN4.PK_BAIL = BAIL.PK_BAIL
	left join
	(
		select * from dbo.f_GET_ANNUAL_LEASE_ALLOWANCES(DATEADD(YEAR, 4, @PK_TEMPS))
	) FRANCHISE_PALIER_AN5
	on FRANCHISE_PALIER_AN5.PK_BAIL = BAIL.PK_BAIL
	left join
	(
		select * from dbo.f_GET_ANNUAL_LEASE_ALLOWANCES(DATEADD(YEAR, 5, @PK_TEMPS))
	) FRANCHISE_PALIER_AN6
	on FRANCHISE_PALIER_AN6.PK_BAIL = BAIL.PK_BAIL
	left join
	(
		select * from dbo.f_GET_ANNUAL_LEASE_ALLOWANCES(DATEADD(YEAR, 6, @PK_TEMPS))
	) FRANCHISE_PALIER_AN7
	on FRANCHISE_PALIER_AN7.PK_BAIL = BAIL.PK_BAIL
	left join
	(
		select * from dbo.f_GET_ANNUAL_LEASE_ALLOWANCES(DATEADD(YEAR, 7, @PK_TEMPS))
	) FRANCHISE_PALIER_AN8
	on FRANCHISE_PALIER_AN8.PK_BAIL = BAIL.PK_BAIL
	left join
	(
		select * from dbo.f_GET_ANNUAL_LEASE_ALLOWANCES(DATEADD(YEAR, 8, @PK_TEMPS))
	) FRANCHISE_PALIER_AN9
	on FRANCHISE_PALIER_AN9.PK_BAIL = BAIL.PK_BAIL
	left join
	(
		select * from dbo.f_GET_ANNUAL_LEASE_ALLOWANCES(DATEADD(YEAR, 9, @PK_TEMPS))
	) FRANCHISE_PALIER_AN10
	on FRANCHISE_PALIER_AN10.PK_BAIL = BAIL.PK_BAIL
	where BAIL.CD_SOCIETE = '11'
	and ISNULL(BAIL.DT_SORTIE, '29990101') >= @PK_TEMPS
	and MANDAT.IND_MANDAT_ACTIF = 'O'
) FRANCHISE_PALIER_PREV
on FRANCHISE_PALIER_PREV.PK_BAIL = REQ.FK_BAIL
ORDER BY 
   REQ.DT_REF
 , REQ.NM_PROPRIETAIRE
 , REQ.NM_IMMEUBLE
 , REQ.CD_STATUT
 , REQ.NM_BAIL

END