-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
CREATE PROCEDURE [dbo].[GET_DETAIL_ENGAGEMENT_FOURNISSEUR] 
(
	@PK_SIREN VARCHAR(MAX),
	@PK_ANNEE VARCHAR(4)
)
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;

SELECT CD_FOURNISSEUR
     , NOM_FOURNISSEUR
	 , dbo.INITCAP(TIERS.RUE) + ' - ' + UPPER(TIERS.BDIS) AS ADRESSE 
	 , LEFT(TIERS.SIRET, 10) AS SIREN
	 , TIERS.SIRET
	 , CEXO
	 , CAST(SUM(MT_ENGAGE_CONTRAT) AS NUMERIC(18, 2)) AS MT_ENGAGE_CONTRAT
	 , CAST(SUM(MT_ENGAGE_BT) AS NUMERIC(18, 2)) AS MT_ENGAGE_BT
	 , CAST(SUM(MT_ENGAGE_OPERATION) AS NUMERIC(18, 2)) AS MT_ENGAGE_OPERATION
FROM
(
	SELECT 
		  CTR.CORG
		 , CTR.CTIERS AS CD_FOURNISSEUR
		 , UPPER(T.LTIERS) AS NOM_FOURNISSEUR
		 , EB.CEXO
		 , ISNULL(EB.MT_CONTRAT_ENGAGE, 0) AS MT_ENGAGE_CONTRAT
		 , 0 AS MT_ENGAGE_BT
		 , 0 AS MT_ENGAGE_OPERATION
	FROM MASTER_ESTIA..ESTIA_CTRTIERS CTR
	LEFT JOIN MASTER_ESTIA..ESTIA_TIERS T
	ON T.PK_TIERS = CTR.FK_TIERS
	LEFT JOIN
	(
		SELECT B.FK_TIERS
		     , B.FK_CTRTIERS
			 , B.CORG
			 , B.CEXO 
			 , ISNULL(SUM(CAST(MONTANT AS NUMERIC(18, 2))), 0) AS MT_CONTRAT_ENGAGE
		FROM MASTER_ESTIA..ESTIA_ECRIB B
		LEFT JOIN MASTER_ESTIA..ESTIA_TIERS TIERS
		ON TIERS.PK_TIERS = B.FK_TIERS
		WHERE B.TYPBON = 'CTR' 
		AND B.CORG = '11'
		AND B.CEXO = @PK_ANNEE
		AND B.CCRITDP IN (1001, 1002, 1003, 1004, 1005, 1006, 1012, 9003, 9004, 9005, 9006, 9012)
		AND B.CSTE IN  ('EG')
		AND TIERS.SIRET IS NOT NULL
		GROUP BY B.FK_TIERS, B.FK_CTRTIERS, B.CORG, B.CEXO
	) EB
	ON EB.FK_TIERS = CTR.FK_TIERS
	WHERE CTR.CORG = '11'
	AND EB.CEXO = @PK_ANNEE
	--GROUP BY CTR.CORG, CTR.CTIERS, T.LTIERS, EB.CEXO
	--SELECT 
	--	  CTR.CORG
	--	 , CTR.CTIERS AS CD_FOURNISSEUR
	--	 , UPPER(TIERS.LTIERS) AS NOM_FOURNISSEUR
	--	 , DATEPART(YEAR, CTR.DDEBVAL) AS CEXO
	--	 , ISNULL(CONTNAT.MT_CONTRAT, 0) AS MT_ENGAGE_CONTRAT
	--	 , 0 AS MT_ENGAGE_BT
	--	 , 0 AS MT_ENGAGE_OPERATION
	--FROM MASTER_ESTIA..ESTIA_CTRTIERS CTR
	--LEFT JOIN MASTER_ESTIA..ESTIA_TIERS TIERS
	--ON TIERS.PK_TIERS = CTR.FK_TIERS
	--LEFT JOIN 
	--(
	--	SELECT CORG, CCONTFRS, 
	--	SUM(MTHT) AS MT_CONTRAT
	--	FROM MASTER_ESTIA..ESTIA_CONTNAT 
	--	GROUP BY CORG, CCONTFRS
	--) CONTNAT
	--ON CONTNAT.CORG = CTR.CORG AND CONTNAT.CCONTFRS = CTR.CCONTFRS
	--WHERE CTR.CORG = '11'
	--AND DATEPART(YEAR, CTR.DDEBVAL) = @PK_ANNEE
	--AND GETDATE() BETWEEN CTR.DDEBVAL AND CTR.DFINVAL
union
	SELECT D.CORG
		 , FOURNISSEUR.CTIERS AS CD_FOURNISSEUR
		 , FOURNISSEUR.LTIERS AS NOM_FOURNISSEUR
		 , E.CEXO
		 , 0 AS MT_ENGAGE_CONTRAT
		 , ISNULL(SUM(CAST(E.MONTANT AS NUMERIC(18, 2))), 0) AS MT_ENGAGE_BT
		 , 0 AS MT_ENGAGE_OPERATION
		FROM MASTER_ESTIA..ESTIA_DEMINT AS D
		LEFT JOIN MASTER_ESTIA..ESTIA_INTBT AS I
		ON UPPER(I.CORG) = UPPER(D.CORG)
		  AND I.NODEM    = D.NODEM
		LEFT JOIN MASTER_ESTIA..ESTIA_ECRIB E
		ON UPPER(E.CORG) = UPPER(I.CORG)
		  AND E.NOBON    = I.NOINTBT
		LEFT JOIN MASTER_ESTIA..ESTIA_LOCATION L
		ON L.FK_TIERS = D.FK_TIERS
		LEFT JOIN MASTER_ESTIA..ESTIA_TIERS FOURNISSEUR
		ON FOURNISSEUR.PK_TIERS = E.FK_TIERS
		WHERE D.CORG = '11'
		  AND E.CSTE     = 'EG'
		  AND E.SENS     = 'D'
		  AND UPPER(E.LIBELLE) LIKE '%ENG. BT%'
		  AND E.CEXO = @PK_ANNEE
		GROUP BY D.CORG
		, FOURNISSEUR.CTIERS
		, FOURNISSEUR.LTIERS
		, E.CEXO
union
      SELECT  PAB.CORG
			, PAB.CFOUR AS CD_FOURNISSEUR
			, FOURNISSEUR.LTIERS AS NOM_FOURNISSEUR
	        , DATEPART(YEAR, ISNULL(PAB.DECR, PAB.DSIGN)) AS CEXO 
			, 0 AS MT_ENGAGE_CONTRAT
			, 0 AS MT_ENGAGE_BT
			, SUM(CAST(PAB.MTTTC AS NUMERIC(18,2))) AS MT_ENGAGE_OPERATION
      FROM MASTER_ESTIA..ESTIA_PABASIT PAB
	  LEFT JOIN MASTER_ESTIA..ESTIA_TIERS FOURNISSEUR
	  ON FOURNISSEUR.CTIERS = PAB.CFOUR
	  WHERE PAB.CORG = '11'
	  AND DATEPART(YEAR, ISNULL(PAB.DECR, PAB.DSIGN)) = @PK_ANNEE
      GROUP BY PAB.CORG, PAB.CFOUR, FOURNISSEUR.LTIERS, PAB.DECR, PAB.DSIGN
) REQ
LEFT JOIN MASTER_ESTIA..ESTIA_TIERS TIERS
ON TIERS.CTIERS = REQ.CD_FOURNISSEUR
WHERE CEXO = @PK_ANNEE
AND LEFT(TIERS.SIRET, 10) IN (SELECT VALUE FROM dbo.ufn_SplitMultiValue(@PK_SIREN,',')) --= @PK_SIREN
GROUP BY CD_FOURNISSEUR, NOM_FOURNISSEUR, TIERS.RUE, TIERS.BDIS, TIERS.SIRET, CEXO
ORDER BY NOM_FOURNISSEUR, LEFT(TIERS.SIRET, 10), TIERS.SIRET

END