-- =============================================
-- Author:		Mario NADIR
-- Create date: 2017-08-25
-- Description:	<Description,,>
-- =============================================
CREATE PROCEDURE [dbo].[GET_DATE_ANALYSE] 
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;

	SELECT DISTINCT
	  F_ETAT_LOCATIF.PK_TEMPS AS DATE_ANALYSE,
	  CONVERT(VARCHAR(10), F_ETAT_LOCATIF.PK_TEMPS, 103) AS PK_TEMPS,
	  REQ1.DATE_ARRETE
	FROM  F_ETAT_LOCATIF
	LEFT JOIN
	(
	SELECT
	MIN(DATE_ANALYSE) AS DATE_ARRETE
	FROM
	(SELECT DISTINCT
	  F_ETAT_LOCATIF.PK_TEMPS AS DATE_ANALYSE
	FROM
	  F_ETAT_LOCATIF
	WHERE DATEPART(YEAR, F_ETAT_LOCATIF.PK_TEMPS) = DATEPART(YEAR, GETDATE())
	AND DATEPART(MONTH, F_ETAT_LOCATIF.PK_TEMPS) = DATEPART(MONTH, GETDATE())
	) REQ
	) REQ1
	ON REQ1.DATE_ARRETE = F_ETAT_LOCATIF.DT_REF
	ORDER BY F_ETAT_LOCATIF.PK_TEMPS DESC

END