-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
CREATE PROCEDURE [dbo].[GET_ENGAGEMENT_FOURNISSEUR] 
(
	@PK_SIREN VARCHAR(10),
	@PK_ANNEE VARCHAR(4)
)
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;

WITH REQ AS
(
	SELECT ENG.SIREN
		 , ENG.CEXO
		 , CAST(SUM(ENG.MT_ENGAGE) AS NUMERIC(18, 2)) AS MT_ENGAGE
	FROM
	(
	--	SELECT 
	--		  CTR.CORG
	--		 , LEFT(T.SIRET, 10) AS SIREN
	--		 , EB.CEXO
	--		 , ISNULL(EB.MT_CONTRAT_ENGAGE, 0) AS MT_ENGAGE
	--	FROM MASTER_ESTIA..ESTIA_CTRTIERS CTR
	--	LEFT JOIN MASTER_ESTIA..ESTIA_TIERS T
	--	ON T.PK_TIERS = CTR.FK_TIERS
	--	LEFT JOIN
	--	(
	--		SELECT REQ.CORG
	--			 , REQ.SIREN
	--			 , REQ.CEXO 
	--			 , ISNULL(SUM(CAST(REQ.MONTANT AS NUMERIC(18, 2))), 0) AS MT_CONTRAT_ENGAGE
	--		FROM
	--		(
	--			SELECT B.CORG
	--				 , LEFT(T.SIRET, 10) AS SIREN
	--				 , B.CEXO
	--				 , B.MONTANT
	--			FROM MASTER_ESTIA..ESTIA_ECRIB B
	--			LEFT JOIN MASTER_ESTIA..ESTIA_TIERS T
	--			ON T.PK_TIERS = B.FK_TIERS
	--			WHERE B.TYPBON = 'CTR' 
	--			AND B.CORG = '11'
	--			AND B.CCRITDP IN (1001, 1002, 1003, 1004, 1005, 1006, 1012, 9003, 9004, 9005, 9006, 9012)
	--			AND B.CSTE IN  ('EG')
	--			AND LEFT(T.SIRET, 10) = @PK_SIREN
	--			AND B.CEXO = @PK_ANNEE
	--		) REQ
	--		GROUP BY REQ.CORG, REQ.SIREN, REQ.CEXO
	--	) EB
	--	ON EB.CORG = CTR.CORG AND EB.SIREN = LEFT(T.SIRET, 10) AND EB.CEXO = @PK_ANNEE
	--	WHERE CTR.CORG = '11'
	--	AND EB.CEXO = @PK_ANNEE
	--	AND LEFT(T.SIRET, 10) = @PK_SIREN
	--	GROUP BY CTR.CORG
	--		   , LEFT(T.SIRET, 10)
	--		   , EB.CEXO
	--		   , EB.MT_CONTRAT_ENGAGE
		SELECT CTR.CORG
			 , LEFT(TIERS.SIRET, 10) AS SIREN
			 , DATEPART(YEAR, CTR.DDEBVAL) AS CEXO
			 , ISNULL(CAST(SUM(CONTNAT.MT_CONTRAT) AS NUMERIC(18, 2)), 0) AS MT_ENGAGE
		FROM MASTER_ESTIA..ESTIA_CTRTIERS CTR
		LEFT JOIN 
		(
			SELECT CORG, CCONTFRS, 
			SUM(MTTC) AS MT_CONTRAT
			FROM MASTER_ESTIA..ESTIA_CONTNAT 
			GROUP BY CORG, CCONTFRS
		) CONTNAT
		ON CONTNAT.CORG = CTR.CORG AND CONTNAT.CCONTFRS = CTR.CCONTFRS
		LEFT JOIN MASTER_ESTIA..ESTIA_TIERS TIERS
		ON TIERS.PK_TIERS = CTR.FK_TIERS
		WHERE CTR.CORG = '11'
		AND GETDATE() BETWEEN CTR.DDEBVAL AND CTR.DFINVAL
		AND DATEPART(YEAR, CTR.DDEBVAL) = @PK_ANNEE
		--AND LEFT(TIERS.SIRET, 10) = @PK_SIREN--'3837116780'
		GROUP BY CTR.CORG, LEFT(TIERS.SIRET, 10), DATEPART(YEAR, CTR.DDEBVAL)
	union
		SELECT  D.CORG
			  , LEFT(FOURNISSEUR.SIRET, 10) AS SIREN
			  , E.CEXO
			  , ISNULL(SUM(CAST(E.MONTANT AS NUMERIC(18, 2))), 0) AS MT_ENGAGE
			FROM MASTER_ESTIA..ESTIA_DEMINT AS D
			LEFT JOIN MASTER_ESTIA..ESTIA_INTBT AS I
			ON UPPER(I.CORG) = UPPER(D.CORG)
			  AND I.NODEM    = D.NODEM
			LEFT JOIN MASTER_ESTIA..ESTIA_ECRIB E
			ON UPPER(E.CORG) = UPPER(I.CORG)
			  AND E.NOBON    = I.NOINTBT
			LEFT JOIN MASTER_ESTIA..ESTIA_LOCATION L
			ON L.FK_TIERS = D.FK_TIERS
			LEFT JOIN MASTER_ESTIA..ESTIA_TIERS FOURNISSEUR
			ON FOURNISSEUR.PK_TIERS = E.FK_TIERS
			WHERE D.CORG = '11'
			  AND E.CSTE     = 'EG'
			  AND E.SENS     = 'D'
			  AND UPPER(E.LIBELLE) LIKE '%ENG. BT%'
			  AND LEFT(FOURNISSEUR.SIRET, 10) = @PK_SIREN
			  AND E.CEXO = @PK_ANNEE
			GROUP BY D.CORG
			, LEFT(FOURNISSEUR.SIRET, 10)
			, E.CEXO
	union
		  SELECT  PAB.CORG
				, LEFT(FOURNISSEUR.SIRET, 10) AS SIREN
				, DATEPART(YEAR, ISNULL(PAB.DECR, PAB.DSIGN)) AS CEXO 
				, ISNULL(SUM(CAST(PAB.MTTTC AS NUMERIC(18,2))), 0) AS MT_ENGAGE
		  FROM MASTER_ESTIA..ESTIA_PABASIT PAB
		  LEFT JOIN MASTER_ESTIA..ESTIA_TIERS FOURNISSEUR
		  ON FOURNISSEUR.CTIERS = PAB.CFOUR
		  WHERE PAB.CORG = '11'
		  AND LEFT(FOURNISSEUR.SIRET, 10) = @PK_SIREN
		  AND DATEPART(YEAR, ISNULL(PAB.DECR, PAB.DSIGN)) = @PK_ANNEE
		  GROUP BY PAB.CORG
				 , LEFT(FOURNISSEUR.SIRET, 10)
				 , PAB.DECR
				 , PAB.DSIGN
	) ENG
	WHERE ENG.SIREN = @PK_SIREN
	AND ENG.CEXO = @PK_ANNEE
	GROUP BY SIREN, CEXO
)

SELECT REQ.SIREN
	 , REQ.MT_ENGAGE
FROM REQ
--WHERE REQ.SIREN = '0568006590'
GROUP BY REQ.SIREN
       , REQ.MT_ENGAGE
ORDER BY REQ.SIREN

END