-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
CREATE PROCEDURE [dbo].[GLIFOU] 
( 
	@DT_DEBUT DATETIME,
	@DT_FIN DATETIME,
	@PK_PROPRIETAIRE NVARCHAR(MAX),
	@PK_IMMEUBLE NVARCHAR(MAX),
	@PK_FOURNISSEUR NVARCHAR(MAX),
	@LETTRE BIT
)
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;

SELECT PROPRIETAIRES.PK_TIERS AS PK_PROPRIETAIRE
	 , FOURNISSEURS.PK_TIERS AS PK_FOURNISSEUR
     , GROUPE.PK_GROUPE
	 , PROPRIETAIRES.LTIERS AS NOM_PROPRIETAIRE
	 , ECRITAUX.CCATEG
	 , CATEG.LCATEG
	 , ECRITAUX.CTYPCOM
	 , TYPCOM.LTYPCOM
	 , MANSEC.CSECTANA
	 --, DETSEC.CSECTANA
	 , GROUPE.LGROUPE
	 , ECRITAUX.CTIERS
	 , FOURNISSEURS.LTIERS
	 , ECRITAUX.DATEC
	 , ECRITAUX.LIBELLE
	 , ECRITAUX.NOFACT
	 , ECRITAUX.CJOURNAL
	 , ECRITAUX.CTYPECRI
	 , ECRITAUX.NOPIECE
	 , ECRITAUX.LETTRAGE
	 , CASE ECRITAUX.SENS WHEN 'D' THEN ECRITAUX.MONTANT ELSE 0 END AS MT_DEBIT
	 , CASE ECRITAUX.SENS WHEN 'C' THEN ECRITAUX.MONTANT ELSE 0 END AS MT_CREDIT
	 , ECRITAUX.CMANDAT
FROM MASTER_ESTIA..ESTIA_ECRITAUX ECRITAUX
LEFT JOIN MASTER_ESTIA..ESTIA_CATEG CATEG
ON CATEG.CCATEG = ECRITAUX.CCATEG
LEFT JOIN MASTER_ESTIA..ESTIA_TYPCOM TYPCOM
ON TYPCOM.CTYPCOM = ECRITAUX.CTYPCOM
LEFT JOIN MASTER_ESTIA..WRK_GROUPE_MANGES WGM
ON WGM.CORG = ECRITAUX.CORG AND WGM.CMANDAT = ECRITAUX.CMANDAT
LEFT JOIN MASTER_ESTIA..ESTIA_TIERS PROPRIETAIRES
ON PROPRIETAIRES.PK_TIERS = WGM.FK_TIERS
LEFT JOIN MASTER_ESTIA..ESTIA_TIERS FOURNISSEURS
ON FOURNISSEURS.CTIERS = ECRITAUX.CTIERS
LEFT JOIN 
(
	SELECT DISTINCT CORG
			, CMANDAT
			, CSECTANA
	FROM MASTER_ESTIA..ESTIA_MANSEC 
) MANSEC
ON MANSEC.CORG = ECRITAUX.CORG AND MANSEC.CMANDAT = ECRITAUX.CMANDAT
LEFT JOIN
(
	SELECT CORG
			, CTYPTIERS
			, CTIERS
			, REF
			, LIGNE
			, CSECTANA
			, (CASE SENS WHEN 'D' THEN MONTANT ELSE 0 END) AS CUMUL_PERIODE_DEBIT
			, (CASE SENS WHEN 'C' THEN MONTANT ELSE 0 END) AS CUMUL_PERIODE_CREDIT
	FROM MASTER_ESTIA..ESTIA_DETSEC
	WHERE CORG = '11'
) DETSEC
ON DETSEC.CORG = ECRITAUX.CORG AND DETSEC.CTYPTIERS = ECRITAUX.CTYPTIERS AND DETSEC.CTIERS = ECRITAUX.CTIERS AND DETSEC.REF = ECRITAUX.REF AND DETSEC.LIGNE = ECRITAUX.LIGNE
LEFT JOIN MASTER_ESTIA..ESTIA_GROUPE GROUPE
ON GROUPE.PK_GROUPE = WGM.PK_GROUPE
WHERE ECRITAUX.CORG = '11' 
AND ECRITAUX.DATEC BETWEEN @DT_DEBUT AND @DT_FIN
AND PROPRIETAIRES.PK_TIERS IN (SELECT VALUE FROM dbo.ufn_SplitMultiValue(@PK_PROPRIETAIRE,',')) 
AND GROUPE.PK_GROUPE IN (SELECT VALUE FROM dbo.ufn_SplitMultiValue(@PK_IMMEUBLE,','))
AND FOURNISSEURS.PK_TIERS IN (SELECT VALUE FROM dbo.ufn_SplitMultiValue(@PK_FOURNISSEUR,','))
AND ECRITAUX.CTYPCOM = 'F'
AND ECRITAUX.BLET = CASE WHEN @LETTRE = 1 THEN  'L' ELSE 'X' END
ORDER BY ECRITAUX.CMANDAT
	   , WGM.CGROUPE 
	   , ECRITAUX.DATEC

END