-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
CREATE PROCEDURE [dbo].[HIST_BAUX] 
(
	@PK_PROPRIETAIRE  NVARCHAR(MAX),
	@PK_AGENCE  NVARCHAR(MAX),
	@PK_IMMEUBLE NVARCHAR(MAX)
)
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;

select WHL.FK_BAIL
	 , WHL.CMANDAT
	 , PROP.LTIERS
	 , WHL.CAGENCE
	 , dbo.LPAD(WHL.CGROUPE, 4, '0') AS CGROUPE
	 , WHL.CIMMEUB
	 , dbo.LPAD(WHL.CLOCAL, 4, '0') AS CLOCAL
	 , LOCATAIRE.LTIERS AS NOM_LOCATAIRE
	 , WHL.CCOMPTE
	 , LOCATION.DATEFFET
	 , WHL.DATENTQUIT
	 , WHL.DATSORQUIT
from MASTER_ESTIA..WRK_HISTO_LOT WHL
left join MASTER_ESTIA..ESTIA_TIERS PROP
on PROP.PK_TIERS = WHL.FK_PROPRIETAIRE
left join MASTER_ESTIA..ESTIA_AGENCE AGENCE
on AGENCE.PK_AGENCE = WHL.FK_AGENCE
left join MASTER_ESTIA..ESTIA_GROUPE GROUPE
on GROUPE.PK_GROUPE = WHL.FK_GROUPE 
left join MASTER_ESTIA..ESTIA_LOCATION LOCATION
on LOCATION.PK_LOCATION = WHL.FK_BAIL
left join MASTER_ESTIA..ESTIA_TIERS LOCATAIRE
on LOCATAIRE.PK_TIERS = WHL.FK_TIERS
where CD_STATUT = 'L'
and WHL.CORG = '11'
AND PROP.PK_TIERS IN (SELECT VALUE FROM dbo.ufn_SplitMultiValue(@PK_PROPRIETAIRE,',')) --= @PK_PROPRIETAIRE
AND AGENCE.PK_AGENCE  IN (SELECT VALUE FROM dbo.ufn_SplitMultiValue(@PK_AGENCE,',')) 
AND GROUPE.PK_GROUPE IN (SELECT VALUE FROM dbo.ufn_SplitMultiValue(@PK_IMMEUBLE,','))
order by WHL.CAGENCE, WHL.CGROUPE, WHL.CIMMEUB, WHL.CLOCAL, LOCATION.DATEFFET DESC

END