-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
CREATE PROCEDURE [dbo].[LISTE_LOCATAIRE_COMPTA_LOCATAIRE_CAIRN] 
(
	@PK_IMMEUBLE NVARCHAR(MAX)
)
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;

SELECT DISTINCT
   FCL.FK_LOCATAIRE AS PK_LOCATAIRE
  ,D_LOCATAIRE.CD_LOCATAIRE
  ,ISNULL(D_LOCATAIRE.NM_LOCATAIRE, 99999) AS NM_LOCATAIRE
  ,CAST(ISNULL(D_LOCATAIRE.NM_LOCATAIRE, 99999) AS VARCHAR(14)) + ' - ' + dbo.InitCap(ISNULL(D_LOCATAIRE.NOM_LOCATAIRE, 'VACANT')) AS NOM_LOCATAIRE
FROM
  D_LOCATAIRE
  INNER JOIN D_BAIL 
    ON D_BAIL.FK_LOCATAIRE = D_LOCATAIRE.PK_LOCATAIRE
  INNER JOIN D_IMMEUBLE
    ON D_IMMEUBLE.PK_IMMEUBLE = D_BAIL.FK_IMMEUBLE
  RIGHT JOIN (SELECT DISTINCT CPTGLOB.FK_GROUPE AS FK_IMMEUBLE, ISNULL(CPTGLOB.FK_TIERS, 99999) AS FK_LOCATAIRE FROM  MASTER_ESTIA..ESTIA_CPTGLOB AS CPTGLOB)FCL
    ON FCL.FK_IMMEUBLE = D_IMMEUBLE.PK_IMMEUBLE AND FCL.FK_LOCATAIRE = D_LOCATAIRE.PK_LOCATAIRE
WHERE
  FCL.FK_IMMEUBLE IN (SELECT VALUE FROM dbo.ufn_SplitMultiValue(@PK_IMMEUBLE,','))

END