-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
CREATE PROCEDURE [dbo].[LISTE_CONTRAT_SALEFORCE] 
(
	--@PK_IMMEUBLE NVARCHAR(MAX),
	@CD_IMMEUBLE_DREAM NVARCHAR(MAX),
	@PK_TIERS NVARCHAR(MAX)
)
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;

SELECT CTR.PK_CTRTIERS
	 , IMMEUBLE.PK_GROUPE
	 , T.PK_TIERS
	 , CTR.CCONTFRS
	 , UPPER(CTR.LCTRTIERS) + ' - ' + CTR.LIBFAC AS LB_CONTRAT
FROM MASTER_ESTIA..ESTIA_CTRTIERS CTR
LEFT JOIN MASTER_ESTIA..ESTIA_TIERS T
ON T.PK_TIERS = CTR.FK_TIERS
LEFT JOIN
(
	SELECT DISTINCT FK_CTRTIERS, FK_GROUPE AS FK_IMMEUBLE
	FROM MASTER_ESTIA..ESTIA_VENTPCHA
) VENTPCHA
ON VENTPCHA.FK_CTRTIERS = CTR.PK_CTRTIERS
LEFT JOIN MASTER_ESTIA..ESTIA_GROUPE IMMEUBLE
ON IMMEUBLE.PK_GROUPE = VENTPCHA.FK_IMMEUBLE
LEFT JOIN MASTER_ESTIA..P_TRANSCO_IMMEUBLE_EASYFOLDER P
ON IMMEUBLE.CGROUPE = P.NM_IMMEUBLE_ESTIA
WHERE IMMEUBLE.CORG = '11' 
--AND IMMEUBLE.PK_GROUPE IN (SELECT VALUE FROM dbo.ufn_SplitMultiValue(@PK_IMMEUBLE,',')) -- = 4310
AND P.CD_IMMEUBLE_DREAM IN (SELECT VALUE FROM dbo.ufn_SplitMultiValue(@CD_IMMEUBLE_DREAM,','))
AND T.PK_TIERS IN (SELECT VALUE FROM dbo.ufn_SplitMultiValue(@PK_TIERS,',')) -- = 4620

END