-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
CREATE PROCEDURE [dbo].[LISTE_IMMEUBLE_CAIRN] 
(
	@PK_PROPRIETAIRE NVARCHAR(MAX)
)
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;

	 SELECT
	    D_MANDAT_GERANCE.FK_PROPRIETAIRE AS PK_PROPRIETAIRE
	  , D_MANDAT_GERANCE.CD_MANDAT + ' - ' + GROUPE.LGROUPE AS CD_MANDAT
	  , GROUPE.PK_GROUPE AS PK_IMMEUBLE
	  , REPLACE(STR(GROUPE.CGROUPE, 4, 0), ' ', '0') AS CD_IMMEUBLE
	  , GROUPE.CGROUPE AS NM_IMMEUBLE
	  , GROUPE.LGROUPE AS ADRLGN1
	  , UPPER(CONCAT(CAST(REPLACE(STR(GROUPE.CGROUPE, 4, 0), ' ', '0') AS VARCHAR(4)) + ' - ', GROUPE.LGROUPE)) as NOM_IMMEUBLE
	  , D_MANDAT_GERANCE.IND_MANDAT_ACTIF
	FROM
	  D_MANDAT_GERANCE
	  INNER JOIN MASTER_ESTIA..ESTIA_GROUPE GROUPE
	  on GROUPE.PK_GROUPE = D_MANDAT_GERANCE.FK_IMMEUBLE
	  INNER JOIN D_PROPRIETAIRE
		ON D_MANDAT_GERANCE.FK_PROPRIETAIRE = D_PROPRIETAIRE.PK_PROPRIETAIRE
	  --INNER JOIN MASTER_ESTIA..ESTIA_AGENCE AGENCE
	  --ON AGENCE.PK_AGENCE = GROUPE.FK_AGENCE
	WHERE
	  D_MANDAT_GERANCE.IND_MANDAT_ACTIF LIKE N'O'
	  AND D_MANDAT_GERANCE.FK_PROPRIETAIRE IN (SELECT VALUE FROM dbo.ufn_SplitMultiValue(@PK_PROPRIETAIRE,','))
	  AND GROUPE.LGROUPE NOT LIKE '%GENERIQUE%'
	ORDER BY GROUPE.CGROUPE

END