-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
CREATE PROCEDURE [dbo].[LISTE_FOURNISSEUR_CAIRN] 
(
	@DT_DEBUT DATETIME,
	@DT_FIN DATETIME,
	@PK_IMMEUBLE NVARCHAR(MAX)
)
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;

SELECT T.PK_TIERS
	 , T.CTIERS AS CD_FOURNISSEUR
	 , T.CTIERS + ' - ' + UPPER(T.LTIERS) AS NOM_FOURNISSEUR
FROM MASTER_ESTIA..ESTIA_ECRITAUX ECRITAUX
LEFT JOIN MASTER_ESTIA..ESTIA_TIERS T
ON T.PK_TIERS = ECRITAUX.FK_TIERS
LEFT JOIN MASTER_ESTIA..WRK_GROUPE_MANGES WGM
ON WGM.CORG = ECRITAUX.CORG AND WGM.CMANDAT = ECRITAUX.CMANDAT
LEFT JOIN MASTER_ESTIA..ESTIA_GROUPE GROUPE
ON GROUPE.PK_GROUPE = WGM.PK_GROUPE
WHERE GROUPE.PK_GROUPE IN (SELECT VALUE FROM dbo.ufn_SplitMultiValue(@PK_IMMEUBLE,','))
AND  ECRITAUX.DATEC BETWEEN @DT_DEBUT AND @DT_FIN
GROUP BY T.PK_TIERS, T.CTIERS, T.LTIERS

END