-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
CREATE PROCEDURE [dbo].[LISTE_IMMEUBLE_SALEFORCE] 
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;

	--(
	 SELECT
	    D_MANDAT_GERANCE.FK_PROPRIETAIRE AS PK_PROPRIETAIRE
	  , D_IMMEUBLE.PK_IMMEUBLE
	  , D_IMMEUBLE.CD_IMMEUBLE
	  , P.CD_IMMEUBLE_DREAM
	  , D_IMMEUBLE.NM_IMMEUBLE
	  , D_IMMEUBLE.ADRLGN1
	  , UPPER(CONCAT(CAST(D_IMMEUBLE.CD_IMMEUBLE AS VARCHAR(4)) + ' - ', D_IMMEUBLE.ADRLGN1)) as NOM_IMMEUBLE
	  , UPPER(CONCAT(CAST(P.CD_IMMEUBLE_DREAM AS VARCHAR(11)) + ' - ', D_IMMEUBLE.ADRLGN1)) as NOM_IMMEUBLE_DREAM  
	  , D_MANDAT_GERANCE.IND_MANDAT_ACTIF
	FROM
	  D_MANDAT_GERANCE
	  INNER JOIN D_IMMEUBLE
		ON D_MANDAT_GERANCE.FK_IMMEUBLE = D_IMMEUBLE.PK_IMMEUBLE
	  LEFT JOIN MASTER_ESTIA..P_TRANSCO_IMMEUBLE_EASYFOLDER P
		ON D_IMMEUBLE.NM_IMMEUBLE = P.NM_IMMEUBLE_ESTIA
	  INNER JOIN D_PROPRIETAIRE
		ON D_MANDAT_GERANCE.FK_PROPRIETAIRE = D_PROPRIETAIRE.PK_PROPRIETAIRE
	WHERE
	  D_MANDAT_GERANCE.IND_MANDAT_ACTIF LIKE N'O'
 --  )
 --  UNION
 --  (
	-- SELECT
	--    PROPRIETAIRE.PK_PROPRIETAIRE
	--  , D_IMMEUBLE.PK_IMMEUBLE
	--  , D_IMMEUBLE.CD_IMMEUBLE
	--  , D_IMMEUBLE.NM_IMMEUBLE
	--  , D_IMMEUBLE.ADRLGN1
	--  , UPPER(CONCAT(CAST(D_IMMEUBLE.CD_IMMEUBLE AS VARCHAR(4)) + ' - ', D_IMMEUBLE.ADRLGN1)) as NOM_IMMEUBLE
	--  , PROPERTY_ETL.dbo.GetACTIF(IMMEUBLE.DT_DEB_GEST, IMMEUBLE.DT_FIN_GEST, GETDATE()) AS IND_MANDAT_ACTIF
	--FROM
	--D_IMMEUBLE
	--  INNER JOIN PROPERTY_ETL.DBO.IMMEUBLE IMMEUBLE
	--    ON IMMEUBLE.PK_IMMEUBLE = D_IMMEUBLE.PK_IMMEUBLE
	--  INNER JOIN PROPERTY_ETL.DBO.PROPRIETAIRE PROPRIETAIRE
	--    ON PROPRIETAIRE.CD_PROPRIETAIRE = IMMEUBLE.CD_PROPRIETAIRE
	--WHERE
	--  PROPERTY_ETL.dbo.GetACTIF(IMMEUBLE.DT_DEB_GEST, IMMEUBLE.DT_FIN_GEST, GETDATE()) = 'O'
 --  )
   	ORDER BY P.CD_IMMEUBLE_DREAM

END