-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
CREATE PROCEDURE [dbo].[LISTE_PROPRIETAIRE_EXPERT_COMPT] 
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;

	SELECT DISTINCT 
	  D_PROPRIETAIRE.PK_PROPRIETAIRE
	, D_PROPRIETAIRE.CD_PROPRIETAIRE
	, D_PROPRIETAIRE.NM_PROPRIETAIRE
	, CAST(D_PROPRIETAIRE.NM_PROPRIETAIRE AS VARCHAR(14)) + ' - ' + D_PROPRIETAIRE.NOM_PROPRIETAIRE AS NOM_PROPRIETAIRE
	FROM D_PROPRIETAIRE
	WHERE D_PROPRIETAIRE.NM_PROPRIETAIRE IN (13219,13224,23698,37947,41448,42027,42267,42327,42328,48177,48383,48438)
	ORDER BY D_PROPRIETAIRE.NM_PROPRIETAIRE

END