-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
CREATE PROCEDURE [dbo].[LISTE_LOCATAIRE] 
(
	@PK_TEMPS DATETIME,
	@PK_IMMEUBLE NVARCHAR(MAX)
)
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;

SELECT DISTINCT
   FEL.FK_LOCATAIRE AS PK_LOCATAIRE
  ,D_LOCATAIRE.CD_LOCATAIRE
  ,CASE WHEN FEL.FK_LOCATAIRE = '-88888' THEN 88888 ELSE ISNULL(D_LOCATAIRE.NM_LOCATAIRE, 99999) END AS NM_LOCATAIRE
  , CASE WHEN FEL.FK_LOCATAIRE = '-88888' THEN '88888' ELSE CAST(ISNULL(D_LOCATAIRE.NM_LOCATAIRE, 99999) AS VARCHAR(14)) END + ' - ' + CASE WHEN FEL.FK_LOCATAIRE = '-88888' THEN 'Gardien' ELSE dbo.InitCap(ISNULL(D_LOCATAIRE.NOM_LOCATAIRE, 'VACANT')) END AS NOM_LOCATAIRE
FROM
  D_LOCATAIRE
  INNER JOIN D_BAIL 
    ON D_BAIL.FK_LOCATAIRE = D_LOCATAIRE.PK_LOCATAIRE
  INNER JOIN D_IMMEUBLE
    ON D_IMMEUBLE.PK_IMMEUBLE = D_BAIL.FK_IMMEUBLE
  RIGHT JOIN 
  (
	SELECT DISTINCT F_ETAT_LOCATIF.FK_IMMEUBLE, ISNULL(F_ETAT_LOCATIF.FK_LOCATAIRE, 99999) AS FK_LOCATAIRE 
	FROM F_ETAT_LOCATIF WHERE F_ETAT_LOCATIF.PK_TEMPS = (@PK_TEMPS)
 )FEL
    ON FEL.FK_IMMEUBLE = D_IMMEUBLE.PK_IMMEUBLE AND FEL.FK_LOCATAIRE = D_LOCATAIRE.PK_LOCATAIRE
WHERE
  FEL.FK_IMMEUBLE IN (SELECT VALUE FROM dbo.ufn_SplitMultiValue(@PK_IMMEUBLE,','))--(@PK_IMMEUBLE)

END