CREATE PROCEDURE [dbo].[LISTE_SOUS_CRITERE] 
(
	@PK_IMMEUBLE NVARCHAR(MAX),
	@CCRITDP VARCHAR(MAX)
)
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;

SELECT CGROUPE
	 , CSCRITDP
	 , LSCRITDP
FROM
(
	SELECT SCRITDP.CGROUPE
		 , SCRITDP.CSCRITDP
		 , concat(cast(SCRITDP.CSCRITDP as varchar(10)), ' - ' + SCRITDP.LSCRITDP) LSCRITDP
	from MASTER_ESTIA..ESTIA_SCRITDP SCRITDP
	LEFT JOIN MASTER_ESTIA..ESTIA_GROUPE IMMEUBLE
	ON IMMEUBLE.PK_GROUPE = SCRITDP.FK_GROUPE
	LEFT JOIN MASTER_ESTIA..ESTIA_CRITDP CRITDP
	ON CRITDP.CCRITDP = SCRITDP.CCRITDP
	WHERE SCRITDP.CORG = '11'
	AND IMMEUBLE.PK_GROUPE IN (SELECT VALUE FROM dbo.ufn_SplitMultiValue(@PK_IMMEUBLE,','))
	AND CRITDP.CCRITDP IN (SELECT VALUE FROM dbo.ufn_SplitMultiValue(@CCRITDP,','))
	GROUP BY SCRITDP.CGROUPE, SCRITDP.CSCRITDP, SCRITDP.LSCRITDP
) SRC
ORDER BY CGROUPE, CSCRITDP

END