-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
CREATE PROCEDURE [dbo].[LISTE_LOCATAIRE_COMPTA_LOC_SALEFORCE] 
(
	--@PK_IMMEUBLE NVARCHAR(MAX)
	@CD_IMMEUBLE_DREAM NVARCHAR(MAX)
)
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;

SELECT DISTINCT
   FCL.FK_LOCATAIRE AS PK_LOCATAIRE
  ,D_LOCATAIRE.CD_LOCATAIRE
  ,ISNULL(D_LOCATAIRE.NM_LOCATAIRE, 99999) AS NM_LOCATAIRE
  ,CAST(ISNULL(D_LOCATAIRE.NM_LOCATAIRE, 99999) AS VARCHAR(14)) + ' - ' + dbo.InitCap(ISNULL(D_LOCATAIRE.NOM_LOCATAIRE, 'VACANT')) AS NOM_LOCATAIRE
FROM
  D_LOCATAIRE
  INNER JOIN D_BAIL 
    ON D_BAIL.FK_LOCATAIRE = D_LOCATAIRE.PK_LOCATAIRE
  INNER JOIN D_IMMEUBLE
    ON D_IMMEUBLE.PK_IMMEUBLE = D_BAIL.FK_IMMEUBLE
  RIGHT JOIN (SELECT DISTINCT F_COMPTABILITE_LOCATAIRE.FK_IMMEUBLE, ISNULL(F_COMPTABILITE_LOCATAIRE.FK_LOCATAIRE, 99999) AS FK_LOCATAIRE FROM F_COMPTABILITE_LOCATAIRE)FCL
    ON FCL.FK_IMMEUBLE = D_IMMEUBLE.PK_IMMEUBLE AND FCL.FK_LOCATAIRE = D_LOCATAIRE.PK_LOCATAIRE
  LEFT JOIN MASTER_ESTIA..P_TRANSCO_IMMEUBLE_EASYFOLDER P
    ON D_IMMEUBLE.NM_IMMEUBLE = P.NM_IMMEUBLE_ESTIA
WHERE
  --FCL.FK_IMMEUBLE IN (SELECT VALUE FROM dbo.ufn_SplitMultiValue(@PK_IMMEUBLE,','))--(@PK_IMMEUBLE)  
  P.CD_IMMEUBLE_DREAM IN (SELECT VALUE FROM dbo.ufn_SplitMultiValue(@CD_IMMEUBLE_DREAM,','))

END