-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
CREATE PROCEDURE [dbo].[TRAIT_BAUX_EASYFOLDER]
AS
BEGIN

SET ANSI_WARNINGS OFF

DECLARE @DT DATETIME
SET @DT = CONVERT(DATETIME, CONVERT(VARCHAR(10),GETDATE(),103), 103)


-- AJOUT DES BAUX AJOUTES MANUELLEMENT
DELETE FROM WRK_INTERFACE_EASYFOLDER_BAUX WHERE PK_TEMPS = @DT AND IFC_STATUT_TRAITEMENT IS NOT NULL;

-- AJOUT DES BAUX AJOUTES MANUELLEMENT DANS LA TABLE WRK_INTERFACE_EASYFOLDER_BAUX
INSERT INTO WRK_INTERFACE_EASYFOLDER_BAUX(PK_TEMPS, ACTION, IDENTIFIANT_BAIL_DREAM, IDENTIFIANT_DREAM_IMMEUBLE, NOM_IMMEUBLE, IDENTIFIANT_ESTIA_IMMEUBLE, IDENTIFIANT_ESTIA_COMPTE, NOBAIL_ESTIA, LOCATAIRE_PRINCIPAL, DT_EFFET, DT_FIN)
select @DT AS PK_TEMPS
	 , 'ADD' AS ACTION
	 , IDENTIFIANT_BAIL_DREAM
	 , IDENTIFIANT_DREAM_IMMEUBLE
	 , P.NOM_IMMEUBLE_DREAM
	 , IDENTIFIANT_ESTIA_IMMEUBLE
	 , IDENTIFIANT_ESTIA_COMPTE  
	 , NOBAIL_ESTIA
	 , LOCATAIRE_PRINCIPAL
	 , DT_EFFET
	 , DT_FIN
from TMP_INTERFACE_EASYFOLDER_BAUX
left join P_TRANSCO_IMMEUBLE_EASYFOLDER P
ON P.CD_IMMEUBLE_DREAM = IDENTIFIANT_DREAM_IMMEUBLE
where not exists
(select 1  from L_INTERFACE_EASYFOLDER_BAUX
where L_INTERFACE_EASYFOLDER_BAUX.IDENTIFIANT_BAIL_DREAM = TMP_INTERFACE_EASYFOLDER_BAUX.IDENTIFIANT_BAIL_DREAM)

-- AJOUT DES NOUVEAUX BAUX DANS LA TABLE L_INTERFACE_EASYFOLDER_BAUX
INSERT INTO L_INTERFACE_EASYFOLDER_BAUX(IDENTIFIANT_BAIL_DREAM, IDENTIFIANT_DREAM_IMMEUBLE, IDENTIFIANT_ESTIA_IMMEUBLE, /*NOM_DU_FICHIER_PDF,*/ IDENTIFIANT_ESTIA_COMPTE, NOBAIL_ESTIA, LOCATAIRE_PRINCIPAL, DT_EFFET, DT_FIN)
SELECT IDENTIFIANT_BAIL_DREAM
	 , IDENTIFIANT_DREAM_IMMEUBLE
	 , IDENTIFIANT_ESTIA_IMMEUBLE
	 --, NOM_DU_FICHIER_PDF
	 , IDENTIFIANT_ESTIA_COMPTE
	 , NOBAIL_ESTIA
	 , LOCATAIRE_PRINCIPAL
	 , DT_EFFET
	 , DT_FIN 
FROM WRK_INTERFACE_EASYFOLDER_BAUX
WHERE PK_TEMPS = @DT
AND ACTION = 'ADD'

-- AJOUT DES NOUVEAUX BAUX DANS LA TABLE WRK_INTERFACE_EASYFOLDER_BAUX
INSERT INTO WRK_INTERFACE_EASYFOLDER_BAUX(PK_TEMPS, ACTION, IDENTIFIANT_BAIL_DREAM, IDENTIFIANT_DREAM_IMMEUBLE, NOM_IMMEUBLE, IDENTIFIANT_ESTIA_IMMEUBLE, /*NOM_DU_FICHIER_PDF,*/ IDENTIFIANT_ESTIA_COMPTE, NOBAIL_ESTIA, LOCATAIRE_PRINCIPAL, DT_EFFET, DT_FIN)
SELECT @DT AS PK_TEMPS
	 , 'ADD' AS ACTION
	 , 'BAIL' + dbo.LPAD(cast(LAST_IDENT + ROW_NUMBER() OVER (ORDER BY CCOMPTE, NOBAIL/*NOM_DU_FICHIER_PDF*/) as NVARCHAR(251)), 6, '0') AS IDENTIFIANT_BAIL_DREAM --LAST_IDENT + ROW_NUMBER() OVER (ORDER BY NOM_DU_FICHIER_PDF) as IDENT
	 , IDENTIFIANT_DREAM_IMMEUBLE
	 , NOM_IMMEUBLE
	 , IDENTIFIANT_ESTIA_IMMEUBLE
	 --, NOM_DU_FICHIER_PDF
	 , IDENTIFIANT_ESTIA_COMPTE
	 , NOBAIL_ESTIA
	 , LOCATAIRE_PRINCIPAL
	 , DT_EFFET
	 , DT_FIN
FROM
(
	SELECT (SELECT CAST(RIGHT(MAX(IDENTIFIANT_BAIL_DREAM), 6) AS NUMERIC(6,0)) FROM L_INTERFACE_EASYFOLDER_BAUX) AS LAST_IDENT
		 , P.CD_IMMEUBLE_DREAM AS IDENTIFIANT_DREAM_IMMEUBLE
		 , LOCATION.CGROUPE AS IDENTIFIANT_ESTIA_IMMEUBLE
		 , P.NOM_IMMEUBLE_DREAM AS NOM_IMMEUBLE
		 --, CAST(RIGHT(LOCATION.CCOMPTE, 4) AS VARCHAR(4)) + CAST(LOCATION.NOBAIL AS VARCHAR(3)) AS NOM_DU_FICHIER_PDF
		 , CAST(RIGHT(LOCATION.CCOMPTE, 4) AS VARCHAR(4)) AS CCOMPTE
		 , CAST(LOCATION.NOBAIL AS VARCHAR(3)) AS NOBAIL
		 , LOCATION.CCOMPTE AS IDENTIFIANT_ESTIA_COMPTE
		 , LOCATION.NOBAIL AS NOBAIL_ESTIA
		 , TIERS.LTIERS AS LOCATAIRE_PRINCIPAL
		 , LOCATION.DATEFFET AS DT_EFFET
		 , LOCATION.DATFIN AS DT_FIN--ISNULL(LOCATION.DATFIN, DATEADD(MONTH, LOCATION.DURBAIL, LOCATION.DATEFFET)) AS DT_FIN
		 , RANK() OVER (PARTITION BY LOCATION.CORG ORDER BY LOCATION.CCOMPTE, LOCATION.NOBAIL) RK
	FROM  ESTIA_LOCATION AS LOCATION 
		LEFT OUTER JOIN	ESTIA_GROUPE AS GROUPE ON GROUPE.PK_GROUPE = LOCATION.FK_GROUPE 
		INNER JOIN V_D_MANDAT_GERANCE MANDAT ON MANDAT.FK_IMMEUBLE = GROUPE.PK_GROUPE	
		LEFT OUTER JOIN	DBO.ESTIA_LIENLOC AS LIENLOC ON LIENLOC.CORG = LOCATION.CORG AND LIENLOC.CCOMPTE = LOCATION.CCOMPTE AND LIENLOC.RK = 1 
		LEFT OUTER JOIN	DBO.ESTIA_TIERS AS TIERS ON TIERS.CTYPTIERS = LIENLOC.CTYPTIERS AND TIERS.CTIERS = LIENLOC.CTIERS
		LEFT OUTER JOIN DBO.P_TRANSCO_IMMEUBLE_EASYFOLDER AS P ON P.NM_IMMEUBLE_ESTIA = GROUPE.CGROUPE
	WHERE  (LOCATION.CORG = '11') AND (LOCATION.NOLOCAT = LOCATION.CONTLOC) --AND (LOCATION.DATEFFET > GETDATE()
	AND MANDAT.IND_MANDAT_ACTIF = 'O'
	AND GROUPE.CGROUPE NOT IN ('2222', '8888', '4027', '9999', '8510', '1024', '4444', '1111', '3057')
	AND UPPER(GROUPE.LGROUPE) NOT LIKE '%GENERIQUE%'
	AND ISNULL(LOCATION.DATFIN, '29990101') > @DT
) REQ
WHERE NOT EXISTS
(
	SELECT * FROM L_INTERFACE_EASYFOLDER_BAUX L
	WHERE L.IDENTIFIANT_ESTIA_compte = REQ.IDENTIFIANT_ESTIA_COMPTE AND L.NOBAIL_ESTIA = REQ.NOBAIL_ESTIA
)


-- AJOUT DES BAUX AJOUTES MANUELLEMENT DANS LA TABLE L_INTERFACE_EASYFOLDER_BAUX
--insert into L_INTERFACE_EASYFOLDER_BAUX
--select *  
--from TMP_INTERFACE_EASYFOLDER_BAUX
--where not exists
--(select 1  from L_INTERFACE_EASYFOLDER_BAUX
--where L_INTERFACE_EASYFOLDER_BAUX.IDENTIFIANT_BAIL_DREAM = TMP_INTERFACE_EASYFOLDER_BAUX.IDENTIFIANT_BAIL_DREAM)


---- AJOUT DES NOUVEAUX BAUX DANS LA TABLE L_INTERFACE_EASYFOLDER_BAUX
--INSERT INTO L_INTERFACE_EASYFOLDER_BAUX(IDENTIFIANT_BAIL_DREAM, IDENTIFIANT_DREAM_IMMEUBLE, IDENTIFIANT_ESTIA_IMMEUBLE, /*NOM_DU_FICHIER_PDF,*/ IDENTIFIANT_ESTIA_COMPTE, NOBAIL_ESTIA, LOCATAIRE_PRINCIPAL, DT_EFFET, DT_FIN)
--SELECT IDENTIFIANT_BAIL_DREAM
--	 , IDENTIFIANT_DREAM_IMMEUBLE
--	 , IDENTIFIANT_ESTIA_IMMEUBLE
--	 --, NOM_DU_FICHIER_PDF
--	 , IDENTIFIANT_ESTIA_COMPTE
--	 , NOBAIL_ESTIA
--	 , LOCATAIRE_PRINCIPAL
--	 , DT_EFFET
--	 , DT_FIN 
--FROM WRK_INTERFACE_EASYFOLDER_BAUX
--WHERE PK_TEMPS = @DT
--AND ACTION = 'ADD'

---- AJOUT DES NOUVEAUX BAUX DANS LA TABLE L_INTERFACE_EASYFOLDER_BAUX
INSERT INTO L_INTERFACE_EASYFOLDER_BAUX(IDENTIFIANT_BAIL_DREAM, IDENTIFIANT_DREAM_IMMEUBLE, IDENTIFIANT_ESTIA_IMMEUBLE, /*NOM_DU_FICHIER_PDF,*/ IDENTIFIANT_ESTIA_COMPTE, NOBAIL_ESTIA, LOCATAIRE_PRINCIPAL, DT_EFFET, DT_FIN)
SELECT IDENTIFIANT_BAIL_DREAM
	 , IDENTIFIANT_DREAM_IMMEUBLE
	 , IDENTIFIANT_ESTIA_IMMEUBLE
	 --, NOM_DU_FICHIER_PDF
	 , IDENTIFIANT_ESTIA_COMPTE
	 , NOBAIL_ESTIA
	 , LOCATAIRE_PRINCIPAL
	 , DT_EFFET
	 , DT_FIN 
FROM WRK_INTERFACE_EASYFOLDER_BAUX
WHERE PK_TEMPS = @DT
AND ACTION = 'ADD'
AND IDENTIFIANT_ESTIA_IMMEUBLE IS NOT NULL
AND NOT EXISTS
(
	SELECT * FROM L_INTERFACE_EASYFOLDER_BAUX L
	WHERE L.IDENTIFIANT_ESTIA_compte = WRK_INTERFACE_EASYFOLDER_BAUX.IDENTIFIANT_ESTIA_COMPTE AND L.NOBAIL_ESTIA = WRK_INTERFACE_EASYFOLDER_BAUX.NOBAIL_ESTIA
)

-- AJOUT DES MAJ DE BAUX DANS LA TABLE WRK_INTERFACE_EASYFOLDER_BAUX
INSERT INTO WRK_INTERFACE_EASYFOLDER_BAUX(PK_TEMPS, ACTION, IDENTIFIANT_BAIL_DREAM, IDENTIFIANT_DREAM_IMMEUBLE, NOM_IMMEUBLE, IDENTIFIANT_ESTIA_IMMEUBLE, /*NOM_DU_FICHIER_PDF,*/ IDENTIFIANT_ESTIA_COMPTE, NOBAIL_ESTIA, LOCATAIRE_PRINCIPAL, DT_EFFET, DT_FIN)
SELECT @DT AS PK_TEMPS
	 , 'UPDATE' AS ACTION
	 , L.IDENTIFIANT_BAIL_DREAM
	 , L.IDENTIFIANT_DREAM_IMMEUBLE
	 , P.NOM_IMMEUBLE_DREAM
	 , L.IDENTIFIANT_ESTIA_IMMEUBLE
	 --, L.NOM_DU_FICHIER_PDF
	 , L.IDENTIFIANT_ESTIA_COMPTE
	 , L.NOBAIL_ESTIA
	 , L.LOCATAIRE_PRINCIPAL
	 , L.DT_EFFET
	 --, LOCATION.DATFIN
	 , LOCATION.DATSORQUIT
FROM L_INTERFACE_EASYFOLDER_BAUX L
INNER JOIN ESTIA_LOCATION LOCATION
ON LOCATION.CGROUPE = L.IDENTIFIANT_ESTIA_IMMEUBLE AND LOCATION.CCOMPTE = L.IDENTIFIANT_ESTIA_COMPTE AND LOCATION.NOBAIL = L.NOBAIL_ESTIA
LEFT OUTER JOIN	ESTIA_GROUPE AS GROUPE ON GROUPE.PK_GROUPE = LOCATION.FK_GROUPE
LEFT OUTER JOIN DBO.P_TRANSCO_IMMEUBLE_EASYFOLDER AS P ON P.NM_IMMEUBLE_ESTIA = GROUPE.CGROUPE
--CASE WHEN P.NM_IMMEUBLE_ESTIA IS NOT NULL THEN P.NM_IMMEUBLE_ESTIA ELSE P.CD_IMMEUBLE_DREAM END = 
--CASE WHEN P.NM_IMMEUBLE_ESTIA IS NOT NULL THEN GROUPE.CGROUPE ELSE L.IDENTIFIANT_DREAM_IMMEUBLE END
WHERE (LOCATION.CORG = '11') AND (LOCATION.NOLOCAT = LOCATION.CONTLOC)
AND LOCATION.DATSORQUIT IS NOT NULL
--AND L.DT_FIN IS NULL
AND (L.DT_FIN IS NULL OR LOCATION.DATSORQUIT > L.DT_FIN)

-- MAJ DES BAUX DANS LA TABLE L_INTERFACE_EASYFOLDER_BAUX
MERGE INTO L_INTERFACE_EASYFOLDER_BAUX L
USING
(
	SELECT IDENTIFIANT_BAIL_DREAM
		 , IDENTIFIANT_DREAM_IMMEUBLE
		 , IDENTIFIANT_ESTIA_IMMEUBLE
		 --, NOM_DU_FICHIER_PDF
		 , IDENTIFIANT_ESTIA_COMPTE
		 , NOBAIL_ESTIA
		 , LOCATAIRE_PRINCIPAL
		 , DT_EFFET
		 , DT_FIN  
	FROM WRK_INTERFACE_EASYFOLDER_BAUX
	WHERE PK_TEMPS = @DT
	AND ACTION = 'UPDATE'
) SRC
ON (SRC.IDENTIFIANT_ESTIA_IMMEUBLE = L.IDENTIFIANT_ESTIA_IMMEUBLE /*AND SRC.NOM_DU_FICHIER_PDF = L.NOM_DU_FICHIER_PDF*/ AND SRC.IDENTIFIANT_ESTIA_COMPTE = L.IDENTIFIANT_ESTIA_COMPTE AND SRC.NOBAIL_ESTIA = L.NOBAIL_ESTIA)
WHEN MATCHED THEN UPDATE SET DT_FIN = SRC.DT_FIN;

-- SUPPRIMER LES ENREGISTREMENTS DANS LA tABLE TMP_INTERFACE_EASYFOLDER_BAUX
TRUNCATE TABLE TMP_INTERFACE_EASYFOLDER_BAUX

END