-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
CREATE PROCEDURE [dbo].[TRAIT_CONTRATS_EASYFOLDER]
AS
BEGIN

SET ANSI_WARNINGS OFF

DECLARE @DT DATETIME
SET @DT = CONVERT(DATETIME, CONVERT(VARCHAR(10),DATEADD(DAY, -1, DATEADD(YEAR , DATEDIFF(YEAR, 0, GETDATE()) + 1, 0)),103), 103)

DELETE FROM WRK_INTERFACE_EASYFOLDER_CONTRATS WHERE PK_TEMPS = @DT AND IFC_STATUT_TRAITEMENT IS NOT NULL;

-- AJOUT DE NOUVEAUX CONTRATS DANS LA TABLE WRK_INTERFACE_EASYFOLDER_CONTRATS
INSERT INTO WRK_INTERFACE_EASYFOLDER_CONTRATS(PK_TEMPS, ACTION, IDENTIFIANT_DREAM_IMMEUBLE, IDENTIFIANT_ESTIA_IMMEUBLE, NOM_IMMEUBLE_ESTIA, NUM_CONTRAT, LB_CONTRAT, DT_FIN_PRESTATION)
SELECT @DT AS PK_TEMPS
	 , 'ADD' AS ACTION
	 , IDENTIFIANT_DREAM_IMMEUBLE
	 , IDENTIFIANT_ESTIA_IMMEUBLE
	 , NOM_IMMEUBLE_ESTIA
	 , NUM_CONTRAT
	 , LB_CONTRAT
	 , DT_FIN_PRESTATION
FROM
(
	SELECT P.CD_IMMEUBLE_DREAM AS IDENTIFIANT_DREAM_IMMEUBLE
		 , IMMEUBLE.CGROUPE AS IDENTIFIANT_ESTIA_IMMEUBLE
		 , IMMEUBLE.LGROUPE AS NOM_IMMEUBLE_ESTIA
		 , CAST(CTR.CCONTFRS AS INT) AS NUM_CONTRAT
		 , CONCAT(T.LTIERS, + ' - ' + CONVERT(VARCHAR(10), CAST(CTR.CCONTFRS AS INT)) + ' - ' + CTR.LIBFAC) AS LB_CONTRAT
		 , CTR.DLIMPREST AS DT_FIN_PRESTATION
	FROM MASTER_ESTIA..ESTIA_CTRTIERS CTR
	LEFT JOIN MASTER_ESTIA..ESTIA_TIERS T
	ON T.PK_TIERS = CTR.FK_TIERS
	LEFT JOIN
	(
		SELECT DISTINCT FK_CTRTIERS, FK_GROUPE AS FK_IMMEUBLE
		FROM MASTER_ESTIA..ESTIA_VENTPCHA
	) VENTPCHA
	ON VENTPCHA.FK_CTRTIERS = CTR.PK_CTRTIERS
	LEFT JOIN MASTER_ESTIA..ESTIA_GROUPE IMMEUBLE
	ON IMMEUBLE.PK_GROUPE = VENTPCHA.FK_IMMEUBLE
	INNER JOIN V_D_MANDAT_GERANCE MANDAT 
	ON MANDAT.FK_IMMEUBLE = IMMEUBLE.PK_GROUPE	
	LEFT OUTER JOIN DBO.P_TRANSCO_IMMEUBLE_EASYFOLDER AS P ON P.NM_IMMEUBLE_ESTIA = IMMEUBLE.CGROUPE
	WHERE CTR.DDEBVAL <= GETDATE()
	AND CTR.DLIMPREST >= GETDATE()
	AND CTR.CORG = '11'
	AND MANDAT.IND_MANDAT_ACTIF = 'O'
) REQ
WHERE NOT EXISTS
(
	SELECT * FROM L_INTERFACE_EASYFOLDER_CONTRATS L
	WHERE L.NUM_CONTRAT = REQ.NUM_CONTRAT
)


-- AJOUT DES NOUVELLES OPERATIONS DANS LA TABLE L_INTERFACE_EASYFOLDER_OPERATIONS
INSERT INTO L_INTERFACE_EASYFOLDER_CONTRATS(IDENTIFIANT_DREAM_IMMEUBLE, IDENTIFIANT_ESTIA_IMMEUBLE, NOM_IMMEUBLE_ESTIA, NUM_CONTRAT, LB_CONTRAT, DT_FIN_PRESTATION)
SELECT IDENTIFIANT_DREAM_IMMEUBLE
	 , IDENTIFIANT_ESTIA_IMMEUBLE
	 , NOM_IMMEUBLE_ESTIA
	 , NUM_CONTRAT
	 , LB_CONTRAT
	 , DT_FIN_PRESTATION
FROM WRK_INTERFACE_EASYFOLDER_CONTRATS
WHERE PK_TEMPS = @DT
AND ACTION = 'ADD'

END