




CREATE VIEW [dbo].[V_HREVIS]
AS
SELECT DISTINCT LOCATION.FK_BAIL, HREVIS.CORG, HREVIS.CAGENCE, HREVIS.CGROUPE, HREVIS.CIMMEUB, HREVIS.CLOCAL, HREVIS.OCC, 
		HREVIS.CSTE, IND_HREVIS, CD_INDICE_REVISION, DT_REVISION_PRECEDENTE, VAL_INDICE_INITIAL, VAL_INDICE_PRECEDENT, 
                         VAL_INDICE_ACTUEL, CD_INDICE_INITIAL, CD_INDICE_ACTUEL, DT_INDICE_INITIAL, DT_INDICE_ACTUEL
/*FROM            MASTER_ESTIA..WRK_HREVIS HREVIS INNER JOIN MASTER_ESTIA..ESTIA_LOCATION AS LOCATION
    ON LOCATION.CORG = HREVIS.CORG
    AND LOCATION.CAGENCE = HREVIS.CAGENCE
    AND LOCATION.CGROUPE = HREVIS.CGROUPE
    AND LOCATION.CIMMEUB = HREVIS.CIMMEUB
    AND LOCATION.CLOCAL = HREVIS.CLOCAL
    AND LOCATION.OCC = HREVIS.OCC*/
	FROM MASTER_ESTIA..ESTIA_HQLOCAT AS HQLOCAT INNER JOIN
MASTER_ESTIA..ESTIA_LOCATION AS LOCATION 
	ON HQLOCAT.CORG = LOCATION.CORG 
	AND HQLOCAT.CAGENCE = LOCATION.CAGENCE 
	AND HQLOCAT.CGROUPE = LOCATION.CGROUPE 
	AND HQLOCAT.CIMMEUB = LOCATION.CIMMEUB 
	AND HQLOCAT.CLOCAL = LOCATION.CLOCAL 
	AND HQLOCAT.OCC = LOCATION.OCC LEFT OUTER JOIN
MASTER_ESTIA..WRK_HREVIS HREVIS 
    ON HREVIS.CORG = HQLOCAT.CORG
    AND HREVIS.CAGENCE = HQLOCAT.CAGENCE
    AND HREVIS.CGROUPE = HQLOCAT.CGROUPE
    AND HREVIS.CIMMEUB = HQLOCAT.CIMMEUB
    AND HREVIS.CLOCAL = HQLOCAT.CLOCAL
    AND HREVIS.OCC = HQLOCAT.OCC
	AND HREVIS.CRUB = HQLOCAT.CRUB 
	AND HREVIS.CSTE = HQLOCAT.CSTE INNER JOIN
MASTER_ESTIA..P_RUBRIQUE 
ON P_RUBRIQUE.CD_RUBRIQUE = HQLOCAT.CRUB
WHERE        (HREVIS.CORG = '11')
AND P_RUBRIQUE.CD_SOUS_REG_ELTFAC = 'LOY'
AND GETDATE() BETWEEN HQLOCAT.DDEB AND HQLOCAT.DFIN