CREATE TABLE [dbo].[ACCES_POLE_IMMEUBLE] (
    [CODE_PROPRIETAIRE] VARCHAR (10) NULL,
    [NOM_PROPRIETAIRE]  VARCHAR (50) NULL,
    [CODE_IMMEUBLE]     VARCHAR (10) NULL,
    [NOM_IMMEUBLE]      VARCHAR (50) NULL,
    [POLE_GESTION]      VARCHAR (50) NULL
);

