CREATE TABLE [dbo].[D_BAIL] (
    [DT_REF]                      DATETIME        NULL,
    [PK_BAIL]                     INT             NOT NULL,
    [FK_LOCATAIRE]                INT             NULL,
    [FK_PROPRIETAIRE]             INT             NULL,
    [FK_MANDAT_GERANCE]           INT             NULL,
    [FK_IMMEUBLE]                 INT             NULL,
    [CD_ORIGINE]                  VARCHAR (5)     NULL,
    [CD_SOCIETE]                  VARCHAR (4)     NULL,
    [CD_MANDAT_GERANCE]           VARCHAR (16)    NULL,
    [NM_MANDAT_GERANCE]           NUMERIC (16)    NULL,
    [CD_BAIL]                     VARCHAR (20)    NULL,
    [NM_BAIL]                     NUMERIC (15)    NULL,
    [CD_IMMEUBLE]                 VARCHAR (4)     NULL,
    [NM_IMMEUBLE]                 INT             NULL,
    [CD_LOCATAIRE]                VARCHAR (14)    NULL,
    [NM_LOCATAIRE]                NUMERIC (7)     NULL,
    [CD_STATUT_OCCUPANT]          VARCHAR (3)     NULL,
    [LB_STATUT_OCCUPANT]          VARCHAR (30)    NULL,
    [CD_USAGE_BAIL]               VARCHAR (6)     NULL,
    [LB_USAGE_BAIL]               VARCHAR (60)    NULL,
    [CD_NATURE_BAIL]              VARCHAR (4)     NULL,
    [LB_NATURE_BAIL]              VARCHAR (60)    NULL,
    [DT_SIGNATURE]                DATETIME        NULL,
    [DT_PREMIER_BAIL]             DATETIME        NULL,
    [DT_EFFET]                    DATETIME        NULL,
    [DT_EXPIRATION]               DATETIME        NULL,
    [NB_MOIS_PREAVIS]             INT             NULL,
    [DT_ENTREE]                   DATETIME        NULL,
    [DT_CONGE]                    DATETIME        NULL,
    [DT_SORTIE]                   DATETIME        NULL,
    [DT_PREMIERE_ASSOCIATION_LOT] DATETIME        NULL,
    [DUREE_AN]                    INT             NULL,
    [DUREE_MOIS]                  INT             NULL,
    [LB_DUREE]                    VARCHAR (15)    NULL,
    [DUR_MINIMUM_BAIL_MOIS]       INT             NULL,
    [CD_LOT_PRINCIPAL]            VARCHAR (4)     NULL,
    [NM_LOT_PRINCIPAL]            INT             NULL,
    [CD_TYPE_LOT_PRL]             VARCHAR (4)     NULL,
    [LB_TYPE_LOT_PRL]             VARCHAR (30)    NULL,
    [CD_USAGE_LOT_PRL]            VARCHAR (6)     NULL,
    [LB_USAGE_LOT_PRL]            VARCHAR (60)    NULL,
    [ETAGES]                      VARCHAR (40)    NULL,
    [CD_ORIGINE_CONGE]            VARCHAR (4)     NULL,
    [LB_ORIGINE_CONGE]            VARCHAR (60)    NULL,
    [CD_NON_RELANCE]              VARCHAR (3)     NULL,
    [LB_NON_RELANCE]              VARCHAR (30)    NULL,
    [IND_CONTENTIEUX]             VARCHAR (1)     NULL,
    [CD_TERME]                    VARCHAR (1)     NULL,
    [LB_TERME]                    VARCHAR (8)     NULL,
    [CD_FREQUENCE_QUITTANCEMENT]  VARCHAR (2)     NULL,
    [CD_MODE_REVISION]            VARCHAR (10)    NULL,
    [CD_FREQUENCE_REVISION]       VARCHAR (2)     NULL,
    [DT_PROCHAINE_REVISION]       DATETIME        NULL,
    [CD_CHARGES_GRATUITES]        VARCHAR (1)     NULL,
    [MT_DG_PRINCIPAL]             NUMERIC (12, 2) NULL,
    [MT_DG_ANNEXE]                NUMERIC (12, 2) NULL,
    [NB_MOIS_DG]                  INT             NULL,
    [IND_DG_REVISABLE]            VARCHAR (1)     NULL,
    [IND_BAIL_SOUMIS_TVA]         VARCHAR (1)     NULL,
    [CD_TYPE_CAUTION]             VARCHAR (4)     NULL,
    [LB_TYPE_CAUTION]             VARCHAR (60)    NULL,
    [DT_DEBUT_CAUTION]            DATETIME        NULL,
    [DT_FIN_CAUTION]              DATETIME        NULL,
    [DUREE_CAUTION_MOIS]          INT             NULL,
    [MT_CAUTION]                  NUMERIC (12, 2) NULL,
    [IND_CAUTION_REVISABLE]       VARCHAR (1)     NULL,
    [DT_DEBUT_FRANCHISE]          DATETIME        NULL,
    [DT_FIN_FRANCHISE]            DATETIME        NULL,
    [DUREE_FRANCHISE_MOIS]        INT             NULL,
    [IND_GROS_TRAVAUX]            VARCHAR (1)     NULL,
    [ANNEE_CA]                    INT             NULL,
    [MT_CA]                       NUMERIC (13, 2) NULL,
    [DT_TRIEN_POT_1]              DATETIME        NULL,
    [DT_TRIEN_POT_2]              DATETIME        NULL,
    [DT_TRIEN_POT_3]              DATETIME        NULL,
    [DT_TRIEN_POT_4]              DATETIME        NULL,
    [DT_TRIEN_POT_5]              DATETIME        NULL,
    [DT_TRIEN_POT_6]              DATETIME        NULL,
    [DT_TRIEN_POT_7]              DATETIME        NULL,
    [DT_PRCH_TRIEN_POT]           DATETIME        NULL,
    [DT_RISQUE_CPLT_BAIL]         DATETIME        NULL,
    [DT_RISQUE]                   DATETIME        NULL,
    [PC_RECUP_TF]                 NUMERIC (9, 2)  NULL,
    [PC_RECUP_HO]                 NUMERIC (9, 2)  NULL,
    [PC_RECUP_TB]                 NUMERIC (9, 2)  NULL,
    [PC_RECUP_AS]                 NUMERIC (9, 2)  NULL,
    [PC_RECUP_605]                NUMERIC (9, 2)  NULL,
    [PC_RECUP_606]                NUMERIC (9, 2)  NULL,
    [DT_FIN]                      DATETIME        NULL,
    [CHEMIN_BAIL]                 NVARCHAR (2000) NULL,
    [MT_LOYER_BASE]               NUMERIC (13, 2) NULL,
    [MT_DG_BASE]                  NUMERIC (13, 2) NULL,
    [COMMENTAIRES]                VARCHAR (1074)  NULL,
    [PC_RECUP_TOM]                NUMERIC (9, 2)  NULL,
    CONSTRAINT [PK_D_BAIL_1] PRIMARY KEY CLUSTERED ([PK_BAIL] ASC)
);

