CREATE TABLE [dbo].[D_MANDAT_GERANCE] (
    [DT_REF]                       DATETIME        NULL,
    [PK_MANDAT_GERANCE]            INT             NOT NULL,
    [FK_PROPRIETAIRE]              INT             NULL,
    [FK_IMMEUBLE]                  INT             NULL,
    [CD_ORIGINE]                   VARCHAR (5)     NULL,
    [CD_SOCIETE]                   VARCHAR (4)     NULL,
    [CD_MANDAT]                    VARCHAR (16)    NULL,
    [NM_MANDAT]                    NUMERIC (16)    NULL,
    [CD_IMMEUBLE]                  VARCHAR (4)     NULL,
    [NM_IMMEUBLE]                  INT             NULL,
    [CD_PROPRIETAIRE]              VARCHAR (14)    NULL,
    [NM_PROPRIETAIRE]              NUMERIC (16)    NULL,
    [DT_DEBUT_GESTION]             DATE            NULL,
    [DT_FIN_GESTION]               DATE            NULL,
    [IND_MANDAT_ACTIF]             VARCHAR (1)     NULL,
    [DT_CLOTURE_COMPTES]           DATE            NULL,
    [CD_GESTIONNAIRE]              INT             NULL,
    [NOM_GESTIONNAIRE]             VARCHAR (60)    NULL,
    [CD_GROUPE]                    INT             NULL,
    [LB_GROUPE]                    VARCHAR (60)    NULL,
    [PRORATA_TVA]                  NUMERIC (17, 2) NULL,
    [IND_TOTALITE_TVA]             VARCHAR (1)     NULL,
    [IND_TAXE_ADDITIONNELLE]       VARCHAR (1)     NULL,
    [IND_DEDUCTION_REVENU_FONCIER] VARCHAR (10)    NULL,
    [IND_PRORATA_QUITTANCE]        VARCHAR (1)     NULL,
    [IND_EDITION_BDX_ENCAISSEMENT] VARCHAR (1)     NULL,
    [DT_TERME_DERN_QUITTANCEMENT]  DATE            NULL,
    [MT_FRAIS_DOSSIER]             NUMERIC (13, 2) NULL,
    [MT_FRAIS_RELANCE_SIMPLE]      NUMERIC (13, 2) NULL,
    [MT_FRAIS_RELANCE_RECOMMANDEE] NUMERIC (13, 2) NULL,
    [CD_FREQUENCE_REDDITION]       INT             NULL,
    [NM_MOIS_FIN_REDDITION]        INT             NULL,
    [IND_VIREMENT_AUTO]            VARCHAR (1)     NULL,
    [IND_ACOMPTE_PROPRIETAIRE]     VARCHAR (2)     NULL,
    [CD_FREQUENCE_HONORAIRES]      INT             NULL,
    [NM_MOIS_FIN_HONORAIRES]       INT             NULL,
    [CD_TYPE_COMPTABILITE]         VARCHAR (4)     NULL,
    [LB_TYPE_COMPTABILITE]         VARCHAR (64)    NULL,
    [CD_TECHNICIEN]                INT             NULL,
    [NOM_TECHNICIEN]               VARCHAR (60)    NULL,
    [IND_MANDAT_AXA]               VARCHAR (1)     NULL,
    [CD_IMMEUBLE_AXA]              VARCHAR (60)    NULL,
    [OPAQUE]                       VARCHAR (1)     NULL,
    CONSTRAINT [PK_D_MANDAT_GERANCE_1] PRIMARY KEY CLUSTERED ([PK_MANDAT_GERANCE] ASC)
);

