CREATE TABLE [dbo].[D_TEMPS] (
    [PK_TEMPS]                  DATETIME     NOT NULL,
    [CD_MOIS]                   VARCHAR (7)  NULL,
    [NM_MOIS]                   INT          NULL,
    [LB_MOIS]                   VARCHAR (10) NULL,
    [LBC_MOIS]                  VARCHAR (8)  NULL,
    [LBL_MOIS]                  VARCHAR (15) NULL,
    [CD_TRIMESTRE]              VARCHAR (6)  NULL,
    [NM_TRIMESTRE]              INT          NULL,
    [LB_TRIMESTRE]              VARCHAR (11) NULL,
    [LBC_TRIMESTRE]             VARCHAR (8)  NULL,
    [LBL_TRIMESTRE]             VARCHAR (16) NULL,
    [CD_SEMESTRE]               VARCHAR (6)  NULL,
    [NM_SEMESTRE]               INT          NULL,
    [LB_SEMESTRE]               VARCHAR (50) NULL,
    [LBC_SEMESTRE]              VARCHAR (15) NULL,
    [LBL_SEMESTRE]              VARCHAR (15) NULL,
    [CD_ANNEE]                  VARCHAR (4)  NULL,
    [NM_ANNEE]                  INT          NULL,
    [IND_DERNIERE_ALIMENTATION] VARCHAR (1)  NULL,
    [IND_MOIS_ACTUEL]           VARCHAR (1)  NULL,
    [IND_MOIS_DERNIER]          VARCHAR (1)  NULL,
    [IND_TRIMESTRE_ACTUEL]      VARCHAR (1)  NULL,
    [IND_TRIMESTRE_DERNIER]     VARCHAR (1)  NULL,
    [IND_SEMESTRE_ACTUEL]       VARCHAR (1)  NULL,
    [IND_SEMESTRE_DERNIER]      VARCHAR (1)  NULL,
    [IND_ANNEE_ACTUELLE]        VARCHAR (1)  NULL,
    [IND_ANNEE_DERNIERE]        VARCHAR (1)  NULL,
    CONSTRAINT [PK_D_TEMPS] PRIMARY KEY CLUSTERED ([PK_TEMPS] ASC)
);

