CREATE TABLE [dbo].[F_ETAT_LOCATIF] (
    [DT_REF]                          DATETIME        NULL,
    [PK_ETAT_LOCATIF]                 INT             IDENTITY (1, 1) NOT NULL,
    [PK_TEMPS]                        DATETIME        NULL,
    [PK_LOT]                          INT             NULL,
    [FK_PROPRIETAIRE]                 INT             NULL,
    [FK_MANDAT_GERANCE]               INT             NULL,
    [FK_IMMEUBLE]                     INT             NULL,
    [FK_BAIL]                         INT             NULL,
    [FK_LOCATAIRE]                    INT             NULL,
    [CMANDAT]                         VARCHAR (16)    NULL,
    [CORG]                            VARCHAR (4)     NULL,
    [CAGENCE]                         VARCHAR (4)     NULL,
    [CGROUPE]                         INT             NULL,
    [CIMMEUB]                         INT             NULL,
    [CLOCAL]                          INT             NULL,
    [OCC]                             INT             NULL,
    [CCOMPTE]                         VARCHAR (22)    NULL,
    [NOBAIL]                          INT             NULL,
    [OCC_PREC]                        INT             NULL,
    [CCOMPTE_PREC]                    VARCHAR (22)    NULL,
    [NOBAIL_PREC]                     INT             NULL,
    [OCC_SUIV]                        INT             NULL,
    [CCOMPTE_SUIV]                    VARCHAR (22)    NULL,
    [NOBAIL_SUIV]                     INT             NULL,
    [IND_LOT_PRINCIPAL]               VARCHAR (1)     NULL,
    [CD_STATUT]                       VARCHAR (1)     NULL,
    [LB_STATUT]                       VARCHAR (6)     NULL,
    [DT_DEBUT_STATUT]                 DATETIME        NULL,
    [DT_FIN_STATUT]                   DATETIME        NULL,
    [CD_SOCIETE_PRECEDENTE]           VARCHAR (4)     NULL,
    [NM_MANDAT_PRECEDENT]             INT             NULL,
    [CD_MANDAT_PRECEDENT]             VARCHAR (16)    NULL,
    [NM_BAIL_PRECEDENT]               NUMERIC (20)    NULL,
    [CD_BAIL_PRECEDENT]               VARCHAR (20)    NULL,
    [NOM_LOCATAIRE_PRECEDENT]         VARCHAR (76)    NULL,
    [DT_ENTREE_LOCATAIRE_PRECEDENT]   DATETIME        NULL,
    [DT_SORTIE_LOCATAIRE_PRECEDENT]   DATETIME        NULL,
    [VAL_SURFACE_TOTALE]              NUMERIC (13, 2) NULL,
    [VAL_SURFACE_LOUEE]               NUMERIC (13, 2) NULL,
    [VAL_SURFACE_VACANTE]             NUMERIC (13, 2) NULL,
    [VAL_SURF_CORRIGEE_TOTALE]        NUMERIC (13, 2) NULL,
    [VAL_SURF_CORRIGEE_LOUEE]         NUMERIC (13, 2) NULL,
    [VAL_SURF_CORRIGEE_VACANTE]       NUMERIC (13, 2) NULL,
    [NB_LOTS_TOTAL]                   INT             NULL,
    [NB_LOTS_LOUES]                   INT             NULL,
    [NB_LOTS_VANCATS]                 INT             NULL,
    [NB_PARKINGS]                     INT             NULL,
    [NB_PARKINGS_LOUES]               INT             NULL,
    [NB_PARKINGS_VACANTS]             INT             NULL,
    [NB_EMPLACEMENTS_PARKING]         INT             NULL,
    [NB_EMPLACEMENTS_PARKING_LOUES]   INT             NULL,
    [NB_EMPLACEMENTS_PARKING_VACANTS] INT             NULL,
    [MT_LOYER_FACIAL]                 NUMERIC (13, 2) NULL,
    [MT_LOYER_ACTUEL]                 NUMERIC (13, 2) NULL,
    [MT_CHARGES]                      NUMERIC (13, 2) NULL,
    [MT_DG]                           NUMERIC (13, 2) NULL,
    [DT_RISQUE]                       DATETIME        NULL,
    [DT_INDICE_INITIAL]               DATETIME        NULL,
    [VAL_INDICE_INITIAL]              NUMERIC (20, 5) NULL,
    [LB_INDICE_INITIAL]               VARCHAR (20)    NULL,
    [DT_INDICE_ACTUEL]                DATETIME        NULL,
    [VAL_INDICE_ACTUEL]               NUMERIC (20, 5) NULL,
    [LB_INDICE_ACTUEL]                VARCHAR (20)    NULL,
    [DT_PROCHAIN_INDICE]              DATETIME        NULL,
    [VAL_PROCHAIN_INDICE]             NUMERIC (20, 5) NULL,
    [LB_PROCHAIN_INDICE]              VARCHAR (20)    NULL,
    [DT_REVISION_PRECEDENTE]          DATETIME        NULL,
    [DT_PROCHAINE_REVISION]           DATETIME        NULL,
    [MT_LOYER_FRANCHISE]              NUMERIC (13, 2) NULL,
    [MT_PALIER]                       NUMERIC (13, 2) NULL,
    [CD_INDICE_INITIAL]               INT             NULL,
    [CD_INDICE_ACTUEL]                INT             NULL,
    [CD_PROCHAIN_INDICE]              INT             NULL,
    [CD_INDICE_REVISION]              VARCHAR (10)    NULL,
    [MT_LOYER_ACTUEL_FACTURABLE]      NUMERIC (13, 2) NULL,
    CONSTRAINT [PK_F_ETAT_LOCATIF] PRIMARY KEY CLUSTERED ([PK_ETAT_LOCATIF] ASC)
);

