

CREATE VIEW [dbo].[V_D_PROPRIETAIRE]
AS
SELECT     GETDATE() AS DT_REF, TIERS.PK_TIERS AS PK_PROPRIETAIRE, 'ESTIA' AS CD_ORIGINE, TIERS.CTIERS AS CD_PROPRIETAIRE, 
                      CASE WHEN ISNUMERIC(TIERS.CTIERS) <> 0 THEN CONVERT(NUMERIC(14, 0), TIERS.CTIERS) END AS NM_PROPRIETAIRE, 
                      TIERS.CQC AS CD_QUALITE_CIVILE, QC.LQC AS LB_QUALITE_CIVILE, TIERS.LTIERS AS NOM_PROPRIETAIRE, 
                      TIERS.PRENOM AS PRENOM_PROPRIETAIRE, CONVERT(VARCHAR(30), NULL) AS CPLT_NOM_PROPRIETAIRE, TIERS.RUE AS ADRLGN1, 
                      TIERS.COMMUNE AS ADRLGN2, CONVERT(VARCHAR(76), NULL) AS ADRLGN3, TIERS.CPOS AS CODPOS, TIERS.BDIS AS VILLE, 
                      TIERS.TEL AS TELEPHONE, TIERS.TELCONT AS TELEPHONE_2, TIERS.TELECOP AS FAX, TIERS.POUM AS CD_TYPE_TIERS, 
                      CASE TIERS.POUM WHEN 'P' THEN 'Personne physique' ELSE 'Personne morale' END AS LB_TYPE_TIERS, TIERS.CAPE AS CODE_APE, 
                      APE.LAPE AS LIBELLE_APE, TIERS.INSEE AS REF_EXTERIEURE, CONVERT(VARCHAR(3), NULL) AS SOCIETE_IRIS, 
                      WPC.CTYPROPR AS CD_TYPE_SOCIETE, WPC.LTYPROPR AS LB_TYPE_SOCIETE
FROM         dbo.ESTIA_TIERS AS TIERS LEFT OUTER JOIN
                      dbo.WRK_PRO_COMPTABILITE AS WPC ON TIERS.CTYPTIERS = WPC.CTYPTIERS AND TIERS.CTIERS = WPC.CTIERS LEFT OUTER JOIN
                      dbo.ESTIA_APE AS APE ON TIERS.CAPE = APE.CAPE LEFT OUTER JOIN
                      dbo.ESTIA_QC AS QC ON TIERS.CQC = QC.CQC
WHERE     EXISTS
                          (SELECT     PK_MANPROP, FK_MANGES, FK_TIERS, CMANDAT, CQUALPR, CTYPTIERS, CTIERS, PARTPROP, PARTREP, REGISTRE, REPRES, TRIG, 
                                                   CTIERSI, CTYPTIERSI, CORG, CCOMPTE, NOBAIL, CONVOC, NODOMR, NODOMA, DDEB, DFIN, MIGCOMPT, SUIVIASSU, RK
                            FROM          dbo.ESTIA_MANPROP AS MANPROP
                            WHERE      (CTYPTIERS = TIERS.CTYPTIERS) AND (CTIERS = TIERS.CTIERS))
AND convert(numeric(13,0), TIERS.CTIERS) NOT IN ('13223', '24977', '24979', '24980', '25336', '25998')