








CREATE VIEW [dbo].[V_D_BAIL]
AS
SELECT     GETDATE() AS DT_REF, LOCATION.PK_LOCATION AS PK_BAIL, TIERS.PK_TIERS AS FK_LOCATAIRE, MANPROP.FK_TIERS AS FK_PROPRIETAIRE, 
                      WGM.FK_MANGES AS FK_MANDAT_GERANCE, LOCATION.FK_GROUPE AS FK_IMMEUBLE, 'ESTIA' AS CD_ORIGINE, LOCATION.CORG AS CD_SOCIETE, 
                      WGM.CMANDAT AS CD_MANDAT_GERANCE, CASE WHEN ISNUMERIC(WGM.CMANDAT) <> 0 THEN CONVERT(NUMERIC(16, 0), WGM.CMANDAT) 
                      END AS NM_MANDAT_GERANCE, LOCATION.CCOMPTE + '/' + REPLACE(STR(LOCATION.NOBAIL, 2, 0), ' ', '0') AS CD_BAIL, 
                      CASE WHEN ISNUMERIC(LOCATION.CCOMPTE) <> 0 THEN CONVERT(NUMERIC(15, 0), LOCATION.CCOMPTE) 
                      * 100 + LOCATION.NOBAIL END AS NM_BAIL, REPLACE(STR(LOCATION.CGROUPE, 4, 0), ' ', '0') AS CD_IMMEUBLE, 
                      LOCATION.CGROUPE AS NM_IMMEUBLE, LIENLOC.CTIERS AS CD_LOCATAIRE, CASE WHEN ISNUMERIC(LIENLOC.CTIERS) 
                      <> 0 THEN CONVERT(NUMERIC(7, 0), LIENLOC.CTIERS) END AS NM_LOCATAIRE, CONVERT(VARCHAR(3), NULL) AS CD_STATUT_OCCUPANT, 
                      CONVERT(VARCHAR(30), NULL) AS LB_STATUT_OCCUPANT, PLOCAL.CUSALOC AS CD_USAGE_BAIL, PU.LB_USAGE AS LB_USAGE_BAIL, 
                      LOCATION.CBAIL AS CD_NATURE_BAIL, PNB.LB_NATURE_BAIL, 
					  -- Debut modif MNA 280318
                      --CASE WHEN WH.DT_SIGNATURE >= '1900-01-01' THEN WH.DT_SIGNATURE END AS DT_SIGNATURE 
					  CASE WHEN LOCATION.DATENTBAIL >= '1900-01-01' THEN LOCATION.DATENTBAIL END AS DT_SIGNATURE, 
					  WH.DT_PREMIER_BAIL,
					  -- WH.DT_ENTREE AS DT_EFFET/*WH.DT_EFFET*/, 
					  CASE WHEN DATEPART(YEAR, LOCATION.DATEFFET) < 1900 THEN '19000101' ELSE LOCATION.DATEFFET END AS DT_EFFET,
                      ISNULL(WH.DT_EXPIRATION, DATEADD(day, - 1, DATEADD(month, LOCATION.DURBAIL, LOCATION.DATEFFET))) AS DT_EXPIRATION, 
                      LOCATION.DURPREAV AS NB_MOIS_PREAVIS, CASE WHEN DATEPART(YEAR, LOCATION.DATEFFET) < 1900 THEN '19000101' ELSE LOCATION.DATEFFET END AS DT_ENTREE/*WH.DT_ENTREE*/, LOCATION.DATFIN AS DT_FIN, LOCATION.DATSORCONT AS DT_CONGE, LOCATION.DATSORPREV AS DT_SORTIE, 
					  -- Fin modif MNA 280318
                      WLLOT.DT_PREMIERE_ASSOCIATION_LOT, (LOCATION.DURBAIL - LOCATION.DURBAIL % 12) / 12 AS DUREE_AN, 
                      LOCATION.DURBAIL % 12 AS DUREE_MOIS, 
                      CASE WHEN LOCATION.DURBAIL >= 12 THEN REPLACE(STR((LOCATION.DURBAIL - LOCATION.DURBAIL % 12) / 12, 2, 0), ' ', '0') 
                      ELSE '' END + CASE WHEN LOCATION.DURBAIL % 12 <> 0 THEN REPLACE(STR(LOCATION.DURBAIL % 12, 2, 0), ' ', '0') ELSE '' END AS LB_DUREE, 
                      ISNULL(LOCATION.PFERME, 0) AS DUR_MINIMUM_BAIL_MOIS, REPLACE(STR(LOCATION.CLOCAL, 4, 0), ' ', '0') AS CD_LOT_PRINCIPAL, 
                      LOCATION.CLOCAL AS NM_LOT_PRINCIPAL, LOCATION.CTYPLOC AS CD_TYPE_LOT_PRL, PTL.LB_TYPE_LOT AS LB_TYPE_LOT_PRL, 
                      PLOCAL.CUSALOC AS CD_USAGE_LOT_PRL, PU.LB_USAGE AS LB_USAGE_LOT_PRL, PU.CD_USAGE_SALEFORCE, WBE.ETAGES, 
                      LOCATION.CMOTDDE AS CD_ORIGINE_CONGE, MOTDDE.LMOTDDE AS LB_ORIGINE_CONGE, CONVERT(VARCHAR(3), NULL) AS CD_NON_RELANCE, 
                      CONVERT(VARCHAR(30), NULL) AS LB_NON_RELANCE, ISNULL(WD.IND_CONTENTIEUX, 'N') AS IND_CONTENTIEUX, 
                      CASE WHEN LOCATION.TERME <> 0 THEN 'A' ELSE 'E' END AS CD_TERME, 
                      CASE WHEN LOCATION.TERME <> 0 THEN 'A échoir' ELSE 'Echu' END AS LB_TERME, REPLACE(STR(LOCATION.PERIOD, 2, 0), ' ', '0') 
                      AS CD_FREQUENCE_QUITTANCEMENT, CASE WHEN LEN(LOCATION.CNUMI) > 0 THEN LOCATION.CNUMI ELSE 'NR' END AS CD_MODE_REVISION, 
                      REPLACE(STR(LOCATION.PEREVISION, 2, 0), ' ', '0') AS CD_FREQUENCE_REVISION, LOCATION.DREVISION AS DT_PROCHAINE_REVISION, 
                      CONVERT(VARCHAR(1), NULL) AS CD_CHARGES_GRATUITES, ISNULL(WBD.MT_DG_PRINCIPAL, 0) AS MT_DG_PRINCIPAL, 
                      ISNULL(WLH.MT_DG_PRINCIPAL, 0) AS MT_DG_PRINCIPAL_TARIFS, ISNULL(WBD.MT_DG_ANNEXE, 0) AS MT_DG_ANNEXE, 
                      ISNULL(WLH.MT_DG_ANNEXE, 0) AS MT_DG_ANNEXE_TARIFS, LOCATION.PRCCA AS NB_MOIS_DG, ISNULL(WLH.IND_DG_REVISABLE, '0') 
                      AS IND_DG_REVISABLE, CASE WHEN LOCATION.LTVA <> 0 THEN 'O' ELSE 'N' END AS IND_BAIL_SOUMIS_TVA, WLL.CD_TYPE_CAUTION, 
                      WLL.LB_TYPE_CAUTION, WLL.DT_DEBUT_CAUTION, WLL.DT_FIN_CAUTION, WLL.DUREE_CAUTION_MOIS, ISNULL(WLL.IND_REVISABLE, 'N') 
                      AS IND_CAUTION_REVISABLE, WLL.MT_CAUTION, WLH.DT_DEBUT_FRANCHISE, WLH.DT_FIN_FRANCHISE, WLH.DUREE_FRANCHISE_MOIS, 
                      ISNULL(WLN.IND_GROS_TRAVAUX, 'N') AS IND_GROS_TRAVAUX, WLCA.ANNEE_CA, WLCA.MT_CA, WH.DT_TRIEN_POT_1, WH.DT_TRIEN_POT_2, 
                      WH.DT_TRIEN_POT_3, WH.DT_TRIEN_POT_4, WH.DT_TRIEN_POT_5, WH.DT_TRIEN_POT_6, WH.DT_TRIEN_POT_7, WH.DT_PRCH_TRIEN_POT, 
                      WH.DT_RISQUE_CPLT_BAIL, WH.DT_RISQUE, WLN.PC_RECUP_TF, WLN.PC_RECUP_HO, WLN.PC_RECUP_TB, WLN.PC_RECUP_AS, 
                      WLN.PC_RECUP_605, WLN.PC_RECUP_606, WLN.PC_RECUP_TOM,
					  '\\viveris.local\VIVERIS-DFS\IMMO\DOCS IMMEUBLES\GED\' + ltrim(rtrim(P_IMMEUBLE.LB_IMMEUBLE_GED)) + '\9 situation locative\9.2 Baux et avenants en cours\'
					  + RIGHT(LOCATION.CCOMPTE, 4) + CONVERT(VARCHAR(2), LOCATION.NOBAIL) + '.pdf' AS CHEMIN_BAIL, COMMENT_ AS COMMENTAIRES
FROM         dbo.ESTIA_LOCATION AS LOCATION LEFT OUTER JOIN
                      dbo.P_NATURE_BAIL AS PNB ON PNB.CD_NATURE_BAIL = LOCATION.CBAIL INNER JOIN
                      dbo.ESTIA_PLOCAL AS PLOCAL ON PLOCAL.CORG = LOCATION.CORG AND PLOCAL.CAGENCE = LOCATION.CAGENCE AND 
                      PLOCAL.CGROUPE = LOCATION.CGROUPE AND PLOCAL.CIMMEUB = LOCATION.CIMMEUB AND 
                      PLOCAL.CPLOCAL = LOCATION.CLOCAL LEFT OUTER JOIN
                      dbo.WRK_LOCATION_NEGOCH AS WLN ON LOCATION.CORG = WLN.CORG AND LOCATION.CCOMPTE = WLN.CCOMPTE AND 
                      LOCATION.NOBAIL = WLN.NOBAIL LEFT OUTER JOIN
                      dbo.WRK_BAIL_DG AS WBD ON LOCATION.FK_BAIL = WBD.PK_BAIL LEFT OUTER JOIN
                      dbo.WRK_BAIL_ETAGES AS WBE ON LOCATION.FK_BAIL = WBE.PK_BAIL LEFT OUTER JOIN
                      dbo.WRK_LOCATION_LOCAL AS WLLOT ON LOCATION.NOBAIL = WLLOT.NOBAIL AND LOCATION.CORG = WLLOT.CORG AND 
                      LOCATION.CCOMPTE = WLLOT.CCOMPTE LEFT OUTER JOIN
                      dbo.WRK_DPROCTX AS WD ON LOCATION.NOBAIL = WD.NOBAIL AND LOCATION.CORG = WD.CORG AND 
                      LOCATION.CCOMPTE = WD.CCOMPTE LEFT OUTER JOIN
                      dbo.WRK_LOCATION_HLOYCA AS WLCA ON LOCATION.CORG = WLCA.CORG AND LOCATION.NOBAIL = WLCA.NOBAIL AND 
                      LOCATION.CCOMPTE = WLCA.CCOMPTE LEFT OUTER JOIN
                      dbo.WRK_LOCATION_LCAUTION AS WLL ON LOCATION.CORG = WLL.CORG AND LOCATION.CCOMPTE = WLL.CCOMPTE AND 
                      LOCATION.NOBAIL = WLL.NOBAIL LEFT OUTER JOIN
                      dbo.WRK_LOCATION_HQLOCAT AS WLH ON LOCATION.CORG = WLH.CORG AND LOCATION.CCOMPTE = WLH.CCOMPTE AND 
                      LOCATION.NOBAIL = WLH.NOBAIL LEFT OUTER JOIN
                      dbo.ESTIA_MOTDDE AS MOTDDE ON LOCATION.CMOTDDE = MOTDDE.CMOTDDE LEFT OUTER JOIN
                      dbo.P_TYPE_LOT AS PTL ON PLOCAL.CTYPLOG = PTL.CD_TYPE_LOT LEFT OUTER JOIN
                      dbo.P_USAGE AS PU ON PLOCAL.CUSALOC = PU.CD_USAGE LEFT OUTER JOIN
                      dbo.ESTIA_LIENLOC AS LIENLOC ON LIENLOC.CORG = LOCATION.CORG AND LIENLOC.CCOMPTE = LOCATION.CCOMPTE AND 
                      LIENLOC.RK = 1 LEFT OUTER JOIN
                      dbo.ESTIA_TIERS AS TIERS ON TIERS.CTYPTIERS = LIENLOC.CTYPTIERS AND TIERS.CTIERS = LIENLOC.CTIERS LEFT OUTER JOIN
                      dbo.WRK_GROUPE_MANGES AS WGM ON WGM.CORG = LOCATION.CORG AND WGM.CAGENCE = LOCATION.CAGENCE AND 
                      WGM.CGROUPE = LOCATION.CGROUPE LEFT OUTER JOIN
                      dbo.ESTIA_MANPROP AS MANPROP ON MANPROP.CMANDAT = WGM.CMANDAT AND MANPROP.RK = 1 LEFT OUTER JOIN
                      dbo.WRK_HQRBAIL AS WH ON WH.CORG = LOCATION.CORG AND WH.CCOMPTE = LOCATION.CCOMPTE AND 
                      WH.NOBAIL = LOCATION.NOBAIL LEFT OUTER JOIN
					  dbo.P_IMMEUBLE on P_IMMEUBLE.CD_SOCIETE = LOCATION.CORG AND P_IMMEUBLE.CD_AGENCE = LOCATION.CAGENCE
					  AND P_IMMEUBLE.NM_IMMEUBLE = LOCATION.CGROUPE
					  --LEFT OUTER JOIN dbo.P_COMPLEMENT_BAIL AS PCB ON '0000000'+PCB.NM_BAIL = LOCATION.CCOMPTE + '/' + REPLACE(STR(LOCATION.NOBAIL, 2, 0), ' ', '0')--PCB.PK_BAIL = LOCATION.PK_LOCATION
						LEFT OUTER JOIN 
						(
							SELECT * 
							FROM ESTIA_COMMENT
							WHERE NOFICH = 'LOCATION'
							AND SECTEUR = 'TEXTE'
						) COMMENT
						ON COMMENT.CLEFICH = LOCATION.CORG+LOCATION.CCOMPTE+CASE WHEN LEN(CONVERT(VARCHAR(2), LOCATION.NOBAIL)) = 1 THEN 
						'0'+ CONVERT(VARCHAR(2), LOCATION.NOBAIL) ELSE CONVERT(VARCHAR(2), LOCATION.NOBAIL) END
WHERE     (LOCATION.NOLOCAT = LOCATION.CONTLOC)