


CREATE VIEW [dbo].[V_D_MANDAT_GERANCE]
AS
SELECT     GETDATE() AS DT_REF, MANGES.PK_MANGES AS PK_MANDAT_GERANCE, MANPROP.FK_TIERS AS FK_PROPRIETAIRE, WMG.FK_GROUPE AS FK_IMMEUBLE, 
                      'ESTIA' AS CD_ORIGINE, MANGES.CORG AS CD_SOCIETE, MANGES.CMANDAT AS CD_MANDAT, CASE WHEN ISNUMERIC(MANGES.CMANDAT) 
                      <> 0 THEN CONVERT(NUMERIC(16, 0), MANGES.CMANDAT) END AS NM_MANDAT, REPLACE(STR(WMG.CGROUPE, 4, 0), ' ', '0') AS CD_IMMEUBLE, 
                      WMG.CGROUPE AS NM_IMMEUBLE, MANPROP.CTIERS AS CD_PROPRIETAIRE, CASE WHEN ISNUMERIC(MANPROP.CTIERS) <> 0 THEN CONVERT(NUMERIC(16, 0), 
                      MANPROP.CTIERS) END AS NM_PROPRIETAIRE, MANGES.DEFFET AS DT_DEBUT_GESTION, MANGES.DFINGEST AS DT_FIN_GESTION, 
                      CASE WHEN CONVERT(DATETIME, CONVERT(VARCHAR(10), GETDATE(), 103), 103) BETWEEN ISNULL(MANGES.DEFFET, '1900/01/01') AND 
                      ISNULL(MANGES.DFINGEST, '2999/01/01') THEN 'O' ELSE 'N' END AS IND_MANDAT_ACTIF, MANGES.DCLOTURE AS DT_CLOTURE_COMPTES, 
                      MANGES.CEMPLOY AS CD_GESTIONNAIRE, EMPLOY.LEMPLOY AS NOM_GESTIONNAIRE, MANGES.REMPLOY AS CD_GROUPE, 
                      REMPLOY.LEMPLOY AS LB_GROUPE, ISNULL(WMM.TAUXD, 0) AS PRORATA_TVA, CASE WHEN WMM.TAUXD = 100 THEN 'O' ELSE 'N' END AS IND_TOTALITE_TVA, 
                      CONVERT(VARCHAR(1), NULL) AS IND_TAXE_ADDITIONNELLE, MANGES.CTYPDECRF AS IND_DEDUCTION_REVENU_FONCIER, 'O' AS IND_PRORATA_QUITTANCE, 
                      CONVERT(VARCHAR(1), NULL) AS IND_EDITION_BDX_ENCAISSEMENT, CONVERT(DATE, NULL) AS DT_TERME_DERN_QUITTANCEMENT, CONVERT(NUMERIC(13, 
                      2), NULL) AS MT_FRAIS_DOSSIER, CONVERT(NUMERIC(13, 2), NULL) AS MT_FRAIS_RELANCE_SIMPLE, CONVERT(NUMERIC(13, 2), NULL) 
                      AS MT_FRAIS_RELANCE_RECOMMANDEE, MANGES.PERIOD AS CD_FREQUENCE_REDDITION, MANGES.MFINR AS NM_MOIS_FIN_REDDITION, 
                      CONVERT(VARCHAR(1), NULL) AS IND_VIREMENT_AUTO, MANGES.CALCULAC AS IND_ACOMPTE_PROPRIETAIRE, 
                      MANGES.HONOFREQ AS CD_FREQUENCE_HONORAIRES, MANGES.MFINH AS NM_MOIS_FIN_HONORAIRES,  
                      ORG.LORG AS LB_TYPE_COMPTABILITE, MANGES.TEMPLOY AS CD_TECHNICIEN, TEMPLOY.LEMPLOY AS NOM_TECHNICIEN, MANGES.PROVHT AS OPAQUE
FROM dbo.ESTIA_ORG AS ORG RIGHT OUTER JOIN
     dbo.ESTIA_MANGES AS MANGES ON ORG.CORG = MANGES.CORG LEFT OUTER JOIN
     dbo.ESTIA_EMPLOY AS REMPLOY ON MANGES.REMPLOY = REMPLOY.CEMPLOY LEFT OUTER JOIN
     dbo.ESTIA_EMPLOY AS TEMPLOY ON MANGES.TEMPLOY = TEMPLOY.CEMPLOY LEFT OUTER JOIN
     dbo.WRK_MANGES_MANTVA AS WMM ON MANGES.CMANDAT = WMM.CMANDAT LEFT OUTER JOIN
     dbo.ESTIA_EMPLOY AS EMPLOY ON MANGES.CEMPLOY = EMPLOY.CEMPLOY LEFT OUTER JOIN
     dbo.WRK_MANGES_GROUPE AS WMG ON WMG.CMANDAT = MANGES.CMANDAT LEFT OUTER JOIN
     dbo.ESTIA_MANPROP AS MANPROP ON MANPROP.CMANDAT = MANGES.CMANDAT AND MANPROP.RK = 1