





CREATE VIEW [dbo].[V_D_LOT]
AS
SELECT     GETDATE() AS DT_REF, LOCAL.PK_LOCAL AS PK_LOT, LOCAL.FK_GROUPE AS FK_IMMEUBLE, WGM.FK_MANGES AS FK_MANDAT_GERANCE, 
                      'ESTIA' AS CD_ORIGINE, LOCAL.CORG AS CD_SOCIETE, REPLACE(STR(LOCAL.CGROUPE, 4, 0), ' ', '0') AS CD_IMMEUBLE, 
                      LOCAL.CGROUPE AS NM_IMMEUBLE, REPLACE(STR(LOCAL.CLOCAL, 4, 0), ' ', '0') AS CD_LOT, LOCAL.CLOCAL AS NM_LOT, 
                      PLOCAL.CTYPLOG AS CD_TYPE_LOT, TYPLOG.LTYPLOG AS LB_TYPE_LOT, ISNULL(PLOCAL.CUSALOC, 'DI') AS CD_USAGE, ISNULL(USALOC.LUSALOC, 'Divers') AS LB_USAGE, 
                      PLOCAL.BAT AS CD_BATIMENT, PLOCAL.ESC AS CD_ESCALIER, 
                      CASE WHEN PLOCAL.ETAGE = 0 THEN 'RDC' WHEN PLOCAL.ETAGE < 0 THEN 'R' + CONVERT(VARCHAR(50), PLOCAL.ETAGE) 
                      ELSE 'R+' + CONVERT(VARCHAR(50), PLOCAL.ETAGE) END AS ETAGE, PLOCAL.ETAGE AS NM_ETAGE, PLOCAL.PORTE, 
                      TYPLOG.NBPIEC AS NB_PIECES, CASE WHEN PTL.NB_EMPLACEMENTS_PARKING > 0 THEN 0 ELSE ISNULL(WLS.SURF_HAB, 0) 
                      END AS VAL_SURFACE_REELLE, CASE WHEN PTL.NB_EMPLACEMENTS_PARKING > 0 THEN 0 ELSE ISNULL(WLS.SURF_COR, 0) 
                      END AS VAL_SURFACE_CORRIGEE, CASE WHEN PTL.NB_EMPLACEMENTS_PARKING > 0 THEN 1 ELSE 0 END AS NB_PARKINGS, 
                      ISNULL(PTL.NB_EMPLACEMENTS_PARKING, 0) AS NB_EMPLACEMENTS_PARKING, LOCAL.CORG AS CD_SOCIETE_GERANCE, 
                      WGM.CMANDAT AS CD_MANDAT_GERANCE, CASE WHEN ISNUMERIC(WGM.CMANDAT) <> 0 THEN CONVERT(NUMERIC(16, 0), WGM.CMANDAT) 
                      END AS NM_MANDAT_GERANCE, LOCAL.DEBLOC AS DT_DEBUT_EN_SERVICE, LOCAL.DFINML AS DT_FIN_EN_SERVICE, 
                      RTRIM(LEFT(LOCAL.CMOTVAC, 2)) AS CD_MOTIF_VACANCE, RTRIM(LEFT(MOTVAC.LMOTVAC, 30)) AS LB_MOTIF_VACANCE, 
                      ISNULL(WLH.MT_LOYER_MARCHE, 0) AS MT_LOYER_MARCHE, ISNULL(WLH.MT_CHARGES_MARCHE, 0) AS MT_CHARGES_MARCHE,
					  ISNULL(PU.CD_REG_USAGE, 'ACT') AS CD_REG_USAGE, ISNULL(PU.LB_REG_USAGE, 'Activité') AS LB_REG_USAGE
FROM         dbo.ESTIA_LOCAL AS LOCAL INNER JOIN
                      dbo.ESTIA_PLOCAL AS PLOCAL ON LOCAL.CORG = PLOCAL.CORG AND LOCAL.CAGENCE = PLOCAL.CAGENCE AND 
                      LOCAL.CGROUPE = PLOCAL.CGROUPE AND LOCAL.CIMMEUB = PLOCAL.CIMMEUB AND LOCAL.CLOCAL = PLOCAL.CPLOCAL INNER JOIN
                      dbo.WRK_LOCAL_SURFACE AS WLS ON LOCAL.CORG = WLS.CORG AND LOCAL.CAGENCE = WLS.CAGENCE AND 
                      LOCAL.CGROUPE = WLS.CGROUPE AND LOCAL.CIMMEUB = WLS.CIMMEUB AND LOCAL.CLOCAL = WLS.CLOCAL LEFT OUTER JOIN
                      dbo.ESTIA_MOTVAC AS MOTVAC ON LOCAL.CMOTVAC = MOTVAC.CMOTVAC LEFT OUTER JOIN
                      dbo.WRK_LOCAL_HQLOCAL AS WLH ON PLOCAL.CORG = WLH.CORG AND PLOCAL.CAGENCE = WLH.CAGENCE AND 
                      PLOCAL.CGROUPE = WLH.CGROUPE AND PLOCAL.CIMMEUB = WLH.CIMMEUB AND PLOCAL.CPLOCAL = WLH.CLOCAL LEFT OUTER JOIN
                      dbo.P_USAGE AS PU ON PLOCAL.CUSALOC = PU.CD_USAGE LEFT OUTER JOIN
                      dbo.ESTIA_USALOC AS USALOC ON PLOCAL.CUSALOC = USALOC.CUSALOC LEFT OUTER JOIN
                      dbo.ESTIA_TYPLOG AS TYPLOG ON PLOCAL.CTYPLOG = TYPLOG.CTYPLOG LEFT OUTER JOIN
                      dbo.P_TYPE_LOT AS PTL ON PLOCAL.CTYPLOG = PTL.CD_TYPE_LOT LEFT OUTER JOIN
                      dbo.WRK_GROUPE_MANGES AS WGM ON LOCAL.CORG = WGM.CORG AND LOCAL.CAGENCE = WGM.CAGENCE AND 
                      LOCAL.CGROUPE = WGM.CGROUPE