
CREATE VIEW [dbo].[V_D_RUBRIQUE]
AS
SELECT	GETDATE() AS DT_REF
	  , RUB.PK_RUB AS PK_RUBRIQUE
	  , 'ESTIA' AS ORIGINE
	  , '' AS CD_SOCIETE
	  , REPLACE(STR(RUB.CRUB, 3, 0), ' ', '0') AS CD_RUBRIQUE
	  , RUB.CRUB AS NM_RUBRIQUE
	  , RUB.LRUB AS LB_RUBRIQUE
	  , RUB.CNATRUB AS CD_NATURE_RUBRIQUE
	  , NATRUB.LNATRUB AS LB_NATURE_RUBRIQUE
	  , PR.IND_SURLOYER
	  , PR.IND_FRANCHISE_LOYER
FROM dbo.ESTIA_RUB AS RUB 
	LEFT OUTER JOIN dbo.P_RUBRIQUE AS PR ON RUB.CRUB = PR.CD_RUBRIQUE 
	LEFT OUTER JOIN dbo.ESTIA_NATRUB AS NATRUB ON RUB.CNATRUB = NATRUB.CNATRUB