CREATE VIEW [dbo].[V_D_LOCATAIRE]
AS
SELECT     GETDATE() AS DT_REF, TIERS.PK_TIERS AS PK_LOCATAIRE, 'ESTIA' AS CD_ORIGINE, TIERS.CTIERS AS CD_LOCATAIRE, 
                      CASE WHEN ISNUMERIC(TIERS.CTIERS) <> 0 THEN CONVERT(NUMERIC(14, 0), TIERS.CTIERS) END AS NM_LOCATAIRE, 
                      TIERS.CQC AS CD_QUALITE_CIVILE, QC.LQC AS LB_QUALITE_CIVILE, TIERS.LTIERS AS NOM_LOCATAIRE, TIERS.PRENOM AS PRENOM_LOCATAIRE, 
                      CONVERT(VARCHAR(30), NULL) AS CPLT_NOM_LOCATAIRE, TIERS.RUE AS ADRLGN1, TIERS.COMMUNE AS ADRLGN2, CONVERT(VARCHAR(76), NULL) 
                      AS ADRLGN3, TIERS.CPOS AS CODPOS, TIERS.BDIS AS VILLE, TIERS.TEL AS TELEPHONE, TIERS.TELCONT AS TELEPHONE_2, 
                      TIERS.TELECOP AS FAX, TIERS.POUM AS CD_TYPE_TIERS, 
                      CASE TIERS.POUM WHEN 'P' THEN 'Personne physique' ELSE 'Personne morale' END AS LB_TYPE_TIERS, TIERS.CAPE AS CODE_APE, 
                      APE.LAPE AS LIBELLE_APE, CONVERT(VARCHAR(15), NULL) AS CODE_NAF, CONVERT(VARCHAR(30), NULL) AS NOM_COMMERCIAL, 
                      CONVERT(VARCHAR(1), NULL) AS IND_LOYER_VARIABLE, CONVERT(NUMERIC(13, 2), NULL) AS MT_CA, CONVERT(NUMERIC(4, 0), NULL) 
                      AS ANNEE_CA, CONVERT(VARCHAR(5), NULL) AS CD_CLIENT, CASE TIERS.POUM WHEN 'P' THEN 'PH' ELSE 'MO' END AS CD_TYPE_PERSONNE_AXA
FROM         dbo.ESTIA_TIERS AS TIERS LEFT OUTER JOIN
                      dbo.ESTIA_APE AS APE ON TIERS.CAPE = APE.CAPE LEFT OUTER JOIN
                      dbo.ESTIA_QC AS QC ON TIERS.CQC = QC.CQC
WHERE     EXISTS
                          (SELECT     PK_LIENLOC
                            FROM          dbo.ESTIA_LIENLOC AS LIENLOC
                            WHERE      (CTYPTIERS = TIERS.CTYPTIERS) AND (CTIERS = TIERS.CTIERS))