CREATE TABLE [dbo].[CTRL_ESTIA_TMP] (
    [DATE_CTRL]            DATE          NOT NULL,
    [ANNEE]                VARCHAR (50)  NULL,
    [MOIS]                 VARCHAR (50)  NULL,
    [CODE_ERREUR]          VARCHAR (100) NULL,
    [MANDAT]               VARCHAR (50)  NULL,
    [NOM_CLIENT]           VARCHAR (50)  NULL,
    [BAIL]                 VARCHAR (50)  NULL,
    [LOT]                  VARCHAR (50)  NULL,
    [CONTRAT]              VARCHAR (50)  NULL,
    [OS]                   VARCHAR (50)  NULL,
    [BT]                   VARCHAR (50)  NULL,
    [PARAMETRAGE]          VARCHAR (50)  NULL,
    [NOM_TABLE]            VARCHAR (50)  NULL,
    [DESC_TABLE]           VARCHAR (50)  NULL,
    [NOM_COLONNE]          VARCHAR (50)  NULL,
    [DESC_COLONNE]         VARCHAR (50)  NULL,
    [TYPE_ERREUR]          VARCHAR (50)  NULL,
    [DESC_ERREUR]          VARCHAR (100) NULL,
    [VALEUR]               VARCHAR (50)  NULL,
    [DESC_VALEUR]          VARCHAR (100) NULL,
    [VALEUR_ANT]           VARCHAR (50)  NULL,
    [DESC_VALEUR_ANT]      VARCHAR (100) NULL,
    [VALEUR_ATTENDUE]      VARCHAR (50)  NULL,
    [DESC_VALEUR_ATTENDUE] VARCHAR (100) NULL,
    [RESP_ERREUR]          VARCHAR (50)  NULL,
    [DOMAINE]              VARCHAR (50)  NULL,
    [NB_ENVOI]             INT           NULL
);

