CREATE TABLE [dbo].[ESTIA_PLOCAL] (
    [PK_PLOCAL]          INT             IDENTITY (1, 1) NOT NULL,
    [FK_ORG]             INT             NULL,
    [FK_AGENCE]          INT             NULL,
    [FK_GROUPE]          INT             NULL,
    [FK_IMMEUB]          INT             NULL,
    [CORG]               VARCHAR (4)     NOT NULL,
    [CAGENCE]            VARCHAR (4)     NOT NULL,
    [CGROUPE]            INT             NOT NULL,
    [CIMMEUB]            INT             NOT NULL,
    [CPLOCAL]            INT             NOT NULL,
    [ESC]                VARCHAR (4)     NULL,
    [ETAGE]              INT             NULL,
    [SCORR]              NUMERIC (17, 2) NULL,
    [SHAB]               NUMERIC (17, 2) NULL,
    [CTYPLOG]            VARCHAR (6)     NULL,
    [CNATLOG]            VARCHAR (4)     NULL,
    [TEMPATRI]           VARCHAR (1)     NULL,
    [RUE]                VARCHAR (76)    NULL,
    [LIEUDIT]            VARCHAR (76)    NULL,
    [CPOS]               VARCHAR (10)    NULL,
    [CAVE]               VARCHAR (8)     NULL,
    [BAT]                VARCHAR (4)     NULL,
    [PORTE]              VARCHAR (8)     NULL,
    [SGAR]               NUMERIC (17, 2) NULL,
    [VILLE]              VARCHAR (64)    NULL,
    [DEBLOC]             DATE            NULL,
    [CENTR]              NUMERIC (17, 2) NULL,
    [CSITU]              NUMERIC (17, 2) NULL,
    [TXDIM]              NUMERIC (17, 2) NULL,
    [TXMAJ]              NUMERIC (17, 2) NULL,
    [DATTRAV]            DATE            NULL,
    [DFINTXS]            DATE            NULL,
    [DFINTXP]            DATE            NULL,
    [DFINTXR]            DATE            NULL,
    [DURTRAV]            INT             NULL,
    [PARK]               VARCHAR (8)     NULL,
    [GARAGE]             VARCHAR (8)     NULL,
    [CHAUFF]             VARCHAR (2)     NULL,
    [LOGCOM]             VARCHAR (2)     NULL,
    [CCATHLM]            VARCHAR (6)     NULL,
    [CVIDORD]            VARCHAR (2)     NULL,
    [ASCENS]             VARCHAR (2)     NULL,
    [INDCOL]             VARCHAR (2)     NULL,
    [LOGSOC]             VARCHAR (2)     NULL,
    [SCHAU]              NUMERIC (17, 2) NULL,
    [JARDIN]             VARCHAR (8)     NULL,
    [CCOMM]              INT             NULL,
    [SCALC]              VARCHAR (2)     NULL,
    [GCENTR]             NUMERIC (17, 2) NULL,
    [GCSITU]             NUMERIC (17, 2) NULL,
    [GTXDIM]             NUMERIC (17, 2) NULL,
    [GTXMAJ]             NUMERIC (17, 2) NULL,
    [SUTILE]             NUMERIC (17, 2) NULL,
    [SCUTILE]            NUMERIC (19, 4) NULL,
    [SANNEXE]            NUMERIC (17, 2) NULL,
    [DECOMPTE]           VARCHAR (2)     NULL,
    [CUTIL]              VARCHAR (24)    NULL,
    [DMAJ]               DATE            NULL,
    [CCATIMM]            VARCHAR (6)     NULL,
    [LINDCOL]            VARCHAR (2)     NULL,
    [REFIMP]             VARCHAR (28)    NULL,
    [CDEPART]            VARCHAR (4)     NULL,
    [CFINANC]            VARCHAR (10)    NULL,
    [CHANDI]             VARCHAR (2)     NULL,
    [CUSALOC]            VARCHAR (6)     NULL,
    [CQUART]             VARCHAR (6)     NULL,
    [CSECTEUR]           VARCHAR (6)     NULL,
    [CZONE]              VARCHAR (6)     NULL,
    [CBASSIN]            VARCHAR (6)     NULL,
    [TRIG]               VARCHAR (2)     NULL,
    [SREELLE]            NUMERIC (17, 2) NULL,
    [SIMPOS]             NUMERIC (17, 2) NULL,
    [LPLOCAL]            VARCHAR (60)    NULL,
    [COPE]               VARCHAR (22)    NULL,
    [CCONVSU]            VARCHAR (24)    NULL,
    [COEF]               NUMERIC (19, 4) NULL,
    [PEGAS]              DATE            NULL,
    [TRIGD]              DATE            NULL,
    [NOMBMP]             VARCHAR (80)    NULL,
    [XPLAN]              INT             NULL,
    [YPLAN]              INT             NULL,
    [LPLAN]              INT             NULL,
    [HPLAN]              INT             NULL,
    [CSERVI1]            VARCHAR (16)    NULL,
    [CSERVI2]            VARCHAR (16)    NULL,
    [CEMPLOY1]           INT             NULL,
    [CEMPLOY2]           INT             NULL,
    [CARROND]            INT             NULL,
    [ADRCOMP]            VARCHAR (76)    NULL,
    [CTYPQUAR]           VARCHAR (6)     NULL,
    [CFINORI]            VARCHAR (10)    NULL,
    [CONVDSU]            VARCHAR (20)    NULL,
    [CLOCCONT]           INT             NULL,
    [MIGCOMPT]           INT             NULL,
    [CPHASENT]           INT             NULL,
    [DPHASENT]           DATE            NULL,
    [CPHASSOR]           INT             NULL,
    [DPHASSOR]           DATE            NULL,
    [CETAGE]             VARCHAR (6)     NULL,
    [PREMANN]            INT             NULL,
    [SOUMTFPB]           VARCHAR (1)     NULL,
    [ADRESSE_ID]         INT             NULL,
    [ALLEE]              VARCHAR (30)    NULL,
    [CHAUFFAGE]          VARCHAR (1)     NULL,
    [CLIMATISATION]      VARCHAR (1)     NULL,
    [COMMUN]             VARCHAR (1)     NULL,
    [DUPLEX]             VARCHAR (1)     NULL,
    [GESTIONTECH]        VARCHAR (2)     NULL,
    [HAUTEUR]            NUMERIC (17, 2) NULL,
    [IMMEUB_ID]          INT             NULL,
    [NBPIECES]           INT             NULL,
    [PLOCAL_ID]          INT             NULL,
    [SURFDISPONIBLE]     NUMERIC (17, 2) NULL,
    [SURFGRAPHIQUE]      NUMERIC (17, 2) NULL,
    [SURFPIECEGRAPHIQUE] NUMERIC (17, 2) NULL,
    [SURFVITREE]         NUMERIC (17, 2) NULL,
    [VIDORDURE]          VARCHAR (1)     NULL,
    [MOTIOCCUPATION]     VARCHAR (1)     NULL,
    [CTYPOCCUP]          VARCHAR (10)    NULL,
    [REMOCCUP]           VARCHAR (400)   NULL,
    [CMOTINOCCUP]        VARCHAR (10)    NULL,
    [REMINOCCUP]         VARCHAR (400)   NULL,
    [ARCHIVE]            VARCHAR (1)     NULL,
    [DFINML]             DATE            NULL,
    [DDEBHAL]            DATE            NULL,
    [DATACHAT]           DATE            NULL,
    [PRTYPTIERS]         VARCHAR (2)     NULL,
    [PRTIERS]            VARCHAR (14)    NULL,
    [NOTYPTIERS]         VARCHAR (2)     NULL,
    [NOTIERS]            VARCHAR (14)    NULL,
    [VOTYPTIERS]         VARCHAR (2)     NULL,
    [VOTIERS]            VARCHAR (14)    NULL,
    [MTVEN]              NUMERIC (17, 2) NULL,
    [MTACHAT]            NUMERIC (17, 2) NULL,
    [DVENTE]             DATE            NULL,
    [DATEVAL]            DATE            NULL,
    [DAUTO]              DATE            NULL,
    [PRXVENT]            NUMERIC (17, 2) NULL,
    [PRXPLAN]            NUMERIC (17, 2) NULL,
    [ACTYPTIERS]         VARCHAR (2)     NULL,
    [ACTIERS]            VARCHAR (14)    NULL,
    [DOTYPTIERS]         VARCHAR (2)     NULL,
    [DOTIERS]            VARCHAR (14)    NULL,
    [IDPRGES]            VARCHAR (14)    NULL,
    [DDCONS]             DATE            NULL,
    [DFINCONS]           DATE            NULL,
    [DREHAB]             DATE            NULL,
    [CTYPPROP]           VARCHAR (4)     NULL,
    [DPREVENT]           DATE            NULL,
    [DATAUTO]            DATE            NULL,
    [DDEBPAL]            DATE            NULL,
    [DATESORTIE]         DATE            NULL,
    [CMOTSORTIE]         VARCHAR (4)     NULL,
    [DPREVACHAT]         DATE            NULL,
    CONSTRAINT [PK_ESTIA_PLOCAL] PRIMARY KEY CLUSTERED ([CORG] ASC, [CAGENCE] ASC, [CGROUPE] ASC, [CIMMEUB] ASC, [CPLOCAL] ASC)
);

