CREATE TABLE [dbo].[ESTIA_SECURITE] (
    [CLEPRIN]  INT           NOT NULL,
    [CLESEC]   NVARCHAR (50) NULL,
    [CODCHAMP] NVARCHAR (50) NULL,
    [CODFONCT] NVARCHAR (50) NOT NULL,
    [DATE]     DATETIME2 (7) NOT NULL,
    [DOMAINE]  NVARCHAR (50) NOT NULL,
    [ENTIPRIN] NVARCHAR (50) NOT NULL,
    [ENTISEC]  NVARCHAR (50) NOT NULL,
    [HEURE]    INT           NOT NULL,
    [LACTIF]   INT           NOT NULL,
    [LIBCHAMP] NVARCHAR (50) NULL,
    [TRIG]     NVARCHAR (50) NOT NULL,
    [UTIL]     NVARCHAR (50) NOT NULL,
    [VALAPMOD] NVARCHAR (50) NULL,
    [VALAVMOD] NVARCHAR (50) NULL
);

