CREATE TABLE [dbo].[ESTIA_TIERSF] (
    [PK_TIERSF]    INT          IDENTITY (1, 1) NOT NULL,
    [CTIERS]       VARCHAR (14) NULL,
    [CTYPTIERS]    VARCHAR (2)  NULL,
    [CTYPFACT]     VARCHAR (2)  NULL,
    [NBFACT]       VARCHAR (2)  NULL,
    [CMODREG]      VARCHAR (4)  NULL,
    [CTYPDAT]      VARCHAR (2)  NULL,
    [CDECALA]      VARCHAR (4)  NULL,
    [CDECALD]      VARCHAR (2)  NULL,
    [DUREE]        INT          NULL,
    [LBANQUE]      VARCHAR (52) NULL,
    [GUICHET]      VARCHAR (10) NULL,
    [CBANQUE]      VARCHAR (10) NULL,
    [NUMCPTE]      VARCHAR (22) NULL,
    [RIB]          INT          NULL,
    [REGTVA]       VARCHAR (2)  NULL,
    [CTYPREL]      VARCHAR (2)  NULL,
    [PERREL]       VARCHAR (2)  NULL,
    [ECHREL]       VARCHAR (1)  NULL,
    [CCATEG]       VARCHAR (4)  NULL,
    [CTYPPREL]     VARCHAR (2)  NULL,
    [TRIG]         VARCHAR (2)  NULL,
    [UTIL]         VARCHAR (24) NULL,
    [UNLETTRAG]    VARCHAR (2)  NULL,
    [BLCFAC]       VARCHAR (1)  NULL,
    [MIGCOMPT]     INT          NULL,
    [CODNAT]       VARCHAR (4)  NULL,
    [CLEIBAN]      VARCHAR (4)  NULL,
    [COORDBANQ_ID] INT          NULL
);

