CREATE TABLE [dbo].[ESTIA_HQLOCAT] (
    [PK_HQLOCAT]  INT             IDENTITY (1, 1) NOT NULL,
    [FK_ORG]      INT             NULL,
    [FK_AGENCE]   INT             NULL,
    [FK_GROUPE]   INT             NULL,
    [FK_IMMEUB]   INT             NULL,
    [FK_LOCAL]    INT             NULL,
    [FK_LOCATION] INT             NULL,
    [FK_BAIL]     INT             NULL,
    [FK_RUB]      INT             NULL,
    [CORG]        VARCHAR (4)     NULL,
    [CAGENCE]     VARCHAR (4)     NULL,
    [CGROUPE]     INT             NULL,
    [CIMMEUB]     INT             NULL,
    [CLOCAL]      INT             NULL,
    [OCC]         INT             NULL,
    [CRUB]        INT             NULL,
    [DDEB]        DATE            NULL,
    [DFIN]        DATE            NULL,
    [CSTE]        VARCHAR (2)     NULL,
    [NB]          NUMERIC (18, 3) NULL,
    [MONUNIT]     NUMERIC (17, 2) NULL,
    [ECHEANCE]    DATE            NULL,
    [TRAIT]       VARCHAR (6)     NULL,
    [LIBELLE]     VARCHAR (60)    NULL,
    [CMETREV]     VARCHAR (6)     NULL,
    [MONTREV]     NUMERIC (18, 3) NULL,
    [INDANC]      NUMERIC (20, 5) NULL,
    [DATENRGT]    DATE            NULL,
    [TRIG]        VARCHAR (2)     NULL,
    [CTYPDEC]     VARCHAR (2)     NULL,
    [CCOMREV]     INT             NULL,
    [NOLIG]       INT             NULL,
    [POURCIDR]    NUMERIC (17, 2) NULL,
    [PEREVISION]  INT             NULL,
    [DREVISION]   DATE            NULL,
    [TRIMIND]     INT             NULL,
    [ANCNB]       NUMERIC (18, 3) NULL,
    [ANCMONUNIT]  NUMERIC (17, 2) NULL,
    [TMR]         NUMERIC (19, 4) NULL,
    [TR]          NUMERIC (19, 4) NULL,
    [TAUXR]       NUMERIC (19, 4) NULL,
    [VALPOINT]    NUMERIC (19, 4) NULL,
    [ANCTRIMIND]  INT             NULL,
    [MPOURC]      NUMERIC (18, 3) NULL,
    [LFACIAL]     VARCHAR (1)     NULL,
    [LREVIS]      VARCHAR (1)     NULL,
    [DREVIS]      DATE            NULL,
    [LDG]         VARCHAR (1)     NULL,
    [PROVHT]      VARCHAR (1)     NULL,
    [CCATHLM]     VARCHAR (6)     NULL,
    [LGESHONO]    VARCHAR (1)     NULL,
    [MIGCOMPT]    INT             NULL,
    [ERUB]        VARCHAR (2)     NULL
);

