CREATE TABLE [dbo].[ESTIA_LCAUTION] (
    [PK_LCAUTION] INT             IDENTITY (1, 1) NOT NULL,
    [CTYPTIERS]   VARCHAR (2)     NOT NULL,
    [CTIERS]      VARCHAR (14)    NOT NULL,
    [CORG]        VARCHAR (4)     NULL,
    [CCOMPTE]     VARCHAR (22)    NULL,
    [DORG]        VARCHAR (4)     NULL,
    [NODEM]       INT             NULL,
    [MONTANT]     NUMERIC (17, 2) NULL,
    [NOBAIL]      INT             NULL,
    [DDVAL]       DATE            NULL,
    [DFVAL]       DATE            NULL,
    [DENVOI]      DATE            NULL,
    [TRIG]        VARCHAR (2)     NULL,
    [EMTYPTIERS]  VARCHAR (2)     NULL,
    [EMTIERS]     VARCHAR (14)    NULL,
    [CPARENTE]    VARCHAR (6)     NULL,
    [LIEUNAI]     VARCHAR (60)    NULL,
    [DATNAI]      DATE            NULL,
    [MTREV]       NUMERIC (17, 2) NULL,
    [CMOTIF]      VARCHAR (4)     NULL,
    [DMOTIF]      VARCHAR (4)     NULL,
    [LREVIS]      VARCHAR (1)     NULL,
    [DREVIS]      DATE            NULL,
    [LCOURR1]     VARCHAR (1)     NULL,
    [LCOURR2]     VARCHAR (1)     NULL,
    [BANAL1]      INT             NULL,
    [BANAL2]      VARCHAR (1)     NULL,
    [BANAL3]      NUMERIC (17, 2) NULL,
    [BANAL4]      VARCHAR (40)    NULL,
    [NBJCAUT]     INT             NULL,
    [LCLOCAUT]    VARCHAR (1)     NULL,
    [TRIMIND]     INT             NULL,
    [ANCTRIMIND]  INT             NULL,
    [CNUMI]       VARCHAR (10)    NULL,
    [INDANC]      NUMERIC (20, 5) NULL,
    [INDNOUV]     NUMERIC (20, 5) NULL,
    [DVALREV]     DATE            NULL,
    [MIGCOMPT]    INT             NULL,
    [LPTYPTIE]    VARCHAR (2)     NULL,
    [LPCTIERS]    VARCHAR (14)    NULL,
    [REFEXTERNE]  VARCHAR (60)    NULL,
    [LCAUTION_ID] VARCHAR (10)    NULL
);

