CREATE TABLE [dbo].[ESTIA_POPS1] (
    [corg]     VARCHAR (4)     NOT NULL,
    [cope]     VARCHAR (22)    NOT NULL,
    [ver]      VARCHAR (4)     NOT NULL,
    [cdepp]    INT             NULL,
    [mtht]     NUMERIC (17, 2) NULL,
    [mtttc]    NUMERIC (17, 2) NULL,
    [cdept]    VARCHAR (6)     NULL,
    [ctva]     VARCHAR (4)     NULL,
    [deprec]   VARCHAR (2)     NULL,
    [cdepg]    INT             NULL,
    [type]     VARCHAR (2)     NULL,
    [deffet]   DATE            NULL,
    [lib]      VARCHAR (60)    NULL,
    [ctranche] INT             NULL,
    [mtvalasm] NUMERIC (17, 2) NULL,
    [mtva]     NUMERIC (17, 2) NULL,
    [stva]     VARCHAR (4)     NULL,
    [cphase]   VARCHAR (8)     NULL,
    [pourc]    NUMERIC (15)    NULL,
    [avht]     NUMERIC (17, 2) NULL,
    [detreg]   VARCHAR (2)     NULL,
    [htd]      NUMERIC (17, 2) NULL,
    [mtactu]   NUMERIC (17, 2) NULL,
    [mtrevi]   NUMERIC (17, 2) NULL,
    [varc1]    VARCHAR (40)    NULL,
    [varc2]    VARCHAR (40)    NULL,
    [vard1]    NUMERIC (17, 2) NULL,
    [vard2]    NUMERIC (17, 2) NULL,
    [comment]  VARCHAR (120)   NULL,
    [cpmcal]   INT             NULL,
    [lsource]  VARCHAR (100)   NULL,
    [valeur]   NUMERIC (17, 2) NULL,
    [cbanal]   VARCHAR (60)    NULL
);

