CREATE TABLE [dbo].[ESTIA_MANGES] (
    [PK_MANGES]   INT             IDENTITY (1, 1) NOT NULL,
    [CTYPTIERS]   VARCHAR (2)     NULL,
    [CTIERS]      VARCHAR (14)    NULL,
    [CMANDAT]     VARCHAR (16)    NOT NULL,
    [REFMAND]     VARCHAR (80)    NULL,
    [CTYPMAN]     VARCHAR (6)     NULL,
    [NIVEAU]      VARCHAR (2)     NULL,
    [DATTRIB]     DATE            NULL,
    [DRENOUV]     DATE            NULL,
    [DCLOTURE]    DATE            NULL,
    [CMOTMAN]     VARCHAR (6)     NULL,
    [CONDFACT]    VARCHAR (80)    NULL,
    [ACTUAL]      VARCHAR (1)     NULL,
    [TRIG]        VARCHAR (2)     NULL,
    [LMANDAT]     VARCHAR (60)    NULL,
    [FACTURATION] VARCHAR (2)     NULL,
    [NBMOIS]      INT             NULL,
    [DSIGN]       DATE            NULL,
    [MONTANT]     NUMERIC (17, 2) NULL,
    [CTVA]        VARCHAR (4)     NULL,
    [CCATEG]      VARCHAR (4)     NULL,
    [HCATEG]      VARCHAR (4)     NULL,
    [DEFFET]      DATE            NULL,
    [CORG]        VARCHAR (4)     NULL,
    [CAGENCE]     VARCHAR (4)     NULL,
    [CGROUPE]     INT             NULL,
    [CIMMEUB]     INT             NULL,
    [CLOCAL]      INT             NULL,
    [TXHONO]      NUMERIC (17, 2) NULL,
    [MTHONO]      NUMERIC (17, 2) NULL,
    [MTGARANT]    NUMERIC (17, 2) NULL,
    [TYPGARANT]   VARCHAR (2)     NULL,
    [COMMENT]     VARCHAR (1000)  NULL,
    [VACANCE]     VARCHAR (1)     NULL,
    [PERIOD]      INT             NULL,
    [DG]          VARCHAR (1)     NULL,
    [DUREE]       INT             NULL,
    [DELAI]       INT             NULL,
    [PERENOUV]    INT             NULL,
    [PRIORITE]    VARCHAR (4)     NULL,
    [HONOCALC]    VARCHAR (2)     NULL,
    [REPRES]      VARCHAR (14)    NULL,
    [DESIGN]      DATE            NULL,
    [CCG]         VARCHAR (28)    NULL,
    [HORG]        VARCHAR (4)     NULL,
    [DFINGEST]    DATE            NULL,
    [MFDR]        NUMERIC (17, 2) NULL,
    [DFDR]        DATE            NULL,
    [MDEJAREV]    NUMERIC (17, 2) NULL,
    [CEMPLOY]     INT             NULL,
    [PART]        NUMERIC (15)    NULL,
    [ASSPERT]     VARCHAR (1)     NULL,
    [CALCULAC]    VARCHAR (2)     NULL,
    [CTYPDECRF]   VARCHAR (10)    NULL,
    [CTYPDEDRF]   VARCHAR (6)     NULL,
    [DECTVA]      VARCHAR (1)     NULL,
    [DEREDD]      VARCHAR (12)    NULL,
    [EDITBOR]     VARCHAR (1)     NULL,
    [EDITDEP]     VARCHAR (2)     NULL,
    [EDITQUIT]    VARCHAR (2)     NULL,
    [EDITREP]     VARCHAR (2)     NULL,
    [EXIG]        VARCHAR (2)     NULL,
    [FORFACPTE]   NUMERIC (17, 2) NULL,
    [HONOCPTA]    VARCHAR (2)     NULL,
    [HONOFREQ]    INT             NULL,
    [INDIVIS]     VARCHAR (1)     NULL,
    [MFINH]       INT             NULL,
    [MFINR]       INT             NULL,
    [MTFRDOS]     NUMERIC (17, 2) NULL,
    [NBDEP]       VARCHAR (2)     NULL,
    [NBREP]       VARCHAR (2)     NULL,
    [POUREV]      NUMERIC (17, 2) NULL,
    [PRESGEST]    VARCHAR (2)     NULL,
    [PRESQUIT]    VARCHAR (2)     NULL,
    [PRORATA]     NUMERIC (17, 2) NULL,
    [PROVHT]      VARCHAR (1)     NULL,
    [REGLE]       VARCHAR (2)     NULL,
    [REPORTINC]   VARCHAR (2)     NULL,
    [SOUMTVA]     VARCHAR (1)     NULL,
    [TAXADD]      VARCHAR (2)     NULL,
    [TERMNREL]    VARCHAR (12)    NULL,
    [TERMQUIT]    VARCHAR (12)    NULL,
    [VIRPROPR]    VARCHAR (1)     NULL,
    [CFREQAC]     VARCHAR (6)     NULL,
    [DREDD]       DATE            NULL,
    [DTERME]      VARCHAR (12)    NULL,
    [EXEMP]       INT             NULL,
    [TEMPLOY]     INT             NULL,
    [DISPO]       NUMERIC (15)    NULL,
    [ADRCOMP]     VARCHAR (76)    NULL,
    [CPOS]        VARCHAR (10)    NULL,
    [LIEUDIT]     VARCHAR (76)    NULL,
    [RUE]         VARCHAR (76)    NULL,
    [VILLE]       VARCHAR (64)    NULL,
    [SEUILMINI]   NUMERIC (17, 2) NULL,
    [CBANQUE]     VARCHAR (10)    NULL,
    [GUICHET]     VARCHAR (10)    NULL,
    [COMPTE]      VARCHAR (22)    NULL,
    [CONVOC]      VARCHAR (6)     NULL,
    [DDBRELANC]   DATE            NULL,
    [DFNRELANC]   DATE            NULL,
    [TERME]       INT             NULL,
    [TPSPRE]      VARCHAR (1)     NULL,
    [DERACPTE]    DATE            NULL,
    [ISOLE]       VARCHAR (4)     NULL,
    [DECRL]       VARCHAR (2)     NULL,
    [DDEBMDT]     DATE            NULL,
    [DFINMDT]     DATE            NULL,
    [NIVREL]      VARCHAR (2)     NULL,
    [CMOTFDR]     VARCHAR (6)     NULL,
    [TYPEMDT]     VARCHAR (2)     NULL,
    [MIGCOMPT]    INT             NULL,
    [CMANDOM]     INT             NULL,
    [NMANDOM]     VARCHAR (2)     NULL,
    [PRIM1]       NUMERIC (17, 2) NULL,
    [PRIM2]       NUMERIC (17, 2) NULL,
    [PRIMCAL]     VARCHAR (2)     NULL,
    [REGLT]       VARCHAR (1000)  NULL,
    [DVERCPT]     DATE            NULL,
    [CNUMI]       VARCHAR (10)    NULL,
    [DEFFETREVIS] DATE            NULL,
    [DREVIS]      DATE            NULL,
    [DREVISION]   DATE            NULL,
    [INDPREC]     INT             NULL,
    [INDREF]      INT             NULL,
    [PEREVISION]  INT             NULL,
    [TRIMIND]     INT             NULL,
    [ADFPER]      INT             NULL,
    [ADFREGUL]    VARCHAR (2)     NULL,
    [ADFTYPE]     VARCHAR (6)     NULL,
    [REMPLOY]     INT             NULL,
    [ECRTVA]      VARCHAR (1)     NULL,
    CONSTRAINT [PK_ESTIA_MANGES] PRIMARY KEY CLUSTERED ([CMANDAT] ASC)
);

