CREATE TABLE [dbo].[ESTIA_ECRITANA] (
    [CORG]     VARCHAR (4)     NOT NULL,
    [CJOURNAL] VARCHAR (6)     NULL,
    [TYPPOS]   VARCHAR (2)     NULL,
    [CCB]      VARCHAR (28)    NULL,
    [NOPIECE]  VARCHAR (16)    NULL,
    [REF]      VARCHAR (42)    NULL,
    [DATEC]    DATE            NOT NULL,
    [DVAL]     DATE            NULL,
    [PERIODE]  VARCHAR (12)    NOT NULL,
    [LIBELLE]  VARCHAR (80)    NULL,
    [CCG]      VARCHAR (28)    NULL,
    [ETECR]    VARCHAR (2)     NULL,
    [MONTANT]  NUMERIC (17, 2) NULL,
    [SENS]     VARCHAR (2)     NULL,
    [CTYPECRI] VARCHAR (6)     NULL,
    [CNATANA]  VARCHAR (16)    NOT NULL,
    [CSECTANA] VARCHAR (16)    NOT NULL,
    [UTIL]     VARCHAR (24)    NULL,
    [ORD]      INT             NULL,
    [INFO]     VARCHAR (44)    NULL,
    [CSTE]     VARCHAR (4)     NOT NULL,
    [CEXO]     VARCHAR (8)     NULL,
    [CSECTREG] VARCHAR (16)    NULL,
    [TRIG]     VARCHAR (2)     NULL,
    [CACCESS]  VARCHAR (2)     NULL,
    [NODOC]    VARCHAR (24)    NULL,
    [MTTC]     NUMERIC (17, 2) NULL,
    [MTHT]     NUMERIC (17, 2) NULL
);

