CREATE TABLE [dbo].[ESTIA_EMPLOY] (
    [CEMPLOY]    INT             NOT NULL,
    [CQC]        VARCHAR (8)     NULL,
    [LEMPLOY]    VARCHAR (60)    NULL,
    [CRESP]      VARCHAR (12)    NULL,
    [CVEHIC]     VARCHAR (4)     NULL,
    [CPAYS]      VARCHAR (6)     NULL,
    [DATNAI]     DATE            NULL,
    [IDENT]      VARCHAR (30)    NULL,
    [RUE]        VARCHAR (76)    NULL,
    [LIEUDIT]    VARCHAR (76)    NULL,
    [CPOS]       VARCHAR (10)    NULL,
    [VILLE]      VARCHAR (64)    NULL,
    [AUTACT]     VARCHAR (60)    NULL,
    [TRIG]       VARCHAR (2)     NULL,
    [CSERVI]     VARCHAR (16)    NULL,
    [DOSS]       VARCHAR (1)     NULL,
    [TECH]       VARCHAR (1)     NULL,
    [TECHCO]     VARCHAR (1)     NULL,
    [DEM]        VARCHAR (1)     NULL,
    [EDL]        VARCHAR (1)     NULL,
    [MTBON]      NUMERIC (17, 2) NULL,
    [INTERV]     VARCHAR (1)     NULL,
    [EMET]       VARCHAR (1)     NULL,
    [CTX]        VARCHAR (1)     NULL,
    [PCTX]       VARCHAR (1)     NULL,
    [MAR]        VARCHAR (1)     NULL,
    [CTRE]       VARCHAR (1)     NULL,
    [APOF]       VARCHAR (1)     NULL,
    [TELPH]      VARCHAR (60)    NULL,
    [LISTSTOCK]  VARCHAR (120)   NULL,
    [CFONCTIO]   VARCHAR (10)    NULL,
    [OPERATION]  VARCHAR (1)     NULL,
    [CTYPTIERS]  VARCHAR (2)     NULL,
    [CTIERS]     VARCHAR (14)    NULL,
    [CDIVIS]     VARCHAR (6)     NULL,
    [CSDIVIS]    VARCHAR (16)    NULL,
    [UTIL]       VARCHAR (24)    NULL,
    [CLIEU]      VARCHAR (6)     NULL,
    [CACTIVITE]  VARCHAR (8)     NULL,
    [AUTORISE]   VARCHAR (1000)  NULL,
    [SAUTORISE]  VARCHAR (1000)  NULL,
    [CAUTORISE]  VARCHAR (1000)  NULL,
    [INITIALES]  VARCHAR (10)    NULL,
    [INTERNET]   VARCHAR (200)   NULL,
    [ADRCOMP]    VARCHAR (76)    NULL,
    [GESTIONEDI] VARCHAR (1)     NULL,
    [TECHEDI]    VARCHAR (1)     NULL,
    [MIGCOMPT]   INT             NULL,
    [PRENOM]     VARCHAR (40)    NULL,
    [FAX]        VARCHAR (50)    NULL,
    [PORTABLE]   VARCHAR (50)    NULL,
    [EYTIERS]    VARCHAR (14)    NULL,
    [EYTYPTIERS] VARCHAR (2)     NULL,
    CONSTRAINT [PK_ESTIA_EMPLOY] PRIMARY KEY CLUSTERED ([CEMPLOY] ASC)
);

