CREATE TABLE [dbo].[ESTIA_LBUDLOC] (
    [PK_LBUDLOC] INT             IDENTITY (1, 1) NOT NULL,
    [FK_ORG]     INT             NULL,
    [FK_AGENCE]  INT             NULL,
    [FK_GROUPE]  INT             NULL,
    [FK_EBUDLOC] INT             NULL,
    [FK_CRITDP]  INT             NULL,
    [FK_SCRITDP] INT             NULL,
    [FK_BASE]    INT             NULL,
    [CORG]       VARCHAR (4)     NOT NULL,
    [CAGENCE]    VARCHAR (4)     NOT NULL,
    [CGROUPE]    INT             NOT NULL,
    [CBUDLOC]    VARCHAR (16)    NOT NULL,
    [VERSION]    INT             NOT NULL,
    [NOLIG]      INT             NOT NULL,
    [CCRITDP]    INT             NULL,
    [CSCRITDP]   INT             NULL,
    [MONTANT]    NUMERIC (17, 2) NULL,
    [LIB]        VARCHAR (60)    NULL,
    [CRUB]       INT             NULL,
    [MONTANTREF] NUMERIC (17, 2) NULL,
    [POURCEVOL]  NUMERIC (17, 2) NULL,
    [TYPEREF]    VARCHAR (2)     NULL,
    [TRIG]       VARCHAR (2)     NULL,
    [MIGCOMPT]   INT             NULL,
    [MTHT]       NUMERIC (17, 2) NULL,
    [MTTVA]      NUMERIC (17, 2) NULL,
    [MTREFHT]    NUMERIC (17, 2) NULL,
    [MTREFTVA]   NUMERIC (17, 2) NULL,
    [DDEBIMP]    DATE            NULL,
    [DFINIMP]    DATE            NULL,
    [BUDPROP]    VARCHAR (1)     NULL,
    [ADF]        VARCHAR (1)     NULL,
    [TEXTPRO]    VARCHAR (50)    NULL,
    CONSTRAINT [PK_ESTIA_LBUDLOC] PRIMARY KEY CLUSTERED ([CORG] ASC, [CAGENCE] ASC, [CGROUPE] ASC, [CBUDLOC] ASC, [VERSION] ASC, [NOLIG] ASC)
);



