CREATE TABLE [dbo].[ESTIA_CRITDP] (
    [PK_CCRITDP] AS              ([CCRITDP]),
    [CCRITDP]    INT             NOT NULL,
    [LCRITDP]    VARCHAR (60)    NULL,
    [CRUB]       INT             NULL,
    [MONTANT]    NUMERIC (17, 2) NULL,
    [POURC]      NUMERIC (18, 3) NULL,
    [GCRITDP]    INT             NULL,
    [TRIG]       VARCHAR (2)     NULL,
    [TYPFAC]     VARCHAR (2)     NULL,
    [CNOMENM]    VARCHAR (22)    NULL,
    [ACTRLER]    VARCHAR (1)     NULL,
    [HONO]       VARCHAR (1)     NULL,
    [REVERSE]    VARCHAR (1)     NULL,
    [CRUBTVA]    INT             NULL,
    [CHARCONV]   VARCHAR (2)     NULL,
    [TAUXRED]    VARCHAR (1)     NULL,
    [IMMO]       VARCHAR (1)     NULL,
    [CCHAPITRE]  VARCHAR (4)     NULL,
    [CLETTRF]    VARCHAR (60)    NULL,
    [CREGCPTE]   VARCHAR (4)     NULL,
    [CRUBC]      INT             NULL,
    [REGREPART]  VARCHAR (4)     NULL,
    [REGRF]      VARCHAR (4)     NULL,
    [LIBIS]      VARCHAR (60)    NULL,
    [NCRITDP]    INT             NULL,
    [ACOMPTE]    VARCHAR (1)     NULL,
    [STOCK]      VARCHAR (2)     NULL,
    [FACTDIR]    VARCHAR (2)     NULL,
    [BANTVA]     VARCHAR (2)     NULL,
    [COPRO]      VARCHAR (2)     NULL,
    [CCRITLOC]   INT             NULL,
    [TYPEMDT]    VARCHAR (2)     NULL,
    [MIGCOMPT]   INT             NULL,
    [PEVOL]      NUMERIC (17, 2) NULL,
    [LACTIF]     VARCHAR (1)     NULL,
    [HCRITDP]    INT             NULL,
    [CDEPR]      INT             NULL,
    CONSTRAINT [PK_ESTIA_CRITDP] PRIMARY KEY CLUSTERED ([CCRITDP] ASC)
);

