CREATE TABLE [dbo].[ESTIA_METREV] (
    [CMETREV] VARCHAR (6)  NOT NULL,
    [LMETREV] VARCHAR (60) NULL,
    [TRIG]    VARCHAR (2)  NULL,
    [LACTIF]  VARCHAR (2)  NULL,
    CONSTRAINT [PK_ESTIA_METREV] PRIMARY KEY CLUSTERED ([CMETREV] ASC)
);

