CREATE TABLE [dbo].[ESTIA_COMPTE] (
    [PK_COMPTE]  INT             IDENTITY (1, 1) NOT NULL,
    [CORG]       VARCHAR (4)     NOT NULL,
    [CCOMPTE]    VARCHAR (22)    NOT NULL,
    [CQC]        VARCHAR (8)     NULL,
    [NOM]        VARCHAR (76)    NULL,
    [RUE]        VARCHAR (76)    NULL,
    [LIEUDIT]    VARCHAR (76)    NULL,
    [CPOS]       VARCHAR (50)    NULL,
    [VILLE]      VARCHAR (64)    NULL,
    [CCOMM]      VARCHAR (64)    NULL,
    [TELPH]      VARCHAR (50)    NULL,
    [MONDERQ]    VARCHAR (50)    NULL,
    [LOYER]      NUMERIC (17, 2) NULL,
    [SDAVQUIT]   NUMERIC (17, 2) NULL,
    [DATPLAN]    VARCHAR (10)    NULL,
    [CMODPLAN]   VARCHAR (4)     NULL,
    [CCATRET]    VARCHAR (6)     NULL,
    [DPRET]      DATE            NULL,
    [COPRO]      VARCHAR (2)     NULL,
    [CODBAR]     VARCHAR (50)    NULL,
    [DATDERQUIT] DATE            NULL,
    [DERAPL]     NUMERIC (17, 2) NULL,
    [DEMISAVIS]  VARCHAR (10)    NULL,
    [SEMISAVIS]  NUMERIC (17, 2) NULL,
    [DATDEN]     VARCHAR (10)    NULL,
    [DIMPQUITT]  VARCHAR (10)    NULL,
    [MTPREL]     NUMERIC (17, 2) NULL,
    [MONRAP]     NUMERIC (17, 2) NULL,
    [DDEBDEN1]   VARCHAR (10)    NULL,
    [DFINDEN1]   VARCHAR (10)    NULL,
    [DDEBDEN2]   VARCHAR (10)    NULL,
    [DFINDEN2]   VARCHAR (10)    NULL,
    [TRUET]      VARCHAR (76)    NULL,
    [TLIEUDIT]   VARCHAR (76)    NULL,
    [TCPOS]      VARCHAR (10)    NULL,
    [TVILLE]     VARCHAR (64)    NULL,
    [TCOMM]      INT             NULL,
    [TTELPH]     VARCHAR (50)    NULL,
    [DATDEB]     DATE            NULL,
    [DATFIN]     DATE            NULL,
    [TRIG]       VARCHAR (2)     NULL,
    [CCATMENPDR] VARCHAR (6)     NULL,
    [CCATMENSLS] VARCHAR (6)     NULL,
    [REFDEROG]   VARCHAR (24)    NULL,
    [CMOTDERO]   VARCHAR (4)     NULL,
    [DDEROG]     VARCHAR (10)    NULL,
    [DEPASS]     NUMERIC (17, 2) NULL,
    [DEBPASS]    VARCHAR (10)    NULL,
    [DFINPASS]   VARCHAR (10)    NULL,
    [TEMPLOY]    INT             NULL,
    [MTCRDTP]    NUMERIC (17, 2) NULL,
    [MTCRDTC]    NUMERIC (17, 2) NULL,
    [CPAYS]      VARCHAR (6)     NULL,
    [TCPAYS]     VARCHAR (6)     NULL,
    [ADRCOMP]    VARCHAR (76)    NULL,
    [TADRCOMP]   VARCHAR (76)    NULL,
    [CQC2]       VARCHAR (8)     NULL,
    [NOM2]       VARCHAR (76)    NULL,
    [CONVOC]     VARCHAR (6)     NULL,
    [NIVAPP]     VARCHAR (2)     NULL,
    [MIGCOMPT]   INT             NULL,
    [RESIDENT]   VARCHAR (2)     NULL,
    [CCQC1]      VARCHAR (8)     NULL,
    [CNOM1]      VARCHAR (76)    NULL,
    [CCQC2]      VARCHAR (8)     NULL,
    [CNOM2]      VARCHAR (76)    NULL,
    [CLIEUDIT]   VARCHAR (76)    NULL,
    [CADRCOMP]   VARCHAR (76)    NULL,
    [CRUE]       VARCHAR (76)    NULL,
    [CCPOS]      VARCHAR (10)    NULL,
    [CVILLE]     VARCHAR (64)    NULL,
    [CCOMCONV]   INT             NULL,
    [PAYSCONV]   VARCHAR (6)     NULL,
    [CPAYSCON]   VARCHAR (6)     NULL,
    [EXTIDENT]   VARCHAR (76)    NULL,
    [EXTPASSE]   VARCHAR (40)    NULL,
    [EXTACC]     VARCHAR (2)     NULL,
    [EXTVER]     VARCHAR (2)     NULL,
    CONSTRAINT [PK_ESTIA_COMPTE] PRIMARY KEY CLUSTERED ([CORG] ASC, [CCOMPTE] ASC)
);

