CREATE TABLE [dbo].[ESTIA_TYPROPR] (
    [PK_TYPROPR] INT          IDENTITY (1, 1) NOT NULL,
    [CMANDAT]    VARCHAR (16) NULL,
    [CTIERS]     VARCHAR (14) NULL,
    [CTYPTIERS]  VARCHAR (2)  NULL,
    [CTYPROPR]   VARCHAR (4)  NULL,
    [DARRETE]    DATE         NULL,
    [DDEB]       DATE         NULL,
    [DFIN]       DATE         NULL,
    [MIGCOMPT]   VARCHAR (10) NULL,
    [TRIG]       VARCHAR (2)  NULL,
    [TYPROPR_ID] VARCHAR (50) NOT NULL,
    CONSTRAINT [PK_ESTIA_TYPROPR] PRIMARY KEY CLUSTERED ([TYPROPR_ID] ASC)
);

