CREATE TABLE [dbo].[ESTIA_CONTNAT] (
    [CORG]           VARCHAR (4)     NULL,
    [MTTC]           NUMERIC (17, 2) NULL,
    [MENSUEL]        VARCHAR (50)    NULL,
    [CCONTFRS]       VARCHAR (50)    NULL,
    [CRUB]           VARCHAR (3)     NULL,
    [CNATECH]        VARCHAR (50)    NULL,
    [MTHT]           NUMERIC (17, 2) NULL,
    [TVA]            NUMERIC (17, 2) NULL,
    [DORIG]          VARCHAR (50)    NULL,
    [PF]             VARCHAR (50)    NULL,
    [DDREVIS]        DATE            NULL,
    [TRIG]           VARCHAR (50)    NULL,
    [DSIGN]          DATE            NULL,
    [MTREVIS]        NUMERIC (17, 2) NULL,
    [ANCREVI]        VARCHAR (50)    NULL,
    [CTVA]           VARCHAR (50)    NULL,
    [PROGRESS_RECID] VARCHAR (50)    NULL,
    [RABAIS]         VARCHAR (50)    NULL,
    [DATREP]         VARCHAR (50)    NULL,
    [MTMINI]         VARCHAR (50)    NULL,
    [VALIDE]         VARCHAR (50)    NULL,
    [DETAT]          VARCHAR (50)    NULL,
    [CNOMENM]        VARCHAR (50)    NULL,
    [MOISREV]        VARCHAR (50)    NULL,
    [REVCRIT]        VARCHAR (50)    NULL,
    [DPECFNP]        VARCHAR (50)    NULL
);

