CREATE TABLE [dbo].[ESTIA_PERIODICITE] (
    [CPERIODICITE] INT          NOT NULL,
    [LPERIODICITE] VARCHAR (60) NULL,
    [TRIG]         VARCHAR (2)  NULL,
    [MIGCOMPT]     INT          NULL,
    [LACTIF]       VARCHAR (2)  NULL,
    CONSTRAINT [PK_ESTIA_PERIODICITE] PRIMARY KEY CLUSTERED ([CPERIODICITE] ASC)
);

