CREATE TABLE [dbo].[ESTIA_RUB] (
    [PK_RUB]     AS              ([CRUB]),
    [CRUB]       INT             NOT NULL,
    [LRUB]       VARCHAR (60)    NULL,
    [CNATRUB]    VARCHAR (2)     NULL,
    [SENS]       VARCHAR (2)     NULL,
    [TPSPRE]     VARCHAR (1)     NULL,
    [RTOTAVIS]   VARCHAR (1)     NULL,
    [TEMREGUL]   VARCHAR (1)     NULL,
    [CMETHCAL]   INT             NULL,
    [TEMBAIL]    VARCHAR (1)     NULL,
    [SORTI]      VARCHAR (1)     NULL,
    [QUITT]      VARCHAR (1)     NULL,
    [ECHEANCE]   VARCHAR (1)     NULL,
    [NOORD]      INT             NULL,
    [ERUB]       INT             NULL,
    [DDEBLOC]    INT             NULL,
    [TRIG]       VARCHAR (2)     NULL,
    [CRUBTAX]    VARCHAR (40)    NULL,
    [NCOLEDIT]   VARCHAR (18)    NULL,
    [EDITDEM]    VARCHAR (1)     NULL,
    [LOYPRIN]    VARCHAR (1)     NULL,
    [CTYPTAX]    VARCHAR (4)     NULL,
    [CTASS]      INT             NULL,
    [PRELEV]     VARCHAR (1)     NULL,
    [NATAPL]     VARCHAR (2)     NULL,
    [DRUB]       INT             NULL,
    [NCOLECRAN]  VARCHAR (18)    NULL,
    [CMETARR]    VARCHAR (4)     NULL,
    [TEMIMP]     VARCHAR (1)     NULL,
    [RRUB]       INT             NULL,
    [ARUB]       INT             NULL,
    [NORDEC]     INT             NULL,
    [LIBANNEXE]  VARCHAR (60)    NULL,
    [COMPVAC]    VARCHAR (1)     NULL,
    [CNATANA]    VARCHAR (16)    NULL,
    [TXEFFORT]   VARCHAR (1)     NULL,
    [CRUPTURE]   VARCHAR (4)     NULL,
    [REVERSE]    VARCHAR (1)     NULL,
    [AREVERSER]  VARCHAR (1)     NULL,
    [DECOMPTE]   VARCHAR (1)     NULL,
    [LIDR]       VARCHAR (1)     NULL,
    [LHONO]      VARCHAR (1)     NULL,
    [LGARANT]    VARCHAR (1)     NULL,
    [TRUB]       INT             NULL,
    [BRUB]       INT             NULL,
    [SRUB]       INT             NULL,
    [CNUMI]      VARCHAR (10)    NULL,
    [PEREVISION] INT             NULL,
    [TRIMIND]    INT             NULL,
    [CBASE]      INT             NULL,
    [LOCCOP]     VARCHAR (2)     NULL,
    [PRUB]       INT             NULL,
    [MRUB]       INT             NULL,
    [CTRLBUD]    VARCHAR (2)     NULL,
    [CNATHON]    VARCHAR (4)     NULL,
    [CTRLEXO]    VARCHAR (1)     NULL,
    [HRUB]       INT             NULL,
    [XRUB]       INT             NULL,
    [LREVIS]     VARCHAR (1)     NULL,
    [FRUB]       INT             NULL,
    [RTASS]      INT             NULL,
    [PRIORO]     INT             NULL,
    [PRIORT]     INT             NULL,
    [CCHAPITRE]  VARCHAR (4)     NULL,
    [CLETTRF]    VARCHAR (60)    NULL,
    [CREGCPTE]   VARCHAR (4)     NULL,
    [HONAUTRE]   VARCHAR (4)     NULL,
    [REGREPART]  VARCHAR (4)     NULL,
    [REGRF]      VARCHAR (4)     NULL,
    [COPRO]      VARCHAR (2)     NULL,
    [LIBIS]      VARCHAR (60)    NULL,
    [NRUB]       INT             NULL,
    [IRUB1]      INT             NULL,
    [IRUB2]      INT             NULL,
    [CPTADET]    VARCHAR (1)     NULL,
    [NOLIGRF]    INT             NULL,
    [ACOMPTE]    VARCHAR (1)     NULL,
    [ASSPERT]    VARCHAR (1)     NULL,
    [PCA]        VARCHAR (1)     NULL,
    [GRUB]       INT             NULL,
    [ALISSER]    VARCHAR (1)     NULL,
    [FRANRUB]    INT             NULL,
    [CCRITLOC]   INT             NULL,
    [CTSCAT]     VARCHAR (4)     NULL,
    [CCRITCOMP]  INT             NULL,
    [AUTORISE]   VARCHAR (1000)  NULL,
    [SAUTORISE]  VARCHAR (1000)  NULL,
    [CAUTORISE]  VARCHAR (1000)  NULL,
    [TYPEMDT]    VARCHAR (2)     NULL,
    [TASSPAR]    VARCHAR (1)     NULL,
    [TASSPRE]    VARCHAR (1)     NULL,
    [LGESHONO]   VARCHAR (1)     NULL,
    [SEUIL]      NUMERIC (17, 2) NULL,
    [PRIME]      VARCHAR (2)     NULL,
    [CPRESTA]    VARCHAR (16)    NULL,
    [LACTIF]     VARCHAR (1)     NULL,
    [PCABAIL]    VARCHAR (1)     NULL,
    [ADFVAC]     VARCHAR (2)     NULL,
    CONSTRAINT [PK_ESTIA_RUB] PRIMARY KEY CLUSTERED ([CRUB] ASC)
);

