CREATE TABLE [dbo].[ESTIA_TYPLOG] (
    [CTYPLOG]   VARCHAR (6)  NOT NULL,
    [LTYPLOG]   VARCHAR (60) NULL,
    [CEXTERNE]  VARCHAR (90) NULL,
    [LGEXTERNE] VARCHAR (30) NULL,
    [TRIG]      VARCHAR (2)  NULL,
    [TRIGD]     DATE         NULL,
    [NBPIEC]    INT          NULL,
    [CTYPCIL]   VARCHAR (4)  NULL,
    [PEGAS]     DATE         NULL,
    [TSOUMTAX]  VARCHAR (1)  NULL,
    [TYPUSALO]  VARCHAR (2)  NULL,
    [LACTIF]    VARCHAR (1)  NULL,
    CONSTRAINT [PK_ESTIA_TYPLOG] PRIMARY KEY CLUSTERED ([CTYPLOG] ASC)
);

