CREATE TABLE [dbo].[ESTIA_DEMINT] (
    [PK_DEMINT] INT           IDENTITY (1, 1) NOT NULL,
    [FK_ORG]    INT           NULL,
    [FK_INTBT]  INT           NULL,
    [FK_AGENCE] INT           NULL,
    [FK_GROUPE] INT           NULL,
    [FK_TIERS]  INT           NULL,
    [CORG]      VARCHAR (4)   NOT NULL,
    [NODEM]     INT           NOT NULL,
    [DATEDEM]   DATE          NULL,
    [XORG]      VARCHAR (4)   NULL,
    [CNATREC]   VARCHAR (4)   NULL,
    [DATSOUFIN] DATE          NULL,
    [CAGENCE]   VARCHAR (4)   NOT NULL,
    [CGROUPE]   INT           NOT NULL,
    [CIMMEUB]   INT           NULL,
    [CLOCAL]    INT           NULL,
    [CNATPIEC]  VARCHAR (4)   NULL,
    [TELDOM]    VARCHAR (50)  NULL,
    [TELTRA]    VARCHAR (50)  NULL,
    [TRIG]      VARCHAR (2)   NULL,
    [IEMPLOY]   INT           NULL,
    [ENCOURS]   VARCHAR (1)   NULL,
    [OEMPLOY]   INT           NULL,
    [DATCLO]    DATE          NULL,
    [COMPL]     VARCHAR (60)  NULL,
    [CMOTCLO]   VARCHAR (4)   NULL,
    [OCC]       INT           NULL,
    [CNATFIN]   VARCHAR (4)   NULL,
    [DNATFIN]   VARCHAR (4)   NULL,
    [CORIREC]   VARCHAR (4)   NULL,
    [CURGENCE]  INT           NULL,
    [DATLIM]    DATE          NULL,
    [DATINF]    DATE          NULL,
    [ESCALIER]  VARCHAR (4)   NULL,
    [ETAGE]     INT           NULL,
    [FACTEDIT]  VARCHAR (2)   NULL,
    [REGCPT]    VARCHAR (2)   NULL,
    [CLE]       VARCHAR (60)  NULL,
    [BAT]       VARCHAR (4)   NULL,
    [CTYPTIERS] VARCHAR (2)   NULL,
    [CTIERS]    VARCHAR (14)  NULL,
    [HEURDEM]   VARCHAR (16)  NULL,
    [OCC2]      INT           NULL,
    [CMANDAT]   VARCHAR (16)  NULL,
    [MIGCOMPT]  INT           NULL,
    [EMAIL]     VARCHAR (200) NULL,
    [CSOLLICIT] VARCHAR (50)  NULL
);

