CREATE TABLE [dbo].[ESTIA_CRITLIB] (
    [NOFICH]   VARCHAR (16)   NOT NULL,
    [CLEFICH]  VARCHAR (120)  NOT NULL,
    [CLCRIT]   VARCHAR (10)   NOT NULL,
    [CCRIT]    VARCHAR (10)   NOT NULL,
    [TRIG]     VARCHAR (2)    NULL,
    [DCRITLIB] DATE           NULL,
    [BANAL]    VARCHAR (2100) NULL,
    [MIGCOMPT] VARCHAR (2)    NULL,
    CONSTRAINT [PK_ESTIA_CRITLIB] PRIMARY KEY CLUSTERED ([NOFICH] ASC, [CLEFICH] ASC, [CLCRIT] ASC, [CCRIT] ASC)
);

