CREATE TABLE [dbo].[ESTIA_CTRTIERS] (
    [PK_CTRTIERS]  INT             IDENTITY (1, 1) NOT NULL,
    [FK_TIERS]     INT             NULL,
    [CMODINT]      VARCHAR (6)     NULL,
    [CTIERS]       VARCHAR (14)    NULL,
    [CCONTFRS]     VARCHAR (24)    NOT NULL,
    [DURINIT]      VARCHAR (12)    NULL,
    [LCTRTIERS]    VARCHAR (500)   NULL,
    [DCTRTIERS]    DATE            NULL,
    [DDEBVAL]      DATE            NULL,
    [DFINVAL]      DATE            NULL,
    [LOCAT]        VARCHAR (2)     NULL,
    [CORG]         VARCHAR (4)     NOT NULL,
    [CCONTPREST]   VARCHAR (40)    NULL,
    [CFREQINT]     VARCHAR (6)     NULL,
    [DURCONT]      VARCHAR (12)    NULL,
    [DURPREAV]     VARCHAR (4)     NULL,
    [DFPERESS]     DATE            NULL,
    [TRIG]         VARCHAR (2)     NULL,
    [SUIVICO]      VARCHAR (1)     NULL,
    [DLIMPREST]    DATE            NULL,
    [CUNITE]       VARCHAR (4)     NULL,
    [CEMPLOY]      INT             NULL,
    [CPENAL]       VARCHAR (6)     NULL,
    [CPERFAC]      VARCHAR (6)     NULL,
    [TERME]        VARCHAR (2)     NULL,
    [DRADIAT]      DATE            NULL,
    [CMOTRAD]      VARCHAR (6)     NULL,
    [FOURNITURE]   VARCHAR (1)     NULL,
    [BT]           VARCHAR (1)     NULL,
    [ENTRETIEN]    VARCHAR (1)     NULL,
    [CTEQUI]       INT             NULL,
    [DATCOM]       DATE            NULL,
    [DELAI]        VARCHAR (6)     NULL,
    [HEUROUV]      VARCHAR (40)    NULL,
    [CCONTPRIX]    VARCHAR (6)     NULL,
    [DPREVINT]     DATE            NULL,
    [DDEBPREV]     DATE            NULL,
    [AVECAO]       VARCHAR (1)     NULL,
    [CONSO]        VARCHAR (1)     NULL,
    [TYPCONT]      VARCHAR (2)     NULL,
    [HMARCHE]      VARCHAR (1)     NULL,
    [CMODPASS]     VARCHAR (6)     NULL,
    [ECART]        NUMERIC (17, 2) NULL,
    [DATREPORT]    DATE            NULL,
    [RENOUV]       VARCHAR (1)     NULL,
    [POURC]        VARCHAR (1)     NULL,
    [AGEAUT]       VARCHAR (120)   NULL,
    [MTPLURI]      NUMERIC (17, 2) NULL,
    [CONTROLE]     VARCHAR (2)     NULL,
    [TACITE]       VARCHAR (1)     NULL,
    [CNATPRES]     VARCHAR (6)     NULL,
    [GESTIONHT]    VARCHAR (1)     NULL,
    [CBANQUE]      VARCHAR (10)    NULL,
    [CGUICHET]     VARCHAR (10)    NULL,
    [COMPTE]       VARCHAR (22)    NULL,
    [CLE]          VARCHAR (4)     NULL,
    [MODTVA]       VARCHAR (2)     NULL,
    [PCONTFRS]     VARCHAR (24)    NULL,
    [CCATEG]       VARCHAR (4)     NULL,
    [CODNAT]       VARCHAR (4)     NULL,
    [CLEIBAN]      VARCHAR (4)     NULL,
    [COORDBANQ_ID] INT             NULL,
    [LIBFAC]       VARCHAR (60)    NULL,
    [SIGAUTORISE]  VARCHAR (2)     NULL,
    CONSTRAINT [PK_ESTIA_CTRTIERS] PRIMARY KEY CLUSTERED ([CORG] ASC, [CCONTFRS] ASC)
);

