CREATE TABLE [dbo].[ESTIA_TVA] (
    [CTVA]   VARCHAR (4)     NOT NULL,
    [LTVA]   VARCHAR (60)    NULL,
    [TTVA]   NUMERIC (18, 3) NULL,
    [TRIG]   VARCHAR (2)     NULL,
    [LACTIF] VARCHAR (2)     NULL,
    CONSTRAINT [PK_ESTIA_TVA] PRIMARY KEY CLUSTERED ([CTVA] ASC)
);

