CREATE TABLE [dbo].[ESTIA_PECRIP] (
    [CORG]      VARCHAR (4)     NOT NULL,
    [COPE]      VARCHAR (22)    NOT NULL,
    [CCG]       VARCHAR (28)    NOT NULL,
    [DECR]      DATE            NULL,
    [DVAL]      DATE            NULL,
    [CTYPECRI]  VARCHAR (6)     NULL,
    [LIB]       VARCHAR (60)    NULL,
    [MONTANT]   NUMERIC (17, 2) NULL,
    [SENS]      VARCHAR (2)     NULL,
    [NOPIECE]   VARCHAR (16)    NULL,
    [CJOURNAL]  VARCHAR (6)     NULL,
    [TRAIT]     VARCHAR (6)     NULL,
    [REF]       VARCHAR (42)    NULL,
    [TYPCPTA]   VARCHAR (4)     NULL,
    [CBANQUE]   VARCHAR (10)    NULL,
    [LOTDEP]    INT             NULL,
    [CFOUR]     VARCHAR (14)    NULL,
    [NORD]      INT             NOT NULL,
    [TYPTRV]    VARCHAR (2)     NULL,
    [CTYPOP]    VARCHAR (4)     NULL,
    [CPTAB]     VARCHAR (1)     NULL,
    [CTYPCOM]   VARCHAR (2)     NULL,
    [ORD]       INT             NULL,
    [GRORD]     INT             NULL,
    [NODOC]     VARCHAR (24)    NULL,
    [CLOT]      INT             NULL,
    [CMODREG]   VARCHAR (4)     NULL,
    [NOAVTS]    INT             NULL,
    [DECH]      DATE            NULL,
    [DFACT]     DATE            NULL,
    [TRIGD]     DATE            NULL,
    [UTIL]      VARCHAR (24)    NULL,
    [CTRANCHE]  INT             NULL,
    [CDEPR]     INT             NULL,
    [CPOSTE]    INT             NULL,
    [MTHT]      NUMERIC (17, 2) NULL,
    [MTTTC]     NUMERIC (17, 2) NULL,
    [TYPE]      VARCHAR (2)     NULL,
    [MTCONVERT] NUMERIC (17, 2) NULL,
    [DEVISE]    VARCHAR (1)     NULL,
    [NOMTIREUR] VARCHAR (60)    NULL,
    [CAGENCE]   VARCHAR (4)     NULL,
    [CCOMPTE]   VARCHAR (22)    NULL,
    [CPHASE]    VARCHAR (8)     NULL,
    [TTVA]      NUMERIC (17, 2) NULL,
    [TEMIGRA]   VARCHAR (2)     NULL,
    [PCELASM]   VARCHAR (2)     NULL,
    [REFINIT]   VARCHAR (42)    NULL,
    [P1LASM]    NUMERIC (15)    NULL,
    [P2LASM]    NUMERIC (15)    NULL,
    [S1TTVA]    NUMERIC (15)    NULL,
    [S2TTVA]    NUMERIC (15)    NULL,
    [REFITVA]   VARCHAR (42)    NULL,
    [MTVALASM]  NUMERIC (17, 2) NULL,
    [CSECTANA]  VARCHAR (16)    NULL,
    [CSECTREG]  VARCHAR (16)    NULL,
    [HTD]       NUMERIC (17, 2) NULL,
    [BANAL]     VARCHAR (100)   NULL,
    [REFDUPLI]  VARCHAR (42)    NULL,
    [MIGCOMPT]  INT             NULL
);

