CREATE TABLE [dbo].[ESTIA_ORG] (
    [PK_ORG]       INT             IDENTITY (1, 1) NOT NULL,
    [CORG]         VARCHAR (4)     NOT NULL,
    [LORG]         VARCHAR (64)    NULL,
    [RSOC]         VARCHAR (120)   NULL,
    [RUE]          VARCHAR (76)    NULL,
    [LIEUDIT]      VARCHAR (76)    NULL,
    [CPOS]         VARCHAR (10)    NULL,
    [VILLE]        VARCHAR (64)    NULL,
    [CCOMM]        INT             NULL,
    [SIRET]        VARCHAR (30)    NULL,
    [CAPE]         VARCHAR (12)    NULL,
    [TELPH]        VARCHAR (40)    NULL,
    [TELEX]        VARCHAR (40)    NULL,
    [FAX]          VARCHAR (40)    NULL,
    [CONSORG]      VARCHAR (4)     NULL,
    [DDEBEX]       DATE            NULL,
    [DFINEX]       DATE            NULL,
    [DDEB2EX]      DATE            NULL,
    [DFIN2EX]      DATE            NULL,
    [DDEB1EX]      DATE            NULL,
    [DFIN1EX]      DATE            NULL,
    [DDEBSEX]      DATE            NULL,
    [DFINSEX]      DATE            NULL,
    [DDERCLO]      DATE            NULL,
    [DDERCAN]      DATE            NULL,
    [TEMCLO]       INT             NULL,
    [CONTACT]      VARCHAR (60)    NULL,
    [CFONCTIO]     VARCHAR (10)    NULL,
    [TEMPATRI]     VARCHAR (1)     NULL,
    [CDOMSOC]      INT             NULL,
    [TRIG]         VARCHAR (2)     NULL,
    [DVOTE]        DATE            NULL,
    [INOM]         VARCHAR (60)    NULL,
    [IRUE]         VARCHAR (76)    NULL,
    [ILIEUDIT]     VARCHAR (76)    NULL,
    [IPOS]         VARCHAR (10)    NULL,
    [IVILLE]       VARCHAR (64)    NULL,
    [IBANQUE]      VARCHAR (10)    NULL,
    [IGUICHET]     VARCHAR (10)    NULL,
    [ICOMPTE]      VARCHAR (22)    NULL,
    [ILIBRIB]      VARCHAR (60)    NULL,
    [CPRESENT]     VARCHAR (12)    NULL,
    [DFICBAF]      DATE            NULL,
    [NOM]          VARCHAR (60)    NULL,
    [FCT]          VARCHAR (60)    NULL,
    [LIEU]         VARCHAR (60)    NULL,
    [CBAILLEUR]    VARCHAR (10)    NULL,
    [COTIERS]      VARCHAR (14)    NULL,
    [CIB]          VARCHAR (12)    NULL,
    [DFICDEC]      DATE            NULL,
    [DFICPUB]      DATE            NULL,
    [CNATGEST]     VARCHAR (4)     NULL,
    [FINACTIVITE]  DATE            NULL,
    [COTYPTIERS]   VARCHAR (2)     NULL,
    [CAPITAL]      NUMERIC (17, 2) NULL,
    [RESERVES]     NUMERIC (17, 2) NULL,
    [EMPRUNTS]     NUMERIC (17, 2) NULL,
    [CEXO]         VARCHAR (8)     NULL,
    [CEXO1]        VARCHAR (8)     NULL,
    [CEXO2]        VARCHAR (8)     NULL,
    [ASSUJ]        VARCHAR (1)     NULL,
    [NUMORG]       INT             NULL,
    [PEGAS]        DATE            NULL,
    [TRIGD]        DATE            NULL,
    [ORGPROMO]     VARCHAR (1)     NULL,
    [NOMBMP]       VARCHAR (80)    NULL,
    [XPLAN]        INT             NULL,
    [YPLAN]        INT             NULL,
    [LPLAN]        INT             NULL,
    [HPLAN]        INT             NULL,
    [RORG]         VARCHAR (4)     NULL,
    [TYPGEST]      VARCHAR (2)     NULL,
    [CARTPRO]      VARCHAR (40)    NULL,
    [REPRES]       VARCHAR (14)    NULL,
    [CSIREN]       VARCHAR (28)    NULL,
    [CSEQ]         VARCHAR (6)     NULL,
    [CARTET]       VARCHAR (40)    NULL,
    [CCATEG]       VARCHAR (4)     NULL,
    [CTIERS]       VARCHAR (14)    NULL,
    [CTYPTIERS]    VARCHAR (2)     NULL,
    [GATIERS]      VARCHAR (14)    NULL,
    [GATYPTIERS]   VARCHAR (2)     NULL,
    [LIMITEG]      DATE            NULL,
    [LIMITET]      DATE            NULL,
    [MTGARANT]     INT             NULL,
    [VILLEG]       VARCHAR (54)    NULL,
    [VILLET]       VARCHAR (54)    NULL,
    [DGARANT]      DATE            NULL,
    [MTGAR1]       INT             NULL,
    [IADRCOMP]     VARCHAR (76)    NULL,
    [ADRCOMP]      VARCHAR (76)    NULL,
    [TVACEE]       VARCHAR (30)    NULL,
    [D1FUSION]     DATE            NULL,
    [D2FUSION]     DATE            NULL,
    [SECTACT]      VARCHAR (10)    NULL,
    [ORGREF]       VARCHAR (2)     NULL,
    [HCATEG]       VARCHAR (4)     NULL,
    [CTYPIMP]      VARCHAR (6)     NULL,
    [EMAIL]        VARCHAR (200)   NULL,
    [RCS]          VARCHAR (100)   NULL,
    [ORG_ID]       INT             NULL,
    [ADRESSE_ID]   INT             NULL,
    [CEMETDEMUNIQ] VARCHAR (20)    NULL,
    [MIROIR]       VARCHAR (2)     NULL,
    [REFERENCE]    VARCHAR (60)    NULL,
    CONSTRAINT [PK_ESTIA_ORG] PRIMARY KEY CLUSTERED ([CORG] ASC)
);

