CREATE TABLE [dbo].[ESTIA_HDEPCS] (
    [PK_HDEPCS]        INT             IDENTITY (1, 1) NOT NULL,
    [FK_ORG]           INT             NULL,
    [FK_AGENCE]        INT             NULL,
    [FK_GROUPE]        INT             NULL,
    [FK_SCRITDP]       INT             NULL,
    [FK_BASE]          INT             NULL,
    [FK_ENTFAC]        INT             NULL,
    [FK_TIERS]         INT             NULL,
    [ECRAC_ID_RE]      INT             NULL,
    [CTRL_MT_ECRAC_RE] VARCHAR (3)     NULL,
    [ECRAC_ID_NR]      INT             NULL,
    [CTRL_MT_ECRAC_NR] VARCHAR (3)     NULL,
    [CORG]             VARCHAR (4)     NOT NULL,
    [CAGENCE]          VARCHAR (4)     NULL,
    [CGROUPE]          INT             NULL,
    [CCRITDP]          INT             NULL,
    [CSCRITDP]         INT             NULL,
    [DEFFETREG]        DATE            NULL,
    [REF]              VARCHAR (42)    NULL,
    [MTHT]             NUMERIC (17, 2) NULL,
    [MTTVA]            NUMERIC (17, 2) NULL,
    [TEXTDEP]          VARCHAR (1)     NULL,
    [MTRECUP]          NUMERIC (17, 2) NULL,
    [MTTC]             NUMERIC (17, 2) NULL,
    [TYPDEP]           VARCHAR (2)     NULL,
    [TRIG]             VARCHAR (2)     NULL,
    [MTBASE]           NUMERIC (17, 2) NULL,
    [MTNREC]           NUMERIC (17, 2) NULL,
    [MTTVADED]         NUMERIC (17, 2) NULL,
    [CTVA]             VARCHAR (4)     NULL,
    [PRORATA]          NUMERIC (17, 2) NULL,
    [CSECTANA]         VARCHAR (16)    NULL,
    [CSECTREG]         VARCHAR (16)    NULL,
    [LIBELLE]          VARCHAR (80)    NULL,
    [CCATEG]           VARCHAR (4)     NULL,
    [DEVHT]            NUMERIC (17, 2) NULL,
    [DEVTVA]           NUMERIC (17, 2) NULL,
    [DEVRECUP]         NUMERIC (17, 2) NULL,
    [DEVTTC]           NUMERIC (17, 2) NULL,
    [DEVBASE]          NUMERIC (17, 2) NULL,
    [DEVNREC]          NUMERIC (17, 2) NULL,
    [DEVTVADED]        NUMERIC (17, 2) NULL,
    [TEXTCOP]          VARCHAR (1)     NULL,
    [DATEC]            DATE            NULL,
    [NUMINV]           VARCHAR (50)    NULL,
    [RECUPTX]          NUMERIC (17, 2) NULL,
    [CNOMENM]          VARCHAR (22)    NULL,
    [TVACOMPTA]        VARCHAR (2)     NULL,
    [PROVHT]           VARCHAR (1)     NULL,
    [NORD]             INT             NULL,
    [HTRECUP]          NUMERIC (17, 2) NULL,
    [TTCRECUP]         NUMERIC (17, 2) NULL,
    [TVARECUP]         NUMERIC (17, 2) NULL,
    [ANAENC]           VARCHAR (2)     NULL,
    [MTTVADEDREC]      NUMERIC (17, 2) NULL,
    [EXTRAC]           VARCHAR (6)     NULL,
    [CMANDAT]          VARCHAR (16)    NULL,
    [CPRESTA]          VARCHAR (16)    NULL,
    [QTE]              NUMERIC (17, 2) NULL,
    [CEDIRGT]          VARCHAR (12)    NULL,
    [CENSEMBLE]        VARCHAR (20)    NULL,
    [RENOUV]           VARCHAR (2)     NULL,
    [ADF]              VARCHAR (2)     NULL,
    [TEXTPRO]          VARCHAR (1)     NULL
);

