CREATE TABLE [dbo].[ESTIA_IMMEUB] (
    [PK_IMMEUB]       INT             IDENTITY (1, 1) NOT NULL,
    [FK_ORG]          INT             NULL,
    [FK_AGENCE]       INT             NULL,
    [FK_GROUPE]       INT             NULL,
    [CORG]            VARCHAR (4)     NOT NULL,
    [CAGENCE]         VARCHAR (4)     NOT NULL,
    [CGROUPE]         INT             NOT NULL,
    [CIMMEUB]         INT             NOT NULL,
    [LIMMEUB]         VARCHAR (64)    NULL,
    [RUE]             VARCHAR (76)    NULL,
    [LIEUDIT]         VARCHAR (76)    NULL,
    [CPOS]            VARCHAR (10)    NULL,
    [VILLE]           VARCHAR (64)    NULL,
    [CCOMM]           INT             NULL,
    [CQUART]          VARCHAR (6)     NULL,
    [CSECTEUR]        VARCHAR (6)     NULL,
    [CBASSIN]         VARCHAR (6)     NULL,
    [CFACT]           VARCHAR (2)     NULL,
    [CCATHLM]         VARCHAR (6)     NULL,
    [CCATIMM]         VARCHAR (6)     NULL,
    [RCTIERS]         VARCHAR (14)    NULL,
    [DEBLOC]          DATE            NULL,
    [DATREHA]         DATE            NULL,
    [CFINANC]         VARCHAR (10)    NULL,
    [GETIERS]         VARCHAR (14)    NULL,
    [CENCAIS]         INT             NULL,
    [DATCONV]         DATE            NULL,
    [CONTCONV]        VARCHAR (60)    NULL,
    [DATDCONS]        DATE            NULL,
    [DATFCONS]        DATE            NULL,
    [DATACHAT]        DATE            NULL,
    [DATSERV]         DATE            NULL,
    [TEMPATRI]        VARCHAR (1)     NULL,
    [SSOL]            NUMERIC (17, 2) NULL,
    [LONG]            NUMERIC (17, 2) NULL,
    [LARG]            NUMERIC (17, 2) NULL,
    [HAUT]            NUMERIC (17, 2) NULL,
    [VOLUME]          NUMERIC (17, 2) NULL,
    [NBNIV]           INT             NULL,
    [COEFOBJ]         NUMERIC (19, 4) NULL,
    [COEFREL]         NUMERIC (19, 4) NULL,
    [CREGIS]          INT             NULL,
    [CZONE]           VARCHAR (6)     NULL,
    [LOYMAXI]         NUMERIC (18, 3) NULL,
    [RIMMEUB]         INT             NULL,
    [CTYPTOUR]        INT             NULL,
    [INTIERS]         VARCHAR (14)    NULL,
    [COEFSURL]        NUMERIC (20, 5) NULL,
    [FINGEST]         DATE            NULL,
    [GELLOC]          VARCHAR (1)     NULL,
    [GEOVAR]          VARCHAR (1)     NULL,
    [PRIXMARCHE]      NUMERIC (15)    NULL,
    [COTIERS]         VARCHAR (14)    NULL,
    [RCTYPTIERS]      VARCHAR (2)     NULL,
    [GETYPTIERS]      VARCHAR (2)     NULL,
    [COTYPTIERS]      VARCHAR (2)     NULL,
    [INTYPTIERS]      VARCHAR (2)     NULL,
    [TRIG]            VARCHAR (2)     NULL,
    [DOTIERS]         VARCHAR (14)    NULL,
    [DOTYPTIERS]      VARCHAR (2)     NULL,
    [DTRANSF]         DATE            NULL,
    [ANCSOC]          VARCHAR (4)     NULL,
    [ANCAG]           VARCHAR (4)     NULL,
    [MONTANT]         NUMERIC (17, 2) NULL,
    [DEXPERT]         DATE            NULL,
    [PRTYPTIERS]      VARCHAR (2)     NULL,
    [PRTIERS]         VARCHAR (14)    NULL,
    [PREPOND]         VARCHAR (1)     NULL,
    [SHORSOEUVRE]     NUMERIC (17, 2) NULL,
    [DVENTE]          DATE            NULL,
    [DAUTO]           DATE            NULL,
    [MTACHAT]         NUMERIC (17, 2) NULL,
    [MTVEN]           NUMERIC (17, 2) NULL,
    [VOTYPTIERS]      VARCHAR (2)     NULL,
    [VOTIERS]         VARCHAR (14)    NULL,
    [ACTYPTIERS]      VARCHAR (2)     NULL,
    [ACTIERS]         VARCHAR (14)    NULL,
    [PRXVENT]         NUMERIC (17, 2) NULL,
    [PRXPLAN]         NUMERIC (17, 2) NULL,
    [DATEVAL]         DATE            NULL,
    [NOTYPTIERS]      VARCHAR (2)     NULL,
    [NOTIERS]         VARCHAR (14)    NULL,
    [ODTIERS]         VARCHAR (14)    NULL,
    [ODTYPTIERS]      VARCHAR (2)     NULL,
    [TRTYPTIERS]      VARCHAR (2)     NULL,
    [TRTIERS]         VARCHAR (14)    NULL,
    [DATAUTO]         DATE            NULL,
    [PEGAS]           DATE            NULL,
    [TRIGD]           DATE            NULL,
    [NOMBMP]          VARCHAR (80)    NULL,
    [XPLAN]           INT             NULL,
    [YPLAN]           INT             NULL,
    [LPLAN]           INT             NULL,
    [HPLAN]           INT             NULL,
    [LBAT]            VARCHAR (60)    NULL,
    [GESTDEPUIS]      DATE            NULL,
    [CONVENT]         VARCHAR (1)     NULL,
    [CARROND]         INT             NULL,
    [ADRCOMP]         VARCHAR (76)    NULL,
    [DDEBTRAV]        DATE            NULL,
    [DFINTRAV]        DATE            NULL,
    [SURFINV]         NUMERIC (17, 2) NULL,
    [SURFPRECOM]      NUMERIC (17, 2) NULL,
    [COMMENT]         VARCHAR (2100)  NULL,
    [MIGCOMPT]        INT             NULL,
    [TEMMAJ]          VARCHAR (2)     NULL,
    [DATMAJ]          DATE            NULL,
    [PREMANN]         INT             NULL,
    [SOUMTFPB]        VARCHAR (1)     NULL,
    [CDEPART]         VARCHAR (4)     NULL,
    [ADRESSE_ID]      INT             NULL,
    [ARCHIVE]         VARCHAR (1)     NULL,
    [BATIMENT_ID]     INT             NULL,
    [CETATBATI]       VARCHAR (10)    NULL,
    [CETATIMMEUB]     VARCHAR (10)    NULL,
    [CFONCTION]       VARCHAR (10)    NULL,
    [CINCENDIE]       VARCHAR (6)     NULL,
    [COMBLE]          VARCHAR (1)     NULL,
    [CSECURITE]       VARCHAR (40)    NULL,
    [CSFONCTION]      VARCHAR (10)    NULL,
    [DFEXONERATION]   DATE            NULL,
    [DPREVACHAT]      DATE            NULL,
    [DPREVENT]        DATE            NULL,
    [DRENOVATION]     DATE            NULL,
    [GROUPE_ID]       INT             NULL,
    [HAUTEUR]         NUMERIC (17, 2) NULL,
    [IMMEUB_ID]       INT             NULL,
    [LARGEUR]         NUMERIC (17, 2) NULL,
    [LONGUEUR]        NUMERIC (17, 2) NULL,
    [NBASCENSEURS]    INT             NULL,
    [NBCABLE]         INT             NULL,
    [NBCAVES]         INT             NULL,
    [NBENTREES]       INT             NULL,
    [NBENTREPOTS]     INT             NULL,
    [NBEXTINCTEURS]   INT             NULL,
    [NBIMMEUB]        INT             NULL,
    [NBLOCAUX]        INT             NULL,
    [NBNIVEAUX]       INT             NULL,
    [NBSOUSOLS]       INT             NULL,
    [NBVIDEORDURE]    INT             NULL,
    [NBVMC]           INT             NULL,
    [NOMLONG]         VARCHAR (140)   NULL,
    [REFERENCE]       VARCHAR (60)    NULL,
    [SANITAIRE]       VARCHAR (1)     NULL,
    [SHOB]            NUMERIC (17, 2) NULL,
    [SURFCOMMERCIALE] NUMERIC (17, 2) NULL,
    [SURFDEPOT]       NUMERIC (17, 2) NULL,
    [SURFENTREPOT]    NUMERIC (17, 2) NULL,
    [SURFGRAPHIQUE]   NUMERIC (17, 2) NULL,
    [SREELLE]         NUMERIC (17, 2) NULL,
    [SURFLOCAUX]      NUMERIC (17, 2) NULL,
    [SURFRESERVE]     NUMERIC (17, 2) NULL,
    [SURFSUCCURSALE]  NUMERIC (17, 2) NULL,
    [SURFTERRAIN]     NUMERIC (17, 2) NULL,
    [TCOMMUN]         VARCHAR (1)     NULL,
    [TLOCATION]       VARCHAR (1)     NULL,
    [TOCCUPATION]     VARCHAR (1)     NULL,
    [ANCSOC_ID]       INT             NULL,
    [ANCAG_ID]        INT             NULL,
    [ACTIERS_ID]      INT             NULL,
    [DOTIERS_ID]      INT             NULL,
    [ODTIERS_ID]      INT             NULL,
    [VOTIERS_ID]      INT             NULL,
    [NOTIERS_ID]      INT             NULL,
    [PRTIERS_ID]      INT             NULL,
    [TRTIERS_ID]      INT             NULL,
    [DACHAT]          DATE            NULL,
    CONSTRAINT [PK_ESTIA_IMMEUB] PRIMARY KEY CLUSTERED ([CORG] ASC, [CAGENCE] ASC, [CGROUPE] ASC, [CIMMEUB] ASC)
);

