CREATE TABLE [dbo].[ESTIA_TYPCOM] (
    [CTYPCOM] VARCHAR (50) NOT NULL,
    [LTYPCOM] VARCHAR (50) NULL,
    [TRIG]    VARCHAR (50) NULL,
    [UTILPI]  VARCHAR (50) NULL,
    [LACTIF]  VARCHAR (50) NULL,
    CONSTRAINT [PK_ESTIA_TYPCOM] PRIMARY KEY CLUSTERED ([CTYPCOM] ASC)
);

