CREATE TABLE [dbo].[ESTIA_APE] (
    [CAPE]   VARCHAR (50)  NOT NULL,
    [LAPE]   VARCHAR (130) NULL,
    [TRIG]   VARCHAR (100) NULL,
    [LACTIF] VARCHAR (100) NULL,
    CONSTRAINT [PK_ESTIA_APE] PRIMARY KEY CLUSTERED ([CAPE] ASC)
);

