CREATE TABLE [dbo].[ESTIA_TYPROC] (
    [CTYPROC]  VARCHAR (50)  NULL,
    [LISTUTIL] VARCHAR (350) NULL,
    [LTYPROC]  VARCHAR (50)  NULL,
    [TEMCTX]   VARCHAR (50)  NULL,
    [TRIG]     VARCHAR (50)  NULL
);

