CREATE TABLE [dbo].[ESTIA_NATRUB] (
    [CNATRUB] VARCHAR (2)  NOT NULL,
    [LNATRUB] VARCHAR (60) NULL,
    [TRIG]    VARCHAR (2)  NULL,
    [LACTIF]  VARCHAR (2)  NULL,
    CONSTRAINT [PK_ESTIA_NATRUB] PRIMARY KEY CLUSTERED ([CNATRUB] ASC)
);

