CREATE TABLE [dbo].[ESTIA_CRIT] (
    [NOFICH] VARCHAR (16) NOT NULL,
    [CLCRIT] VARCHAR (10) NOT NULL,
    [CCRIT]  VARCHAR (10) NOT NULL,
    [LCRIT]  VARCHAR (60) NULL,
    [TRIG]   VARCHAR (2)  NULL,
    [LACTIF] VARCHAR (1)  NULL,
    CONSTRAINT [PK_ESTIA_CRIT] PRIMARY KEY CLUSTERED ([NOFICH] ASC, [CLCRIT] ASC, [CCRIT] ASC)
);

