CREATE TABLE [dbo].[ESTIA_POPE] (
    [PK_POPE]     INT             IDENTITY (1, 1) NOT NULL,
    [CORG]        VARCHAR (4)     NOT NULL,
    [COPE]        VARCHAR (22)    NOT NULL,
    [LOPE]        VARCHAR (60)    NULL,
    [RUE]         VARCHAR (76)    NULL,
    [LIEUDIT]     VARCHAR (76)    NULL,
    [VILLE]       VARCHAR (64)    NULL,
    [CPOS]        VARCHAR (10)    NULL,
    [CCOMM]       INT             NULL,
    [DACQ]        DATE            NULL,
    [MTACQ]       NUMERIC (17, 2) NULL,
    [MTFRACQ]     NUMERIC (17, 2) NULL,
    [NTIERS]      VARCHAR (14)    NULL,
    [ACTIV]       VARCHAR (2)     NULL,
    [COMMENT]     VARCHAR (1000)  NULL,
    [CTVA]        VARCHAR (4)     NULL,
    [COMPTENGA]   VARCHAR (2)     NULL,
    [DORS]        DATE            NULL,
    [CPTVENT]     VARCHAR (4)     NULL,
    [DOCHAN]      DATE            NULL,
    [ADCHAN]      INT             NULL,
    [MDCHAN]      INT             NULL,
    [DDCOM]       DATE            NULL,
    [DFCOM]       DATE            NULL,
    [DPV]         DATE            NULL,
    [DDD]         DATE            NULL,
    [DFGAR]       DATE            NULL,
    [MTPAPGR]     NUMERIC (17, 2) NULL,
    [NUMOC]       VARCHAR (20)    NULL,
    [DPRELIM]     DATE            NULL,
    [DAUTOR]      DATE            NULL,
    [DLANCOP]     DATE            NULL,
    [DEPIECE]     DATE            NULL,
    [PERSTDEF]    VARCHAR (12)    NULL,
    [DERPERST]    VARCHAR (12)    NULL,
    [DACHEV]      DATE            NULL,
    [CSCHEMREF]   VARCHAR (8)     NULL,
    [CTIERS]      VARCHAR (14)    NULL,
    [CAGENCE]     VARCHAR (4)     NULL,
    [IOUC]        VARCHAR (2)     NULL,
    [DDGAR]       DATE            NULL,
    [DASSYN]      DATE            NULL,
    [STIERS]      VARCHAR (14)    NULL,
    [DCLOTU]      DATE            NULL,
    [CSECTCLI]    VARCHAR (10)    NULL,
    [CZGEO]       INT             NULL,
    [SHONTOT]     NUMERIC (17, 2) NULL,
    [SHABTOT]     NUMERIC (17, 2) NULL,
    [NBRECEP]     INT             NULL,
    [DREF]        DATE            NULL,
    [SANXTOT]     NUMERIC (17, 2) NULL,
    [SCORTOTC]    NUMERIC (17, 2) NULL,
    [SCORTOTR]    NUMERIC (17, 2) NULL,
    [DPREC]       DATE            NULL,
    [MTIERS]      VARCHAR (14)    NULL,
    [CBANQUE]     VARCHAR (14)    NULL,
    [CFPAP]       NUMERIC (17, 2) NULL,
    [VTIERS]      VARCHAR (14)    NULL,
    [DCERTIF]     DATE            NULL,
    [CLABCONS]    VARCHAR (210)   NULL,
    [DDOSLOC]     DATE            NULL,
    [DMHEAU]      DATE            NULL,
    [DDPLOC]      DATE            NULL,
    [CFINPAL]     VARCHAR (100)   NULL,
    [NOMTECH]     VARCHAR (80)    NULL,
    [DDECFIN]     DATE            NULL,
    [NDECFIN]     VARCHAR (16)    NULL,
    [DEFFIN]      DATE            NULL,
    [NOCONV]      VARCHAR (60)    NULL,
    [TRESP]       VARCHAR (14)    NULL,
    [MRESP]       VARCHAR (12)    NULL,
    [MTCOMM]      NUMERIC (17, 2) NULL,
    [POURCOMM]    NUMERIC (17, 2) NULL,
    [CNATPROD]    VARCHAR (6)     NULL,
    [ATIERS]      VARCHAR (14)    NULL,
    [VISUTVA]     VARCHAR (2)     NULL,
    [MTX]         VARCHAR (2)     NULL,
    [MTSTI]       NUMERIC (17, 2) NULL,
    [DDLOC]       DATE            NULL,
    [ANCNEUF]     VARCHAR (2)     NULL,
    [PXLOYM2]     NUMERIC (17, 2) NULL,
    [NBLGT]       INT             NULL,
    [DLIV]        DATE            NULL,
    [MISSION]     VARCHAR (4)     NULL,
    [DSIGCON]     DATE            NULL,
    [TXHON]       NUMERIC (17, 2) NULL,
    [CPRES]       VARCHAR (14)    NULL,
    [NATURE]      VARCHAR (60)    NULL,
    [NBJR1]       INT             NULL,
    [NBJR2]       INT             NULL,
    [CFI]         VARCHAR (2)     NULL,
    [RISQUE]      NUMERIC (17, 2) NULL,
    [FENGAGE]     NUMERIC (17, 2) NULL,
    [PRESIDAS]    VARCHAR (60)    NULL,
    [DESPVERT]    DATE            NULL,
    [BETIERS]     VARCHAR (14)    NULL,
    [BCTIERS]     VARCHAR (14)    NULL,
    [IGTIERS]     VARCHAR (14)    NULL,
    [ASTIERS]     VARCHAR (14)    NULL,
    [COOTIERS]    VARCHAR (14)    NULL,
    [GTIERS]      VARCHAR (14)    NULL,
    [SLOTTOT]     NUMERIC (17, 2) NULL,
    [UNITTOT]     NUMERIC (17, 2) NULL,
    [MILTOT]      VARCHAR (1)     NULL,
    [CSTE]        VARCHAR (2)     NULL,
    [VETIERS]     VARCHAR (14)    NULL,
    [REFCONT]     VARCHAR (16)    NULL,
    [CCPTE]       VARCHAR (22)    NULL,
    [PTIERS]      VARCHAR (14)    NULL,
    [COMVE]       NUMERIC (17, 2) NULL,
    [REMPRES]     NUMERIC (17, 2) NULL,
    [PRIMPAR]     NUMERIC (17, 2) NULL,
    [DETTIERS]    VARCHAR (14)    NULL,
    [DPORS]       DATE            NULL,
    [DPDD]        DATE            NULL,
    [DPCLOTU]     DATE            NULL,
    [DPLIV]       DATE            NULL,
    [CTYPOP]      VARCHAR (4)     NULL,
    [CASMOD]      VARCHAR (10)    NULL,
    [ASSUTVA]     VARCHAR (1)     NULL,
    [DESTOCK]     VARCHAR (6)     NULL,
    [DPACHEV]     DATE            NULL,
    [CTRANCHE]    INT             NULL,
    [PRORATA]     NUMERIC (17, 2) NULL,
    [LDECID]      INT             NULL,
    [DDECID]      DATE            NULL,
    [TEMOIN]      VARCHAR (1)     NULL,
    [DSAD]        DATE            NULL,
    [LASMCTVA]    VARCHAR (4)     NULL,
    [LPRORATA]    NUMERIC (17, 2) NULL,
    [MIXTE]       VARCHAR (1)     NULL,
    [DDEFLASM]    VARCHAR (1000)  NULL,
    [CPAYS]       VARCHAR (6)     NULL,
    [CAPREV]      NUMERIC (17, 2) NULL,
    [ETAT]        VARCHAR (40)    NULL,
    [CBORDERO]    VARCHAR (4)     NULL,
    [CJOURNAL]    VARCHAR (6)     NULL,
    [CETAT]       VARCHAR (4)     NULL,
    [TYPE]        VARCHAR (2)     NULL,
    [DEBENC]      VARCHAR (2)     NULL,
    [CTYPDEST]    VARCHAR (6)     NULL,
    [PAICJOURNAL] VARCHAR (6)     NULL,
    [PAICBORDERO] VARCHAR (4)     NULL,
    [DDSTK]       DATE            NULL,
    [NBACQ]       INT             NULL,
    [CRITLIB1]    VARCHAR (60)    NULL,
    [CRITLIB2]    VARCHAR (60)    NULL,
    [CRITLIB3]    VARCHAR (60)    NULL,
    [MASQUEE]     VARCHAR (1)     NULL,
    [ADRCOMP]     VARCHAR (76)    NULL,
    [CFISCAL]     VARCHAR (6)     NULL,
    [CMANDAT]     VARCHAR (16)    NULL,
    [CGROUPE]     INT             NULL,
    [CIMMEUB]     INT             NULL,
    CONSTRAINT [PK_ESTIA_POPE] PRIMARY KEY CLUSTERED ([CORG] ASC, [COPE] ASC)
);

