CREATE TABLE [dbo].[ESTIA_AGENCE] (
    [PK_AGENCE]  INT             IDENTITY (1, 1) NOT NULL,
    [FK_ORG]     INT             NULL,
    [CORG]       VARCHAR (4)     NOT NULL,
    [CAGENCE]    VARCHAR (4)     NOT NULL,
    [LAGENCE]    VARCHAR (64)    NULL,
    [RSOC]       VARCHAR (120)   NULL,
    [RUE]        VARCHAR (76)    NULL,
    [LIEUDIT]    VARCHAR (76)    NULL,
    [CPOS]       VARCHAR (10)    NULL,
    [VILLE]      VARCHAR (64)    NULL,
    [CCOMM]      INT             NULL,
    [TELEX]      VARCHAR (40)    NULL,
    [TELPH]      VARCHAR (40)    NULL,
    [FAX]        VARCHAR (40)    NULL,
    [CONTACT]    VARCHAR (60)    NULL,
    [CFONCTIO]   VARCHAR (60)    NULL,
    [TEMPATRI]   VARCHAR (1)     NULL,
    [COTIERS]    VARCHAR (14)    NULL,
    [TRIG]       VARCHAR (2)     NULL,
    [COTYPTIERS] VARCHAR (2)     NULL,
    [TXBIBLITA]  NUMERIC (17, 2) NULL,
    [CEMPLOY]    INT             NULL,
    [NUMAGENCE]  INT             NULL,
    [PEGAS]      DATE            NULL,
    [TRIGD]      DATE            NULL,
    [NOMBMP]     VARCHAR (80)    NULL,
    [XPLAN]      INT             NULL,
    [YPLAN]      INT             NULL,
    [LPLAN]      INT             NULL,
    [HPLAN]      INT             NULL,
    [ADRCOMP]    VARCHAR (76)    NULL,
    [CEMPLOY2]   INT             NULL,
    [ORG_ID]     INT             NULL,
    [AGENCE_ID]  INT             NULL,
    [ADRESSE_ID] INT             NULL,
    [REFERENCE]  VARCHAR (60)    NULL,
    CONSTRAINT [PK_ESTIA_AGENCE] PRIMARY KEY CLUSTERED ([CORG] ASC, [CAGENCE] ASC)
);

