CREATE TABLE [dbo].[ESTIA_INTBT] (
    [PK_INTBT]    INT             IDENTITY (1, 1) NOT NULL,
    [FK_TIERS]    INT             NULL,
    [FK_MANDAT]   INT             NULL,
    [FK_ORG]      INT             NULL,
    [FK_AGENCE]   INT             NULL,
    [FK_GROUPE]   INT             NULL,
    [CORG]        VARCHAR (4)     NOT NULL,
    [NODEM]       INT             NOT NULL,
    [NOINTBT]     INT             NOT NULL,
    [CSTE1]       VARCHAR (4)     NOT NULL,
    [CSTE2]       VARCHAR (4)     NULL,
    [CEMPLOY]     INT             NULL,
    [CCORETA]     VARCHAR (4)     NULL,
    [IEMPLOY]     INT             NULL,
    [CTYPTIERS]   VARCHAR (2)     NULL,
    [CTIERS]      VARCHAR (14)    NULL,
    [DATCREA]     DATE            NULL,
    [DATREND]     DATE            NULL,
    [HHREND]      VARCHAR (4)     NULL,
    [MNREND]      VARCHAR (4)     NULL,
    [TEMCLO]      VARCHAR (1)     NULL,
    [DATCLO]      DATE            NULL,
    [CMOTCLO]     VARCHAR (4)     NULL,
    [DATFINT]     DATE            NULL,
    [DATDINT]     DATE            NULL,
    [TERMINE]     VARCHAR (1)     NULL,
    [DATFINTRAV]  DATE            NULL,
    [CNATTRAV]    VARCHAR (4)     NULL,
    [DEJEDIT]     VARCHAR (1)     NULL,
    [DATREL1]     DATE            NULL,
    [DATREL2]     DATE            NULL,
    [DLEDIT]      DATE            NULL,
    [LAEDIT]      VARCHAR (1)     NULL,
    [QUITUS]      VARCHAR (1)     NULL,
    [TRIG]        VARCHAR (4)     NULL,
    [CNATPRES]    VARCHAR (6)     NULL,
    [TEMLIG]      VARCHAR (1)     NULL,
    [DLIMFAC]     DATE            NULL,
    [DATDEBTRAV]  DATE            NULL,
    [DATRELFAC1]  DATE            NULL,
    [DATRELFAC2]  DATE            NULL,
    [TEMBUD]      VARCHAR (1)     NULL,
    [DATPREMFAC]  DATE            NULL,
    [NORD]        INT             NULL,
    [DATFACREG]   DATE            NULL,
    [CONGE]       VARCHAR (1)     NULL,
    [DATREP]      DATE            NULL,
    [PENALITE]    VARCHAR (120)   NULL,
    [PEGAS]       DATE            NULL,
    [RABAIS]      VARCHAR (1)     NULL,
    [DATRET]      DATE            NULL,
    [REFINTERF]   VARCHAR (40)    NULL,
    [EDITFAC]     VARCHAR (1)     NULL,
    [PRORATA]     NUMERIC (17, 2) NULL,
    [GESTIONHT]   VARCHAR (1)     NULL,
    [VALIDE]      VARCHAR (4)     NULL,
    [DETAT]       DATE            NULL,
    [CTVA]        VARCHAR (4)     NULL,
    [TEMINT]      VARCHAR (4)     NULL,
    [DATINT]      DATE            NULL,
    [DATEXP]      DATE            NULL,
    [CNOMENM]     VARCHAR (22)    NULL,
    [MODTVA]      VARCHAR (4)     NULL,
    [CMANDAT]     VARCHAR (16)    NULL,
    [CCRITDP]     INT             NULL,
    [CSCRITDP]    INT             NULL,
    [TXHAB]       NUMERIC (17, 2) NULL,
    [AGEIMM]      INT             NULL,
    [ATTESTVA]    VARCHAR (1)     NULL,
    [REFORD]      VARCHAR (42)    NULL,
    [NUMINV]      VARCHAR (50)    NULL,
    [CENSEMBLE]   VARCHAR (20)    NULL,
    [DRELDEVP1]   DATE            NULL,
    [DRELDEVP2]   DATE            NULL,
    [DRELDEVP3]   DATE            NULL,
    [DRELDEVE1]   DATE            NULL,
    [DRELDEVE2]   DATE            NULL,
    [DRELDEVE3]   DATE            NULL,
    [MIGCOMPT]    INT             NULL,
    [CNATHON]     VARCHAR (4)     NULL,
    [NATCTVA]     VARCHAR (4)     NULL,
    [NATMTHT]     NUMERIC (17, 2) NULL,
    [NATMTTC]     NUMERIC (17, 2) NULL,
    [DATEMAIL]    DATE            NULL,
    [ASSDO]       VARCHAR (100)   NULL,
    [CAGENCE]     VARCHAR (4)     NULL,
    [CGROUPE]     INT             NULL,
    [CBATIMENT]   VARCHAR (12)    NULL,
    [CIMMEUB]     INT             NULL,
    [CLOCAL]      INT             NULL,
    [CPIECE]      VARCHAR (12)    NULL,
    [OCC]         INT             NULL,
    [NOEDL]       INT             NULL,
    [LIBELLE]     VARCHAR (60)    NULL,
    [DATDEMANDE]  DATE            NULL,
    [DATSYSTEME]  DATE            NULL,
    [DATVALIDD]   DATE            NULL,
    [LIBREND]     VARCHAR (60)    NULL,
    [BATREND]     VARCHAR (12)    NULL,
    [ESCREND]     VARCHAR (10)    NULL,
    [ETAGEREND]   VARCHAR (10)    NULL,
    [CCAUSEBT]    VARCHAR (4)     NULL,
    [MONOPAT]     VARCHAR (1)     NULL,
    [DELAI]       INT             NULL,
    [DATSOUFIN]   DATE            NULL,
    [CURGENCE]    INT             NULL,
    [CSOLLICIT]   INT             NULL,
    [CAPTYPTIERS] VARCHAR (4)     NULL,
    [CAPTIERS]    VARCHAR (14)    NULL,
    [DATEDIT]     DATE            NULL,
    [PREENREG]    VARCHAR (1)     NULL,
    [FACTURE]     VARCHAR (1)     NULL,
    [INVALIDE]    VARCHAR (2)     NULL,
    [EDITFALOC]   VARCHAR (1)     NULL,
    [ETAT]        VARCHAR (4)     NULL,
    [LASM]        VARCHAR (1)     NULL,
    [DCOMPTA]     DATE            NULL,
    [HTENGAGE]    NUMERIC (17, 2) NULL,
    [TVAENGAGE]   NUMERIC (17, 2) NULL,
    [HTREALISE]   NUMERIC (17, 2) NULL,
    [TVAREALISE]  NUMERIC (17, 2) NULL,
    [CONVENT]     VARCHAR (1)     NULL,
    [COMPTAREGIE] VARCHAR (4)     NULL,
    [TYPENGAG]    VARCHAR (4)     NULL,
    [CCSTE]       VARCHAR (6)     NULL,
    [CCTYPTIERS]  VARCHAR (4)     NULL,
    [CCTIERS]     VARCHAR (14)    NULL,
    [NVVALIDE]    VARCHAR (4)     NULL,
    [ACTEVT_ID]   INT             NULL,
    [TYPOCC]      VARCHAR (4)     NULL,
    [TYPADB]      VARCHAR (4)     NULL,
    CONSTRAINT [PK_ESTIA_INTBT] PRIMARY KEY CLUSTERED ([CORG] ASC, [NOINTBT] ASC, [CSTE1] ASC)
);

