CREATE TABLE [dbo].[ESTIA_ECRIB] (
    [PK_ECRIB]    INT             IDENTITY (1, 1) NOT NULL,
    [FK_ORG]      INT             NULL,
    [FK_AGENCE]   INT             NULL,
    [FK_GROUPE]   INT             NULL,
    [FK_CRITDP]   INT             NULL,
    [FK_SCRITDP]  INT             NULL,
    [FK_BASE]     INT             NULL,
    [FK_INTBT]    INT             NULL,
    [FK_CTRTIERS] INT             NULL,
    [FK_TIERS]    INT             NULL,
    [CSTE]        VARCHAR (4)     NULL,
    [CORG]        VARCHAR (4)     NULL,
    [CEXO]        VARCHAR (8)     NULL,
    [TYPPOS]      VARCHAR (2)     NULL,
    [CCB]         VARCHAR (28)    NULL,
    [MONTANT]     NUMERIC (17, 2) NULL,
    [SENS]        VARCHAR (2)     NULL,
    [TYPBON]      VARCHAR (6)     NULL,
    [NOBON]       INT             NULL,
    [CTRAIT]      VARCHAR (6)     NULL,
    [LIBELLE]     VARCHAR (80)    NULL,
    [CJOURNAL]    VARCHAR (6)     NULL,
    [DATEC]       DATE            NULL,
    [PERIODE]     VARCHAR (12)    NOT NULL,
    [REF]         VARCHAR (42)    NOT NULL,
    [ORD]         INT             NOT NULL,
    [CCG]         VARCHAR (28)    NULL,
    [CCRITDP]     INT             NULL,
    [TRIG]        VARCHAR (2)     NULL,
    [NOPIECE]     VARCHAR (16)    NULL,
    [REFMAN]      VARCHAR (42)    NULL,
    [TYPLIG]      VARCHAR (2)     NULL,
    [RECUP]       VARCHAR (1)     NULL,
    [REGMAN]      VARCHAR (400)   NULL,
    [UTIL]        VARCHAR (24)    NULL,
    [INFO]        VARCHAR (44)    NULL,
    [ANALYT]      VARCHAR (1)     NULL,
    [CTYPCOM]     VARCHAR (2)     NULL,
    [BANAL]       VARCHAR (40)    NULL,
    [REFART]      VARCHAR (1200)  NULL,
    [QTE]         NUMERIC (17, 2) NULL,
    [PUHT]        NUMERIC (17, 2) NULL,
    [PRORATA]     NUMERIC (17, 2) NULL,
    [CTVA]        VARCHAR (4)     NULL,
    [CAGENCE]     VARCHAR (4)     NULL,
    [CGROUPE]     INT             NULL,
    [MTTC]        NUMERIC (17, 2) NULL,
    [MTHT]        NUMERIC (17, 2) NULL,
    [NODOC]       VARCHAR (24)    NULL,
    [PUHTDEV]     NUMERIC (17, 2) NULL,
    [CNOMENM]     VARCHAR (22)    NULL,
    [CSCRITDP]    INT             NULL,
    [PROVHT]      VARCHAR (1)     NULL,
    CONSTRAINT [PK_ESTIA_ECRIB] PRIMARY KEY CLUSTERED ([REF] ASC, [ORD] ASC, [PERIODE] ASC)
);

