CREATE TABLE [dbo].[ESTIA_PTYPOP] (
    [CTYPOP]         NVARCHAR (255) NULL,
    [LTYPOP]         NVARCHAR (255) NULL,
    [ACCESS]         NVARCHAR (255) NULL,
    [INDCOL]         NVARCHAR (255) NULL,
    [TEMAPPEL]       NVARCHAR (255) NULL,
    [ACTOPE]         NVARCHAR (255) NULL,
    [CMODCOMP]       NVARCHAR (255) NULL,
    [GESTCOMP]       NVARCHAR (255) NULL,
    [RENOUV]         NVARCHAR (255) NULL,
    [LACTIF]         NVARCHAR (255) NULL,
    [IMPBUDG]        NVARCHAR (255) NULL,
    [IMPCOMPTA]      NVARCHAR (255) NULL,
    [IMPTIERSCLIENT] NVARCHAR (255) NULL,
    [IMPAXA]         NVARCHAR (255) NULL,
    [RECUP]          NVARCHAR (255) NULL,
    [MIGCOMP]        FLOAT (53)     NULL
);

