CREATE TABLE [dbo].[ESTIA_MANPAT] (
    [PK_MANPAT] INT             IDENTITY (1, 1) NOT NULL,
    [FK_MANGES] INT             NULL,
    [FK_ORG]    INT             NULL,
    [FK_AGENCE] INT             NULL,
    [FK_GROUPE] INT             NULL,
    [FK_IMMEUB] INT             NULL,
    [FK_LOCAL]  INT             NULL,
    [CTYPTIERS] VARCHAR (2)     NULL,
    [CTIERS]    VARCHAR (14)    NULL,
    [CMANDAT]   VARCHAR (16)    NULL,
    [NIVEAU]    VARCHAR (2)     NULL,
    [CORG]      VARCHAR (4)     NULL,
    [CAGENCE]   VARCHAR (4)     NULL,
    [CGROUPE]   INT             NULL,
    [CIMMEUB]   INT             NULL,
    [CLOCAL]    INT             NULL,
    [MTCOL1]    NUMERIC (17, 2) NULL,
    [MTCOL2]    NUMERIC (17, 2) NULL,
    [MTCOL3]    NUMERIC (17, 2) NULL,
    [MTCOL4]    NUMERIC (17, 2) NULL,
    [MTCOL5]    NUMERIC (17, 2) NULL,
    [MTCOL6]    NUMERIC (17, 2) NULL,
    [MTVENT]    NUMERIC (17, 2) NULL,
    [TRIG]      VARCHAR (2)     NULL,
    [MIGCOMPT]  INT             NULL,
    [CMANDOM]   VARCHAR (2)     NULL
);

