CREATE TABLE [dbo].[ESTIA_TYPECRI] (
    [CTYPECRI] VARCHAR (6)  NOT NULL,
    [LTYPECRI] VARCHAR (60) NULL,
    [TRIG]     VARCHAR (2)  NULL,
    [RTYPECRI] VARCHAR (30) NULL,
    [TASS]     VARCHAR (1)  NULL,
    [DCN]      VARCHAR (2)  NULL,
    [RVA]      VARCHAR (2)  NULL,
    [PRL]      VARCHAR (2)  NULL,
    [PIN]      VARCHAR (2)  NULL,
    [DEA]      VARCHAR (2)  NULL,
    [FAC]      VARCHAR (1)  NULL,
    [RPRL]     VARCHAR (2)  NULL,
    [RAUP]     VARCHAR (2)  NULL,
    [LACTIF]   VARCHAR (1)  NULL,
    CONSTRAINT [PK_ESTIA_TYPECRI] PRIMARY KEY CLUSTERED ([CTYPECRI] ASC)
);

