CREATE TABLE [dbo].[ESTIA_COMMENT] (
    [NOFICH]      VARCHAR (8)    NULL,
    [CLEFICH]     VARCHAR (21)   NULL,
    [COMMENT_]    VARCHAR (1074) NULL,
    [NPAGE]       SMALLINT       NULL,
    [AUTEUR]      VARCHAR (12)   NULL,
    [DCREA]       DATETIME       NULL,
    [DPREV]       VARCHAR (MAX)  NULL,
    [DREEL]       VARCHAR (MAX)  NULL,
    [TYPE]        VARCHAR (1)    NULL,
    [ETAT]        VARCHAR (1)    NULL,
    [REFER]       VARCHAR (1)    NULL,
    [INTERLOC]    VARCHAR (1)    NULL,
    [SECTEUR]     VARCHAR (5)    NULL,
    [DEST]        VARCHAR (1)    NULL,
    [SUP]         VARCHAR (1)    NULL,
    [MODIF]       VARCHAR (1)    NULL,
    [DAVIS]       VARCHAR (MAX)  NULL,
    [DBANAL]      VARCHAR (MAX)  NULL,
    [MONTANT]     SMALLINT       NULL,
    [BANAL]       VARCHAR (1)    NULL,
    [MOTCLE]      VARCHAR (1)    NULL,
    [CLE2]        VARCHAR (1)    NULL,
    [HEURE]       VARCHAR (50)   NULL,
    [DMODIF]      DATETIME       NULL,
    [POSTE]       VARCHAR (1)    NULL,
    [CCATCOMMENT] VARCHAR (1)    NULL,
    [LIBELLE]     VARCHAR (1)    NULL,
    [NIVEAU]      VARCHAR (1)    NULL,
    [UTIL]        VARCHAR (1)    NULL
);

