CREATE TABLE [dbo].[ESTIA_CATEG] (
    [LISTORG]   VARCHAR (400) NULL,
    [CCATEG]    VARCHAR (4)   NOT NULL,
    [LCATEG]    VARCHAR (60)  NULL,
    [CTYPTIERS] VARCHAR (2)   NULL,
    [FJOURNAL]  VARCHAR (6)   NULL,
    [AJOURNAL]  VARCHAR (6)   NULL,
    [DERCLO]    DATE          NULL,
    [BALEDIT]   VARCHAR (2)   NULL,
    [XJOURNAL]  VARCHAR (6)   NULL,
    [TRIG]      VARCHAR (2)   NULL,
    [LACTIF]    VARCHAR (2)   NULL,
    CONSTRAINT [PK_ESTIA_CATEG] PRIMARY KEY CLUSTERED ([CCATEG] ASC)
);

