CREATE TABLE [dbo].[ESTIA_NUMI] (
    [CNUMI]  VARCHAR (10) NOT NULL,
    [LNUMI]  VARCHAR (60) NULL,
    [PERIOD] VARCHAR (30) NULL,
    [TRIG]   VARCHAR (2)  NULL,
    [LACTIF] VARCHAR (2)  NULL,
    CONSTRAINT [PK_ESTIA_NUMI] PRIMARY KEY CLUSTERED ([CNUMI] ASC)
);

