CREATE TABLE [dbo].[ESTIA_PDEPOP] (
    [PK_PDEPOP]    INT             IDENTITY (1, 1) NOT NULL,
    [FK_POPE]      INT             NULL,
    [CORG]         VARCHAR (4)     NOT NULL,
    [COPE]         VARCHAR (22)    NOT NULL,
    [CDEPR]        INT             NOT NULL,
    [MTINI]        NUMERIC (17, 2) NULL,
    [CTVA]         VARCHAR (4)     NULL,
    [CFOUR]        VARCHAR (14)    NULL,
    [MTCAU]        NUMERIC (17, 2) NULL,
    [POURCRG]      NUMERIC (18, 3) NULL,
    [NANTIS]       VARCHAR (4)     NULL,
    [MARSIGN]      DATE            NULL,
    [MTPEN]        NUMERIC (17, 2) NULL,
    [TEMRJ]        VARCHAR (1)     NULL,
    [CFOURP]       VARCHAR (14)    NULL,
    [PRORATA]      VARCHAR (1)     NULL,
    [DMLEV]        DATE            NULL,
    [RESERV]       VARCHAR (1)     NULL,
    [DLRESERV]     DATE            NULL,
    [NORD]         INT             NOT NULL,
    [DLAIJOUR]     INT             NULL,
    [JPDLAI]       INT             NULL,
    [TEMAPP]       VARCHAR (1)     NULL,
    [LNORD]        VARCHAR (60)    NULL,
    [SITUAT]       INT             NULL,
    [SUIVI]        VARCHAR (1)     NULL,
    [TOTMIL]       INT             NULL,
    [ANCPT]        INT             NULL,
    [MOCPT]        INT             NULL,
    [EDISIT]       VARCHAR (1)     NULL,
    [ACTUA]        VARCHAR (1)     NULL,
    [REVIS]        VARCHAR (1)     NULL,
    [COEFIX]       NUMERIC (20, 5) NULL,
    [COEFVA]       NUMERIC (20, 5) NULL,
    [SOUMIS]       DATE            NULL,
    [CAGENCE]      VARCHAR (4)     NULL,
    [CMODREG]      VARCHAR (4)     NULL,
    [CAGENCEB]     VARCHAR (4)     NULL,
    [CFOURB]       VARCHAR (14)    NULL,
    [DATLIB]       DATE            NULL,
    [ANBAS]        INT             NULL,
    [MOBAS]        INT             NULL,
    [MTSSTRAITE]   NUMERIC (17, 2) NULL,
    [TEMCP]        VARCHAR (4)     NULL,
    [NOAVTS]       INT             NULL,
    [MTLIB]        NUMERIC (17, 2) NULL,
    [DTLIB]        DATE            NULL,
    [DORS]         DATE            NULL,
    [STRAIT]       VARCHAR (4)     NULL,
    [TTIERS]       VARCHAR (14)    NULL,
    [PDIRECT]      VARCHAR (4)     NULL,
    [DEFFET]       DATE            NULL,
    [JURID]        VARCHAR (4)     NULL,
    [CALCRG]       VARCHAR (1)     NULL,
    [UTILRET]      VARCHAR (80)    NULL,
    [TAUXRET]      VARCHAR (140)   NULL,
    [CTRANCHE]     INT             NOT NULL,
    [ASPOL]        VARCHAR (30)    NULL,
    [ASCON]        VARCHAR (30)    NULL,
    [ASDAT]        DATE            NULL,
    [DRECEPT]      DATE            NULL,
    [DDECOMP]      DATE            NULL,
    [DNOTIF]       DATE            NULL,
    [DGAP]         DATE            NULL,
    [LIB]          VARCHAR (60)    NULL,
    [RLIB]         VARCHAR (60)    NULL,
    [CPHASE]       VARCHAR (6)     NULL,
    [CASSUR]       VARCHAR (14)    NULL,
    [CBANQUE]      VARCHAR (14)    NULL,
    [GUICHET]      VARCHAR (14)    NULL,
    [CCOMPTE]      VARCHAR (22)    NULL,
    [RIB]          INT             NULL,
    [COMMENT]      VARCHAR (1000)  NULL,
    [CTYPVIR]      VARCHAR (4)     NULL,
    [CDECALA]      VARCHAR (4)     NULL,
    [CDECALD]      VARCHAR (100)   NULL,
    [DUREE]        INT             NULL,
    [REPERE]       VARCHAR (10)    NULL,
    [CTYPPREL]     VARCHAR (50)    NULL,
    [CTYPDAT]      VARCHAR (50)    NULL,
    [TYPE]         VARCHAR (50)    NULL,
    [RG]           VARCHAR (1)     NULL,
    [MTCONV]       NUMERIC (17, 2) NULL,
    [DEVISE]       VARCHAR (4)     NULL,
    [MTTTCCONV]    NUMERIC (17, 2) NULL,
    [DDERSIT]      DATE            NULL,
    [RABAIS]       NUMERIC (18, 3) NULL,
    [PROLASM]      NUMERIC (17, 3) NULL,
    [TEMOIN]       VARCHAR (1)     NULL,
    [MIXTE]        VARCHAR (1)     NULL,
    [ACOUV]        VARCHAR (1)     NULL,
    [CCOUV]        VARCHAR (6)     NULL,
    [DEBENC]       VARCHAR (4)     NULL,
    [MTTCINI]      NUMERIC (17, 2) NULL,
    [CRITLIB1]     VARCHAR (60)    NULL,
    [CRITLIB2]     VARCHAR (60)    NULL,
    [CRITLIB3]     VARCHAR (60)    NULL,
    [PXMIL]        NUMERIC (19, 4) NULL,
    [CTIERSB]      VARCHAR (14)    NULL,
    [TXPRESTA]     NUMERIC (17, 2) NULL,
    [TEMPRESTA]    VARCHAR (1)     NULL,
    [DDEXEC]       DATE            NULL,
    [DFINPREV]     DATE            NULL,
    [PAVANC]       NUMERIC (17, 2) NULL,
    [REMUMOD]      VARCHAR (2)     NULL,
    [REMUFOR]      NUMERIC (17, 2) NULL,
    [DMARNOT]      DATE            NULL,
    [FRACTR]       VARCHAR (4)     NULL,
    [FRACBC]       VARCHAR (4)     NULL,
    [GRPT]         VARCHAR (4)     NULL,
    [NATAV]        VARCHAR (4)     NULL,
    [CMODCOMP]     VARCHAR (18)    NULL,
    [GESTCOMP]     VARCHAR (4)     NULL,
    [CODNAT]       VARCHAR (4)     NULL,
    [CLEIBAN]      VARCHAR (4)     NULL,
    [MIGCOMPT]     INT             NULL,
    [COORDBANQ_ID] INT             NULL,
    [EXHONO]       VARCHAR (4)     NULL,
    [CCORETA]      VARCHAR (4)     NULL,
    [TRIG]         VARCHAR (50)    NULL,
    [CTYPAVANCE]   VARCHAR (50)    NULL,
    [POURCAVANCE]  NUMERIC (18)    NULL,
    [NBMOISACTU]   NUMERIC (18)    NULL,
    [DDERMAJ]      VARCHAR (50)    NULL,
    CONSTRAINT [PK_ESTIA_PDEPOP] PRIMARY KEY CLUSTERED ([CORG] ASC, [COPE] ASC, [CTRANCHE] ASC, [CDEPR] ASC, [NORD] ASC)
);

