CREATE TABLE [dbo].[ESTIA_MANSEC] (
    [CJOURNAL] VARCHAR (50) NULL,
    [CMANDAT]  VARCHAR (50) NULL,
    [CMANDOM]  NUMERIC (18) NULL,
    [CORG]     VARCHAR (50) NULL,
    [CSECTANA] VARCHAR (50) NULL,
    [DDEB]     DATETIME     NULL,
    [DEPREC]   VARCHAR (50) NULL,
    [DFIN]     DATETIME     NULL,
    [TRIG]     VARCHAR (50) NULL
);

