CREATE TABLE [dbo].[ESTIA_GRPSEC] (
    [CORG]     NVARCHAR (255) NULL,
    [CAGENCE]  NVARCHAR (255) NULL,
    [CGROUPE]  NUMERIC (38)   NULL,
    [CMODULE]  NVARCHAR (255) NULL,
    [CSECTANA] NVARCHAR (255) NULL,
    [CSECTREG] NVARCHAR (255) NULL
);

