CREATE TABLE [dbo].[ESTIA_ECRAC] (
    [PK_ECRAC]        INT             IDENTITY (1, 1) NOT NULL,
    [IND_LIEN_HDEPCS] VARCHAR (1)     CONSTRAINT [DF_ESTIA_ECRAC_IND_LIEN_HDEPCS] DEFAULT ('N') NOT NULL,
    [DT_SAISIE]       DATETIME        NULL,
    [FK_ECRITAUX]     INT             NULL,
    [FK_TSECR]        INT             NULL,
    [FK_MANGES]       INT             NULL,
    [FK_PLANC]        INT             NULL,
    [ETECR]           VARCHAR (2)     NOT NULL,
    [CORG]            VARCHAR (4)     NOT NULL,
    [CJOURNAL]        VARCHAR (6)     NOT NULL,
    [DATEC]           DATE            NULL,
    [DVAL]            DATE            NULL,
    [CCG]             VARCHAR (28)    NULL,
    [LIBELLE]         VARCHAR (80)    NULL,
    [SENS]            VARCHAR (2)     NULL,
    [MONTANT]         NUMERIC (17, 2) NULL,
    [CTYPECRI]        VARCHAR (6)     NULL,
    [NOPIECE]         VARCHAR (16)    NULL,
    [REF]             VARCHAR (42)    NULL,
    [TRAIT]           VARCHAR (6)     NULL,
    [TYPCPTA]         VARCHAR (4)     NULL,
    [REGROUPE]        VARCHAR (48)    NULL,
    [PERIODE]         VARCHAR (12)    NULL,
    [CNATANA]         VARCHAR (16)    NULL,
    [CSECTANA]        VARCHAR (16)    NULL,
    [BANAL]           VARCHAR (60)    NULL,
    [MODIF]           VARCHAR (1)     NULL,
    [EDITJOUR]        VARCHAR (1)     NULL,
    [EXTRAC]          VARCHAR (1)     NULL,
    [CCGERR]          VARCHAR (40)    NULL,
    [CCPARTIE]        VARCHAR (28)    NULL,
    [CAGENCE]         VARCHAR (4)     NULL,
    [GRTRESOR]        VARCHAR (16)    NULL,
    [ORD]             INT             NULL,
    [CBORDERO]        VARCHAR (4)     NULL,
    [GRORD]           INT             NULL,
    [REGROUPCUM]      VARCHAR (16)    NULL,
    [UTIL]            VARCHAR (24)    NULL,
    [REGROUPLOC]      VARCHAR (40)    NULL,
    [ANALYT]          VARCHAR (2)     NULL,
    [NODOC]           VARCHAR (24)    NULL,
    [INFO]            VARCHAR (44)    NULL,
    [INTERFACE]       VARCHAR (50)    NULL,
    [CMODREG]         VARCHAR (42)    NULL,
    [TRIG]            VARCHAR (2)     NULL,
    [REGROUP2]        VARCHAR (48)    NULL,
    [ARCHIVE]         VARCHAR (1)     NULL,
    [FOLIO]           INT             NULL,
    [LIGNE]           INT             NULL,
    [DPEC]            DATE            NULL,
    [BAN2]            VARCHAR (60)    NULL,
    [ECCG]            VARCHAR (42)    NULL,
    [MTLET]           NUMERIC (17, 2) NULL,
    [CMANDAT]         VARCHAR (16)    NULL,
    [ECRAC_ID]        INT             NULL,
    [MIGCOMPT]        INT             NULL
);



