CREATE TABLE [dbo].[ESTIA_USALOC] (
    [CUSALOC]  VARCHAR (6)     NOT NULL,
    [LUSALOC]  VARCHAR (60)    NULL,
    [TRIG]     VARCHAR (2)     NULL,
    [TRIGD]    DATE            NULL,
    [PEGAS]    DATE            NULL,
    [TYPUSALO] VARCHAR (2)     NULL,
    [TSOUMTAX] VARCHAR (1)     NULL,
    [NBMMINI]  NUMERIC (17, 2) NULL,
    [LACTIF]   VARCHAR (1)     NULL,
    CONSTRAINT [PK_ESTIA_USALOC] PRIMARY KEY CLUSTERED ([CUSALOC] ASC)
);

