CREATE TABLE [dbo].[ESTIA_MOTDDE] (
    [CMOTDDE]   VARCHAR (4)  NOT NULL,
    [LMOTDDE]   VARCHAR (60) NULL,
    [CEXTERNE]  VARCHAR (90) NULL,
    [LGEXTERNE] VARCHAR (30) NULL,
    [TRIG]      VARCHAR (2)  NULL,
    [POINT]     INT          NULL,
    [REGROUP]   VARCHAR (4)  NULL,
    [LACTIF]    VARCHAR (2)  NULL,
    CONSTRAINT [PK_ESTIA_MOTDDE] PRIMARY KEY CLUSTERED ([CMOTDDE] ASC)
);

