CREATE TABLE [dbo].[ESTIA_LOCAL] (
    [PK_LOCAL]   INT             IDENTITY (1, 1) NOT NULL,
    [FK_ORG]     INT             NULL,
    [FK_AGENCE]  INT             NULL,
    [FK_GROUPE]  INT             NULL,
    [FK_IMMEUB]  INT             NULL,
    [CORG]       VARCHAR (4)     NOT NULL,
    [CAGENCE]    VARCHAR (4)     NOT NULL,
    [CGROUPE]    INT             NOT NULL,
    [CIMMEUB]    INT             NOT NULL,
    [CLOCAL]     INT             NOT NULL,
    [RUE]        VARCHAR (76)    NULL,
    [LIEUDIT]    VARCHAR (76)    NULL,
    [CPOS]       VARCHAR (10)    NULL,
    [VILLE]      VARCHAR (64)    NULL,
    [CCOMM]      INT             NULL,
    [BAT]        VARCHAR (4)     NULL,
    [ESC]        VARCHAR (4)     NULL,
    [ETAGE]      INT             NULL,
    [PORTE]      VARCHAR (8)     NULL,
    [CAVE]       VARCHAR (8)     NULL,
    [PARK]       VARCHAR (8)     NULL,
    [GARAGE]     VARCHAR (8)     NULL,
    [CTYPLOG]    VARCHAR (6)     NULL,
    [CCATHLM]    VARCHAR (6)     NULL,
    [CCATIMM]    VARCHAR (6)     NULL,
    [CNATLOG]    VARCHAR (4)     NULL,
    [GETIERS]    VARCHAR (14)    NULL,
    [DFINML]     DATE            NULL,
    [RCTIERS]    VARCHAR (14)    NULL,
    [TERME]      INT             NULL,
    [PERIOD]     INT             NULL,
    [DEPASS]     NUMERIC (17, 2) NULL,
    [AVIAPEL]    VARCHAR (2)     NULL,
    [CBAIL]      VARCHAR (4)     NULL,
    [CACCESS]    VARCHAR (2)     NULL,
    [SHAB]       NUMERIC (17, 2) NULL,
    [SCORR]      NUMERIC (17, 2) NULL,
    [SGAR]       NUMERIC (17, 2) NULL,
    [CINDCOL]    VARCHAR (2)     NULL,
    [RCTYPTIERS] VARCHAR (2)     NULL,
    [GETYPTIERS] VARCHAR (2)     NULL,
    [COTYPTIERS] VARCHAR (2)     NULL,
    [COEFPOND]   NUMERIC (19, 4) NULL,
    [CTEMLOC]    VARCHAR (2)     NULL,
    [LOGCOM]     VARCHAR (2)     NULL,
    [CVIDORD]    VARCHAR (2)     NULL,
    [AFACT]      VARCHAR (2)     NULL,
    [DEBLOC]     DATE            NULL,
    [LINDCOL]    VARCHAR (2)     NULL,
    [REFIMP]     VARCHAR (28)    NULL,
    [COTIERS]    VARCHAR (14)    NULL,
    [LOGSOC]     VARCHAR (2)     NULL,
    [CDEPART]    VARCHAR (4)     NULL,
    [CTYPALL]    VARCHAR (2)     NULL,
    [TEMPROP]    VARCHAR (1)     NULL,
    [TRAVCOND]   VARCHAR (1)     NULL,
    [TRAVAUX]    VARCHAR (1)     NULL,
    [CREGIS]     INT             NULL,
    [CENCAIS]    INT             NULL,
    [CMOTVAC]    VARCHAR (4)     NULL,
    [SCHAU]      NUMERIC (17, 2) NULL,
    [JARDIN]     VARCHAR (8)     NULL,
    [OSHAB]      NUMERIC (17, 2) NULL,
    [OSCORR]     NUMERIC (17, 2) NULL,
    [DDEBPAL]    DATE            NULL,
    [TEMPAL]     VARCHAR (2)     NULL,
    [DDEBHAL]    DATE            NULL,
    [TEMHAL]     VARCHAR (2)     NULL,
    [DEBPASS]    DATE            NULL,
    [CFINANC]    VARCHAR (10)    NULL,
    [CHANDI]     VARCHAR (2)     NULL,
    [CLIMAT]     VARCHAR (2)     NULL,
    [FINGEST]    DATE            NULL,
    [SDISPO]     NUMERIC (17, 2) NULL,
    [GEOVAR]     VARCHAR (1)     NULL,
    [CUSALOC]    VARCHAR (6)     NULL,
    [CFACT]      VARCHAR (2)     NULL,
    [DFINPASS]   DATE            NULL,
    [TRIG]       VARCHAR (2)     NULL,
    [NBHABIT]    INT             NULL,
    [DATCONV]    DATE            NULL,
    [CONTCONV]   VARCHAR (60)    NULL,
    [COEFREL]    NUMERIC (19, 4) NULL,
    [COEFOBJ]    NUMERIC (19, 4) NULL,
    [COEFSURL]   NUMERIC (20, 5) NULL,
    [CQUART]     VARCHAR (6)     NULL,
    [CSECTEUR]   VARCHAR (6)     NULL,
    [CZONE]      VARCHAR (6)     NULL,
    [CBASSIN]    VARCHAR (6)     NULL,
    [DATACHAT]   DATE            NULL,
    [ISTYPTIERS] VARCHAR (2)     NULL,
    [ISTIERS]    VARCHAR (14)    NULL,
    [IEMPLOY]    INT             NULL,
    [REFDEROG]   VARCHAR (24)    NULL,
    [DDEROG]     DATE            NULL,
    [CMOTDERO]   VARCHAR (4)     NULL,
    [NOTYPTIERS] VARCHAR (2)     NULL,
    [NOTIERS]    VARCHAR (14)    NULL,
    [DATEVAL]    DATE            NULL,
    [DATAUTO]    DATE            NULL,
    [PRXVENT]    NUMERIC (17, 2) NULL,
    [PRXPLAN]    NUMERIC (17, 2) NULL,
    [ACTYPTIERS] VARCHAR (2)     NULL,
    [ACTIERS]    VARCHAR (14)    NULL,
    [DECOMPTE]   VARCHAR (2)     NULL,
    [GESUTIL]    VARCHAR (1)     NULL,
    [AEMPLOY]    INT             NULL,
    [TEMPLOY]    INT             NULL,
    [EEMPLOY]    INT             NULL,
    [HUTYPTIERS] VARCHAR (2)     NULL,
    [HUTIERS]    VARCHAR (14)    NULL,
    [AVTYPTIERS] VARCHAR (2)     NULL,
    [AVTIERS]    VARCHAR (14)    NULL,
    [ELTYPTIERS] VARCHAR (2)     NULL,
    [ELTIERS]    VARCHAR (14)    NULL,
    [GATYPTIERS] VARCHAR (2)     NULL,
    [GATIERS]    VARCHAR (14)    NULL,
    [EATYPTIERS] VARCHAR (2)     NULL,
    [EATIERS]    VARCHAR (14)    NULL,
    [TETYPTIERS] VARCHAR (2)     NULL,
    [TETIERS]    VARCHAR (14)    NULL,
    [POTYPTIERS] VARCHAR (2)     NULL,
    [POTIERS]    VARCHAR (14)    NULL,
    [CMTYPTIERS] VARCHAR (2)     NULL,
    [CMTIERS]    VARCHAR (14)    NULL,
    [ORTYPTIERS] VARCHAR (2)     NULL,
    [ORTIERS]    VARCHAR (14)    NULL,
    [CPTYPTIERS] VARCHAR (2)     NULL,
    [CPTIERS]    VARCHAR (14)    NULL,
    [GRTYPTIERS] VARCHAR (2)     NULL,
    [GRTIERS]    VARCHAR (14)    NULL,
    [DOTYPTIERS] VARCHAR (2)     NULL,
    [DOTIERS]    VARCHAR (14)    NULL,
    [MXTYPTIERS] VARCHAR (2)     NULL,
    [MXTIERS]    VARCHAR (14)    NULL,
    [MONLOY]     NUMERIC (17, 2) NULL,
    [MONCHARG]   NUMERIC (18, 3) NULL,
    [TSLS]       VARCHAR (1)     NULL,
    [DGEL]       DATE            NULL,
    [CCONVSU]    VARCHAR (24)    NULL,
    [CREGENC]    INT             NULL,
    [PRTYPTIERS] VARCHAR (2)     NULL,
    [PRTIERS]    VARCHAR (14)    NULL,
    [VOTYPTIERS] VARCHAR (2)     NULL,
    [VOTIERS]    VARCHAR (14)    NULL,
    [MTVEN]      NUMERIC (17, 2) NULL,
    [MTACHAT]    NUMERIC (17, 2) NULL,
    [DVENTE]     DATE            NULL,
    [DAUTO]      DATE            NULL,
    [PEGAS]      DATE            NULL,
    [TRIGD]      DATE            NULL,
    [TXEFF]      NUMERIC (17, 2) NULL,
    [DRELOC]     DATE            NULL,
    [TPTYPTIERS] VARCHAR (2)     NULL,
    [TPTIERS]    VARCHAR (14)    NULL,
    [CARROND]    INT             NULL,
    [ADRCOMP]    VARCHAR (76)    NULL,
    [SRU]        VARCHAR (1)     NULL,
    [IDPRGES]    VARCHAR (12)    NULL,
    [IZURB]      VARCHAR (20)    NULL,
    [DDCONS]     DATE            NULL,
    [DFINCONS]   DATE            NULL,
    [DREHAB]     DATE            NULL,
    [CTYPPROP]   VARCHAR (4)     NULL,
    [DPREVENT]   DATE            NULL,
    [CTYPDEDRF]  VARCHAR (6)     NULL,
    [TEMTRANS]   VARCHAR (1)     NULL,
    [DATDEBTR]   DATE            NULL,
    [CLOCCONT]   INT             NULL,
    [MIGCOMPT]   INT             NULL,
    [ASSUR]      VARCHAR (2)     NULL,
    [PRCASS]     NUMERIC (17, 2) NULL,
    [TEMMAJ]     VARCHAR (2)     NULL,
    [DATMAJ]     DATE            NULL,
    [DDESIUNIQ]  DATE            NULL,
    [TDESIUNIQ]  VARCHAR (1)     NULL,
    [CMOTSORTIE] VARCHAR (4)     NULL,
    [DATESORTIE] DATE            NULL,
    [DPREVACHAT] DATE            NULL,
    [IMMEUB_ID]  INT             NULL,
    [LOCAL_ID]   INT             NULL,
    [ARCHIVE]    VARCHAR (1)     NULL,
    [XEMPLOY]    INT             NULL,
    [NOTEDU]     DATE            NULL,
    CONSTRAINT [PK_ESTIA_LOCAL] PRIMARY KEY CLUSTERED ([CORG] ASC, [CAGENCE] ASC, [CGROUPE] ASC, [CIMMEUB] ASC, [CLOCAL] ASC)
);

