CREATE TABLE [dbo].[ESTIA_ECRITAUX] (
    [PK_ECRITAUX] INT             IDENTITY (1, 1) NOT NULL,
    [FK_TIERS]    INT             NULL,
    [FK_POPE]     INT             NULL,
    [CORG]        VARCHAR (4)     NOT NULL,
    [CTYPTIERS]   VARCHAR (2)     NOT NULL,
    [TRIG]        VARCHAR (2)     NULL,
    [CJOURNAL]    VARCHAR (6)     NOT NULL,
    [FOLIO]       INT             NULL,
    [LIGNE]       INT             NULL,
    [NOPIECE]     VARCHAR (16)    NULL,
    [REF]         VARCHAR (42)    NULL,
    [DATEC]       DATE            NOT NULL,
    [DVAL]        DATE            NULL,
    [PERIODE]     VARCHAR (12)    NOT NULL,
    [LIBELLE]     VARCHAR (80)    NULL,
    [MONTANT]     NUMERIC (17, 2) NULL,
    [SENS]        VARCHAR (2)     NOT NULL,
    [CTYPECRI]    VARCHAR (6)     NULL,
    [CTIERS]      VARCHAR (14)    NOT NULL,
    [LETTRAGE]    VARCHAR (16)    NULL,
    [TYPCPTA]     VARCHAR (4)     NULL,
    [DATECH]      DATE            NULL,
    [TRAITE]      VARCHAR (1)     NULL,
    [QTE]         INT             NULL,
    [CDEVISE]     VARCHAR (4)     NULL,
    [MTDEVISE]    NUMERIC (17, 2) NULL,
    [FTIERS]      VARCHAR (14)    NULL,
    [CHRONO]      INT             NULL,
    [COMPTA]      VARCHAR (2)     NULL,
    [BLET]        VARCHAR (2)     NULL,
    [DATRAP]      DATE            NULL,
    [RELEVE]      VARCHAR (1)     NULL,
    [CMODREG]     VARCHAR (4)     NULL,
    [CCATEG]      VARCHAR (4)     NOT NULL,
    [CTYPCOM]     VARCHAR (2)     NOT NULL,
    [COPE]        VARCHAR (40)    NULL,
    [REFTIERS]    VARCHAR (80)    NULL,
    [NOFACT]      VARCHAR (24)    NULL,
    [REFFAC]      VARCHAR (48)    NULL,
    [VALIDE]      VARCHAR (1)     NULL,
    [LETRORI]     VARCHAR (16)    NULL,
    [UTIL]        VARCHAR (24)    NULL,
    [EXTRAIT]     VARCHAR (1)     NULL,
    [TRAIT]       VARCHAR (6)     NULL,
    [CDEPR]       INT             NULL,
    [NORD]        INT             NULL,
    [DBOR]        DATE            NULL,
    [CTRANCHE]    INT             NULL,
    [MOTBLOC]     VARCHAR (40)    NULL,
    [CMANDAT]     VARCHAR (16)    NULL
);

