CREATE TABLE [dbo].[ESTIA_TRAIT] (
    [CTRAIT]    VARCHAR (6)    NOT NULL,
    [LTRAIT]    VARCHAR (60)   NULL,
    [TASS]      VARCHAR (1)    NULL,
    [TRIG]      VARCHAR (2)    NULL,
    [AUTORISE]  VARCHAR (1000) NULL,
    [SAUTORISE] VARCHAR (1000) NULL,
    [CAUTORISE] VARCHAR (1000) NULL,
    CONSTRAINT [PK_ESTIA_TRAIT] PRIMARY KEY CLUSTERED ([CTRAIT] ASC)
);

