CREATE TABLE [dbo].[ETAT_DES_SURFACES] (
    [NM_IMMEUBLE]          FLOAT (53)     NULL,
    [NM_IMMEUBLE1]         FLOAT (53)     NULL,
    [NOM_IMMEUBLE]         NVARCHAR (255) NULL,
    [CHEMIN_ETAT_SURFACES] NVARCHAR (255) NULL
);

