CREATE TABLE [dbo].[HRV_RUB] (
    [PK]                      INT             IDENTITY (1, 1) NOT NULL,
    [PK_BAIL]                 INT             NOT NULL,
    [CORG]                    VARCHAR (2)     NOT NULL,
    [CAGENCE]                 VARCHAR (4)     NOT NULL,
    [CGROUPE]                 INT             NOT NULL,
    [CIMMEUB]                 INT             NOT NULL,
    [CLOCAL]                  INT             NOT NULL,
    [OCC]                     INT             NOT NULL,
    [CRUB]                    INT             NOT NULL,
    [CSTE]                    VARCHAR (2)     NOT NULL,
    [IND_HREVIS]              VARCHAR (1)     NULL,
    [CD_INDICE_REVISION]      VARCHAR (10)    NOT NULL,
    [DT_REVISION_PRECEDENTE]  DATETIME        NULL,
    [DT_PROCHAINE_REVISION]   DATETIME        NULL,
    [CD_PERIODICITE_REVISION] INT             NULL,
    [MT_INITIAL]              NUMERIC (18, 3) NULL,
    [VAL_INDICE_INITIAL]      NUMERIC (20, 5) NULL,
    [VAL_INDICE_PRECEDENT]    NUMERIC (20, 5) NULL,
    [VAL_INDICE_ACTUEL]       NUMERIC (20, 5) NULL,
    [VAL_PROCHAIN_INDICE]     NUMERIC (20, 5) NULL,
    [CD_INDICE_INITIAL]       INT             NULL,
    [CD_INDICE_ACTUEL]        INT             NULL,
    [CD_PROCHAIN_INDICE]      INT             NULL,
    [DT_INDICE_INITIAL]       DATETIME        NULL,
    [DT_INDICE_ACTUEL]        DATETIME        NULL,
    [DT_PROCHAIN_INDICE]      DATETIME        NULL,
    [LB_INDICE_INITIAL]       VARCHAR (20)    NULL,
    [LB_INDICE_ACTUEL]        VARCHAR (20)    NULL,
    [LB_PROCHAIN_INDICE]      VARCHAR (20)    NULL
);

