CREATE TABLE [dbo].[L_DESTINATAIRES] (
    [ADRESSE_MAIL] VARCHAR (100) NOT NULL,
    [NOM]          VARCHAR (50)  NULL,
    [DOMAINE]      VARCHAR (50)  NULL,
    [NIVEAU]       INT           NULL,
    CONSTRAINT [PK_L_DESTINATAIRES] PRIMARY KEY CLUSTERED ([ADRESSE_MAIL] ASC)
);



