CREATE TABLE [dbo].[L_INTERFACE_EASYFOLDER_OPERATIONS] (
    [CD_OPERATION]       NVARCHAR (50)  NOT NULL,
    [CD_TRANCHE]         INT            NULL,
    [LB_OPERATION]       NVARCHAR (255) NULL,
    [CD_IMMEUBLE]        NUMERIC (18)   NULL,
    [NOM_IMMEUBLE_ESTIA] NVARCHAR (255) NULL,
    [DT_DEB_OPERATION]   DATE           NULL
);

