CREATE TABLE [dbo].[LISTE_BAUX] (
    [PK_BAIL]       FLOAT (53)     NULL,
    [NM_IMMEUBLE]   FLOAT (53)     NULL,
    [NOM_IMMEUBLE]  NVARCHAR (255) NULL,
    [NM_BAIL]       NVARCHAR (255) NULL,
    [NOM_LOCATAIRE] NVARCHAR (255) NULL,
    [CHEMIN_BAIL]   NVARCHAR (255) NULL
);

