CREATE TABLE [dbo].[P_BANQUE] (
    [CBANQUE]     NVARCHAR (255) NULL,
    [CTYPTIERS]   NVARCHAR (255) NULL,
    [CODE]        NVARCHAR (255) NULL,
    [LBANQUE]     NVARCHAR (255) NULL,
    [BIC]         NVARCHAR (255) NULL,
    [IND_ACTIF]   NVARCHAR (255) NULL,
    [CPAYS_BIC]   NVARCHAR (255) NULL,
    [CBANQUE_BIC] NVARCHAR (255) NULL
);

