CREATE TABLE [dbo].[P_COORDBANQ] (
    [CPAYS_IBAN]     NVARCHAR (255) NULL,
    [CLE_IBAN]       FLOAT (53)     NULL,
    [CODE_IBAN]      NVARCHAR (255) NULL,
    [CPAYS_BIC]      NVARCHAR (255) NULL,
    [CBANQUE_BIC]    NVARCHAR (255) NULL,
    [GUICHET_BIC]    NVARCHAR (255) NULL,
    [CBANQUE_RIB]    NVARCHAR (255) NULL,
    [GUICHET_RIB]    NVARCHAR (255) NULL,
    [NUM_COMPTE_RIB] NVARCHAR (255) NULL,
    [CLE_RIB]        FLOAT (53)     NULL,
    [INTITULE_RIB]   NVARCHAR (255) NULL,
    [IND_ACTIF]      NVARCHAR (255) NULL
);

