CREATE TABLE [dbo].[P_CRITERE_DEPENSE] (
    [NM_CRITERE_DEPENSE]    INT          NOT NULL,
    [LB_CRITERE_DEPENSE]    VARCHAR (60) NULL,
    [IND_CRITERE_SIIC]      VARCHAR (1)  CONSTRAINT [DF_P_CRITERE_DEPENSE_IND_CRITERE_SIIC] DEFAULT ('N') NOT NULL,
    [CD_POSTE_DEPENSE_SIIC] VARCHAR (8)  NULL,
    CONSTRAINT [PK_P_CRITERE_DEPENSE] PRIMARY KEY CLUSTERED ([NM_CRITERE_DEPENSE] ASC)
);

