CREATE TABLE [dbo].[P_IMMEUBLE] (
    [CD_SOCIETE]           VARCHAR (2)     NOT NULL,
    [CD_AGENCE]            VARCHAR (2)     NOT NULL,
    [NM_IMMEUBLE]          INT             NOT NULL,
    [LB_IMMEUBLE]          VARCHAR (64)    NULL,
    [LB_IMMEUBLE_GED]      VARCHAR (64)    NULL,
    [CHEMIN_PLAN]          NVARCHAR (2000) NULL,
    [CHEMIN_ETAT_SURFACES] NVARCHAR (2000) NULL,
    [CHEMIN_TB]            NVARCHAR (2000) NULL,
    [CHEMIN_TF]            NVARCHAR (2000) NULL,
    [POLE_GESTION]         VARCHAR (50)    NULL,
    CONSTRAINT [PK_P_IMMEUBLE] PRIMARY KEY CLUSTERED ([CD_SOCIETE] ASC, [CD_AGENCE] ASC, [NM_IMMEUBLE] ASC)
);

