CREATE TABLE [dbo].[P_NATURE_BAIL] (
    [CD_NATURE_BAIL]      VARCHAR (4)  NOT NULL,
    [LB_NATURE_BAIL]      VARCHAR (60) NULL,
    [CD_TYPE_BAIL]        VARCHAR (4)  NULL,
    [LB_TYPE_BAIL]        VARCHAR (50) NULL,
    [TYPE_BAIL_SALEFORCE] VARCHAR (60) NULL,
    CONSTRAINT [PK_P_NATURE_BAIL] PRIMARY KEY CLUSTERED ([CD_NATURE_BAIL] ASC)
);

