CREATE TABLE [dbo].[P_PERIODICITE_FACTURATION] (
    [CD_PERIODICITE]           INT          NOT NULL,
    [LB_PERIODICITE]           VARCHAR (60) NULL,
    [LB_PERIODICITE_SALEFORCE] VARCHAR (50) NULL
);

