CREATE TABLE [dbo].[P_REG_ELTFAC] (
    [CD_REG_ELTFAC]     VARCHAR (2)  NOT NULL,
    [LB_REG_ELTFAC]     VARCHAR (30) NULL,
    [CD_TRI_REG_ELTFAC] NUMERIC (3)  NULL,
    CONSTRAINT [PK_P_REG_ELTFAC] PRIMARY KEY CLUSTERED ([CD_REG_ELTFAC] ASC)
);

