CREATE TABLE [dbo].[P_RUBRIQUE] (
    [DT_REF]                   DATETIME     CONSTRAINT [DF_P_RUBRIQUE_DT_REF] DEFAULT (getdate()) NULL,
    [CD_RUBRIQUE]              INT          NOT NULL,
    [LB_RUBRIQUE]              VARCHAR (30) NULL,
    [CD_COR_TYPE_LOT_RUBRIQUE] VARCHAR (3)  NULL,
    [CD_SOUS_REG_ELTFAC]       VARCHAR (3)  NULL,
    [IND_SURLOYER]             VARCHAR (1)  CONSTRAINT [DF_P_RUBRIQUE_IND_SURLOYER] DEFAULT ('N') NULL,
    [IND_FRANCHISE_LOYER]      VARCHAR (1)  CONSTRAINT [DF_P_RUBRIQUE_IND_FRANCHISE_LOYER] DEFAULT ('N') NULL,
    [IND_DG_PRINCIPAL]         VARCHAR (1)  CONSTRAINT [DF_P_RUBRIQUE_IND_DG_PRINCIPAL] DEFAULT ('N') NULL,
    [IND_DG_ANNEXE]            VARCHAR (1)  CONSTRAINT [DF_P_RUBRIQUE_IND_DG_ANNEXE] DEFAULT ('N') NULL,
    [IND_PALIER]               VARCHAR (1)  NULL,
    CONSTRAINT [PK_P_RUBRIQUE] PRIMARY KEY CLUSTERED ([CD_RUBRIQUE] ASC)
);

