CREATE TABLE [dbo].[P_RUBRIQUE_COR] (
    [CD_RUBRIQUE]              INT            NULL,
    [LB_RUBRIQUE]              NVARCHAR (255) NULL,
    [CD_COR_TYPE_LOT_RUBRIQUE] NVARCHAR (255) NULL,
    [LB_COR_TYPE_LOT_RUBRIQUE] NVARCHAR (255) NULL,
    [CD_SOUS_REG_ELTFAC]       NVARCHAR (255) NULL,
    [IND_SURLOYER]             NVARCHAR (255) NULL,
    [IND_FRANCHISE_LOYER]      NVARCHAR (255) NULL,
    [IND_DG_PRINCIPAL]         NVARCHAR (255) NULL,
    [IND_DG_ANNEXE]            NVARCHAR (255) NULL,
    [IND_PALIER]               NVARCHAR (255) NULL
);

