CREATE TABLE [dbo].[P_SOUS_CRITERE_DEPENSE] (
    [NM_SOUS_CRITERE_DEPENSE] INT          NOT NULL,
    [LB_SOUS_CRITERE_DEPENSE] VARCHAR (60) NULL,
    [IND_SOUS_CRITERE_SIIC]   VARCHAR (1)  CONSTRAINT [DF_P_SOUS_CRITERE_DEPENSE_IND_SOUS_CRITERE_SIIC] DEFAULT ('N') NOT NULL,
    [CD_CLE_CHARGE_SIIC]      VARCHAR (8)  NULL,
    CONSTRAINT [PK_P_SOUS_CRITERE_DEPENSE] PRIMARY KEY CLUSTERED ([NM_SOUS_CRITERE_DEPENSE] ASC)
);

