CREATE TABLE [dbo].[P_SOUS_REG_ELTFAC] (
    [CD_SOUS_REG_ELTFAC]     VARCHAR (3)  NOT NULL,
    [LB_SOUS_REG_ELTFAC]     VARCHAR (30) NULL,
    [CD_TRI_SOUS_REG_ELTFAC] NUMERIC (3)  NULL,
    [CD_REG_ELTFAC]          VARCHAR (2)  NULL,
    [IND_LOYER_FACIAL]       VARCHAR (1)  CONSTRAINT [DF_P_SOUS_REG_ELTFAC_IND_LOYER_FACIAL] DEFAULT ('N') NULL,
    [IND_CALCUL_LOYER]       VARCHAR (1)  NULL,
    [IND_CALCUL_FRANCHISE]   VARCHAR (1)  NULL,
    [IND_CALCUL_CHARGES]     VARCHAR (1)  NULL,
    [IND_CALCUL_DG]          VARCHAR (1)  NULL,
    [IND_CALCUL_PALIER]      VARCHAR (1)  NULL,
    CONSTRAINT [PK_P_SOUS_REG_ELTFAC] PRIMARY KEY CLUSTERED ([CD_SOUS_REG_ELTFAC] ASC)
);

