CREATE TABLE [dbo].[P_TYPE_LOT] (
    [DT_REF]                   DATETIME     CONSTRAINT [DF_P_TYPE_LOT_DT_REF] DEFAULT (getdate()) NULL,
    [CD_TYPE_LOT]              VARCHAR (3)  NOT NULL,
    [LB_TYPE_LOT]              VARCHAR (30) NULL,
    [IND_ETAT_LOCATIF]         VARCHAR (1)  CONSTRAINT [DF_P_TYPE_LOT_IND_ETAT_LOCATIF] DEFAULT ('O') NULL,
    [NB_EMPLACEMENTS_PARKING]  INT          CONSTRAINT [DF_P_TYPE_LOT_NB_EMPLACEMENTS_PARKING] DEFAULT ((0)) NULL,
    [CD_REG_TYPE_LOT]          VARCHAR (2)  CONSTRAINT [DF_P_TYPE_LOT_CD_REG_TYPE_LOT] DEFAULT ('DI') NULL,
    [LB_EOIV]                  VARCHAR (30) NULL,
    [CD_COR_TYPE_LOT_RUBRIQUE] VARCHAR (3)  NULL,
    CONSTRAINT [PK_P_TYPE_LOT] PRIMARY KEY CLUSTERED ([CD_TYPE_LOT] ASC)
);

