CREATE TABLE [dbo].[P_TYPE_CAUTION] (
    [CD_TYPE_CAUTION] VARCHAR (4)  NOT NULL,
    [LB_TYPE_CAUTION] VARCHAR (60) NULL,
    CONSTRAINT [PK_P_TYPE_CAUTION] PRIMARY KEY CLUSTERED ([CD_TYPE_CAUTION] ASC)
);

