CREATE TABLE [dbo].[P_USAGE] (
    [CD_USAGE]           VARCHAR (6)  NOT NULL,
    [LB_USAGE]           VARCHAR (60) NULL,
    [CD_REG_USAGE]       VARCHAR (3)  NULL,
    [lB_REG_USAGE]       VARCHAR (60) NULL,
    [CD_USAGE_SALEFORCE] VARCHAR (60) NULL,
    CONSTRAINT [PK_P_USAGE] PRIMARY KEY CLUSTERED ([CD_USAGE] ASC)
);

