CREATE TABLE [dbo].[TAB_INIT] (
    [CD_IMMEUBLE]   NUMERIC (38)    NULL,
    [NOM_IMMEUBLE]  NVARCHAR (255)  NULL,
    [NM_BAIL]       NUMERIC (38)    NULL,
    [NOM_LOCATAIRE] NVARCHAR (255)  NULL,
    [NM_LOT]        NUMERIC (38)    NULL,
    [DT_ENTREE]     DATETIME        NULL,
    [DT_SIGNATURE]  DATETIME        NULL,
    [DT_EFFET]      DATETIME        NULL,
    [MT_DG_BASE]    NUMERIC (38, 2) NULL,
    [MT_LOYER_BASE] NUMERIC (38, 2) NULL,
    [NM_BAIL_MOD]   NUMERIC (38)    NULL
);

