CREATE TABLE [dbo].[TMP_INTERFACE_EASYFOLDER_BAUX] (
    [IDENTIFIANT_BAIL_DREAM]     NVARCHAR (255) NULL,
    [IDENTIFIANT_DREAM_IMMEUBLE] NVARCHAR (255) NULL,
    [IDENTIFIANT_ESTIA_IMMEUBLE] NUMERIC (13)   NULL,
    [NOM_DU_FICHIER_PDF]         NVARCHAR (255) NULL,
    [IDENTIFIANT_ESTIA_COMPTE]   NUMERIC (13)   NULL,
    [NOBAIL_ESTIA]               NUMERIC (13)   NULL,
    [LOCATAIRE_PRINCIPAL]        NVARCHAR (255) NULL,
    [DT_EFFET]                   DATETIME       NULL,
    [DT_FIN]                     DATETIME       NULL
);




GO
GRANT VIEW DEFINITION
    ON OBJECT::[dbo].[TMP_INTERFACE_EASYFOLDER_BAUX] TO [user_test]
    AS [dbo];


GO
GRANT VIEW CHANGE TRACKING
    ON OBJECT::[dbo].[TMP_INTERFACE_EASYFOLDER_BAUX] TO [user_test]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[TMP_INTERFACE_EASYFOLDER_BAUX] TO [user_test]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[TMP_INTERFACE_EASYFOLDER_BAUX] TO [user_test]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[TMP_INTERFACE_EASYFOLDER_BAUX] TO [user_test]
    AS [dbo];


GO
GRANT DELETE
    ON OBJECT::[dbo].[TMP_INTERFACE_EASYFOLDER_BAUX] TO [user_test]
    AS [dbo];


GO
GRANT CONTROL
    ON OBJECT::[dbo].[TMP_INTERFACE_EASYFOLDER_BAUX] TO [user_test]
    AS [dbo];


GO
GRANT ALTER
    ON OBJECT::[dbo].[TMP_INTERFACE_EASYFOLDER_BAUX] TO [user_test]
    AS [dbo];

