CREATE TABLE [dbo].[TMP_TRANSCO_IMMEUBLE_EASYFOLDER] (
    [NM_IMMEUBLE_ESTIA]  NUMERIC (38)   NULL,
    [CD_IMMEUBLE_DREAM]  NVARCHAR (255) NULL,
    [NOM_IMMEUBLE_DREAM] NVARCHAR (255) NULL
);


GO
CREATE NONCLUSTERED INDEX [IX_TMP_TRANSCO_IMMEUBLE_EASYFOLDER_1]
    ON [dbo].[TMP_TRANSCO_IMMEUBLE_EASYFOLDER]([NM_IMMEUBLE_ESTIA] ASC);

