CREATE TABLE [dbo].[WRK_GROUPE_MANGES] (
    [PK_GROUPE] INT          NULL,
    [FK_MANGES] INT          NULL,
    [FK_TIERS]  INT          NULL,
    [CORG]      VARCHAR (4)  NOT NULL,
    [CAGENCE]   VARCHAR (4)  NOT NULL,
    [CGROUPE]   INT          NOT NULL,
    [CMANDAT]   VARCHAR (16) NULL,
    CONSTRAINT [PK_WRK_GROUPE_MANGES] PRIMARY KEY CLUSTERED ([CORG] ASC, [CAGENCE] ASC, [CGROUPE] ASC)
);

