CREATE TABLE [dbo].[WRK_HQRBAIL] (
    [PK_BAIL]               INT          NULL,
    [CORG]                  VARCHAR (4)  NOT NULL,
    [CCOMPTE]               VARCHAR (22) NOT NULL,
    [NOBAIL]                INT          NOT NULL,
    [CD_NATURE_BAIL]        VARCHAR (4)  NULL,
    [DT_PREMIER_BAIL]       DATE         NULL,
    [DT_EFFET]              DATE         NULL,
    [DT_ENTREE]             DATE         NULL,
    [DT_EXPIRATION]         DATE         NULL,
    [DUREE_MOIS]            INT          NULL,
    [DUR_MINIMUM_BAIL_MOIS] INT          NULL,
    [DT_MINIMUM]            DATE         NULL,
    [DT_SORTIE]             DATE         NULL,
    [DT_TRIEN_POT_1]        DATE         NULL,
    [DT_TRIEN_POT_2]        DATE         NULL,
    [DT_TRIEN_POT_3]        DATE         NULL,
    [DT_TRIEN_POT_4]        DATE         NULL,
    [DT_TRIEN_POT_5]        DATE         NULL,
    [DT_TRIEN_POT_6]        DATE         NULL,
    [DT_TRIEN_POT_7]        DATE         NULL,
    [DT_PRCH_TRIEN_POT]     DATE         NULL,
    [DT_RISQUE_CPLT_BAIL]   DATE         NULL,
    [DT_RISQUE]             DATE         NULL,
    [IND_CALCUL_BANALDET]   VARCHAR (1)  CONSTRAINT [DF_WRK_HQRBAIL_IND_CALCUL_BANALDET] DEFAULT ('N') NOT NULL,
    [DT_SIGNATURE]          DATE         NULL,
    [DUREE_PREAVIS]         INT          NULL,
    CONSTRAINT [PK_WRK_HQRBAIL] PRIMARY KEY CLUSTERED ([CORG] ASC, [CCOMPTE] ASC, [NOBAIL] ASC)
);

