CREATE TABLE [dbo].[WRK_PABASIT] (
    [PK_PABASIT] INT             NOT NULL,
    [FK_POPE]    INT             NULL,
    [FK_PDEPOP]  INT             NULL,
    [CORG]       VARCHAR (4)     NOT NULL,
    [COPE]       VARCHAR (22)    NOT NULL,
    [CDEPR]      INT             NOT NULL,
    [NORD]       INT             NOT NULL,
    [SITUAT]     INT             NOT NULL,
    [NOLIG]      INT             NOT NULL,
    [LIB]        VARCHAR (80)    NULL,
    [MT]         NUMERIC (17, 2) NULL,
    [TYPE]       VARCHAR (2)     NULL,
    [CFOUR]      VARCHAR (14)    NULL,
    [DECR]       DATE            NULL,
    [DSIGN]      DATE            NULL,
    [MTTVA]      NUMERIC (17, 2) NULL,
    [MTTTC]      NUMERIC (17, 2) NULL,
    [FORMPX]     VARCHAR (4)     NULL,
    [DSOUMIS]    DATE            NULL,
    [DORDS]      DATE            NULL,
    [TRIGD]      DATE            NULL,
    [MTVALASM]   NUMERIC (17, 2) NULL,
    [MTTCLASM]   NUMERIC (17, 2) NULL,
    [HTBASE]     NUMERIC (17, 2) NULL,
    [CTRANCHE]   INT             NOT NULL,
    [DEFFET]     DATE            NULL,
    [TEMIMPUT]   VARCHAR (2)     NULL,
    [CPHASE]     VARCHAR (8)     NULL,
    [TEMIGRA]    VARCHAR (2)     NULL,
    [CMOTIF]     VARCHAR (4)     NULL,
    [HTD]        NUMERIC (17, 2) NULL,
    [CNATPRES]   VARCHAR (6)     NULL,
    [CNOMENM]    VARCHAR (22)    NULL,
    [DCOMNOT]    DATE            NULL,
    [NOCOMM]     INT             NULL,
    [DDEXEC]     DATE            NULL,
    [DELAI]      INT             NULL,
    [MIGCOMPT]   INT             NULL,
    CONSTRAINT [PK_WRK_PABASIT] PRIMARY KEY CLUSTERED ([CORG] ASC, [COPE] ASC, [CTRANCHE] ASC, [CDEPR] ASC, [NORD] ASC, [SITUAT] ASC, [NOLIG] ASC)
);

