CREATE TABLE [dbo].[WRK_MANGES_GROUPE] (
    [PK_MANGES] INT          NULL,
    [FK_GROUPE] INT          NULL,
    [CMANDAT]   VARCHAR (16) NOT NULL,
    [CORG]      VARCHAR (4)  NULL,
    [CAGENCE]   VARCHAR (4)  NULL,
    [CGROUPE]   INT          NULL,
    CONSTRAINT [PK_WRK_MANGES_GROUPE] PRIMARY KEY CLUSTERED ([CMANDAT] ASC)
);

