CREATE TABLE [dbo].[WRK_BAIL_RUB] (
    [CORG]    VARCHAR (4)  NOT NULL,
    [CCOMPTE] VARCHAR (22) NOT NULL,
    [NOBAIL]  INT          NOT NULL,
    [CRUB]    INT          NOT NULL,
    CONSTRAINT [PK_WRK_BAIL_RUB] PRIMARY KEY CLUSTERED ([CORG] ASC, [CCOMPTE] ASC, [NOBAIL] ASC, [CRUB] ASC)
);

