CREATE TABLE [dbo].[WRK_GROUPE_LOCATION] (
    [CORG]           VARCHAR (4) NOT NULL,
    [CAGENCE]        VARCHAR (4) NOT NULL,
    [CGROUPE]        INT         NOT NULL,
    [NB_BAUX_ACTIFS] INT         NULL,
    CONSTRAINT [PK_WRK_GROUPE_LOCATION] PRIMARY KEY CLUSTERED ([CORG] ASC, [CAGENCE] ASC, [CGROUPE] ASC)
);

