CREATE TABLE [dbo].[WRK_INTERFACE_EASYFOLDER_BAUX_TEST] (
    [PK_TEMPS]                   DATETIME       NULL,
    [ACTION]                     NVARCHAR (255) NULL,
    [IDENTIFIANT_BAIL_DREAM]     NVARCHAR (255) NULL,
    [IDENTIFIANT_DREAM_IMMEUBLE] NVARCHAR (255) NULL,
    [NOM_IMMEUBLE]               NVARCHAR (255) NULL,
    [IDENTIFIANT_ESTIA_IMMEUBLE] NUMERIC (38)   NULL,
    [NOM_DU_FICHIER_PDF]         NVARCHAR (255) NULL,
    [IDENTIFIANT_ESTIA_COMPTE]   NUMERIC (38)   NULL,
    [NOBAIL_ESTIA]               NUMERIC (38)   NULL,
    [LOCATAIRE_PRINCIPAL]        NVARCHAR (255) NULL,
    [DT_EFFET]                   DATETIME       NULL,
    [DT_FIN]                     DATETIME       NULL,
    [IFC_DT_TRAITEMENT]          DATETIME       NULL,
    [IFC_STATUT_TRAITEMENT]      NVARCHAR (100) NULL,
    [IFC_ERREUR_TRAITEMENT]      NVARCHAR (MAX) NULL
);

