CREATE TABLE [dbo].[WRK_LOCATION_BANALDET] (
    [CORG]      VARCHAR (4)  NOT NULL,
    [CCOMPTE]   VARCHAR (60) NOT NULL,
    [NOBAIL]    INT          NOT NULL,
    [DT_BREAK1] DATE         NULL,
    [DT_BREAK2] DATE         NULL,
    [DT_BREAK3] DATE         NULL,
    [DT_BREAK4] DATE         NULL,
    [DT_BREAK5] DATE         NULL,
    [DT_BREAK6] DATE         NULL,
    [DT_BREAK7] DATE         NULL,
    CONSTRAINT [PK_WRK_LOCATION_BANALDET] PRIMARY KEY CLUSTERED ([CORG] ASC, [CCOMPTE] ASC, [NOBAIL] ASC)
);

