CREATE TABLE [dbo].[WRK_POPE_TRANCHE] (
    [CORG]     VARCHAR (4)  NOT NULL,
    [COPE]     VARCHAR (22) NOT NULL,
    [DDEXEC]   DATE         NULL,
    [DFEXEC]   DATE         NULL,
    [DFINPREV] DATE         NULL,
    [DCLOTU]   DATE         NULL,
    CONSTRAINT [PK_WRK_POPE_TRANCHE] PRIMARY KEY CLUSTERED ([CORG] ASC, [COPE] ASC)
);

