CREATE TABLE [dbo].[WRK_HISTO_LOT] (
    [PK_HISTO_LOT]      INT             IDENTITY (1, 1) NOT NULL,
    [FK_ORG]            INT             NULL,
    [FK_AGENCE]         INT             NULL,
    [FK_GROUPE]         INT             NULL,
    [FK_IMMEUB]         INT             NULL,
    [FK_LOCAL]          INT             NULL,
    [FK_MANGES]         INT             NULL,
    [FK_PROPRIETAIRE]   INT             NULL,
    [FK_BAIL]           INT             NULL,
    [FK_TIERS]          INT             NULL,
    [CORG]              VARCHAR (4)     NOT NULL,
    [CAGENCE]           VARCHAR (4)     NOT NULL,
    [CGROUPE]           INT             NOT NULL,
    [CIMMEUB]           INT             NOT NULL,
    [CLOCAL]            INT             NOT NULL,
    [OCC]               INT             NULL,
    [CD_STATUT]         VARCHAR (1)     NULL,
    [CTYPLOG]           VARCHAR (6)     NULL,
    [LTYPLOG]           VARCHAR (60)    NULL,
    [SURF_HAB]          NUMERIC (17, 2) NULL,
    [SURF_COR]          NUMERIC (17, 2) NULL,
    [IND_ETAT_LOCATIF]  VARCHAR (1)     NULL,
    [NM_LOT_PRINCIPAL]  INT             NULL,
    [IND_LOT_PRINCIPAL] VARCHAR (1)     CONSTRAINT [DF_WRK_HISTO_LOT_IND_LOT_PRINCIPAL] DEFAULT ('N') NULL,
    [CMANDAT]           VARCHAR (16)    NULL,
    [CCOMPTE]           VARCHAR (22)    NULL,
    [NOBAIL]            INT             NULL,
    [CBAIL]             VARCHAR (4)     NULL,
    [DATENTQUIT]        DATE            NULL,
    [DATSORQUIT]        DATE            NULL,
    [DT_DEBUT_RAT]      DATE            NULL,
    [DT_FIN_RAT]        DATE            NULL,
    [CTYPTIERS]         VARCHAR (2)     NULL,
    [CTIERS]            VARCHAR (14)    NULL,
    [LTIERS]            VARCHAR (76)    NULL,
    [POUM]              VARCHAR (2)     NULL,
    [RK_LOCATION]       INT             NULL,
    [RK_LOCATION_INV]   INT             NULL,
    [FK_BAIL_PREC]      INT             NULL,
    [FK_TIERS_PREC]     INT             NULL,
    [OCC_PREC]          INT             NULL,
    [CCOMPTE_PREC]      VARCHAR (22)    NULL,
    [NOBAIL_PREC]       INT             NULL,
    [CTYPTIERS_PREC]    VARCHAR (2)     NULL,
    [CTIERS_PREC]       VARCHAR (14)    NULL,
    [LTIERS_PREC]       VARCHAR (76)    NULL,
    [DT_ENTREE_PREC]    DATE            NULL,
    [DT_SORTIE_PREC]    DATE            NULL,
    [FK_BAIL_SUIV]      INT             NULL,
    [FK_TIERS_SUIV]     INT             NULL,
    [OCC_SUIV]          INT             NULL,
    [CCOMPTE_SUIV]      VARCHAR (22)    NULL,
    [NOBAIL_SUIV]       INT             NULL,
    [CTYPTIERS_SUIV]    VARCHAR (2)     NULL,
    [CTIERS_SUIV]       VARCHAR (14)    NULL,
    [LTIERS_SUIV]       VARCHAR (76)    NULL,
    [DT_ENTREE_SUIV]    DATE            NULL,
    [DT_SORTIE_SUIV]    DATE            NULL
);

