CREATE TABLE [dbo].[WRK_PRO_COMPTABILITE] (
    [CTYPTIERS] VARCHAR (2)  NOT NULL,
    [CTIERS]    VARCHAR (14) NOT NULL,
    [CTYPROPR]  VARCHAR (4)  NULL,
    [LTYPROPR]  VARCHAR (64) NULL,
    CONSTRAINT [PK_WRK_PRO_COMPTABILITE] PRIMARY KEY CLUSTERED ([CTYPTIERS] ASC, [CTIERS] ASC)
);

