CREATE TABLE [dbo].[WRK_DPROCTX] (
    [CORG]            VARCHAR (4)  NOT NULL,
    [CCOMPTE]         VARCHAR (22) NOT NULL,
    [NOBAIL]          INT          NOT NULL,
    [IND_CONTENTIEUX] VARCHAR (1)  NULL,
    CONSTRAINT [PK_WRK_DPROCTX] PRIMARY KEY CLUSTERED ([CORG] ASC, [CCOMPTE] ASC, [NOBAIL] ASC)
);

