CREATE TABLE [dbo].[WRK_INTERFACE_EASYFOLDER_OPERATIONS] (
    [PK_TEMPS]              DATE           NULL,
    [ACTION]                NVARCHAR (255) NULL,
    [CD_OPERATION]          NVARCHAR (50)  NOT NULL,
    [CD_TRANCHE]            INT            NULL,
    [LB_OPERATION]          NVARCHAR (255) NULL,
    [CD_IMMEUBLE]           NUMERIC (18)   NULL,
    [NOM_IMMEUBLE_ESTIA]    NVARCHAR (255) NULL,
    [DT_DEB_OPERATION]      DATE           NULL,
    [IFC_DT_TRAITEMENT]     DATETIME       NULL,
    [IFC_STATUT_TRAITEMENT] NVARCHAR (100) NULL,
    [IFC_ERREUR_TRAITEMENT] NVARCHAR (MAX) NULL
);

