CREATE TABLE [dbo].[WRK_INTBT_ECRIB] (
    [CORG]                      VARCHAR (4)     NOT NULL,
    [NOINTBT]                   INT             NOT NULL,
    [CSTE1]                     VARCHAR (4)     NOT NULL,
    [MT_ENGAGEMENT_INITIAL_HT]  NUMERIC (38, 2) NULL,
    [MT_ENGAGEMENT_INITIAL_TVA] NUMERIC (38, 2) NULL,
    [MT_ENGAGEMENT_INITIAL_TTC] NUMERIC (38, 2) NULL,
    [MT_ENGAGEMENT_RESTANT_HT]  NUMERIC (38, 2) NULL,
    [MT_ENGAGEMENT_RESTANT_TVA] NUMERIC (38, 2) NULL,
    [MT_ENGAGEMENT_RESTANT_TTC] NUMERIC (38, 2) NULL,
    [MT_REALISE_HT]             NUMERIC (38, 2) NULL,
    [MT_REALISE_TVA]            NUMERIC (38, 2) NULL,
    [MT_REALISE_TTC]            NUMERIC (38, 2) NULL,
    [DT_REALISE]                DATE            NULL,
    CONSTRAINT [PK_WRK_INTBT_ECRIB] PRIMARY KEY CLUSTERED ([CORG] ASC, [NOINTBT] ASC, [CSTE1] ASC)
);

