CREATE TABLE [dbo].[WRK_GROUPE_SURFACE] (
    [CORG]     VARCHAR (4)     NOT NULL,
    [CAGENCE]  VARCHAR (4)     NOT NULL,
    [CGROUPE]  INT             NOT NULL,
    [NB_LOTS]  INT             NULL,
    [SURF_HAB] NUMERIC (17, 2) NULL,
    [SURF_COR] NUMERIC (17, 2) NULL,
    CONSTRAINT [PK_WRK_GROUPE_SURFACE] PRIMARY KEY CLUSTERED ([CORG] ASC, [CAGENCE] ASC, [CGROUPE] ASC)
);

