CREATE TABLE [dbo].[WRK_RUB_TAX] (
    [CRUB]    INT             NOT NULL,
    [LRUB]    VARCHAR (60)    NULL,
    [CNATRUB] VARCHAR (2)     NULL,
    [CTYPTAX] VARCHAR (2)     NULL,
    [CRUBTAX] NUMERIC (3)     NULL,
    [VALTAUX] NUMERIC (19, 4) NOT NULL,
    CONSTRAINT [PK_WRK_RUB_TAX] PRIMARY KEY CLUSTERED ([CRUB] ASC)
);

