CREATE FUNCTION [dbo].[f_GET_ANNUAL_LEASE_ALLOWANCES] 
(
	@DT_ANALYSE DATETIME,
	@ANNEE_PREV VARCHAR(4),
	@PK_BAIL INT
)
RETURNS @retANNUAL_LEASE_ALLOWANCES TABLE   
(  
	PK_GROUPE					int,
	PK_BAIL						int,
	MT_LOYER_FRANCHISE			numeric(17,2),
	MT_PALIER					numeric(17,2)
)  
--Returns a result set that lists all the employees who report to the   
--specific employee directly or indirectly.*/  
AS  
BEGIN  
WITH ANNUAL_LEASE_ALLOWANCES_cte(PK_GROUPE, PK_BAIL, MT_LOYER_FRANCHISE, MT_PALIER) --, CD_FREQUENCE_QUITTANCEMENT)
AS
(
	SELECT PK_GROUPE
		 , PK_BAIL
		 , MT_LOYER_FRANCHISE
		 , MT MT_PALIER
	FROM
	(
		SELECT PK_GROUPE
			 , PK_BAIL
			 , 0 AS MT_LOYER_FRANCHISE
			 --, @ANNEE_PREV ANNEE_PREV
			 --, DDEB, DFIN
			 --, BORNE_INF, BORNE_SUP
			 --, DATEDIFF(MONTH, BORNE_INF, DATEADD(DAY, 1, BORNE_SUP)) NB_MOIS
			 --, NB
			 , CAST(SUM((NB/12) * DATEDIFF(MONTH, BORNE_INF, DATEADD(DAY, 1, BORNE_SUP))) AS NUMERIC(18, 0)) MT
		FROM
		(
			SELECT LOCATION.FK_GROUPE AS PK_GROUPE, LOCATION.PK_LOCATION AS PK_BAIL, LOCATION.PERIOD AS CD_FREQUENCE_QUITTANCEMENT--,
			, HQLOCAT.DDEB, HQLOCAT.DFIN, HQLOCAT.NB
			, CASE WHEN DATEPART(YEAR, DDEB) = @ANNEE_PREV THEN DDEB ELSE @ANNEE_PREV+'0101' END BORNE_INF
			, CASE WHEN DATEPART(YEAR, DFIN) = @ANNEE_PREV THEN DFIN ELSE @ANNEE_PREV+'1231' END BORNE_SUP
			FROM MASTER_ESTIA..ESTIA_LOCATION AS LOCATION
			INNER JOIN 
			(
				SELECT CORG, CAGENCE, CGROUPE, CIMMEUB, CLOCAL, OCC, CRUB, DDEB, DATEADD(YEAR, -1, DFIN) DFIN, NB 
				FROM MASTER_ESTIA..ESTIA_HQLOCAT HQLOCAT
					INNER JOIN MASTER_ESTIA..P_RUBRIQUE AS P
						ON P.CD_RUBRIQUE = HQLOCAT.CRUB
					INNER JOIN MASTER_ESTIA..P_SOUS_REG_ELTFAC AS PSRE
						ON PSRE.CD_SOUS_REG_ELTFAC = P.CD_SOUS_REG_ELTFAC
				WHERE (/*PSRE.IND_CALCUL_FRANCHISE = 'O' OR*/ PSRE.IND_CALCUL_PALIER = 'O')
				AND FK_BAIL = @PK_BAIL
				UNION
				SELECT CORG, CAGENCE, CGROUPE, CIMMEUB, CLOCAL, OCC, CRUB, DATEADD(YEAR, 1, DDEB) DDEB, DFIN, NB
				FROM MASTER_ESTIA..ESTIA_HQLOCAT HQLOCAT
					INNER JOIN MASTER_ESTIA..P_RUBRIQUE AS P
						ON P.CD_RUBRIQUE = HQLOCAT.CRUB
					INNER JOIN MASTER_ESTIA..P_SOUS_REG_ELTFAC AS PSRE
						ON PSRE.CD_SOUS_REG_ELTFAC = P.CD_SOUS_REG_ELTFAC
				WHERE (/*PSRE.IND_CALCUL_FRANCHISE = 'O' OR*/ PSRE.IND_CALCUL_PALIER = 'O')
				AND FK_BAIL = @PK_BAIL
			) HQLOCAT
			ON HQLOCAT.CORG = LOCATION.CORG
			AND HQLOCAT.CAGENCE = LOCATION.CAGENCE
			AND HQLOCAT.CGROUPE = LOCATION.CGROUPE
			AND HQLOCAT.CIMMEUB = LOCATION.CIMMEUB
			AND HQLOCAT.CLOCAL = LOCATION.CLOCAL
			AND HQLOCAT.OCC = LOCATION.OCC
			INNER JOIN MASTER_ESTIA..ESTIA_GROUPE GROUPE
			ON GROUPE.PK_GROUPE = LOCATION.FK_GROUPE
			INNER JOIN MASTER_ESTIA..V_D_MANDAT_GERANCE MANDAT
			ON MANDAT.FK_IMMEUBLE = GROUPE.PK_GROUPE
			WHERE LOCATION.FK_BAIL IS NOT NULL
			AND LOCATION.CORG = '11'
			AND LOCATION.PK_LOCATION = @PK_BAIL
			AND (LOCATION.DATSORQUIT IS NULL OR LOCATION.DATSORQUIT > @DT_ANALYSE)
			AND IND_MANDAT_ACTIF = 'O'
			AND (DATEPART(YEAR, HQLOCAT.DDEB) = @ANNEE_PREV OR DATEPART(YEAR, HQLOCAT.DFIN) = @ANNEE_PREV)
		) SRC
		GROUP BY PK_GROUPE, PK_BAIL
		--SELECT LOCATION.FK_GROUPE AS PK_GROUPE, LOCATION.PK_LOCATION AS PK_BAIL, LOCATION.PERIOD AS CD_FREQUENCE_QUITTANCEMENT,
		--	SUM(CASE WHEN PSRE.IND_CALCUL_FRANCHISE = 'O' THEN 
		--		((HQLOCAT.NB)/12)*DATEDIFF(MONTH, CASE WHEN DATEPART(YEAR, HQLOCAT.DDEB) < DATEPART(YEAR, @DT_ANALYSE) THEN DATEADD(YEAR , DATEDIFF(YEAR, 0, @DT_ANALYSE), 0) ELSE HQLOCAT.DDEB END, 
		--			CASE WHEN DATEPART(YEAR, HQLOCAT.DFIN) > DATEPART(YEAR, @DT_ANALYSE) THEN DATEADD(DAY, -1, DATEADD(YEAR , DATEDIFF(YEAR, 0, @DT_ANALYSE) + 1, 0)) ELSE HQLOCAT.DFIN END) ELSE 0 END) AS MT_LOYER_FRANCHISE,
		--	--SUM(CASE WHEN PSRE.IND_CALCUL_PALIER = 'O' THEN HQLOCAT.NB ELSE 0 END) AS MT_PALIER
		--	SUM(CASE WHEN PSRE.IND_CALCUL_PALIER = 'O' THEN 
		--		((HQLOCAT.NB)/12)*DATEDIFF(MONTH, CASE WHEN DATEPART(YEAR, HQLOCAT.DDEB) < DATEPART(YEAR, @DT_ANALYSE) THEN DATEADD(YEAR , DATEDIFF(YEAR, 0, @DT_ANALYSE), 0) ELSE HQLOCAT.DDEB END, 
		--			CASE WHEN DATEPART(YEAR, HQLOCAT.DFIN) > DATEPART(YEAR, @DT_ANALYSE) THEN DATEADD(DAY, -1, DATEADD(YEAR , DATEDIFF(YEAR, 0, @DT_ANALYSE) + 1, 0)) ELSE HQLOCAT.DFIN END) ELSE 0 END) AS MT_PALIER
		--FROM MASTER_ESTIA..ESTIA_LOCATION AS LOCATION
		--		INNER JOIN MASTER_ESTIA..ESTIA_HQLOCAT AS HQLOCAT
		--			ON HQLOCAT.CORG = LOCATION.CORG
		--			AND HQLOCAT.CAGENCE = LOCATION.CAGENCE
		--			AND HQLOCAT.CGROUPE = LOCATION.CGROUPE
		--			AND HQLOCAT.CIMMEUB = LOCATION.CIMMEUB
		--			AND HQLOCAT.CLOCAL = LOCATION.CLOCAL
		--			AND HQLOCAT.OCC = LOCATION.OCC
		--		INNER JOIN MASTER_ESTIA..P_RUBRIQUE AS P
		--			ON P.CD_RUBRIQUE = HQLOCAT.CRUB
		--		INNER JOIN MASTER_ESTIA..P_SOUS_REG_ELTFAC AS PSRE
		--			ON PSRE.CD_SOUS_REG_ELTFAC = P.CD_SOUS_REG_ELTFAC
		--		INNER JOIN MASTER_ESTIA..ESTIA_GROUPE GROUPE
		--		ON GROUPE.PK_GROUPE = LOCATION.FK_GROUPE
		--		INNER JOIN MASTER_ESTIA..V_D_MANDAT_GERANCE MANDAT
		--		ON MANDAT.FK_IMMEUBLE = GROUPE.PK_GROUPE
		--WHERE DATEPART(YEAR, @DT_ANALYSE) BETWEEN DATEPART(YEAR, HQLOCAT.DDEB) AND DATEPART(YEAR, ISNULL(HQLOCAT.DFIN, '2999/01/01'))
		--AND LOCATION.FK_BAIL IS NOT NULL
		--AND LOCATION.CORG = '11'
		--AND (LOCATION.DATSORQUIT IS NULL OR LOCATION.DATSORQUIT > @DT_ANALYSE)
		--AND IND_MANDAT_ACTIF = 'O'
		--AND (PSRE.IND_CALCUL_FRANCHISE = 'O' OR PSRE.IND_CALCUL_PALIER = 'O')
		--GROUP BY LOCATION.FK_GROUPE, LOCATION.PK_LOCATION, LOCATION.PERIOD
	) SRC
)

-- copy the required columns to the result of the function   
   INSERT @retANNUAL_LEASE_ALLOWANCES  
   SELECT PK_GROUPE, PK_BAIL, MT_LOYER_FRANCHISE, MT_PALIER--, CD_FREQUENCE_QUITTANCEMENT
   FROM ANNUAL_LEASE_ALLOWANCES_cte   
   RETURN  
END;