CREATE FUNCTION [dbo].[f_GLIFOU] 
(
	@DT_DEBUT DATETIME,
	@DT_FIN DATETIME,
	@PK_PROPRIETAIRE INT,
	@PK_IMMEUBLE NVARCHAR(MAX)
)
RETURNS @retGLIFOU TABLE   
(  
	PK_PROPRIETAIRE int,
	PK_FOURNISSEUR int,
	PK_GROUPE int,
	CCATEG varchar(4) NULL,
	LCATEG varchar(60) NULL,
	CTYPCOM varchar(2) NULL,
	LTYPCOM varchar(50) NULL,
	CSECTANA varchar(50) NULL,
	LGROUPE int NULL,	
	CTIERS varchar(14) NULL,
	LTIERS varchar(76) NULL,
	DATEC date,
	LIBELLE varchar(80) NULL,
	NOFACT varchar(24) NULL,
	CJOURNAL varchar(6) NULL,
	CTYPECRI varchar(6) NULL,
	NOPIECE varchar(16) NULL,
	LETTRAGE varchar(18) NULL,
	MT_DEBIT numeric(17, 2) NULL,
	MT_CREDIT numeric(17, 2) NULL,
	CMANDAT varchar(16) NULL


)  
--Returns a result set that lists all the employees who report to the   
--specific employee directly or indirectly.*/  
AS  
BEGIN  
WITH GLIFOU_cte(PK_PROPRIETAIRE, PK_FOURNISSEUR, PK_GROUPE, CCATEG, LCATEG, CTYPCOM, LTYPCOM, CSECTANA, LGROUPE, CTIERS, LTIERS, DATEC, LIBELLE, NOFACT, CJOURNAL, CTYPECRI, NOPIECE, LETTRAGE, MT_DEBIT, MT_CREDIT, CMANDAT)
AS
(
	SELECT PROPRIETAIRES.PK_TIERS AS PK_PROPRIETAIRE
		 , FOURNISSEURS.PK_TIERS AS PK_FOURNISSEUR
		 , GROUPE.PK_GROUPE
		 , ECRITAUX.CCATEG
		 , CATEG.LCATEG
		 , ECRITAUX.CTYPCOM
		 , TYPCOM.LTYPCOM
		 , MANSEC.CSECTANA
		 , GROUPE.LGROUPE
		 , ECRITAUX.CTIERS
		 , FOURNISSEURS.LTIERS
		 , ECRITAUX.DATEC
		 , ECRITAUX.LIBELLE
		 , ECRITAUX.NOFACT
		 , ECRITAUX.CJOURNAL
		 , ECRITAUX.CTYPECRI
		 , ECRITAUX.NOPIECE
		 , ECRITAUX.LETTRAGE
		 , CASE ECRITAUX.SENS WHEN 'D' THEN ECRITAUX.MONTANT ELSE 0 END AS MT_DEBIT
		 , CASE ECRITAUX.SENS WHEN 'C' THEN ECRITAUX.MONTANT ELSE 0 END AS MT_CREDIT
		 , ECRITAUX.CMANDAT
	FROM MASTER_ESTIA..ESTIA_ECRITAUX ECRITAUX
	LEFT JOIN MASTER_ESTIA..ESTIA_CATEG CATEG
	ON CATEG.CCATEG = ECRITAUX.CCATEG
	LEFT JOIN MASTER_ESTIA..ESTIA_TYPCOM TYPCOM
	ON TYPCOM.CTYPCOM = ECRITAUX.CTYPCOM
	LEFT JOIN MASTER_ESTIA..WRK_GROUPE_MANGES WGM
	ON WGM.CORG = ECRITAUX.CORG AND WGM.CMANDAT = ECRITAUX.CMANDAT
	LEFT JOIN MASTER_ESTIA..ESTIA_TIERS PROPRIETAIRES
	ON PROPRIETAIRES.PK_TIERS = WGM.FK_TIERS
	LEFT JOIN MASTER_ESTIA..ESTIA_TIERS FOURNISSEURS
	ON FOURNISSEURS.CTIERS = ECRITAUX.CTIERS
	LEFT JOIN 
	(
		SELECT DISTINCT CORG
				, CMANDAT
				, CSECTANA
		FROM MASTER_ESTIA..ESTIA_MANSEC 
	) MANSEC
	ON MANSEC.CORG = ECRITAUX.CORG AND MANSEC.CMANDAT = ECRITAUX.CMANDAT
	LEFT JOIN MASTER_ESTIA..ESTIA_GROUPE GROUPE
	ON GROUPE.PK_GROUPE = WGM.PK_GROUPE
	WHERE ECRITAUX.CORG = '11' 
	AND ECRITAUX.DATEC BETWEEN @DT_DEBUT AND @DT_FIN
	AND PROPRIETAIRES.PK_TIERS = @PK_PROPRIETAIRE
	AND GROUPE.PK_GROUPE IN (SELECT VALUE FROM dbo.ufn_SplitMultiValue(@PK_IMMEUBLE,','))
	AND ECRITAUX.CTYPCOM = 'F'
)

-- copy the required columns to the result of the function   
   INSERT @retGLIFOU 
   SELECT PK_PROPRIETAIRE, PK_FOURNISSEUR, PK_GROUPE, CCATEG, LCATEG, CTYPCOM, LTYPCOM, CSECTANA, LGROUPE, CTIERS, LTIERS, DATEC, LIBELLE, NOFACT, CJOURNAL, CTYPECRI, NOPIECE, LETTRAGE, MT_DEBIT, MT_CREDIT, CMANDAT
   FROM GLIFOU_cte   
   RETURN  
END;