CREATE FUNCTION [dbo].[f_GLI] 
(
	@DT_DEBUT DATETIME,
	@DT_FIN DATETIME,
	@PK_PROPRIETAIRE INT,
	@PK_IMMEUBLE NVARCHAR(MAX)
)
RETURNS @retGLI TABLE   
(  
	FK_TIERS int,
	PK_GROUPE int,
	CORG varchar(4) NULL,
	CJOURNAL varchar(6) NULL,
	DATEC date,
	DVAL date,
	CCG varchar(28) NULL,
	LIBELLE varchar(80) NULL,
	SENS varchar(2) NULL, 
	MONTANT numeric(17, 2) NULL,
	CTYPECRI varchar(6) NULL,
	NOPIECE varchar(16) NULL,
	REF varchar(42) NULL,
	TRAIT varchar(6) NULL, 
	TYPCPTA varchar(4) NULL,
	PERIODE varchar(12) NULL,
	BANAL varchar(60) NULL,
	ORD int NULL,
	NODOC varchar(24) NULL,
	INTERFACE varchar(50) NULL,
	UTIL varchar(24) NULL,
	INFO varchar(44) NULL,
	ECCG varchar(42) NULL,
	MTLET numeric(17, 2) NULL,
	CMANDAT varchar(16) NULL,
	ECRAC_ID int NULL
)  
--Returns a result set that lists all the employees who report to the   
--specific employee directly or indirectly.*/  
AS  
BEGIN  
WITH GLI_cte(FK_TIERS, PK_GROUPE, CORG, CJOURNAL, DATEC, DVAL, CCG, LIBELLE, SENS, MONTANT, CTYPECRI, NOPIECE, REF, TRAIT, TYPCPTA, PERIODE, BANAL, ORD, NODOC, INTERFACE, UTIL, INFO, ECCG, MTLET, CMANDAT, ECRAC_ID  )
AS
(
	SELECT WGM.FK_TIERS
		 , WGM.PK_GROUPE
		 , ECRAC.CORG
		 , ECRAC.CJOURNAL
		 , ECRAC.DATEC
		 , ECRAC.DVAL
		 , ECRAC.CCG
		 , ECRAC.LIBELLE
		 , ECRAC.SENS
		 , ECRAC.MONTANT
		 , ECRAC.CTYPECRI
		 , ECRAC.NOPIECE
		 , ECRAC.REF
		 , ECRAC.TRAIT
		 , ECRAC.TYPCPTA
		 , ECRAC.PERIODE
		 , ECRAC.BANAL
		 , ECRAC.ORD
		 , ECRAC.NODOC
		 , ECRAC.INTERFACE
		 , ECRAC.UTIL
		 , ECRAC.INFO
		 , ECRAC.ECCG
		 , ECRAC.MTLET
		 , ECRAC.CMANDAT
		 , ECRAC.ECRAC_ID  
	FROM MASTER_ESTIA..ESTIA_ECRAC ECRAC
	LEFT JOIN MASTER_ESTIA..WRK_GROUPE_MANGES WGM
	ON WGM.FK_MANGES = ECRAC.FK_MANGES
	LEFT JOIN MASTER_ESTIA..ESTIA_TIERS TIERS
	ON TIERS.PK_TIERS = WGM.FK_TIERS
	left join
	(
		select LIENMO.CORG, LIENMO.BANOPE, LIENMO.BANMAR
		from MASTER_ESTIA..ESTIA_LIENMO LIENMO
		where LIENMO.CSTE = 'Q'
	) LIENMO
	on LIENMO.CORG = ECRAC.CORG and LIENMO.BANOPE = ECRAC.REF
	left join
	(
		select CPTGLOB.CORG, CPTGLOB.REF, CPTGLOB.NOCHEQUE as AVIS_ECHEANCE
		from MASTER_ESTIA..ESTIA_CPTGLOB CPTGLOB
		where CPTGLOB.TYPCPTA = 'LG'
	) CPTGLOB
	on CPTGLOB.CORG = LIENMO.CORG and CPTGLOB.REF = LIENMO.BANMAR
	WHERE ECRAC.CORG = '11'
	and ECRAC.DATEC between @DT_DEBUT and @DT_FIN --'20161210' AND '20170310'
	and WGM.FK_TIERS = @PK_PROPRIETAIRE  --(10852, 5879, 6318)
	and WGM.PK_GROUPE IN (SELECT VALUE FROM dbo.ufn_SplitMultiValue(@PK_IMMEUBLE,','))
	and ECRAC.ETECR in ('N', 'E')
	and ECRAC.CCG not in ('80100000', '80910000')
)

-- copy the required columns to the result of the function   
   INSERT @retGLI 
   SELECT FK_TIERS, PK_GROUPE, CORG, CJOURNAL, DATEC, DVAL, CCG, LIBELLE, SENS, MONTANT, CTYPECRI, NOPIECE, REF, TRAIT, TYPCPTA, PERIODE, BANAL, ORD, NODOC, INTERFACE, UTIL, INFO, ECCG, MTLET, CMANDAT, ECRAC_ID  
   FROM GLI_cte   
   RETURN  
END;