CREATE FUNCTION dbo.f_LISTE_PROPRIETAIRE_EXPERT_COMPT() 
RETURNS @retLISTE_PROPRIETAIRE_EXPERT_COMPT TABLE   
(  
	PK_PROPRIETAIRE int NULL,
	CD_PROPRIETAIRE varchar(14) NULL,
	NM_PROPRIETAIRE int NULL,
	NOM_PROPRIETAIRE varchar(76) NULL
)  
--Returns a result set that lists all the employees who report to the   
--specific employee directly or indirectly.*/  
AS  
BEGIN 
WITH LISTE_PROPRIETAIRE_EXPERT_COMPT_cte(PK_PROPRIETAIRE, CD_PROPRIETAIRE, NM_PROPRIETAIRE, NOM_PROPRIETAIRE)
AS
(
	SELECT DISTINCT 
	  D_PROPRIETAIRE.PK_PROPRIETAIRE
	, D_PROPRIETAIRE.CD_PROPRIETAIRE
	, D_PROPRIETAIRE.NM_PROPRIETAIRE
	, CAST(D_PROPRIETAIRE.NM_PROPRIETAIRE AS VARCHAR(14)) + ' - ' + D_PROPRIETAIRE.NOM_PROPRIETAIRE AS NOM_PROPRIETAIRE
	FROM D_PROPRIETAIRE
	WHERE D_PROPRIETAIRE.PK_PROPRIETAIRE NOT IN (6320, 6321)
)

-- copy the required columns to the result of the function   
   INSERT @retLISTE_PROPRIETAIRE_EXPERT_COMPT  
   SELECT PK_PROPRIETAIRE, CD_PROPRIETAIRE, NM_PROPRIETAIRE, NOM_PROPRIETAIRE
   FROM LISTE_PROPRIETAIRE_EXPERT_COMPT_cte   
   RETURN  
END;