-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
CREATE FUNCTION [dbo].[SWISS_LIFE_ETAT_LOC_FD]
(	
	@DT DATETIME,
	@IMM VARCHAR
)
RETURNS TABLE 
AS
RETURN 
(
	-- Add the SELECT statement with parameter references here

select	  FEL.PK_TEMPS
		, LOCATAIRE.CD_LOCATAIRE
		, LOCATAIRE.NOM_LOCATAIRE
		, FEL.CCOMPTE
		, BAIL.CD_BAIL
		, BAIL.CD_USAGE_BAIL
		, BAIL.LB_USAGE_BAIL
		, BAIl.LB_DUREE
		, BAIL.DT_SIGNATURE
		, BAIL.DT_EFFET
		, BAIL.DT_ENTREE
		, BAIL.DT_CONGE
		, BAIL.DT_SORTIE
		, IMMEUBLE.CD_IMMEUBLE
		, IMMEUBLE.ADRLGN1
		, IMMEUBLE.ADRLGN2
		, IMMEUBLE.CODPOS
		, IMMEUBLE.VILLE
		, LOT.CD_LOT 
		, LOT.CD_TYPE_LOT
		, LOT.LB_TYPE_LOT
		, BAIL.CD_LOT_PRINCIPAL
		, LOT.ETAGE
		, LOT.VAL_SURFACE_REELLE
		, PROPRIETAIRE.CD_PROPRIETAIRE
		, PROPRIETAIRE.NOM_PROPRIETAIRE
		, BAIL.DT_PRCH_TRIEN_POT
		, BAIL.CD_TERME
		, BAIL.LB_TERME
		, BAIL.CD_TYPE_CAUTION
		, BAIL.LB_TYPE_CAUTION
		, BAIL.MT_DG_PRINCIPAL
		, FEL.MT_DG
		, FEL.MT_LOYER_ACTUEL
		, FEL.MT_CHARGES
		, BAIL.CD_MODE_REVISION
		, BAIL.CD_FREQUENCE_REVISION
		, BAIL.DT_PROCHAINE_REVISION
		, BAIL.PC_RECUP_TB
		, BAIL.PC_RECUP_TF
		, BAIL.PC_RECUP_AS
		, BAIL.PC_RECUP_HO
		, BAIL.PC_RECUP_606
from F_ETAT_LOCATIF FEL
left join D_IMMEUBLE IMMEUBLE on IMMEUBLE.PK_IMMEUBLE = FEL.FK_IMMEUBLE
left join D_LOT LOT on LOT.PK_LOT = FEL.PK_LOT
left join D_PROPRIETAIRE PROPRIETAIRE on PROPRIETAIRE.PK_PROPRIETAIRE = FEL.FK_PROPRIETAIRE
left join D_BAIL BAIL on BAIL.PK_BAIL = FEL.FK_BAIL
left join D_LOCATAIRE LOCATAIRE on LOCATAIRE.PK_LOCATAIRE = FEL.FK_LOCATAIRE
where FEL.PK_TEMPS = @DT
and FEL.FK_IMMEUBLE = @IMM
--order by FEL.CD_STATUT

)